### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'filter_nsfw'

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [TheLastBen/fast-stable-diffusion#1006]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 430, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 544, in process_images_inner
    if opts.filter_nsfw:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 459, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'filter_nsfw'

**Comment by TheLastBen** [comment]
try doing a clean run by removing/renaming the folder "sd"

**Comment by lolxdmainkaisemaanlu** [comment]
thanks, it worked
