### ISSUE TITLE
Dreambooth: rm: cannot remove '/content/stable-diffusion-custom': No such file or directory

### ISSUE THREAD

**Issue by createperhaps** [TheLastBen/fast-stable-diffusion#1011]
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1115, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1066, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 835, in load_models_from_stable_diffusion_checkpoint
    checkpoint = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/content/convertodiff.py", line 817, in load_checkpoint_with_text_encoder_conversion
    state_dict = checkpoint["state_dict"]
KeyError: 'state_dict'
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error
Conversion error
Conversion error
(seems to loop).

Let me know if you need additional context, but I really only copied a path to a checkpoint file and then clicked run.

**Comment by TheLastBen** [comment]
did you choose the right version of the model in the dropdown menu ?

**Comment by createperhaps** [comment]
Yes, I am using Hassen'sblend which I believe is based on 1.5 so there was nothing to change. I'll try a different checkpoint I suppose.  It seemed to work when I put a token in and am using the default checkpoint.

**Comment by patrikzudel** [comment]
Did u figure it out?
