### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.paths'

### ISSUE THREAD

**Issue by hushbook** [TheLastBen/fast-stable-diffusion#1018]
Loading traning model was sucessful, but when running last cell I got next error:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 12, in <module>
    import modules.interrogate
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 13, in <module>
    from modules import devices, paths, lowvram, modelloader
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 9, in <module>
    from modules.upscaler import Upscaler
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/upscaler.py", line 14, in <module>
    from modules.paths import models_path
ModuleNotFoundError: No module named 'modules.paths'

**Comment by TheLastBen** [comment]
remove the folder sd and do a clean run

**Comment by hushbook** [comment]
Thanks, helped
