### ISSUE TITLE
AUTOMATIC not working

### ISSUE THREAD

**Issue by Emetrop** [TheLastBen/fast-stable-diffusion#103]
When I try to generate image it throws

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 184, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 65, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 43, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 291, in process_images
    pprint(p)
TypeError: 'module' object is not callable`

**Comment by Emetrop** [comment]
deleted sd folder and tried again and it works!
