### ISSUE TITLE
Error when adding --gradio-auth

### ISSUE THREAD

**Issue by Weatwagon** [TheLastBen/fast-stable-diffusion#104]
When I add the --gradio-auth="username:password" to webui.py parameters I get the following error

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 125, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 103, in webui
    prevent_thread_lock=True
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 1055, in launch
    "Cannot queue with encryption or authentication enabled."
ValueError: Cannot queue with encryption or authentication enabled.
```
I was doing this just fine in previous iterations of the colab notebook for Automatic 1111 just fine.

**Comment by TheLastBen** [comment]
Because I added the queue parameter to Gradio to fix the freezing when generating a large batch

**Comment by Weatwagon** [comment]
I was looking at the revision diffs and figured as much. I have it commented out for now.

**Comment by TheLastBen** [comment]
just comment out the `demo.queue` .... line
