### ISSUE TITLE
Test The Trained Model error

### ISSUE THREAD

**Issue by khanfar** [TheLastBen/fast-stable-diffusion#1056]
hi , im on this step get this 

Total progress100% 20/20 [00:03<00:00,  5.72it/s]
Error completing request
Arguments: (0, '', '', 'None', 'None', None, None, None, None, None, 0, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 152, in img2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 532, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 832, in init
    image = img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

Downloading: "https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth" to /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/BLIP/model_base_caption_capfilt_large.pth

100% 855M/855M [00:38<00:00, 23.3MB/s]
Downloading100% 232k/232k [00:00<00:00, 263kB/s]
Downloading100% 28.0/28.0 [00:00<00:00, 23.5kB/s]
Downloading100% 570/570 [00:00<00:00, 361kB/s]
load checkpoint from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/BLIP/model_base_caption_capfilt_large.pth
100%|███████████████████████████████████████| 890M/890M [00:14<00:00, 65.2MiB/s]
Error interrogating
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 148, in interrogate
    caption = self.generate_caption(pil_image)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 126, in generate_caption
    gpu_image = transforms.Compose([
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py", line 346, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py", line 462, in resize
    _, image_height, image_width = get_dimensions(img)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py", line 75, in get_dimensions
    return F_pil.get_dimensions(img)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py", line 33, in get_dimensions
    raise TypeError(f"Unexpected type {type(img)}")
TypeError: Unexpected type <class 'NoneType'>

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 148, in interrogate
    caption = self.generate_caption(pil_image)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 126, in generate_caption
    gpu_image = transforms.Compose([
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py", line 346, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py", line 462, in resize
    _, image_height, image_width = get_dimensions(img)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py", line 75, in get_dimensions
    return F_pil.get_dimensions(img)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py", line 33, in get_dimensions
    raise TypeError(f"Unexpected type {type(img)}")
TypeError: Unexpected type <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 269, in interrogate
    prompt = shared.interrogator.interrogate(image)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 177, in interrogate
    res += "<error>"
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by questgugou** [comment]
i think you are right
