### ISSUE TITLE
Warning: Taming Transformers not found at path

### ISSUE THREAD

**Issue by jimys** [TheLastBen/fast-stable-diffusion#108]
It seems that you did not perform training during this session or you chose to use a custom path,
provide the full path to the model (including the name of the model):
/content/gdrive/MyDrive/realjingyang.ckpt
Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/stable-diffusion/src/taming-transformers/taming
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 82, in <module>
    shared.sd_model = modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 158, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ModuleNotFoundError: No module named 'taming'

**Comment by TheLastBen** [comment]
You ran the last cell before going through the setting of the environment, if you want to use the AUTOMATIC1111 webui, there is a colab for it in the main page of the repo

**Comment by jimys** [comment]
> 

can I just generate photo in Google colab?

I tried automatic1111 on my iPad safari, no new Windows pop-up,

Thank you for your reply so quick, you are so kind

**Comment by TheLastBen** [comment]
yes, use this colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by jimys** [comment]
> 

solved!!!thank you very much, you are such a great man,

**Comment by TheLastBen** [comment]
happy to help
