### ISSUE TITLE
Cant train inversion in auto1111 

### ISSUE THREAD

**Issue by 2blackbar** [TheLastBen/fast-stable-diffusion#1080]
Applying xformers cross attention optimization.
Training at rate of 0.05 until step 10000
Preparing dataset...
100% 18/18 [00:02<00:00,  7.27it/s]
  0% 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 328, in train_embedding
    loss = shared.sd_model(x, c)[0] / gradient_step
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 846, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 903, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

Applying xformers cross attention optimization.

**Comment by TheLastBen** [comment]
V2.1 or V1.5 ?

**Comment by boginski345** [comment]
> !sed -i '902s@.*@        self.logvar = self.logvar.to(self.device)@' /content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py

I had the same issue. The solution you suggested fixed everything!
But if choose "Large_Model" nothing works

**Comment by TheLastBen** [comment]
when you use "large_model" it helps loading models over 7GB by sending them to the GPU instead of RAM
