### ISSUE TITLE
Error when loadin new maded colab model to AUTOMATIC1111

### ISSUE THREAD

**Issue by GuglPlay** [TheLastBen/fast-stable-diffusion#1109]
Loading weights [e36eb113] from F:\ai\stable-diffusion-webui\models\Stable-diffusion\Deniska.ckpt
Error verifying pickled file from F:\ai\stable-diffusion-webui\models\Stable-diffusion\Deniska.ckpt:
Traceback (most recent call last):
  File "F:\ai\stable-diffusion-webui\modules\safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "F:\ai\stable-diffusion-webui\modules\safe.py", line 84, in check_pt
    check_zip_filenames(filename, z.namelist())
  File "F:\ai\stable-diffusion-webui\modules\safe.py", line 76, in check_zip_filenames
    raise Exception(f"bad file inside {filename}: {name}")
Exception: bad file inside F:\ai\stable-diffusion-webui\models\Stable-diffusion\Deniska.ckpt: Deniska/data.pkl

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Traceback (most recent call last):
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\ai\stable-diffusion-webui\modules\ui.py", line 1603, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "F:\ai\stable-diffusion-webui\modules\ui.py", line 1444, in run_settings_single
    if not opts.set(key, value):
  File "F:\ai\stable-diffusion-webui\modules\shared.py", line 477, in set
    self.data_labels[key].onchange()
  File "F:\ai\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "F:\ai\stable-diffusion-webui\webui.py", line 62, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "F:\ai\stable-diffusion-webui\modules\sd_models.py", line 302, in reload_model_weights
    load_model_weights(sd_model, checkpoint_info)
  File "F:\ai\stable-diffusion-webui\modules\sd_models.py", line 191, in load_model_weights
    sd = read_state_dict(checkpoint_file)
  File "F:\ai\stable-diffusion-webui\modules\sd_models.py", line 173, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "F:\ai\stable-diffusion-webui\modules\sd_models.py", line 147, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by TheLastBen** [comment]
Add the argument --disable-safe-unpickle
