### ISSUE TITLE
Whats Next?

### ISSUE THREAD

**Issue by Panchor1** [TheLastBen/fast-stable-diffusion#111]
![image](https://user-images.githubusercontent.com/115121154/194774728-db9d49af-9135-4d94-8241-97942353349a.png)

**Comment by TheLastBen** [comment]
Some might encounter freezing when using gradio server, the tunnel seems better.

**Comment by Panchor1** [comment]
I tried all 3 colabs and the only one that worked was relaxed mode


> Some might encounter freezing when using gradio server, the tunnel seems better.

**Comment by misiek75** [comment]
I have this error on a AUTOMATIC1111  
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 85, in <module>
    loaded_hypernetwork = modules.hypernetwork.load_hypernetwork(shared.opts.sd_hypernetwork)
AttributeError: module 'modules' has no attribute 'hypernetwork'

**Comment by TheLastBen** [comment]
They updated their repo .... again, i'll check it out

**Comment by TheLastBen** [comment]
fixed, they keep adding useless features to there webui until there is no more image output, just settings and sliders

**Comment by pixexid** [comment]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 10, in <module>
    from modules.paths import script_path
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    import modules.safe
ModuleNotFoundError: No module named 'modules.safe'

**Comment by TheLastBen** [comment]
AUTOMATIC1111 updated again their repo, in the second cell, check update repo or simply remove the sd folder from your gdrive and do a clean install

**Comment by pixexid** [comment]
Great, thanks! It's working now. One issue I'm facing is: I'm generating my images in 768x512 but on the output folder the images are saved with 512x512px. Any way to fix this?

**Comment by pixexid** [comment]
> AUTOMATIC1111 updated again their repo, in the second cell, check update repo or simply remove the sd folder from your gdrive and do a clean install

Great, thanks! It's working now. One issue I'm facing is: I'm generating my images in 768x512 but on the output folder the images are saved with 512x512px. Any way to fix this?
