### ISSUE TITLE
ModuleNotFoundError: No module named 'blendmodes'

### ISSUE THREAD

**Issue by saviomartin** [TheLastBen/fast-stable-diffusion#1130]
I'm getting this error, i tried from two times from different accounts, but it still happens every time.

![image](https://user-images.githubusercontent.com/61895712/209426701-988349d1-1315-4e46-93d7-0d8c3e86d3f1.png)

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 30, in <module>
    from blendmodes.blend import blendLayers, BlendType
ModuleNotFoundError: No module named 'blendmodes'
```

Please help me fix this

**Comment by norfuer** [comment]
Same issue here.

**Comment by obisims** [comment]
same, it's either that or an import_hook module error.
Sounds like it's because of an AUTOMATIC1111 update.

[ddPn08](https://github.com/ddPn08/automatic1111-colab)'s version can save the enviroment on gDrive if there's storage space but haven't dug deeper yet.

**Comment by rewixx** [comment]
i have the same import_hook roblem 
`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules import import_hook
ImportError: cannot import name 'import_hook' from 'modules' (unknown location)`

**Comment by tamal777** [comment]
same issue.

**Comment by TastyMackerel** [comment]
Facing the same issue here, exact same traceback errors even on complete reinstall.

**Comment by arxivi** [comment]
whew. I thought I was the only one

**Comment by arxivi** [comment]
`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules import import_hook
ImportError: cannot import name 'import_hook' from 'modules' (unknown location)

`

**Comment by TheLastBen** [comment]
fixed

**Comment by roberto-donext** [comment]
After this update, I´m getting this:
usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

**Comment by saviomartin** [comment]
After this update, i'm getting some error when adding instance images, i don't know how. I used the same images before, and it worked perfectly. I also tried renaming the images, it didn't worked either.
![image](https://user-images.githubusercontent.com/61895712/209432481-a59c03b1-1099-4cec-ab9d-a58226ecb15d.png)

Here is the error i'm getting:
```
UnidentifiedImageError                    Traceback (most recent call last)
[<ipython-input-6-ca4527be0fa8>](https://localhost:8080/#) in <module>
     73       identifier=filename.split(".")[0]
     74       new_path_with_file = os.path.join(INSTANCE_DIR, filename)
---> 75       file = Image.open(new_path_with_file)
     76       width, height = file.size
     77       if file.size !=(Crop_size, Crop_size):

[/usr/local/lib/python3.8/dist-packages/PIL/Image.py](https://localhost:8080/#) in open(fp, mode)
   2893     share memory; supported modes include "L", "RGBX", "RGBA", and "CMYK".
   2894 
-> 2895     Note that this function decodes pixel data only, not entire images.
   2896     If you have an entire image file in a string, wrap it in a
   2897     :py:class:`~io.BytesIO` object, and use :py:func:`~PIL.Image.open` to load it.

UnidentifiedImageError: cannot identify image file '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Model/instance_images/Savio (1).jpeg'
```

**Comment by TheLastBen** [comment]
I'll check it out, for now do this : `!pip install pillow==8.4`

**Comment by hartmamt** [comment]
Do we add that after the block that does the dependencies?

**Comment by hartmamt** [comment]
Ok that's what I did. After restarting the runtime that fixed things for now!

**Comment by remlap** [comment]
NameError: name 'capture' is not defined 

After doing pip install after dependencies and trying to download a model from huggingface.

**Comment by TheLastBen** [comment]
fixed, update the notebook

**Comment by remlap** [comment]
> After this update, I´m getting this: usr/local/lib/python3.8/dist-packages/scipy/**init**.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0 warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

```
Training the UNet...
/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
'########:'########:::::'###::::'####:'##::: ##:'####:'##::: ##::'######:::
... ##..:: ##.... ##:::'## ##:::. ##:: ###:: ##:. ##:: ###:: ##:'##... ##::
::: ##:::: ##:::: ##::'##:. ##::: ##:: ####: ##:: ##:: ####: ##: ##:::..:::
::: ##:::: ########::'##:::. ##:: ##:: ## ## ##:: ##:: ## ## ##: ##::'####:
::: ##:::: ##.. ##::: #########:: ##:: ##. ####:: ##:: ##. ####: ##::: ##::
::: ##:::: ##::. ##:: ##.... ##:: ##:: ##:. ###:: ##:: ##:. ###: ##::: ##::
::: ##:::: ##:::. ##: ##:::: ##:'####: ##::. ##:'####: ##::. ##:. ######:::
:::..:::::..:::::..::..:::::..::....::..::::..::....::..::::..:::......::::

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 372, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 466, in _dict_from_json_file
    return json.loads(text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 3 (char 153)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 852, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 563, in main
    noise_scheduler = DDPMScheduler.from_config(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 193, in from_config
    config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 374, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/content/stable-diffusion-custom/scheduler/scheduler_config.json' is not a valid JSON file.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=1000', '--save_n_steps=1000', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/mckgfrul', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/mckgfrul/instance_images', '--output_dir=/content/models/mckgfrul', '--instance_prompt=', '--seed=818788', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=10000']' returned non-zero exit status 1.
Something went wrong
```

**Comment by TheLastBen** [comment]
which custom model are you using ?

**Comment by saviomartin** [comment]
Thank you Ben, everything works well
