### ISSUE TITLE
getting eror while converting to diffuser

### ISSUE THREAD

**Issue by BigDogg99** [TheLastBen/fast-stable-diffusion#1134]
this is the model https://huggingface.co/andite/yohan-diffusion/resolve/main/Cocoa.ckpt

- Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1115, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1066, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 835, in load_models_from_stable_diffusion_checkpoint
    checkpoint = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/content/convertodiff.py", line 817, in load_checkpoint_with_text_encoder_conversion
    state_dict = checkpoint["state_dict"]
KeyError: 'state_dict'
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error
Conversion error
Conversion error
Conversion error

**Comment by TheLastBen** [comment]
make sure you select the right version of the custom model
