### ISSUE TITLE
ImportError: cannot import name 'import_hook' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by konqiDAM** [TheLastBen/fast-stable-diffusion#1137]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules import import_hook
ImportError: cannot import name 'import_hook' from 'modules' (unknown location)

![image](https://user-images.githubusercontent.com/44301655/209431605-8dab7954-4a2e-4e03-a517-49e4c8994391.png)

**Comment by cerarslan** [comment]
delete your sd folder in drive and run lastest .ipynb file

**Comment by mflux** [comment]
I did this and now:

```/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 195, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 133, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 284, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 115, in select_checkpoint
    if len(model_checkpoint) == 0:
TypeError: object of type 'NoneType' has no len()```

**Comment by CodingMaid** [comment]
Delete  SD folder and use a direct CKPT link:
`https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned.ckpt`

`/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Downloading100% 3.94G/3.94G [01:04<00:00, 60.7MB/s]
Loading weights [4bdfc29c] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
^C`

**Comment by rewixx** [comment]
i dosent want to work

**Comment by TheLastBen** [comment]
check the box "large_model"

**Comment by lmcsu** [comment]
Is there a way to quick fix the previous thing without deleting anything?

**Comment by redsparrowgit** [comment]
![image](https://user-images.githubusercontent.com/119093900/209436047-f3949aa9-d339-41d5-b03d-6343c0cb5f03.png)
I have the same problem, I ripped a new colab v1x or 2x, deleted everything, started everything from the beginning , the problem did not disappear

**Comment by lmcsu** [comment]
ok, the issue is with webui
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5967

**Comment by marl0n** [comment]
I'm running this in Colab, same error. Renamed my SD folder, and ran the colab again, letting it create a fresh SD folder. Ran all steps. Then copied my model(s) to the new SD folder, entered a model in the "Path_to_CKPT" line. Then ran the last two steps again, it worked.

**Comment by redsparrowgit** [comment]
LastBen was updated colab. Now works , Thank You

**Comment by TheLastBen** [comment]
> I am using a folder of multiple checkpoints. Looks like something was updated and doesn't work now.
> 
> Deleted my sd folder and now:
> 
> ```
>   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 195, in <module>
>     webui()
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 133, in webui
>     initialize()
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in initialize
>     modules.sd_models.load_model()
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 284, in load_model
>     checkpoint_info = checkpoint_info or select_checkpoint()
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 115, in select_checkpoint
>     if len(model_checkpoint) == 0:
> TypeError: object of type 'NoneType' has no len()```
> ```

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5971

**Comment by Omenizer** [comment]
Same problem, hangs at startup with the above error. Deleted SD folder, didn't help

**Comment by TheLastBen** [comment]
the error will be fixed by A1111 team, soon

**Comment by amratef** [comment]
having same problem

**Comment by TheLastBen** [comment]
it's fixed, remove the folder sd and do a clean run with the latest colab

**Comment by tuangd** [comment]
> I'm running this in Colab, same error. Renamed my SD folder, and ran the colab again, letting it create a fresh SD folder. Ran all steps. Then copied my model(s) to the new SD folder, entered a model in the "Path_to_CKPT" line. Then ran the last two steps again, it worked.
This helps. So you do not have to redownload your models.
 - Renamed my old sd to back it up.
 - Do the fresh install and Requirement step.
 - Then copy all the models, outputs, embeded, extensions to the new sd folder. It works now.
