### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.safe'

### ISSUE THREAD

**Issue by wetcircle** [TheLastBen/fast-stable-diffusion#114]
Getting this error when trying to start stable diffusion on a model I trained. Any ideas? Don't want to retrain
`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 10, in <module>
    from modules.paths import script_path
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    import modules.safe
ModuleNotFoundError: No module named 'modules.safe'`

**Comment by wetcircle** [comment]
Nevermind,   #111
