### ISSUE TITLE
why we have to rename downloaded models to .safetensors every time?

### ISSUE THREAD

**Issue by xone4** [TheLastBen/fast-stable-diffusion#1140]
if i got a .safetensors file link to download into gdrive it rename the file to model.ckpt and it output this message down below but if i manually rename it to .safetensors it works fine, is ther a way to make this in an automated way?

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading100% 961k/961k [00:01<00:00, 863kB/s]
Downloading100% 525k/525k [00:01<00:00, 469kB/s]
Downloading100% 389/389 [00:00<00:00, 344kB/s]
Downloading100% 905/905 [00:00<00:00, 762kB/s]
Downloading100% 4.52k/4.52k [00:00<00:00, 3.90MB/s]
Downloading100% 1.71G/1.71G [00:47<00:00, 35.7MB/s]
Loading weights [d61f229a] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 195, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 133, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 313, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 196, in load_model_weights
    sd = read_state_dict(checkpoint_file)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 173, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 106, in load
    return load_with_extra(filename, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x9f'.

**Comment by TheLastBen** [comment]
I'll fix that soon

**Comment by alberduris** [comment]
What's the status on this? #1560 #1513

**Comment by TheLastBen** [comment]
Always use the diffusers model when avaliable
