### ISSUE TITLE
Upscaling in Extras Broken

### ISSUE THREAD

**Issue by Gushousekai195** [TheLastBen/fast-stable-diffusion#1153]
```
SwinIR tiles100% 15/15 [00:13<00:00,  1.11it/s]
Exception in thread Thread-1142:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gradio/tunneling.py", line 39, in handler
    chan.send(data)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
```

Fix please

**Comment by TheLastBen** [comment]
Uncheck the box "use_gradio_server"
