### ISSUE TITLE
Unable to use Custom Model 

### ISSUE THREAD

**Issue by preston3201** [TheLastBen/fast-stable-diffusion#1167]
Whenever I attempt to input a custom model version under the "Path_to_HuggingFace:" textbox, the Start Dreambooth cell fails to execute and I receive the following error:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 852, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 597, in main
    train_dataloader = torch.utils.data.DataLoader(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 344, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/model_test_1', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/model_test_1/instance_images', '--output_dir=/content/models/model_test_1', '--instance_prompt=', '--seed=135439', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-05', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=1']' returned non-zero exit status 1.
Something went wrong

I've also tried inputting a huggingface.co link in the "CKPT_Link:" field, but receive the same error. The Model Download cell runs just fine, however, and I'm able to run the Start Dreambooth cell without an error if I leave the "Path_to_HuggingFace:" textbox blank and set to the default version 1.5. Does anyone have the same issue or know what could be causing this?

**Comment by preston3201** [comment]
Fix found here: https://github.com/TheLastBen/fast-stable-diffusion/commit/e5a32050db56e74ed4023ca0b87e394b6415e144
