### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.safe'

### ISSUE THREAD

**Issue by mashonoid** [TheLastBen/fast-stable-diffusion#120]
The repo won't update and the next time I tried to run the WEBUI without updating the repo it threw this error

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 10, in <module>
    from modules.paths import script_path
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    import modules.safe
ModuleNotFoundError: No module named 'modules.safe'`

**Comment by TheLastBen** [comment]
you will need to remove the folder "sd" from your gdrive and do a clean run

**Comment by TheLastBen** [comment]
AUTOMATIC1111 added some additional features that required a clean run
