### ISSUE TITLE
The last days installing is keep failing

### ISSUE THREAD

**Issue by plasmasnake88** [TheLastBen/fast-stable-diffusion#1209]
Hi,
Normally things are running smooth, but after pulling the latest release i keep getting the following errors. This is both with 1.5 and 2.1 768 versions.

All cells seems to run fine, but then when it's time to run webui this happens:

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 13, in <module>
    import modules.interrogate
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 13, in <module>
    from modules import devices, paths, lowvram, modelloader
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 18, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['/content/gdrive/MyDrive/sd/stablediffusion', '.', '/content/gdrive/MyDrive/sd']`

**Comment by TheLastBen** [comment]
remove/rename the folder sd and use the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by edwardk1234** [comment]
> remove/rename the folder sd and use the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Hey @TheLastBen, is there a way to easily copy the settings / files from our previous SD version over into the newly created version? I probably need to manually move some wildcards txt files but not sure what else I could miss out as well.

Thanks!

**Comment by TheLastBen** [comment]
don't delete the old sd folder, then slowly add the files you need.

**Comment by rlayne** [comment]
i know theres sexier stuff to do but automating this as part of the colab would probably help cut down your issues list, it does cause weird behaviour the way things are currently (inpainting def model bug with 2.1, loading last used model(?) instead of default(?) etc).
