### ISSUE TITLE
[Bug] Can't load protogen model into the notebook

### ISSUE THREAD

**Issue by MaxTran96** [TheLastBen/fast-stable-diffusion#1219]
Hi, for some reason i couldn't load the model protogen 2.2  into the notebook https://www.reddit.com/r/StableDiffusion/comments/1003bsv/protogen_v22_official_release/'
https://civitai.com/models/3627/protogen-v22-official-release

Steps to reproduce, i first created a folder named xyz in the Sessions folder, uploaded the protogen 2.2 checkpoint file into the folder and then in the notebook, i create/load a session with that xyz session name but it failed to load

This is the error
Session found, loading the trained model ...
Converting to Diffusers ...
2023-01-01 11:51:21.434530: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1107, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1056, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 834, in load_models_from_stable_diffusion_checkpoint
    checkpoint = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/content/convertodiff.py", line 816, in load_checkpoint_with_text_encoder_conversion
    state_dict = checkpoint["state_dict"]
KeyError: 'state_dict'
Conversion error, if the error persists, remove the CKPT file from the current session folder

**Comment by TheLastBen** [comment]
merged models tend to have this problem, try converting it to diffusers in the website huggingface, then load it to the colab

**Comment by LeMemeDream** [comment]
By that, do you mean upload it to huggingface, then download the model from huggingface into the notebook, or to use something like this:
https://huggingface.co/spaces/anzorq/sd-to-diffusers

**Comment by LeMemeDream** [comment]
> merged models tend to have this problem, try converting it to diffusers in the website huggingface, then load it to the colab

By that, do you mean upload it to huggingface, then download the model from huggingface into the notebook, or to use something like this:
https://huggingface.co/spaces/anzorq/sd-to-diffusers

**Comment by TheLastBen** [comment]
> or to use something like this: https://huggingface.co/spaces/anzorq/sd-to-diffusers
that's would be a good solution

**Comment by Taikakim** [comment]
By the way, where do the models need to be to have them available in the dropdown menu in the UI? With some earlier version all of the created models were available there, but now only the currently selected one can be found?

**Comment by Taikakim** [comment]
Ah, right, I was confused when some older version picked them up automatically. Thanks!
