### ISSUE TITLE
 import modules.safe ModuleNotFoundError: No module named 'modules.safe'

### ISSUE THREAD

**Issue by 1blackbar** [TheLastBen/fast-stable-diffusion#123]
Got this error now 3times in a row restarted notebook from 0

**Comment by 1blackbar** [comment]
last one is from 13hrs, it happened 20 mins ago with most recent notebook

**Comment by TheLastBen** [comment]
you will need to remove the "sd" folder or check the "update repo" in the 2nd cell (make sure you delete webui.py and paths.py before that

**Comment by 1blackbar** [comment]
also i trained subject hour ago but all outputs are black image, well , ill wait till tomorrow , maybe more people will  open issues, sometimethings up i guess

**Comment by TheLastBen** [comment]
I just tested it, it works fine, might be your input images

**Comment by 1blackbar** [comment]
ill give it a go now, i have 2 ckpt files that result in black outputs, trained 2hrs ago

**Comment by 1blackbar** [comment]
Now this one, i deleted SD from drive
`Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/taming-transformers/taming
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/CodeFormer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/BLIP/models/blip.py
Warning: k_diffusion not found at path /content/gdrive/MyDrive/sd/k-diffusion/k_diffusion/sampling.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 82, in <module>
    shared.sd_model = modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 177, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ModuleNotFoundError: No module named 'taming'`

**Comment by TheLastBen** [comment]
you skipped the requirement cell

**Comment by 1blackbar** [comment]
i dont know whats going on, i rerun the notebook from start and wiped gdrice, still got taming issue, maybe stuff is not refreshing fast enough after changes , i test models locally for now

**Comment by 1blackbar** [comment]
it worked again, i think theres some delay before notebook and dependencies gets updated

**Comment by TheLastBen** [comment]
the delay is no more than 3minutes

**Comment by 1blackbar** [comment]
Ok happened again, i think this is something that happens after you train something once, then try to train again and run webui second time after second training, you get error with taming even with wiping SD from gdrive

**Comment by TheLastBen** [comment]
just ran it twice, it worked perfectly, I don't see how the training would mess with sd files, the only operation it does on gdrive is copying the model, this error could happen only when you move some folders inside sd or your gdrive is full
