### ISSUE TITLE
Img2img and inpaint error

### ISSUE THREAD

**Issue by apaicu123** [TheLastBen/fast-stable-diffusion#1239]
Hi,

I am getting an error when sending txt2ing to img2img and impaint. Is is something temporary hapenning?

![image](https://user-images.githubusercontent.com/30288824/210355856-0bb114d4-5836-4169-9b2a-241a2f149315.png)

**Comment by TheLastBen** [comment]
copy the error log from the colab output

**Comment by apaicu123** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 110, in send_image_and_dimensions
    img = image_from_url_text(x)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 42, in image_from_url_text
    is_in_right_dir = ui_tempdir.check_tmp_file(shared.demo, filename)
AttributeError: module 'modules.ui_tempdir' has no attribute 'check_tmp_file'

**Comment by Barry-Bot1** [comment]
Getting the same

**Comment by being-peace** [comment]
There is also an error when loading a file with upload.

**Comment by TheLastBen** [comment]
try the latest colab and report back

**Comment by apaicu123** [comment]
Yeap, works well now. Thank you so much!

**Comment by being-peace** [comment]
I use https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb in google colab and the issue is still there for me (with sligthly different line numbers). @apaicu123 for you it´s okay? 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 113, in send_image_and_dimensions
    img = image_from_url_text(x)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 45, in image_from_url_text
    is_in_right_dir = ui_tempdir.check_tmp_file(shared.demo, filename)
AttributeError: module 'modules.ui_tempdir' has no attribute 'check_tmp_file'
`

**Comment by TheLastBen** [comment]
After A1111 got briefly suspended, there were some changes in the repo links, so your sd folder was affected by the change, rename/remove that folder and do a clean run, it should work fine.

**Comment by being-peace** [comment]
Great, thanks! Sorry for asking.
