### ISSUE TITLE
Error loading script api.py when installing Dreambooth Ext

### ISSUE THREAD

**Issue by markojak** [TheLastBen/fast-stable-diffusion#1245]
This is such a great notebook. I'm currently experimenting with training Dreambooth with a custom SD checkpoint but I can't load the Dreambooth extension as I get these errors

What I've tried
- Reading through other issues I tried to add `!pip install -U diffusers` in a different code block
- Deleting the runtime and doing this again

Anyone have any ideas or encountered anything similar?

```
Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 24, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import FilenameTextGetter
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 257, in <module>
    class ImageBuilder:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 330, in ImageBuilder
    def generate_images(self, prompt_data: list[PromptData]) -> [Image]:
TypeError: 'type' object is not subscriptable

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 17, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import ImageBuilder, PromptData
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 257, in <module>
    class ImageBuilder:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 330, in ImageBuilder
    def generate_images(self, prompt_data: list[PromptData]) -> [Image]:
TypeError: 'type' object is not subscriptable
```

**Comment by TheLastBen** [comment]
have you check in the extension repo : https://github.com/d8ahazard/sd_dreambooth_extension
if there is no similar error, I'll see where is the problem from the colab's side

**Comment by markojak** [comment]
Thanks @TheLastBen - Part of the issue definitely seems to be coming from the extension
(see: https://github.com/d8ahazard/sd_dreambooth_extension/issues/593) because of a Python 3.8 problem

Others in the community are also experiencing this so I'm going to close this issue and continue the discussion on here:
Referencing: https://github.com/TheLastBen/fast-stable-diffusion/issues/914
