### ISSUE TITLE
ValueError: Got unexpected field names: ['config'] | Stable diffusion model failed to load, exiting

### ISSUE THREAD

**Issue by ThanapatSornsrivichai** [TheLastBen/fast-stable-diffusion#1248]
Got the error below.
What've I tried:
- use newest notebook
- clean install new sd folder
- latest update from Automatic1111
- tried different model all got the same error

loading stable diffusion model: ValueError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 66, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 309, in load_model
    checkpoint_info = checkpoint_info._replace(config=checkpoint_config.replace(".yaml", "-inpainting.yaml"))
  File "/usr/lib/python3.8/collections/__init__.py", line 413, in _replace
    raise ValueError(f'Got unexpected field names: {list(kwds)!r}')
ValueError: Got unexpected field names: ['config']

Stable diffusion model failed to load, exiting

**Comment by TheLastBen** [comment]
which model are you using

**Comment by asmust** [comment]
I'm having the same issue. I've tried using SD 1.5 and Dreamlike's new photo realistic images. It looks like there is an issue importing the python module, but thats about the extent of what I understand.

**Comment by asmust** [comment]
`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 18, in <module>
    import modules.extras
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 20, in <module>
    from modules.ui import plaintext_to_html
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 23, in <module>
    from modules.ui_components import FormRow, FormGroup, ToolButton
ImportError: cannot import name 'FormGroup' from 'modules.ui_components' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_components.py)`

**Comment by ThanapatSornsrivichai** [comment]
> which model are you using

I tried 1.5 inpainting, and some other .ckpt or safetensor most of it is base on sd1.5

**Comment by ibadmore** [comment]
any info on fix for this? getting the same error with the same exact 1.5 Dreamlike model: https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0

**Comment by Jboby1** [comment]
> `Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 18, in <module> import modules.extras File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 20, in <module> from modules.ui import plaintext_to_html File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 23, in <module> from modules.ui_components import FormRow, FormGroup, ToolButton ImportError: cannot import name 'FormGroup' from 'modules.ui_components' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_components.py)`

Having this same error with the base 1.5 model.

**Comment by TheLastBen** [comment]
Try a clean run withe the latest colab, if the error persists, describe the steps to reproduce the error.

**Comment by Jboby1** [comment]
> Try a clean run with the latest colab, if the error persists, describe the steps to reproduce the error.

Getting a different error this time-- "ModuleNotFoundError" instead of "ImportError". Strange.

1. Deleted most of the files in my 'sd' folder for a near-clean run (keeping my "models" and "output" folders)
2. Ran the collab as normal, putting the path to my "models" folder in the Path_To_CKPT field and leaving all other options unchanged
3. Ran the "Start stable-diffusion" cell with the default options (1.5 model and "Use Gradio Server" checked)

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import import_hook, errors
ModuleNotFoundError: No module named 'modules'`

**Comment by Jboby1** [comment]
...it did.

Huh, must've missed a file while doing a near-clean run and that bungled something up.
