### ISSUE TITLE
Can't convert model to diffusers - 'rm: cannot remove '/content/stable-diffusion-custom': No such file or directory'

### ISSUE THREAD

**Issue by JD1234JD1234** [TheLastBen/fast-stable-diffusion#1257]
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1115, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1066, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 847, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias". 
	Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight". 
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error
Conversion error

using this model:

https://civitai.com/models/2661/uber-realistic-porn-merge-urpm

**Comment by User1231300** [comment]
Experiencing the same problem. Sadly even the hugginface converter is not working for me.

**Comment by User1231300** [comment]
What about circumventing the issue and directly introducing conversion from safetensors? Or that'd be a lot of work?

**Comment by ratsark** [comment]
I put together a one-line fix that's been letting me use Automatic1111-merged models with the colab. Add this line in the "Model Download" step immediately after the relevant `!wget -O convertodiff.py ...` line:

```
!sed -i 's/state_dict = checkpoint\["state_dict"\]/state_dict = checkpoint["state_dict"] if "state_dict" in checkpoint else checkpoint/g' /content/convertodiff.py
```

Basically this says "if there's no state_dict, use the root object instead" - Automatic1111 merges just dump everything into the root object rather then nesting them in state_dict.

NOTE: there are ~8 different places in the "Model Download" step that the convertodiff.py script gets downloaded. If you're not sure which one will be executed, just add it after each one. I myself spent a ton of time debugging issues with the `elif CKPT_Link !="":` branch when I should have been looking at `elif CKPT_Path !="":`, a classic blunder :)

@TheLastBen applying this to the repo should be a ~3 line change whenever you can find the time. Thank you for putting this together and maintaining it!

@User1231300 @JD1234JD1234 you should be able to adapt this workaround to your issue.

**Comment by JD1234JD1234** [comment]
@ratsark This doesn't work for me still getting the same error, here is my CKPT_Link code (I am using 'link' not 'path'):

`elif CKPT_Link !="":   
    %cd /content
    clear_output()     
    !gdown --fuzzy -O model.ckpt $CKPT_Link
    clear_output() 
    if os.path.exists('/content/model.ckpt'):
      if os.path.getsize("/content/model.ckpt") > 1110671599:
        if Custom_Model_Version=='1.5':
          !wget -O refmdlz https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/refmdlz
          !unzip -o -q refmdlz
          !rm -f refmdlz        
          !wget -O convertodiff.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/Dreambooth/convertodiffv1.py
          !sed -i 's/state_dict = checkpoint\["state_dict"\]/state_dict = checkpoint["state_dict"] if "state_dict" in checkpoint else checkpoint/g' /content/convertodiff.py
          clear_output()
          !python /content/convertodiff.py /content/model.ckpt /content/stable-diffusion-custom --v1
          !rm -r /content/refmdl
        elif Custom_Model_Version=='V2.1-512px':
          !wget -O convertodiff.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/Dreambooth/convertodiffv2.py
          !sed -i 's/state_dict = checkpoint\["state_dict"\]/state_dict = checkpoint["state_dict"] if "state_dict" in checkpoint else checkpoint/g' /content/convertodiff.py
          clear_output()
          !python /content/convertodiff.py /content/model.ckpt /content/stable-diffusion-custom --v2 --reference_model stabilityai/stable-diffusion-2-1-base
        elif Custom_Model_Version=='V2.1-768px':
          !wget -O convertodiff.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/Dreambooth/convertodiffv2.py
          !sed -i 's/state_dict = checkpoint\["state_dict"\]/state_dict = checkpoint["state_dict"] if "state_dict" in checkpoint else checkpoint/g' /content/convertodiff.py
          clear_output()
          !python /content/convertodiff.py /content/model.ckpt /content/stable-diffusion-custom --v2 --reference_model stabilityai/stable-diffusion-2-1
        !rm /content/convertodiff.py
        if os.path.exists('/content/stable-diffusion-custom/unet/diffusion_pytorch_model.bin'):
          clear_output()
          MODEL_NAME="/content/stable-diffusion-custom"
          print('[1;32mDONE !')
        else:
          !rm -r /content/stable-diffusion-custom
          !rm /content/model.ckpt
          while not os.path.exists('/content/stable-diffusion-custom/unet/diffusion_pytorch_model.bin'):
            print('[1;31mConversion error')
            time.sleep(5)
      else:
        while os.path.getsize('/content/model.ckpt') < 1110671599:
           print('[1;31mWrong link, check that the link is valid')
           time.sleep(5)`

**Comment by JD1234JD1234** [comment]
@ratsark For some reason, this code fixes it for 'HassanBlend' but not for 'URPM' Model. So still getting the same error for that model. But originally neither worked.

**Comment by TheLastBen** [comment]
I'll check it out soon, thanks

**Comment by JD1234JD1234** [comment]
does anyone know why @ratsark fix works for HassanBlend but not URPM?
