### ISSUE TITLE
Getting this error while i try to run AUTOMATIC1111

### ISSUE THREAD

**Issue by piler87** [TheLastBen/fast-stable-diffusion#126]
Moving __init__.py from /content/gdrive/MyDrive/sd/stable-diffusion-webui/gfpgan to /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/GFPGAN.
Moving train.py from /content/gdrive/MyDrive/sd/stable-diffusion-webui/gfpgan to /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/GFPGAN.
Moving utils.py from /content/gdrive/MyDrive/sd/stable-diffusion-webui/gfpgan to /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/GFPGAN.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
100% 5.10M/5.10M [00:00<00:00, 141MB/s]
Error verifying pickled file from /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 61, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 80, in load
    check_pt(filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 72, in check_pt
    unpickler.load()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 54, in find_class
    raise pickle.UnpicklingError(f"global '{module}/{name}' is forbidden")
_pickle.UnpicklingError: global 'torch._utils/_rebuild_tensor' is forbidden

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 82, in <module>
    shared.sd_model = modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 177, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/encoders/modules.py", line 7, in <module>
    import kornia
  File "/usr/local/lib/python3.7/dist-packages/kornia/__init__.py", line 10, in <module>
    from . import (
  File "/usr/local/lib/python3.7/dist-packages/kornia/augmentation/__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "/usr/local/lib/python3.7/dist-packages/kornia/augmentation/container/__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "/usr/local/lib/python3.7/dist-packages/kornia/augmentation/container/augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "/usr/local/lib/python3.7/dist-packages/kornia/augmentation/container/patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "/usr/local/lib/python3.7/dist-packages/kornia/contrib/__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "/usr/local/lib/python3.7/dist-packages/kornia/contrib/image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "/usr/local/lib/python3.7/dist-packages/kornia/feature/__init__.py", line 4, in <module>
    from .integrated import (
  File "/usr/local/lib/python3.7/dist-packages/kornia/feature/integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "/usr/local/lib/python3.7/dist-packages/kornia/feature/integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "/usr/local/lib/python3.7/dist-packages/kornia/feature/hardnet.py", line 69, in __init__
    self.load_state_dict(pretrained_dict['state_dict'], strict=True)
TypeError: 'NoneType' object is not subscriptable

**Comment by TheLastBen** [comment]
you're using an outdated Colab, remove the folder "sd" from your gdrive and do a clean run using the latest colab from the repo

**Comment by brianheney** [comment]
Sorry for the basic question, but I'm brand new to this and had some of the same of the same errors. So, I'm guessing I'm also using an outdated Colab. Where do find the latest colab? Or what/where is 'the repo'? 

Again, apologies for what is likely an obvious question, but I've never used any of this before this past week. Thanks in advance.

**Comment by TheLastBen** [comment]
You don't need to apologies, we're all here to learn and there is a first time for everything. In this page ; https://github.com/TheLastBen/fast-stable-diffusion scroll a bit down, you'll see a thumbnail titled AUTOMATIC1111, click on it, it will always redirect you to the latest Colab notebook.

**Comment by brianheney** [comment]
Thank you. Got it working. Very helpful.
