### ISSUE TITLE
Parent directory Stable-diffusion does not exist

### ISSUE THREAD

**Issue by aoura80530** [TheLastBen/fast-stable-diffusion#1267]
Having this suddenly. I believe it's from an update. It was working find 4 hours ago.
```
Converting to CKPT ...
Traceback (most recent call last):
  File "/content/convertosd.py", line 228, in <module>
    torch.save(state_dict, checkpoint_path)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion does not exist.
Something went wrong, try again
```

**Comment by TheLastBen** [comment]
try with a new sd folder and the latest colab

**Comment by aoura80530** [comment]
solved follwing your instruction, thanks.
