### ISSUE TITLE
Errors loading extensions

### ISSUE THREAD

**Issue by CJohnDesign** [TheLastBen/fast-stable-diffusion#1293]
To recreate
* I've got a fresh copy of the notebook. 
* I ran A1111 without gradio to install the Deforum and Dreambooth extensions. 
** successfully installed
* restart and apply
** tabs don't show.

Errors I get:
```
Error loading script: deforum.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 20, in <module>
    from deforum_helpers.save_images import dump_frames_cache, reset_frames_cache
ModuleNotFoundError: No module named 'deforum_helpers'

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 24, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import FilenameTextGetter
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 35, in <module>
    class PromptData:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 42, in PromptData
    resolution:tuple[int, int] = (512, 512)
TypeError: 'type' object is not subscriptable

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 16, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.finetune_utils import ImageBuilder, PromptData, generate_dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 35, in <module>
    class PromptData:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/finetune_utils.py", line 42, in PromptData
    resolution:tuple[int, int] = (512, 512)
TypeError: 'type' object is not subscriptable

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 8, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_webhook import save_and_test_webhook
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_webhook.py", line 9, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'
```

I found this issue but it only addresses 2 of the 4 errors: https://github.com/TheLastBen/fast-stable-diffusion/issues/1245

**Comment by CJohnDesign** [comment]
Opened an issue on the extension: https://github.com/d8ahazard/sd_dreambooth_extension/issues/496

**Comment by TheLastBen** [comment]
I'll try to fix the deforum extension
