### ISSUE TITLE
Not able to test any current/saved session

### ISSUE THREAD

**Issue by yamanahlawat** [TheLastBen/fast-stable-diffusion#1295]
While testing the model

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading100% 961k/961k [00:01<00:00, 717kB/s]
Downloading100% 525k/525k [00:01<00:00, 475kB/s]
Downloading100% 389/389 [00:00<00:00, 352kB/s]
Downloading100% 905/905 [00:00<00:00, 804kB/s]
Loading weights [f4917ce8] from /content/gdrive/MyDrive/Fast-Dreambooth/Sessions/somename/somename.ckpt`

Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 210, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 147, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 83, in initialize
    shared.opts.onchange("temp_dir", ui_tempdir.on_tmpdir_changed)
AttributeError: module 'modules.ui_tempdir' has no attribute 'on_tmpdir_changed'

**Comment by yamanahlawat** [comment]
if you are running it on colab, delete the **_stable-diffusion-webui_** folder from your google drive.
