### ISSUE TITLE
Error "save_training_settings_to_txt" on training

### ISSUE THREAD

**Issue by yakua912** [TheLastBen/fast-stable-diffusion#1296]
Latest repo
sd folder removed as a fresh start
created a new embedding
start training
```
Textual inversion embeddings loaded(1): RocksyLight
Training at rate of 0.005 until step 100000
Preparing dataset...
100% 14/14 [00:16<00:00,  1.20s/it]
Applying xformers cross attention optimization.
Error completing request
Arguments: ('RocksyLight', '0.005', 1, 1, '/content/gdrive/MyDrive/Processed/RocksyLight', 'textual_inversion', 512, 512, 100000, 'disabled', '0.1', False, 0, 'once', 500, 500, '/content/gdrive/MyDrive/sd/stable-diffusion-webui/textual_inversion_templates/style_filewords.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/ui.py", line 33, in train_embedding
    embedding, filename = modules.textual_inversion.textual_inversion.train_embedding(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 315, in train_embedding
    if shared.opts.save_training_settings_to_txt:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 489, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'save_training_settings_to_txt'
```

**Comment by TheLastBen** [comment]
That must be an issue with the A1111 repo, I'm sure they will fix it soon

**Comment by yakua912** [comment]
I'm having two colabs opened now and one is traing while this one still has the same error.

**Comment by yakua912** [comment]
Just tested and I found this particularly not working even I removed everything from th gdrive and re-uploaded. Weird.
