### ISSUE TITLE
FormHTML error

### ISSUE THREAD

**Issue by Robb1010** [TheLastBen/fast-stable-diffusion#1302]
Looks like there's an error preventing the start:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 23, in <module>
    import modules.extras
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 20, in <module>
    from modules.ui import plaintext_to_html
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 23, in <module>
    from modules.ui_components import FormRow, FormGroup, ToolButton, FormHTML
ImportError: cannot import name 'FormHTML' from 'modules.ui_components' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_components.py)
```

**Comment by TheLastBen** [comment]
try a clean run, new sd folder and latest colab

**Comment by Robb1010** [comment]
@TheLastBen That worked, thank you!
