### ISSUE TITLE
No module named 'gradio'

### ISSUE THREAD

**Issue by Panchor1** [TheLastBen/fast-stable-diffusion#131]
I get this error when I want to run the webui again
I am not using gradio servers

sed: can't read /usr/local/lib/python3.7/dist-packages/gradio/blocks.py: No such file or directory
sed: can't read /usr/local/lib/python3.7/dist-packages/gradio/blocks.py: No such file or directory
sed: can't read /usr/local/lib/python3.7/dist-packages/gradio/blocks.py: No such file or directory
sed: can't read /usr/local/lib/python3.7/dist-packages/gradio/strings.py: No such file or directory
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/stable-diffusion-webui/scripts/Relaxed.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
  File "/content/gdrive/MyDrive/stable-diffusion-webui/scripts/frontend/frontend.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

**Comment by Panchor1** [comment]
the only solution I find is to delete the sd folder and reinstall everything
