### ISSUE TITLE
AttributeError: 'Options' object has no attribute 'save_training_settings_to_txt'

### ISSUE THREAD

**Issue by onezerotwothree** [TheLastBen/fast-stable-diffusion#1310]
New Google account
Latest webui
When train:
```
Training at rate of 0.005 until step 100000
Preparing dataset...
100% 16/16 [00:10<00:00,  1.49it/s]
Applying xformers cross attention optimization.
Error completing request
Arguments: ('huang_duoduo', '0.005', 1, 1, '/content/gdrive/MyDrive/Processed/Huang-Duoduo', 'textual_inversion', 512, 512, 100000, 'disabled', '0.1', False, 0, 'once', 500, 500, '/content/gdrive/MyDrive/sd/stable-diffusion-webui/textual_inversion_templates/style_filewords.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/ui.py", line 33, in train_embedding
    embedding, filename = modules.textual_inversion.textual_inversion.train_embedding(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 314, in train_embedding
    if shared.opts.save_training_settings_to_txt:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 489, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'save_training_settings_to_txt'
```

**Comment by jcplus** [comment]
Still happening to me

**Comment by TheLastBen** [comment]
That must be caused by this  https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/6372
disable the option "save texutal invesion ... settings"
clique on the screenshot in the thread above to preview how to

**Comment by jcplus** [comment]
Thanks. It starts working as before now since this morning though I didn't find where to change the option "save texutal invesion ... settings".
