### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by hundkillen** [TheLastBen/fast-stable-diffusion#1317]
On google colab (standard plan) i've been getting this error the last couple of weeks, when trying to run stable diffusion
Im guessing its a memory issue?
Do i need to run the pro-plan now to get it to work?
always using the latest update

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 109, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 210, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 147, in webui
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 59, in initialize
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 41, in setup_model
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 89, in list_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 110, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

**Comment by TheLastBen** [comment]
If the error persists, try a different browser.

**Comment by hundkillen** [comment]
unfortunately the problem persists. I usually use chrome, and then it gave me that error, tried for around 2 weeks. same.
Tried safari per your instructions, same issue.
it goes for a while, then I can see the ram-bar filling up in cola, then it maxes out and I get the error.
Any other ideas?

**Comment by TheLastBen** [comment]
run it without gdrive and see if it works, instead of running the first cell (gdrive), skip it and create a new cell like this : 

`!mkdir -p /content/gdrive/MyDrive`

**Comment by TheLastBen** [comment]
also cleaning the browser cookies should fix it, but all your websites settings will reset if you do that.
