### ISSUE TITLE
Unable to save new mixed embeddings - embedding inspector

### ISSUE THREAD

**Issue by Topzie** [TheLastBen/fast-stable-diffusion#1325]
Error:
Error saving "embeddings/colorat1.pt (filename might be invalid)

Terminal output:

Error executing callback ui_tabs_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-embedding-editor/scripts/embedding_editor.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 104, in ui_tabs_callback
    res += c.callback() or []
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-embedding-editor/scripts/embedding_editor.py", line 70, in on_ui_tabs
    determine_embedding_distribution()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-embedding-editor/scripts/embedding_editor.py", line 39, in determine_embedding_distribution
    embedding_layer = cond_model.wrapped.transformer.text_model.embeddings
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FrozenOpenCLIPEmbedder' object has no attribute 'transformer'

**Comment by herbertwestern** [comment]
I have this problem too.

**Comment by Topzie** [comment]
It works now, thank you very much!
