### ISSUE TITLE
train_embedding() missing 1 required positional argument: 'preview_height'

### ISSUE THREAD

**Issue by daspaise** [TheLastBen/fast-stable-diffusion#1330]
I was training a model yesterday and everything works fine. Then I run out of free GPU on my account so I turned it off. This morning (about 10 hours after) I started the same colab as normal. Nothing strange happened until I chose the embedding from yesterday and clicked the Train Embedding button.
I always use default settings so the only thing I changed in the interface is entered the dataset path.
Error is as below:
```
Arguments: ('yu_fan', '0.005', 1, 1, '/content/gdrive/MyDrive/Processed/Yu-Fan', 'textual_inversion', 512, 512, 100000, 'disabled', '0.1', False, 0, 'once', 500, 500, '/content/gdrive/MyDrive/sd/stable-diffusion-webui/textual_inversion_templates/style_filewords.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/ui.py", line 33, in train_embedding
    embedding, filename = modules.textual_inversion.textual_inversion.train_embedding(*args)
TypeError: train_embedding() missing 1 required positional argument: 'preview_height'
```

**Comment by daspaise** [comment]
Restarting didn't help.
Removed sd folder and copied the embedding file into.  Then restarted the colab works.
I still don't know why. Curious.
