### ISSUE TITLE
test the trained model error

### ISSUE THREAD

**Issue by hero5111** [TheLastBen/fast-stable-diffusion#1333]
I've got below error when running google collab notebook

Does anyone know how to fix?

**Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import import_hook, errors
ModuleNotFoundError: No module named 'modules'**

Test The Trained Model

import os
import time
import sys
import fileinput
from IPython.display import clear_output
from subprocess import getoutput
from IPython.utils import capture

Model_Version = "1.5" #@param ["1.5", "V2.1-512", "V2.1-768"]
#@markdown  - Important! Choose the correct version and resolution of the model

Update_repo = True

Session__Name="test" #@param{type: 'string'}

#@markdown - Leave empty if you want to use the current trained model.

Use_Custom_Path = True #@param {type:"boolean"}

try:
  INSTANCE_NAME
  INSTANCET=INSTANCE_NAME  
except:
  pass
#@markdown - if checked, an input box will ask the full path to a desired model.

if Session__Name!="":
  INSTANCET=Session__Name
  INSTANCET=INSTANCET.replace(" ","_")

if Use_Custom_Path:
  try:
    INSTANCET
    del INSTANCET
  except:
    pass

try:
  INSTANCET
  if Session__Name!="":
    path_to_trained_model='/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/'+Session__Name+"/"+Session__Name+'.ckpt'
  else:
    path_to_trained_model=SESSION_DIR+"/"+INSTANCET+'.ckpt'
except:
  print('[1;31mIt seems that you did not perform training during this session [1;32mor you chose to use a custom path,\nprovide the full path to the model (including the name of the model):\n')
  path_to_trained_model=input()
     
while not os.path.exists(path_to_trained_model):
   print("[1;31mThe model doesn't exist on you Gdrive, use the file explorer to get the path : ")
   path_to_trained_model=input()

         
with capture.capture_output() as cap:
    %cd /content/gdrive/MyDrive/
    %mkdir sd
    %cd sd
    !git clone https://github.com/Stability-AI/stablediffusion
    !git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
    %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/
    !mkdir -p cache/{huggingface,torch}
    %cd /content/
    !ln -s /content/gdrive/MyDrive/sd/stable-diffusion-webui/cache/huggingface ../root/.cache/
    !ln -s /content/gdrive/MyDrive/sd/stable-diffusion-webui/cache/torch ../root/.cache/

if Update_repo:
  with capture.capture_output() as cap:
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.sh
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/style.css
    !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py
    %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/
  print('[1;32m')
  !git pull

with capture.capture_output() as cap:
  
  if not os.path.exists('/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion'):
    !mkdir /content/gdrive/MyDrive/sd/stablediffusion/src
    %cd /content/gdrive/MyDrive/sd/stablediffusion/src
    !git clone https://github.com/CompVis/taming-transformers
    !git clone https://github.com/openai/CLIP
    !git clone https://github.com/salesforce/BLIP
    !git clone https://github.com/sczhou/CodeFormer
    !git clone https://github.com/crowsonkb/k-diffusion
    !mv /content/gdrive/MyDrive/sd/stablediffusion/src/CLIP /content/gdrive/MyDrive/sd/stablediffusion/src/clip
    !mv  /content/gdrive/MyDrive/sd/stablediffusion/src/BLIP /content/gdrive/MyDrive/sd/stablediffusion/src/blip
    !mv  /content/gdrive/MyDrive/sd/stablediffusion/src/CodeFormer /content/gdrive/MyDrive/sd/stablediffusion/src/codeformer
    !cp -r /content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion /content/gdrive/MyDrive/sd/stable-diffusion-webui/

with capture.capture_output() as cap:    
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules
  !wget -O paths.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/AUTOMATIC1111_files/paths.py

with capture.capture_output() as cap:
  if not os.path.exists('/tools/node/bin/lt'):
    !npm install -g localtunnel

with capture.capture_output() as cap:
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/
  !wget -O webui.py https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.py
  !sed -i 's@ui.create_ui().*@ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/
  !wget -O shared.py https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/modules/shared.py
  !wget -O ui.py https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/modules/ui.py
  !sed -i 's@css = "".*@with open(os.path.join(script_path, "style.css"), "r", encoding="utf8") as file:\n        css = file.read()@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui
  !wget -O style.css https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/style.css
  !sed -i 's@min-height: 4.*@min-height: 5.5em;@g' /content/gdrive/MyDrive/sd/stable-diffusion-webui/style.css
  !sed -i 's@"multiple_tqdm": true,@\"multiple_tqdm": false,@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/config.json
  !sed -i '902s@.*@        self.logvar = self.logvar.to(self.device)@' /content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py
  if os.path.exists("/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension"):
    %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/openOutpaint-webUI-extension/scripts
    !wget -O main.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/AUTOMATIC1111_files/outpaint/main.py
  %cd /content

Use_Gradio_Server = True #@param {type:"boolean"}
#@markdown  - Only if you have trouble connecting to the local server.

Large_Model= False #@param {type:"boolean"}
#@markdown  - Check if you have trouble loading a model 7GB+

if Large_Model:
  !sed -i 's@cmd_opts.lowram else \"cpu\"@cmd_opts.lowram else \"cuda\"@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py
else:
  !sed -i 's@cmd_opts.lowram else \"cuda\"@cmd_opts.lowram else \"cpu\"@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py

share=''
if Use_Gradio_Server:
  share='--share'
  for line in fileinput.input('/usr/local/lib/python3.8/dist-packages/gradio/blocks.py', inplace=True):
    if line.strip().startswith('self.server_name ='):
        line = '            self.server_name = server_name\n'
    if line.strip().startswith('self.server_port ='):
        line = '            self.server_port = server_port\n'
    sys.stdout.write(line)
  clear_output()
  
else:
  share=''
  !nohup lt --port 7860 > srv.txt 2>&1 &
  time.sleep(2)
  !grep -o 'https[^ ]*' /content/srv.txt >srvr.txt
  time.sleep(2)
  srv= getoutput('cat /content/srvr.txt')

  for line in fileinput.input('/usr/local/lib/python3.8/dist-packages/gradio/blocks.py', inplace=True):
    if line.strip().startswith('self.server_name ='):
        line = f'            self.server_name = "{srv[8:]}"\n'
    if line.strip().startswith('self.server_port ='):
        line = '            self.server_port = 443\n'
    if line.strip().startswith('self.protocol = "https"'):
        line = '            self.protocol = "https"\n'
    if line.strip().startswith('if self.local_url.startswith("https") or self.is_colab'):
        line = ''    
    if line.strip().startswith('else "http"'):
        line = ''              
    sys.stdout.write(line)
    

  !sed -i '13s@.*@    "PUBLIC_SHARE_TRUE": "[32mConnected",@' /usr/local/lib/python3.8/dist-packages/gradio/strings.py
  
  !rm /content/srv.txt
  !rm /content/srvr.txt
  clear_output()

with capture.capture_output() as cap:
  %cd /content/gdrive/MyDrive/sd/stablediffusion/

if Model_Version == "V2.1-768":
  configf="--config /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference-v.yaml"
  !sed -i 's@def load_state_dict(checkpoint_path: str, map_location.*@def load_state_dict(checkpoint_path: str, map_location="cuda"):@' /usr/local/lib/python3.8/dist-packages/open_clip/factory.py
  NM="True"
elif Model_Version == "V2.1-512":
  configf="--config /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference.yaml"
  !sed -i 's@def load_state_dict(checkpoint_path: str, map_location.*@def load_state_dict(checkpoint_path: str, map_location="cuda"):@' /usr/local/lib/python3.8/dist-packages/open_clip/factory.py
  NM="True"
else:
  configf=""
  !sed -i 's@def load_state_dict(checkpoint_path: str, map_location.*@def load_state_dict(checkpoint_path: str, map_location="cpu"):@' /usr/local/lib/python3.8/dist-packages/open_clip/factory.py
  NM="False"

if os.path.exists('/usr/local/lib/python3.8/dist-packages/xformers'):
  xformers="--xformers" 
else:
  xformers=""

if os.path.isfile(path_to_trained_model):
  !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --no-half-vae --enable-insecure-extension-access  --ckpt "$path_to_trained_model" $configf $xformers
else:
  !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --no-half-vae --enable-insecure-extension-access --ckpt-dir "$path_to_trained_model" $configf $xformers

**Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import import_hook, errors
ModuleNotFoundError: No module named 'modules'**

**Comment by TheLastBen** [comment]
remove the sd folder and do a clean run, make sure you have run the session cell
