### ISSUE TITLE
Can't Merge CKPT

### ISSUE THREAD

**Issue by KuzeyVural** [TheLastBen/fast-stable-diffusion#1337]
Can't even merge 4gb models because out of ram, should I use colab pro or any solutions? I can't afford that.

It shows something like that waiting some time after Loading models...:
C^

**Comment by KuzeyVural** [comment]
Any changes to merge larger models?

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/9961920f058b5ff6046ef680caee0949cde82ba2 fixed yesterday

**Comment by KuzeyVural** [comment]
I merged 7G and 2G models without errors thank you for that. My question is, is 7G and 4G model merging impossible? I've tried I know it may be extreme but is it possible?

**Comment by TheLastBen** [comment]
7+4=11 so it might work since the T4 has 15GB (minus the used space)

**Comment by KuzeyVural** [comment]
Tried sadly it didnt worked :(

**Comment by TheLastBen** [comment]
Before doing the merge, try selecting the 7GB model in the model selector first, then do the merging.

**Comment by KuzeyVural** [comment]
I'll try it now 👍

**Comment by KuzeyVural** [comment]
Merging...
 18% 336/1831 [00:00<00:01, 1215.72it/s]
Error loading/saving model file:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1690, in modelmerger
    results = modules.extras.run_modelmerger(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 347, in run_modelmerger
    theta_0[key] = theta_func2(a, b, multiplier)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 282, in weighted_sum
    return ((1 - alpha) * theta0) + (alpha * theta1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 14.76 GiB total capacity; 13.61 GiB already allocated; 79.75 MiB free; 14.10 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by KuzeyVural** [comment]
Tried it but didnt work

**Comment by TheLastBen** [comment]
I guess you'll have to merge the pruned version of one of the models

**Comment by KuzeyVural** [comment]
I don't know how to prune on colab

**Comment by TheLastBen** [comment]
try to find the 2gb version of one of the models on huggingface

**Comment by KuzeyVural** [comment]
It's not on huggingface sadly
