### ISSUE TITLE
Can't Resume Training

### ISSUE THREAD

**Issue by InternalMegaT** [TheLastBen/fast-stable-diffusion#1340]
I'm keep getting this error when trying to resume training. Over an over again. I deleted the model countless times and restarted completely. I don't think this is an error that I'm causing it has to be a colab error. As I have deleted the model several times. Please fix this. I'm also on the account that the files are stored so I don't know why it says Parent directory does not exist.
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1107, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1076, in convert
    key_count = save_stable_diffusion_checkpoint(v2_model, args.model_to_save, text_encoder, unet,
  File "/content/convertodiff.py", line 1013, in save_stable_diffusion_checkpoint
    torch.save(new_ckpt, output_file)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/models does not exist.

**Comment by InternalMegaT** [comment]
Also, I can start the model initially, but I just can't resume it.

**Comment by TheLastBen** [comment]
the model is corrupt, you need a clean run with a new model

**Comment by InternalMegaT** [comment]
> the model is corrupt, you need a clean run with a new model

As I said before. I have ran a new model several times. Still the same thing

**Comment by TheLastBen** [comment]
an original model or a custom one ?

**Comment by InternalMegaT** [comment]
> an original model or a custom one ?

An original model

**Comment by InternalMegaT** [comment]
I found the issue. Its because the model name had of "." in it and it though it was the ckpt file name or something like that. I removed the period and it worked.

**Comment by InternalMegaT** [comment]
For example "ExampleVersion2.1.ckpt" now "Example Version21.ckpt"
