### ISSUE TITLE
Trouble running v1.5

### ISSUE THREAD

**Issue by archimedesinstitute** [TheLastBen/fast-stable-diffusion#1346]
Hey there! I got this error when running v1.5 - I have redownloaded the model.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 390, in <module>
    "img2img_background_color": OptionInfo("#ffffff", "With img2img, fill image's transparent parts with this color.", ui_components.FormColorPicker, {}),
AttributeError: module 'modules.ui_components' has no attribute 'FormColorPicker'

**Comment by brunakrc** [comment]
I have the same error

**Comment by juvesatriani** [comment]
I have same error , Last time I`ve used  without trouble was around 8-10 hours ago  . 
Anyone have temporary solutions? Should I Uncomment those lines which caused error ?

**Comment by paulmaestas** [comment]
im am getting the same error too

**Comment by nativenoble** [comment]
same here

**Comment by TheLastBen** [comment]
remove/rename the folder sd and do a clean run

**Comment by xcreateadmin** [comment]
> remove/rename the folder sd and do a clean run

Still same issue:

```
2023-01-11 12:52:55.106873: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading100% 961k/961k [00:00<00:00, 5.40MB/s]
Downloading100% 4.52k/4.52k [00:00<00:00, 4.13MB/s]
Failed to create model quickly; will retry using slow method.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
loading stable diffusion model: TypeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 74, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 345, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1777, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1932, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/tokenization_clip.py", line 328, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType


Stable diffusion model failed to load, exiting
```

**Comment by TheLastBen** [comment]
caused by the A1111 update: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0f8603a55988d22616b17140e6c4a7e9d0736af5#diff-842cdc48bd0fd92766c5b52f6c1b2502702330268319577f69380c1079f07a57

**Comment by brunakrc** [comment]
I'm still getting the same error, have you found a solution?

**Comment by TheLastBen** [comment]
use the latest colab and remove the folder sd

**Comment by archimedesinstitute** [comment]
I’m no longer having issues

**Comment by Gushousekai195** [comment]
> use the latest colab and remove the folder sd

RIP my custom styles

**Comment by TheLastBen** [comment]
you can rename the folder and copy the custom styles after the fresh run
