### ISSUE TITLE
Cannot continously render in extra mode

### ISSUE THREAD

**Issue by jcplus** [TheLastBen/fast-stable-diffusion#135]
I know there is an open case related to `websocket.close` but I believe this is a different case.

**Error below**

```
Task exception was never retrieved
future: <Task finished coro=<Queue.process_event() done, defined at /usr/local/lib/python3.7/dist-packages/gradio/queue.py:222> exception=RuntimeError("Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 275, in process_event
    await event.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 305, in disconnect
    await self.websocket.close(code=code)
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 181, in close
    {"type": "websocket.close", "code": code, "reason": reason or ""}
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 316, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
```

**Steps to reproduce**

1. Prepare a large image. I used image width 1600px and 2048px.
2. Open a new tab and click into the **Extras** mode.
3. Load the prepared image into the **Single Source** window.
4. Set *Resize* to 4.
5. Choose **ScuNET PSNR** in *Upscaler1* and *Upscaler2*
6. I left the *GFPGAN visibility*, *CodeFormer visibility*, and *CodeFormer weight* to default (0)
7. Click **Generate**.
8. This will work. Once it's done and the generated image is downloadable, click the **Generate** again.
9. You will see the *error*.

**Comment by TheLastBen** [comment]
Adding the queue parameter  to gradio fixed the freezing when doing large batches, but causes some issues in the "Extras" tab, if there is no quick direct solution, I will add the option to disable the queue.

**Comment by jcplus** [comment]
I'm not sure but could it be possible to add someting to clear the `queue`, `cache`, or `anything that could _block_` when the **Generate** button is clicked if that can kind of fix the issue?

**Comment by TheLastBen** [comment]
I reproduced the error but it doesn't stop me from generating again

**Comment by jcplus** [comment]
I'm using T4. If you are using higher than mine, then it's a hardware limit. I will close this ticket.

**Comment by TheLastBen** [comment]
I'm using the T4 and the "websocket.close" message isn't causing a freeze
