### ISSUE TITLE
Colab issue tried several times , still no results!

### ISSUE THREAD

**Issue by MrAshbury20** [TheLastBen/fast-stable-diffusion#1351]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 17, in <module>
    from modules import localization, sd_vae, extensions, script_loading, errors, ui_components
ImportError: cannot import name 'ui_components' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
remove/rename the folder sd in your gdrive and do a clean run with the latest colab from the repo
