### ISSUE TITLE
Please help,everything worked fine until the new version is updated，Thank you very much for your work！

### ISSUE THREAD

**Issue by yanfma123** [TheLastBen/fast-stable-diffusion#1353]
Traceback (most recent call last):
  File "launch.py", line 308, in <module>
    start()
  File "launch.py", line 303, in start
    webui.webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 150, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 86, in initialize
    shared.opts.onchange("temp_dir", ui_tempdir.on_tmpdir_changed)
AttributeError: module 'modules.ui_tempdir' has no attribute 'on_tmpdir_changed'

**Comment by yanfma123** [comment]
After loading model， I couldn't get the website address
