### ISSUE TITLE
Annoying issue where an image renders but CUDA runs out of memry upon completion

### ISSUE THREAD

**Issue by Taikakim** [TheLastBen/fast-stable-diffusion#1354]
Just this... With large resolutions it often happens that the image renders ok and finishes the highres.fix phase, but then the notebook crashes before being able to save the image:

Here it was resize: from 512x640 to 2048x2560 with latent resize with a 16GB T4.

```
INFO:dynamic_prompting.py:Prompt matrix will create 1 images in a total of 1 batches.
100% 70/70 [01:26<00:00,  1.24s/it]
100% 30/30 [1:04:56<00:00, 129.87s/it]
Error completing request
Arguments:*the prompt was here*** 'None', 'None', 70, 14, False, False, 1, 1, 9, -1.0, -1.0, 0, 0, 0, False, 640, 512, True, 0.38, 4, 'Latent', 30, 0, 0, 0, '<div class="dynamic-prompting">\n    <h3><strong>Combinations</strong></h3>\n\n    Choose a number of terms from a list, in this case we choose two artists: \n    <code class="codeblock">{2$$artist1|artist2|artist3}</code><br/>\n\n    If $$ is not provided, then 1$$ is assumed.<br/><br/>\n\n    If the chosen number of terms is greater than the available terms, then some terms will be duplicated, otherwise chosen terms will be unique. This is useful in the case of wildcards, e.g.\n    <code class="codeblock">{2$$__artist__}</code> is equivalent to <code class="codeblock">{2$$__artist__|__artist__}</code><br/><br/>\n\n    A range can be provided:\n    <code class="codeblock">{1-3$$artist1|artist2|artist3}</code><br/>\n    In this case, a random number of artists between 1 and 3 is chosen.<br/><br/>\n\n    Options can be given weights:\n    <code class="codeblock">{2::artist1|artist2}</code><br/>\n    In this case, artist1 will be chosen twice as often as artist2.<br/><br/>\n\n    Wildcards can be used and the joiner can also be specified:\n    <code class="codeblock">{{1-$$and$$__adjective__}}</code><br/>\n\n    Here, a random number between 1 and 3 words from adjective.txt will be chosen and joined together with the word \'and\' instead of the default comma.\n\n    <br/><br/>\n\n    <h3><strong>Wildcards</strong></h3>\n    Find and manage wildcards in the Wildcards Manager tab.\n\n    <br/><br/>\n\n    <small>You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/wildcards. <code class="codeblock">__&#60;folder&#62;/mywildcards__</code> will then become available.</small>\n</div>\n\n', True, True, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, False, False, False, False, False, False, False, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 610, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 610, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 408, in decode_first_stage
    x = model.decode_first_stage(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/model.py", line 641, in forward
    h = self.up[i_level].upsample(h)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/model.py", line 64, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 5.00 GiB (GPU 0; 14.76 GiB total capacity; 8.44 GiB already allocated; 2.86 GiB free; 10.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by TheLastBen** [comment]
what is the max resolution you can reach without crashing ?

**Comment by Taikakim** [comment]
One thing I realised is that I'm running Prototgen 5.8 which is big, but it seems to take the full amount of GPU memory only upon loading it the first time, after doing any render operation it takes even less than 3GB of GPU memory, depending on I don't know what.

I'm now right now rendering this: (on Colab Pro with standard RAM, but that should not affect this compared to PAYG)

DPM++ SDE Karras 512x512px scaled by 3,5x (using the scaling slider) to 1740px , R-ESRGAN 4x+
Memory usage of the GPU:
1st pass: 4330
Upscale: 7146 (?)
2nd pass: 9774 (between scale and 2nd pass did catch 11374 at one point around step 0 of 2nd pass, according to that graph it did jump a lot in between there, probably over 14BG at least)
After finishing 2nd pass: 13750

Maybe something similar happens when finishing the second pass and trying to get the image out of GPU memory, or something? 

Here's a screenshot of the GPU usage: https://ibb.co/B2kd8mq
In this case it seems that the biggest spike was between the upscale and the 2nd pass, although I often have cases too where the crash happes after the last step of the 2nd pass.

**Comment by Taikakim** [comment]
I've been testing this, and it's a bit inconsistent, either the new notebooks from the past few days are somehow more memory hungry, but now it happens that even with smaller models than that test above (4GB vs 7.5GB) I've had to even further decrease the upscale size to prevent out of memory errors with LDSR. It would be nice if this could be beforehand somehow prevented. Now it can also happen in the middle of render of the 2nd pass, like at step 8/50 suddenly I get an out of memory error even though several gigabytes are still free. I don't know if the amount of tokens affects memory use? My prompts are long.
