### ISSUE TITLE
Start error.

### ISSUE THREAD

**Issue by DervlexArt** [TheLastBen/fast-stable-diffusion#1367]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 213, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 150, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 86, in initialize
    shared.opts.onchange("temp_dir", ui_tempdir.on_tmpdir_changed)
AttributeError: module 'modules.ui_tempdir' has no attribute 'on_tmpdir_changed'

Any idea how to fix this ? 
Coming when i try to start the collab at the " Start stable-diffusion " section.

**Comment by TheLastBen** [comment]
new sd folder and latest colab
