### ISSUE TITLE
Models issue (when try to open a model on colab I get this problem every time)

### ISSUE THREAD

**Issue by MrAshbury20** [TheLastBen/fast-stable-diffusion#1369]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [8d1934c1] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
loading stable diffusion model: UnpicklingError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 74, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 350, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 206, in load_model_weights
    sd = read_state_dict(checkpoint_file)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 183, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xcf'.

Stable diffusion model failed to load, exiting

**Comment by TheLastBen** [comment]
all the models or this specific model ?

**Comment by MrAshbury20** [comment]
not all, just some models, for now I tested 4 with the same issue, the others work fine

**Comment by TheLastBen** [comment]
did you download them from civitai or huggingface ?

**Comment by MrAshbury20** [comment]
yep! from Civitai all of them.

**Comment by TheLastBen** [comment]
try downloading one of them from huggingface and see if it works
