### ISSUE TITLE
Dreambooth error

### ISSUE THREAD

**Issue by hushbook** [TheLastBen/fast-stable-diffusion#1371]
Updating 7ec275f..82725f0
error: Your local changes to the following files would be overwritten by merge:
	modules/ui.py
Please commit your changes or stash them before you merge.

What I should do? This appears after I trained my Dreambooth model.

**Comment by hushbook** [comment]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 17, in <module>
    from modules import localization, sd_vae, extensions, script_loading, errors, ui_components
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_vae.py", line 6, in <module>
    from modules import shared, devices, script_callbacks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors
ImportError: cannot import name 'sd_disable_initialization' from 'modules' (unknown location)

Full log after

**Comment by TheLastBen** [comment]
remove the file modules/ui.py to allow the update and fix the issues

**Comment by hushbook** [comment]
> remove the file modules/ui.py to allow the update and fix the issues

Worked, thanks.
