### ISSUE TITLE
No Gradio/local tunnel link being created.

### ISSUE THREAD

**Issue by katyusha020** [TheLastBen/fast-stable-diffusion#1376]
I have tried pretty much everything but no matter what i try, even with everything running no gradio link is created id like no know what should i do in this case.

**Comment by TheLastBen** [comment]
Copy the error/output here

**Comment by katyusha020** [comment]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import import_hook, errors
ImportError: cannot import name 'import_hook' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
Use the latest colab, I added an update to fix that

**Comment by katyusha020** [comment]
now i got this: Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers, upscaler
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 10, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 14, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 14, in <module>
    import modules.sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes
ImportError: cannot import name 'sd_vae' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
stop then rerun the colab by skipping the first cell and try to reproduce the error

**Comment by katyusha020** [comment]
now it works

**Comment by jirat-sumitanun** [comment]
> now i got this: Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in from modules import devices, sd_samplers, upscaler File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 10, in from modules import prompt_parser, devices, processing, images File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 14, in import modules.sd_hijack File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in import modules.textual_inversion.textual_inversion File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in from modules import shared, devices, sd_hijack, processing, sd_models, images File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 14, in import modules.sd_models File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in from modules import shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes ImportError: cannot import name 'sd_vae' from 'modules' (unknown location)

```
from google.colab import drive
drive.mount('/content/gdrive')
```
first cell, change '/content/gdrive' to 'content/drive'

**Comment by TheLastBen** [comment]
@jirat-sumitanun  why ?
