### ISSUE TITLE
'modules.ui_components' has no attribute 'FormColorPicker

### ISSUE THREAD

**Issue by makeoo1** [TheLastBen/fast-stable-diffusion#1377]
Hey, i am getting this error since last night. 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 393, in <module>
    "img2img_background_color": OptionInfo("#ffffff", "With img2img, fill image's transparent parts with this color.", ui_components.FormColorPicker, {}),
AttributeError: module 'modules.ui_components' has no attribute 'FormColorPicker'

can I pls ask if someone could help?
i replaced already the "webui.py" with the one i have on my local machine but still same error

TYSM!

**Comment by makeoo1** [comment]
![werew](https://user-images.githubusercontent.com/113861865/212445725-2a42145c-6a0f-4631-9e96-7c781d4944d7.png)

**Comment by TheLastBen** [comment]
Try renaming the folder sd

**Comment by hushbook** [comment]
Same error

**Comment by makeoo1** [comment]
Hey, i tried but didn't work. 

Do you have any other ideas pls?? 

it's so wired, it worked always without an issue and then out of nowhere i am getting this error :/ 

THX!


> Try renaming the folder sd

**Comment by TheLastBen** [comment]
are you using the latest colab ?

**Comment by makeoo1** [comment]
> are you using the latest colab ?

 i am using the link to colab from your github page.

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
disconnect from the colab runtime, then run it again but this time skip the first cell, if it works, that means the folder sd wasn't correctly removed/renamed in your gdrive

**Comment by makeoo1** [comment]
> disconnect from the colab runtime, then run it again but this time skip the first cell, if it works, that means the folder sd wasn't correctly removed/renamed in your gdrive

it worked! 

this means that to avoid problems i should just deleate the sd folder from my drive and run the notebook again, correct?

TSYM for the quick aswer!
