### ISSUE TITLE
Error trying to start stable diffusion

### ISSUE THREAD

**Issue by Barry-Bot1** [TheLastBen/fast-stable-diffusion#1381]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 394, in <module>
    "img2img_background_color": OptionInfo("#ffffff", "With img2img, fill image's transparent parts with this color.", ui_components.FormColorPicker, {}),
AttributeError: module 'modules.ui_components' has no attribute 'FormColorPicker'

**Comment by TheLastBen** [comment]
rename the folder sd then do a clean run with the latest colab

**Comment by Barry-Bot1** [comment]
I re-downloaded the original model, still getting the same error. What folder do I rename? and what to?

**Comment by raxomen** [comment]
On the left side you have inside the drive folder a folder named "SD" rename it as SD2, clean the colab and it should work.

**Comment by TheLastBen** [comment]
Use the latest colab, now you don't need to rename/remove the folder sd

**Comment by Mr-Jay** [comment]
i'm at the 4th sd folder that i have to create.
Sd colab work fine for a while and suddenly stop, i start it again and i got error, no choice than deleting or renaming sd folder and to create a new one. 
It's so annoying, is there no fix for this?

**Comment by TheLastBen** [comment]
run the colab without connecting to gdrive to make sure the colab works and make sure you use the latest one

**Comment by StabilityFuture** [comment]
> with the last updates you don't need to rename/remove the folder sd anymore

really?
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 17, in <module>
    from modules import localization, sd_vae, extensions, script_loading, errors, ui_components
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_vae.py", line 6, in <module>
    from modules import shared, devices, script_callbacks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes
ImportError: cannot import name 'hashes' from 'modules' (unknown location)

**Comment by Barry-Bot1** [comment]
I tried re-downloading the original model and got this:

Traceback (most recent call last):
  File "/content/convertosd.py", line 228, in <module>
    torch.save(state_dict, checkpoint_path)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion does not exist.
Something went wrong, try again

**Comment by TheLastBen** [comment]
try doing a fresh run and skip the first cell to test if the colab works

**Comment by Barry-Bot1** [comment]
> try doing a fresh run and skip the first cell to test if the colab works

Yes! works without connecting to Gdrive

**Comment by TheLastBen** [comment]
so it's your sd folder what's causing the issue
