### ISSUE TITLE
python3: can't open file '/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/webui.py'

### ISSUE THREAD

**Issue by invitare** [TheLastBen/fast-stable-diffusion#1384]
Hello, the old colab I had stopped working, so I tried using the latest colab now, with the old folders kept ("/content/gdrive/MyDrive/Fast-Dreambooth" and "/content/gdrive/MyDrive/sd").

As I have a session already saved, I just ran the 1º (google.colab), 2º (Dependencies), 4º (Create/Load a Session) and 9º (Test The Trained Model) steps. But I noticed that none of the steps created the new folders "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion" and "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui", causing the mentioned error.

1. So I tried renaming the old "/content/gdrive/MyDrive/sd" folder, but nothing changed.

2. So I tried moving the old "stablediffusion" and "stable-diffusion-webui" folders from the "/content/gdrive/MyDrive/sd" folder to "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db". Then, this error occured:
```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/shared.py", line 13, in <module>
    import modules.interrogate
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/interrogate.py", line 13, in <module>
    from modules import devices, paths, lowvram, modelloader
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/paths.py", line 18, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['/content/gdrive/MyDrive/sd/stablediffusion', '.', '/content/gdrive/MyDrive/Fast-Dreambooth/sd_db']
```

In which steps are the new folders created?
What can I do?

Thanks!

**Comment by TheLastBen** [comment]
fixed, use the latest colab, and don't rename the folders, make sure you rename it back like it was before

**Comment by invitare** [comment]
Thanks!
