### ISSUE TITLE
ImportError: cannot import name 'Block' from 'gradio.blocks' 

### ISSUE THREAD

**Issue by fourteen-0-0-eyes** [TheLastBen/fast-stable-diffusion#1391]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 32, in <module>
    from gradio.blocks import Block
ImportError: cannot import name 'Block' from 'gradio.blocks' (/usr/local/lib/python3.8/dist-packages/gradio/blocks.py)

**Comment by cerarslan** [comment]
same

**Comment by TheLastBen** [comment]
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
it works

**Comment by cerarslan** [comment]
I tried SD not DB sir but it gave me same error. It is not clean install btw so I will try tonight 🙏

**Comment by TahaBinhuraib** [comment]
Same :(

**Comment by cerarslan** [comment]
When I clean instelled its gave me Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared, progress
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 36, in <module>
    from gradio.blocks import Block
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 44, in <module>
    from gradio.documentation import (
ImportError: cannot import name 'document_component_api' from 'gradio.documentation' (/usr/local/lib/python3.8/dist-packages/gradio/documentation.py)

**Comment by TheLastBen** [comment]
use the link I posted above and skip the first cell and see if it works

**Comment by cerarslan** [comment]
> use the link I posted above and skip the first cell and see if it works

Yes, it works like charm! Now, I would like to ask you to 2 questions. Well.. with lastest update can't we not switch between models anymore? And I see black photos when trying to create embedding, how can I fix it, is it relatively .yaml file?

**Comment by TahaBinhuraib** [comment]
I deleted my local sd folders, all is working now! I think that other users just had a conflict with their local unsaved files.
