### ISSUE TITLE
Error converting to diffuser

### ISSUE THREAD

**Issue by MaxTran96** [TheLastBen/fast-stable-diffusion#1402]
Hi i got an error trying to convert the checkpoint file to diffuser on AWS EC2 Ubuntu

This is the error
Converting to Diffusers ...
Traceback (most recent call last):
  File "/home/ubuntu/content/convertodiff.py", line 1115, in <module>
    convert(args)
  File "/home/ubuntu/content/convertodiff.py", line 1066, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/home/ubuntu/content/convertodiff.py", line 835, in load_models_from_stable_diffusion_checkpoint
    checkpoint = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/home/ubuntu/content/convertodiff.py", line 816, in load_checkpoint_with_text_encoder_conversion
    checkpoint = torch.load(ckpt_path, map_location="cuda")
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 1052, in restore_location
    return default_restore_location(storage, map_location)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

Does anyone know if the fast-stable-diffusion only work for cpu training? I ran this on google colab and it works fine and i assume google colab use gpu training?

**Comment by TheLastBen** [comment]
You need a GPU to perform conversion to diffusers
