### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel

### ISSUE THREAD

**Issue by imJunaidAfzal** [TheLastBen/fast-stable-diffusion#1403]
## Failed to convert `ckpt` to model
I'm trying to convert this `https://huggingface.co/Lykon/DreamShaper/blob/main/DreamShaper_3.3.ckpt` to diffusers, but it giving me the following error.
Can you please look at this whats wrong, it there any issue with `.ckpt` or need to improve the `ckpt converter`.

```
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1115, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1066, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 847, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias". 
	Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight". 
```

**Comment by TheLastBen** [comment]
The model is a merge between so many models, sometimes it results in unsupported model by the conversion script.
