### ISSUE TITLE
Error only If using sd_vae on quicksettings

### ISSUE THREAD

**Issue by bhasilius** [TheLastBen/fast-stable-diffusion#1414]
Model weight loads fine without any quicksettings, but it gives me this error when putting sd_vae or CLIP_stop_at_last_layers on quicksettings:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 217, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 159, in webui
    shared.demo = modules.ui.create_ui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1807, in create_ui
    visit(txt2img_interface, loadsave, "txt2img")
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 168, in visit
    visit(c, func, path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 168, in visit
    visit(c, func, path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 168, in visit
    visit(c, func, path)
  [Previous line repeated 2 more times]
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 170, in visit
    func(path + "/" + str(x.label), x)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1805, in loadsave
    apply_field(x, 'value', check_dropdown, getattr(x, 'init_field', None))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1770, in apply_field
    elif condition and not condition(saved_value):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1800, in check_dropdown
    if x.multiselect:
AttributeError: 'Dropdown' object has no attribute 'multiselect'

**Comment by TheLastBen** [comment]
I guess that's a problem with gradio, A1111 seems to not fully support Gradio 3.9 anymore, I'll update it

**Comment by TheLastBen** [comment]
fixed now
