### ISSUE TITLE
Error initializing Gradio

### ISSUE THREAD

**Issue by feesta** [TheLastBen/fast-stable-diffusion#1415]
Possibly related to the Gradio 3.16 update:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 35, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 32, in <module>
    from gradio import (
ImportError: cannot import name 'queue' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/gradio/__init__.py)

**Comment by TheLastBen** [comment]
try disconnecting and reconnecting and rerun the colab

**Comment by feesta** [comment]
That worked! I posted too soon. Thanks!

**Comment by mjedmonds** [comment]
+1, disconnect and reconnecting did not resolve the issue.

However reverting `blocks.py` to the previous commit did fix the issue:

```  
!wget -q -O /usr/local/lib/python3.8/dist-packages/gradio/blocks.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/05746fc1264a929008e0db8ab10e25cd80bd4500/AUTOMATIC1111_files/blocks.py
```

**Comment by TheLastBen** [comment]
it should work fine now, sometimes commits take time to pass
