### ISSUE TITLE
Dreambooth dependencies not installing in python notebook

### ISSUE THREAD

**Issue by OhioPolymerAdditivesResearchCenter** [TheLastBen/fast-stable-diffusion#1416]
Updated to the new notebook / ipynb file for Dreambooth.  Newest build per just checking again.

Deleted my old sd and Dreambooth folders on Google Drive, fresh install.

It connects to G Drive.

Step 2 install dependencies is too fast though.  It only takes 10 seconds roughly and doesn't create a sd or Dreambooth folder in G Drive.

Didn't notice the speed or lack of installs at first so I proceeded.  It allowed me to create a Dreambooth model and upload pics and train it.  But it won't test the model, I presume because the lack of sd and Dreambooth folders in G Drive.

**Comment by OhioPolymerAdditivesResearchCenter** [comment]
I solved this.  On a fresh install, you need to run the Automatic1111 folder first to get the sd folder in your G Drive before running Dreambooth.  

I was in the habit of only launching Dreambooth and it now caught me, hope it doesn't catch anyone else....

**Comment by TheLastBen** [comment]
Dreambooth doesn't use the sd folder in gdrive, it creates sd_db folder inside Fast-Dreambooth folder, you don't need to run A1111 before that.

**Comment by OhioPolymerAdditivesResearchCenter** [comment]
Yea maybe I didn't solve it.  

It looked like it was working but threw this error when testing Dreambooth.

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 32, in <module>
    from gradio.blocks import Block
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 23, in <module>
    from gradio import (
ImportError: cannot import name 'queueing' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/gradio/__init__.py)`

**Comment by OhioPolymerAdditivesResearchCenter** [comment]
Just saw an update, I'll help test it for you....

**Comment by TheLastBen** [comment]
fixed now, wait around 2 minutes then refresh the colab from https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by OhioPolymerAdditivesResearchCenter** [comment]
Reran it with the model that I trained before and it failed with the following error.  Going to do a fresh reinstall of everything though and see if it is just my issue.  
 
Here is the error code though if it helps.

`Model loaded in 26.7s (10.7s create model, 15.4s load weights).
Exception (client): Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2271, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2094, in run
    self._check_banner()
  File "/usr/local/lib/python3.8/dist-packages/paramiko/transport.py", line 2275, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

*** Failed to connect to ec2.gradio.app:22: Error reading SSH protocol banner[Errno 104] Connection reset by peer`

**Comment by OhioPolymerAdditivesResearchCenter** [comment]
Fresh install and everything works, thanks
