### ISSUE TITLE
Test model doesn´t work with localtunnel and without

### ISSUE THREAD

**Issue by TheMETAHUT** [TheLastBen/fast-stable-diffusion#1420]
Error message is the following:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 32, in <module>
    from gradio.blocks import Block
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 23, in <module>
    from gradio import (
ImportError: cannot import name 'queueing' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/gradio/__init__.py)

**Comment by TheLastBen** [comment]
disconnect the runtime and rerun the colab

**Comment by TheMETAHUT** [comment]
Fixed, thanks
