### ISSUE TITLE
dreambooth doesn't work using external_captions

### ISSUE THREAD

**Issue by jbrsfa** [TheLastBen/fast-stable-diffusion#1442]
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 794, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 655, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.8/dist-packages/accelerate/data_loader.py", line 357, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 349, in __getitem__
    instance_image = Image.open(path)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2895, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/fghjk/instance_images/2.txt'
  0% 0/650 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--external_captions', '--stop_text_encoder_training=250', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/fghjk', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/fghjk/instance_images', '--output_dir=/content/models/fghjk', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/fghjk/captions', '--instance_prompt=', '--seed=903542', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=1e-05', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=650']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
did you upload the text captions manually to the instance images folder ?

**Comment by jbrsfa** [comment]
I opened the left tab in Google сolab, created a folder, and then uploaded images there along with text files.

**Comment by TheLastBen** [comment]
You don't need to do that, all you have to do is upload the captions txt files and the images together using the instance images cell, it's automated, just make sure all the instance images have the same extension (png or jpg ...)

**Comment by jbrsfa** [comment]
> You don't need to do that, all you have to do is upload the captions txt files and the images together using the instance images cell, it's automated, just make sure all the instance images have the same extension (png or jpg ...)

What should I do if this method is not for me? It takes a long time to download data, and I have quite a lot of it. Are there any other solutions?

**Comment by TheLastBen** [comment]
it's simple, just put the txt files in the same folder as the images and upload everything

**Comment by jbrsfa** [comment]
It takes a lot of time. Very much. Compared to the way I've always used it, it's an eternity.

**Comment by jbrsfa** [comment]
OSError                                   Traceback (most recent call last)
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in move(src, dst, copy_function)
    790     try:
--> 791         os.rename(src, real_dst)
    792     except OSError:

OSError: [Errno 18] Invalid cross-device link: '0.txt' -> '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/dffdf/instance_images/0.txt'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
3 frames
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in copyfile(src, dst, follow_symlinks)
    262         os.symlink(os.readlink(src), dst)
    263     else:
--> 264         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    265             # macOS
    266             if _HAS_FCOPYFILE:

FileNotFoundError: [Errno 2] No such file or directory: '0.txt'

**Comment by jbrsfa** [comment]
Also I get this error.

**Comment by jbrsfa** [comment]
OSError                                   Traceback (most recent call last)
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in move(src, dst, copy_function)
    790     try:
--> 791         os.rename(src, real_dst)
    792     except OSError:

OSError: [Errno 18] Invalid cross-device link: '6.txt' -> '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/dffdf/instance_images/6.txt'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
3 frames
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in copyfile(src, dst, follow_symlinks)
    262         os.symlink(os.readlink(src), dst)
    263     else:
--> 264         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    265             # macOS
    266             if _HAS_FCOPYFILE:

FileNotFoundError: [Errno 2] No such file or directory: '6.txt'

**Comment by jbrsfa** [comment]
When trying to load another piece of data.

**Comment by TheLastBen** [comment]
each txt file must have the same name as its corresponding image. and you shouldn't use numbers only as the instance images names, use something like "kjhghrndu".

**Comment by jbrsfa** [comment]
> each txt file must have the same name as its corresponding image. and you shouldn't use numbers only as the instance images names, use something like "kjhghrndu".

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in move(src, dst, copy_function)
    790     try:
--> 791         os.rename(src, real_dst)
    792     except OSError:

OSError: [Errno 18] Invalid cross-device link: 'ss (0).txt' -> '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/fdgdsfg/instance_images/ss (0).txt'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
3 frames
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in copyfile(src, dst, follow_symlinks)
    262         os.symlink(os.readlink(src), dst)
    263     else:
--> 264         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    265             # macOS
    266             if _HAS_FCOPYFILE:

FileNotFoundError: [Errno 2] No such file or directory: 'ss (0).txt'

**Comment by jbrsfa** [comment]
> each txt file must have the same name as its corresponding image. and you shouldn't use numbers only as the instance images names, use something like "kjhghrndu".

Do I really have to write without numbers at all? Then it turns out very inconvenient.

**Comment by TheLastBen** [comment]
you can put the numbers in the captions files if you want to include them in the instance name during training.

**Comment by jbrsfa** [comment]
> each txt file must have the same name as its corresponding image. and you shouldn't use numbers only as the instance images names, use something like "kjhghrndu".

OSError                                   Traceback (most recent call last)
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in move(src, dst, copy_function)
    790     try:
--> 791         os.rename(src, real_dst)
    792     except OSError:

OSError: [Errno 18] Invalid cross-device link: 'abldzWuZZh.txt' -> '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/tyuj/instance_images/abldzWuZZh.txt'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
3 frames
[/usr/lib/python3.8/shutil.py](https://localhost:8080/#) in copyfile(src, dst, follow_symlinks)
    262         os.symlink(os.readlink(src), dst)
    263     else:
--> 264         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    265             # macOS
    266             if _HAS_FCOPYFILE:

FileNotFoundError: [Errno 2] No such file or directory: 'abldzWuZZh.txt'

**Comment by jbrsfa** [comment]
> you can put the numbers in the captions files if you want to include them during training.

I renamed the files, now they have no numbers at all, but I still get an error. I don't seem to understand how this should work at all.

**Comment by TheLastBen** [comment]
did you put the textfiles with the images, then uploaded them ?

**Comment by jbrsfa** [comment]
> Ссылка в новом

![image](https://user-images.githubusercontent.com/116489683/213863614-fe552707-5f70-431b-affd-df128f2a09c9.png)
Here is an example of the files that I am trying to upload using the instance images cell.

**Comment by TheLastBen** [comment]
using the latest notebook ? https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by jbrsfa** [comment]
> did you put the textfiles with the images, then uploaded them using the instance images cell?

It's strange, I tried to use the latest version, but it looks like I made a mistake. Everything works according to your link, but I have a couple of questions. Why can't I train the text encoder when training with captions? And it looks like the training uses the file name, how to make sure that only the captions in the text file are used?

**Comment by TheLastBen** [comment]
If you don't want the names to show, then use numbers as filenames as you did before, so that they will be remove during training and only the captions will remain.
The text encoder was disabled when using captions to prevent excessive overfitting.

**Comment by jbrsfa** [comment]
> If you don't want the names to show, then use numbers as filenames as you did before, so that they will be remove during training and only the captions will remain. The text encoder was disabled when using captions to prevent excessive overfitting.

What should I do to enable the text encoder?

**Comment by TheLastBen** [comment]
disable the external captions and use single instance names

**Comment by jbrsfa** [comment]
> disable the external captions and use single instance names

Excuse me for my annoyance, however I need to use external captions and need a text encoder.

**Comment by TheLastBen** [comment]
in the training cell, remove "or external captions" from the line : 

`if Text_Encoder_Training_Steps==0 or External_Captions:`
so it becomes : 
`if Text_Encoder_Training_Steps==0:`

**Comment by jbrsfa** [comment]
> in the training cell, remove "or external captions" from the line :
> 
> `if Text_Encoder_Training_Steps==0 or External_Captions:` so it becomes : `if Text_Encoder_Training_Steps==0:`

Your advice does trigger the training of the encoder text, but it does not read the captions when training.

**Comment by Nalwonk** [comment]
I could be wrong, but the issue seems to be that when uploading captions, it's uploading them to the captions folder AND the images folder, and then attempting to process them as images when training.  I manually deleted the txt files from the instance_images folder after uploading and it seems to work correctly after that.

**Comment by TheLastBen** [comment]
you are right! I used !cp instead of !mv

**Comment by TheLastBen** [comment]
You're right, fixed now https://github.com/TheLastBen/fast-stable-diffusion/commit/64db8fd47a70e6852d26f8354f405a1f4caa0d5a

**Comment by jbrsfa** [comment]
> You're right, fixed now [64db8fd](https://github.com/TheLastBen/fast-stable-diffusion/commit/64db8fd47a70e6852d26f8354f405a1f4caa0d5a)

![image](https://user-images.githubusercontent.com/116489683/214015818-20578705-d69c-4b74-86a4-1966ca104879.png)
The text encoder does not read external captions, what should I do?
