### ISSUE TITLE
Dreambooth tab disappeared

### ISSUE THREAD

**Issue by HectateX** [TheLastBen/fast-stable-diffusion#1458]
Dreambooth tab disappeared on webui, this is the error I get

```Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 26, in <module>
    from extensions.sd_dreambooth_extension.scripts import dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 24, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.sd_to_diff import extract_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 26, in <module>
    from diffusers.pipelines.paint_by_example import PaintByExampleImageEncoder
ModuleNotFoundError: No module named 'diffusers.pipelines.paint_by_example'

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 24, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.sd_to_diff import extract_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 26, in <module>
    from diffusers.pipelines.paint_by_example import PaintByExampleImageEncoder
ModuleNotFoundError: No module named 'diffusers.pipelines.paint_by_example'

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 8, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_webhook import save_and_test_webhook
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_webhook.py", line 9, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'```

**Comment by TheLastBen** [comment]
try `!pip install -U diffusers` butyou should know that due so the dependencies conflict, the dreambooth extension might not work properly

**Comment by giteeeeee** [comment]
> try `!pip install -U diffusers` butyou should know that due so the dependencies conflict, the dreambooth extension might not work properly

I'm getting the same error message.

The problem would occur whenever I launch the session the second time. The dreambooth extension always work during the first colab session (including when turn on and off gradio server). But if I disconnect the session and start a new one, I'll be getting the above error message.

Tried "!pip install -U diffusers", but getting a different error:

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 8, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_webhook import save_and_test_webhook
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_webhook.py", line 9, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'

**Comment by jimlin1668478052** [comment]
You may just install the requirements of dreambooth with

!pip install git+https://github.com/huggingface/diffusers
!pip install git+https://github.com/huggingface/transformers
!pip install discord-webhook
!pip install bitsandbytes
