### ISSUE TITLE
It won't let me start it.

### ISSUE THREAD

**Issue by Temmie667** [TheLastBen/fast-stable-diffusion#1463]
When I try to run "Start stable-diffusion" it tells me this

"The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument."

and idk how to fix it.

Here is the full error

Error verifying pickled file from /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 134, in load_with_extra
    if not shared.cmd_opts.disable_safe_unpickle:
AttributeError: partially initialized module 'modules.shared' has no attribute 'cmd_opts' (most likely due to a circular import)

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared, progress
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 17, in <module>
    from modules import localization, sd_vae, extensions, script_loading, errors, ui_components
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_vae.py", line 6, in <module>
    from modules import shared, devices, script_callbacks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_disable_initialization.py", line 1, in <module>
    import ldm.modules.encoders.modules
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/encoders/modules.py", line 7, in <module>
    import kornia
  File "/usr/local/lib/python3.8/dist-packages/kornia/__init__.py", line 10, in <module>
    from . import (
  File "/usr/local/lib/python3.8/dist-packages/kornia/augmentation/__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "/usr/local/lib/python3.8/dist-packages/kornia/augmentation/container/__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "/usr/local/lib/python3.8/dist-packages/kornia/augmentation/container/augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "/usr/local/lib/python3.8/dist-packages/kornia/augmentation/container/patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "/usr/local/lib/python3.8/dist-packages/kornia/contrib/__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "/usr/local/lib/python3.8/dist-packages/kornia/contrib/image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "/usr/local/lib/python3.8/dist-packages/kornia/feature/__init__.py", line 4, in <module>
    from .integrated import (
  File "/usr/local/lib/python3.8/dist-packages/kornia/feature/integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "/usr/local/lib/python3.8/dist-packages/kornia/feature/integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "/usr/local/lib/python3.8/dist-packages/kornia/feature/hardnet.py", line 69, in __init__
    self.load_state_dict(pretrained_dict['state_dict'], strict=True)
TypeError: 'NoneType' object is not subscriptable

**Comment by TheLastBen** [comment]
running latest colab ? https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by Temmie667** [comment]
Yes, I am using the latest colab

**Comment by Temmie667** [comment]
Looks like I managed to fix it by deleting the "sd" folder and then trying again. You should add a warning or something about it. Something like "If you get an error or something, delete the "sd" folder and try again"

**Comment by TheLastBen** [comment]
I removed the need for removing the folder sd by adding `git reset --hard` but probably some file is preventing the git pull, I need feedback on which file
