### ISSUE TITLE
error when preprocessing images，I have uploaded the sd folder

### ISSUE THREAD

**Issue by yanfma123** [TheLastBen/fast-stable-diffusion#1468]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/ui.py", line 19, in preprocess
    modules.textual_inversion.preprocess.preprocess(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/preprocess.py", line 18, in preprocess
    shared.interrogator.load()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 116, in load
    self.blip_model = self.load_blip_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 86, in load_blip_model
    with paths.Prioritize("BLIP"):
AttributeError: module 'modules.paths' has no attribute 'Prioritize'

**Comment by markarenin** [comment]
Hi! I fixed it by removing with paths.Prioritize line from `interrogate.py` file.

You can go to Google drive and replace file from path `sd/stable-diffusion-webui/modules/interrogate.py` by this one https://gist.github.com/markarenin/14462cb0ca74e49777247f9af9eb0dec

**Comment by yanfma123** [comment]
Yeah，I fixed this too by your method，thank you so much ！@markarenin
