### ISSUE TITLE
No module named 'modules.ui_common'

### ISSUE THREAD

**Issue by arxivi** [TheLastBen/fast-stable-diffusion#1475]
```
 File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 23, in <module>
    import modules.extras
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 10, in <module>
    from modules.ui_common import plaintext_to_html
ModuleNotFoundError: No module named 'modules.ui_common'
```
During the launch

**Comment by chloeg91** [comment]
same here.
```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 23, in <module>
    import modules.extras
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 10, in <module>
    from modules.ui_common import plaintext_to_html
ModuleNotFoundError: No module named 'modules.ui_common'
```
fresh start yesterday with verything delete on gdrive. trained until it stopped.
started again 5 mins ago then having this error.

**Comment by chloeg91** [comment]
by the way i know remove sd folder will fix it. but remove it and config again everytime? copying files around as well.

**Comment by arxivi** [comment]
> by the way i know remove sd folder will fix it. but remove it and config again everytime? copying files around as well.

Delete? Will it help? Hm..

**Comment by Excalibro1** [comment]
![Screenshot_20230125_021326_Chrome](https://user-images.githubusercontent.com/98224593/214347012-b28007c5-4719-4799-9030-d24980802401.jpg)

The error while updating is this. Idk if that helps

**Comment by TheLastBen** [comment]
does your version of the notebook contain the line `!rm webui.sh` ?

**Comment by Excalibro1** [comment]
From what I can see `!rm webui.sh`is present in the auto1111 notebook but not the dreambooth one.

**Comment by TheLastBen** [comment]
The dreambooth UI is frozen, no need for removing webui.sh it's already removed, but why the webui.sh error since it's removed ?

**Comment by OEvgeny** [comment]
Looks like the similar to #1479 fix can be applied to dreamboth colab. I initially stumble upon the issue with webui.sh not being reset after `git reset --hard`, so `git pull` didn't work

**Comment by Excalibro1** [comment]
> The dreambooth UI is frozen, no need for removing webui.sh it's already removed, but why the webui.sh error since it's removed ?

I think my sd_db stable-diffusion-webui folder had the webui.sh in it still, i added !rm webui.sh and !git reset --hard after the fgitclone process and everything worked as it should, might have just been my gdrive setup?

The update to the auto notebook worked also thanks.

**Comment by TheLastBen** [comment]
I moved !rm webui.sh below git reset, now everything should update just fine

**Comment by Excalibro1** [comment]
> I moved !rm webui.sh below git reset, now everything should update just fine

Yeah sorry I was saying the update to the auto1111 notebook worked just fine with those 2 lines moved around but the dreambooth notebook was getting the same error but with another staged file `config.json` so I did what I said in the last comment for the dreambooth notebook and it worked, I don't know if others had this issue in dreambooth also but the fix works for both notebooks as far as I know.

**Comment by TheLastBen** [comment]
I'll fix the dreambooth version
