### ISSUE TITLE
Error Cannot import name 'sd_disable_initialization' from 'modules'

### ISSUE THREAD

**Issue by tuli-pen** [TheLastBen/fast-stable-diffusion#1477]
I'm getting this error when I try to start stable-diffusion:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 17, in <module>
    from modules import localization, sd_vae, extensions, script_loading, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_vae.py", line 6, in <module>
    from modules import shared, devices, script_callbacks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes
ImportError: cannot import name 'sd_disable_initialization' from 'modules' (unknown location)`

I'm using a ckpt from my drive I've used multiple times with AUTOMATIC1111 collab notebook. It worked a few weeks ago, but now I'm getting this error.

Could somebody help me?

**Comment by TheLastBen** [comment]
use the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by tuli-pen** [comment]
> use the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Now it's working! Thank you.
