### ISSUE TITLE
Can't get it to run - Throws this error

### ISSUE THREAD

**Issue by jazmaan** [TheLastBen/fast-stable-diffusion#1478]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 16, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images, sd_vae_approx
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 4, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes
ImportError: cannot import name 'sd_disable_initialization' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
use the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb 
if the problem persists, rename/remove the folder sd

**Comment by jazmaan** [comment]
Renaming the SD folder on My Drive did the trick.  Thanks!

**Comment by OEvgeny** [comment]
@TheLastBen  Looks like there is an issue with git: `git reset --hard` on Google Drive doesn't changed files for me. This helped #1479
