### ISSUE TITLE
external captions don't work.

### ISSUE THREAD

**Issue by reqwrew** [TheLastBen/fast-stable-diffusion#1484]
Training the UNet...
usage: train_dreambooth.py
       [-h]
       --pretrained_model_name_or_path
       PRETRAINED_MODEL_NAME_OR_PATH
       [--tokenizer_name TOKENIZER_NAME]
       --instance_data_dir
       INSTANCE_DATA_DIR
       [--class_data_dir CLASS_DATA_DIR]
       [--instance_prompt INSTANCE_PROMPT]
       [--class_prompt CLASS_PROMPT]
       [--with_prior_preservation]
       [--prior_loss_weight PRIOR_LOSS_WEIGHT]
       [--num_class_images NUM_CLASS_IMAGES]
       [--output_dir OUTPUT_DIR]
       [--seed SEED]
       [--resolution RESOLUTION]
       [--center_crop]
       [--train_text_encoder]
       [--train_batch_size TRAIN_BATCH_SIZE]
       [--sample_batch_size SAMPLE_BATCH_SIZE]
       [--num_train_epochs NUM_TRAIN_EPOCHS]
       [--max_train_steps MAX_TRAIN_STEPS]
       [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
       [--gradient_checkpointing]
       [--learning_rate LEARNING_RATE]
       [--scale_lr]
       [--lr_scheduler LR_SCHEDULER]
       [--lr_warmup_steps LR_WARMUP_STEPS]
       [--use_8bit_adam]
       [--adam_beta1 ADAM_BETA1]
       [--adam_beta2 ADAM_BETA2]
       [--adam_weight_decay ADAM_WEIGHT_DECAY]
       [--adam_epsilon ADAM_EPSILON]
       [--max_grad_norm MAX_GRAD_NORM]
       [--hub_token HUB_TOKEN]
       [--hub_model_id HUB_MODEL_ID]
       [--logging_dir LOGGING_DIR]
       [--mixed_precision {no,fp16,bf16}]
       [--save_n_steps SAVE_N_STEPS]
       [--save_starting_step SAVE_STARTING_STEP]
       [--stop_text_encoder_training STOP_TEXT_ENCODER_TRAINING]
       [--image_captions_filename]
       [--dump_only_text_encoder]
       [--train_only_unet]
       [--train_only_text_encoder]
       [--Style]
       [--Session_dir SESSION_DIR]
       [--external_captions]
       [--captions_dir CAPTIONS_DIR]
       [--local_rank LOCAL_RANK]
train_dreambooth.py: error: the following arguments are required: --pretrained_model_name_or_path, --instance_data_dir
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--external_captions', '--stop_text_encoder_training=250', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cvbhjkl']' returned non-zero exit status 2.
/bin/bash: --pretrained_model_name_or_path=/content/stable-diffusion-custom: No such file or directory
Something went wrong

**Comment by TheLastBen** [comment]
something is wrong with your notebook, use the latest one : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
