### ISSUE TITLE
Error test trained model but generate gradio interface

### ISSUE THREAD

**Issue by billyjoker** [TheLastBen/fast-stable-diffusion#1508]
Error setting up CodeFormer:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/codeformer_model.py", line 38, in setup_model
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/detection/__init__.py", line 10, in <module>
    from .retinaface.retinaface import RetinaFace
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/detection/retinaface/retinaface.py", line 14, in <module>
    from basicsr.utils.misc import get_device
ImportError: cannot import name 'get_device' from 'basicsr.utils.misc' (/usr/local/lib/python3.8/dist-packages/basicsr/utils/misc.py)

**Comment by TheLastBen** [comment]
that's just a warning, I'll fix it later
