### ISSUE TITLE
Failed to load model: _pickle.UnpicklingError: invalid load key, '\xc0'.

### ISSUE THREAD

**Issue by Mixomo** [TheLastBen/fast-stable-diffusion#1513]
hello. when i try to run the downloaded model i get this error....
it happens to me with several models regardless if they are from civitai or hugginface. (they are even very well known and downloaded models that do not have any problem and are not corrupted) does anyone know what is the cause of this error? thanks.

Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: fcfaf106f23cf2e04383f1cf0c4ab29f0c7cc6dc3d250ee10d3c5d24d8fef7bc
Loading weights [fcfaf106f2] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
loading stable diffusion model: UnpicklingError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 103, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 370, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 228, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 209, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xc0'.

Stable diffusion model failed to load, exiting

**Comment by thecoolwolf** [comment]
Running into the same issue

**Comment by alberduris** [comment]
Same here and related to #1560
