### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by bosez** [TheLastBen/fast-stable-diffusion#1515]
I am using the Deforum plugin, and I'm running into this issue after the rendering since the update and fix on Saturday. Any idea how to fix this? 

  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 154, in run_deforum
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2'

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by RONNYKHALIL** [comment]
having this issue in the new paperspace setup (which is amazing btw, and working in every other way!)

**Comment by TheLastBen** [comment]
@RONNYKHALIL you're having this issue with deforum ?

**Comment by RONNYKHALIL** [comment]
with deforum and txt2video...

Got a request to stitch frames to video using FFmpeg.
Frames:
/notebooks/sd/stable-diffusion-webui/outputs/img2img-images/Deforum_20230504221851/20230504221851_%09d.png
To Video:
/notebooks/sd/stable-diffusion-webui/outputs/img2img-images/Deforum_20230504221851/20230504221851.mp4
Stitching *video*...deo*...
** FFMPEG DID NOT STITCH ANY VIDEO ** Error: Error stitching frames to video. Actual runtime error:[Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2'

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
Ok, did some deps updates, update the deforum extension through the webui and try again

**Comment by RONNYKHALIL** [comment]
works like a charm now! (in deforum) thanks for the quick fix.

how about for https://github.com/deforum-art/sd-webui-text2video extension? below is the specific error, is it a similar fix? thanks

Stitching *video*...
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/t2v_helpers/video_audio_utils.py", line 147, in ffmpeg_stitch_video
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/t2v_helpers/render.py", line 24, in run
    vids_pack = process_modelscope(args_dict)
  File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/modelscope/process_modelscope.py", line 220, in process_modelscope
    ffmpeg_stitch_video(ffmpeg_location=video_args.ffmpeg_location, fps=video_args.fps, outmp4_path=outdir_current + os.path.sep + f"vid.mp4", imgs_path=os.path.join(outdir_current,
  File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/t2v_helpers/video_audio_utils.py", line 158, in ffmpeg_stitch_video
    raise Exception(
Exception: Error stitching frames to video. Actual runtime error:[Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2'
Exception occurred: Error stitching frames to video. Actual runtime error:[Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2'

**Comment by RONNYKHALIL** [comment]
hang on, its actually working now (I just had to change the ffmpeg location from the path to simply 'ffmpeg' - and it text2video stitching works now! loving your paperspace adoption. its blazing fast

**Comment by TheLastBen** [comment]
Nice!
