### ISSUE TITLE
Getting error when trying to convert model to diffusers

### ISSUE THREAD

**Issue by monis24** [TheLastBen/fast-stable-diffusion#1519]
Getting the following error when trying to convert my base model to diffusers. 
Any idea what to do ?

Traceback (most recent call last):
  File "/home/ubuntu/fast-stable-diffusion/Dreambooth/convertodiffv1.py", line 1115, in <module> convert(args)
  File "/home/ubuntu/fast-stable-diffusion/Dreambooth/convertodiffv1.py", line 1090, in convert
      save_diffusers_checkpoint(v2_model, args.model_to_save, text_encoder, unet, vae)
  File "/home/ubuntu/fast-stable-diffusion/Dreambooth/convertodiffv1.py", line 1023, in save_diffusers_checkpoint
      scheduler = PNDMScheduler(
  File "/opt/conda/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 376, in inner_init
      init(self, *args, **init_kwargs)
TypeError: __init__() got an unexpected keyword argument 'set_alpha_to_one'

**Comment by TheLastBen** [comment]
try converting it using a huggingface app
