### ISSUE TITLE
ImportError: cannot import name 'get_device' from 'basicsr.utils.misc' (/usr/local/lib/python3.8/dist-packages/basicsr/utils/misc.py)

### ISSUE THREAD

**Issue by rabbit9001** [TheLastBen/fast-stable-diffusion#1524]
hi, 
I got the following problem : 
Error setting up CodeFormer:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/codeformer_model.py", line 38, in setup_model
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/detection/__init__.py", line 10, in <module>
    from .retinaface.retinaface import RetinaFace
  File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/detection/retinaface/retinaface.py", line 14, in <module>
    from basicsr.utils.misc import get_device
ImportError: cannot import name 'get_device' from 'basicsr.utils.misc' (/usr/local/lib/python3.8/dist-packages/basicsr/utils/misc.py)

**Comment by TheLastBen** [comment]
it's just a warning I'll fix it soon

**Comment by CharlesFeo** [comment]
> hi, I got the following problem : Error setting up CodeFormer: Traceback (most recent call last): File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stable-diffusion-webui/modules/codeformer_model.py", line 38, in setup_model from facelib.utils.face_restoration_helper import FaceRestoreHelper File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/utils/face_restoration_helper.py", line 7, in from facelib.detection import init_detection_model File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/detection/**init**.py", line 10, in from .retinaface.retinaface import RetinaFace File "/content/gdrive/MyDrive/Fast-Dreambooth/sd_db/stablediffusion/src/codeformer/facelib/detection/retinaface/retinaface.py", line 14, in from basicsr.utils.misc import get_device ImportError: cannot import name 'get_device' from 'basicsr.utils.misc' (/usr/local/lib/python3.8/dist-packages/basicsr/utils/misc.py)

me too .When I click on 'genarater' I get an error: Something went wrong Expecting value: line 1 column 1 (char 0).
stable-diffusion-webui is not working properly
