### ISSUE TITLE
Downgrade the webui repository and Gradio version

### ISSUE THREAD

**Issue by Bullseye-StableDiffusion** [TheLastBen/fast-stable-diffusion#1530]
Hello!
How is it possible to downgrade the webui repository and the gradio version in the fast stable diffusion notebook?
I tried the commands:
"!git checkout ..." - didn't work with this.
"!sed -i -e "s/gradio==3.16.2/gradio==3.10.0/g" requirements_versions.txt
!sed -i -e "s/gradio==3.16.2/gradio==3.10.0/g" requirements.txt" - didn't work with these either
"!pip uninstall gradio -y
!pip install gradio==3.10.0" - didn't work with these as well.
I even combined all of them and nothing worked.
Thanks!

**Comment by TheLastBen** [comment]
!pip install gradio==3.10 will work, but you'll have to do it every time you start the runtime

**Comment by Bullseye-StableDiffusion** [comment]
> 

I will try this, thanks!

**Comment by Bullseye-StableDiffusion** [comment]
> !pip install gradio==3.10

Nah, it doesn't work. It always sends this error when trying to run the webui:
"Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 32, in <module>
    from gradio.blocks import Block
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 23, in <module>
    from gradio import (
ImportError: cannot import name 'queueing' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/gradio/__init__.py)"

I think that something is interconnected.
