### ISSUE TITLE
Cannot Preprocess images using BLIP for caption

### ISSUE THREAD

**Issue by BFGesus** [TheLastBen/fast-stable-diffusion#1536]
I seem to be missing "models.blip" ? Updating SD has not remedied the situation.

Traceback (most recent call last):
  File "H:\Automatic1111 SD 2\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\Automatic1111 SD 2\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\Automatic1111 SD 2\stable-diffusion-webui\modules\textual_inversion\ui.py", line 19, in preprocess
    modules.textual_inversion.preprocess.preprocess(*args)
  File "H:\Automatic1111 SD 2\stable-diffusion-webui\modules\textual_inversion\preprocess.py", line 17, in preprocess
    shared.interrogator.load()
  File "H:\Automatic1111 SD 2\stable-diffusion-webui\modules\interrogate.py", line 123, in load
    self.blip_model = self.load_blip_model()
  File "H:\Automatic1111 SD 2\stable-diffusion-webui\modules\interrogate.py", line 94, in load_blip_model
    import models.blip
ModuleNotFoundError: No module named 'models.blip'

**Comment by TheLastBen** [comment]
that's a local installation, check with A1111 repo
