### ISSUE TITLE
error Training the UNet Can't load config

### ISSUE THREAD

**Issue by billyjoker** [TheLastBen/fast-stable-diffusion#1542]
Hi  I am facing this error while training. It is the first time I've got it. I've tried also changing the name of the session as well.
Model version 2.1-768px and custom model the same
```
Training the UNet...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 616, in _get_config_dict
    resolved_config_file = cached_path(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 299, in cached_path
    raise EnvironmentError(f"file {url_or_filename} not found")
OSError: file /content/models/4febsesforfunk/text_encoder_trained/config.json not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 794, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 500, in main
    text_encoder = CLIPTextModel.from_pretrained(args.output_dir, subfolder="text_encoder_trained")
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1833, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/configuration_clip.py", line 126, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 561, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 656, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load config for '/content/models/4febsesforfunk'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/content/models/4febsesforfunk' is the correct path to a directory containing a config.json file
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--stop_text_encoder_training=250', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/4febsesforfunk', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/4febsesforfunk/instance_images', '--output_dir=/content/models/4febsesforfunk', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/4febsesforfunk/captions', '--instance_prompt=', '--seed=65069', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=1000']' returned non-zero exit status 1.
Something went wrong
```

**Comment by TheLastBen** [comment]
try a session name that doesn't contain numbers

**Comment by billyjoker** [comment]
I am still facing the same error, it has to be related with this
`OSError: Can't load config for '/content/models/4febsesforfunk'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/content/models/funkobillyfacefeb' is the correct path to a directory containing a config.json file`

**Comment by TheLastBen** [comment]
what model are you using ? the default ?

**Comment by billyjoker** [comment]
I am using a fine model, not default. Finally I was able to load it by copying the config.json file from the model into the GDrive folder session created

**Comment by billyjoker** [comment]
I do not know if it was the config.json because I am loading more fine models using difussion 1.5 and it is working fine.
I close this one, so it is resolved
