### ISSUE TITLE
ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by Gushousekai195** [TheLastBen/fast-stable-diffusion#1543]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 169, in img2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 579, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 950, in init
    image_mask = images.resize_image(2, mask, self.width, self.height)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 300, in resize_image
    res.paste(resized.resize((width, fill_height), box=(0, 0, width, 0)), box=(0, 0))
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2082, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0

But the height and width are greater than 0!

![image](https://user-images.githubusercontent.com/64454655/216791694-12466dd6-e770-4e0f-8f2d-89604ccbdcff.png)

**Comment by scorpiomaj27** [comment]
Same issue, resize is correct and is the original image size.  Happens regardless of model.

**Comment by scorpiomaj27** [comment]
> Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f res = list(func(*args, **kwargs)) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f res = func(*args, **kwargs) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 169, in img2img processed = process_images(p) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 486, in process_images res = process_images_inner(p) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 579, in process_images_inner p.init(p.all_prompts, p.all_seeds, p.all_subseeds) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 950, in init image_mask = images.resize_image(2, mask, self.width, self.height) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 300, in resize_image res.paste(resized.resize((width, fill_height), box=(0, 0, width, 0)), box=(0, 0)) File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2082, in resize return self._new(self.im.resize(size, resample, box)) ValueError: height and width must be > 0
> 
> But the height and width are greater than 0!
> 
> ![image](https://user-images.githubusercontent.com/64454655/216791694-12466dd6-e770-4e0f-8f2d-89604ccbdcff.png)

Try increasing the width or height by a very small amount, I don't know why, but it works, five pixels worked for me.
