### ISSUE TITLE
stable diffusion model failed to load,exiting

### ISSUE THREAD

**Issue by twi3682** [TheLastBen/fast-stable-diffusion#1547]
i executed first three codes "Install/Update AUTOMATIC1111 repo","Requirements","Model Download/Load"
and all of them executed properly.(in addition i used"https://drive.google.com/file/d/1lpmaL6pj4LNzrZtMqf8JrQzbApAtlmZN/view?usp=sharing" as my model_link in "Model Download/Load")
but when i tried executing the fourth one "Start Stable-Diffusion",here comes the error:

Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 4730eaf832be1b3d9c81e34c7fa47a120ab783a04ad48c622c4e800d8f152a57
Loading weights [4730eaf832] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 377, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 232, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 213, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Stable diffusion model failed to load, exiting

**Comment by TheLastBen** [comment]
The CKPT seems corrupt, try loading it from a different source
