### ISSUE TITLE
Returned non-zero exit status 1 problem with Kohya Lora training

### ISSUE THREAD

**Issue by CreamyOcean** [TheLastBen/fast-stable-diffusion#1552]
`Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\train_network.py", line 539, in <module>
    train(args)
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\train_network.py", line 143, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\library\train_util.py", line 1329, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 370, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\ai\stable-diffusion-webui\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\ai\\stable-diffusion-webui\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/ai/stable-diffusion-webui/models/Stable-diffusion/protogenX53Photorealism_10.safetensors', '--train_data_dir=C:/ai/stable-diffusion-webui/Kohya/Sample Images/image', '--resolution=768,512', '--output_dir=C:/ai/stable-diffusion-webui/Kohya/Sample Images/model', '--logging_dir=C:/ai/stable-diffusion-webui/Kohya/Sample Images/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Brooke Monk', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.`

**Comment by TheLastBen** [comment]
This repo is for colab you should check with kohya_ss
