### ISSUE TITLE
10% of trained models are corrupt

### ISSUE THREAD

**Issue by dalmackay** [TheLastBen/fast-stable-diffusion#1558]
After about 50+ models trained on v2.1 (both 512 and 768), about 5 or 6 have returned a corrupt error when trying to load it into auto whether on a colab or locally. It has happened about once a week consistently since 2.1 dropped, with the most recent being today. 

Error:
Loading weights [9b1e5e3764] from D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\models\Stable-diffusion\Moe_XI.ckpt
changing setting sd_model_checkpoint to Moe_XI.ckpt [9b1e5e3764]: RuntimeError
Traceback (most recent call last):
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\shared.py", line 537, in set
    self.data_labels[key].onchange()
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\webui.py", line 84, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\sd_models.py", line 435, in reload_model_weights
    load_model(checkpoint_info)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\sd_models.py", line 392, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\sd_models.py", line 247, in load_model_weights
    sd = read_state_dict(checkpoint_info.filename)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\sd_models.py", line 222, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\venv\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\venv\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\venv\lib\site-packages\torch\serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "D:\Automatic1111\automaticSD\auto-fresh\stable-diffusion-webui-master\venv\lib\site-packages\torch\serialization.py", line 997, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch._UntypedStorage).storage()._untyped()
RuntimeError: PytorchStreamReader failed reading file data/81: invalid header or archive is corrupted

**Comment by TheLastBen** [comment]
try loading them in the A1111 colab, if they load correctly, then the problem is with your local A1111 installation
