### ISSUE TITLE
Stable diffusion model failed to load, exiting

### ISSUE THREAD

**Issue by HopefulCockroach** [TheLastBen/fast-stable-diffusion#1565]
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 4a918c65481609b8e480086aced42c574ea0a041312a13b78dda34c78575135d
Loading weights [4a918c6548] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
SystemError: deallocated bytearray object has exported buffers
loading stable diffusion model: MemoryError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 377, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 232, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 213, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
MemoryError

**Comment by TheLastBen** [comment]
try running the colab without the first cell, if everything works, then your sd folder must be the issue, use the latest notebook : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by Noofayroz** [comment]
ich hava the same issue

**Comment by Noofayroz** [comment]
hey,
i have the same Issue

**Comment by TheLastBen** [comment]
the model file is very likely corrupt, try with a different model

**Comment by Noofayroz** [comment]
Thanks it works well with the Model 1.5
