### ISSUE TITLE
ImportError: cannot import name 'AsyncRequest' from 'gradio.utils''

### ISSUE THREAD

**Issue by billyjoker** [TheLastBen/fast-stable-diffusion#1575]
When play the Test The Trained Model step from a fine model sd-dreambooth-library/fashion: 

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 32, in <module>
    from gradio.blocks import Block
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 23, in <module>
    from gradio import (
  File "/usr/local/lib/python3.8/dist-packages/gradio/queueing.py", line 14, in <module>
    from gradio.utils import AsyncRequest, run_coro_in_background, set_task_name
ImportError: cannot import name 'AsyncRequest' from 'gradio.utils' (/usr/local/lib/python3.8/dist-packages/gradio/utils.py)
```

**Comment by shalman13091994** [comment]
Even I'm facing this issue now

**Comment by TheLastBen** [comment]
Are you using the latest colab ?

**Comment by billyjoker** [comment]
Maybe the new session was over because I had a previous session just closed. I resolved it by opening a new page with other google account.
I am using the latest collab

**Comment by yunfanye** [comment]
Change `!pip install -qq gradio==3.16.2` to `!pip install -qq gradio==3.18.0` would work
