### ISSUE TITLE
Conversion Error In Ben's Dreambooth Colab When Adding CKPT File

### ISSUE THREAD

**Issue by helsia15** [TheLastBen/fast-stable-diffusion#1578]
Anyone knows how to fix this? I tried multiple times to add the CKPT file of the model "Counterfeit V2.5" into TheLastBen's Dreambooth Colab, but each time I add it I get the "Conversion error". The file is originally in safetensors which can't be uploaded on the colab, so I used both the Automatic1111 model converter and another one from huggingface (two tries) to convert it into ckpt and it works when I try to use the model on the webui, but whenever I try the colab I get that error. Can anyone help? 
![Counterfeit Dreambooth error](https://user-images.githubusercontent.com/124475936/218284799-e38a3f6f-e010-40b2-9b59-8aed73525b93.png)

This is the model I want to finetune in dreambooth specifically: https://huggingface.co/gsdf/Counterfeit-V2.5

**Comment by TheLastBen** [comment]
did you choose the right version of the custom model ?

**Comment by CodilX** [comment]
> did you choose the right version of the custom model ?

Exact same error using the Deliberate model from Civitai (v1 and v1.1 PickleTensor versions). 
No post conversions of the downloaded model.
SD 1.5 specified in the description of the model, 1.5 in the notebook selected.

```
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1138, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1089, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 846, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias". 
	Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight". 
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error
Conversion error
```


![Screenshot S221](https://user-images.githubusercontent.com/476633/218575028-280dd420-5ed9-4317-ad9a-7a20080987bc.png)

**Comment by shalman13091994** [comment]
Even I have faced when I try to load the Realistic Vision V1.3 did u found anyway to resolve it

**Comment by helsia15** [comment]
For the other people who have the same issue, someone on reddit made this fork of Ben's colab which fixes the conversion error issue plus allows you to add .safetensors files:
https://colab.research.google.com/github/theovercomer8/sd-playground/blob/main/fast_DreamBooth_TO8_Fork.ipynb
https://github.com/theovercomer8/sd-playground/blob/main/fast_DreamBooth_TO8_Fork.ipynb

**Comment by shalman13091994** [comment]
Did u tried this where I was getting error while trying to convert to diffuser

**Comment by helsia15** [comment]
yep tried this and no more errors

**Comment by Mazvy** [comment]
> For the other people who have the same issue, someone on reddit made this fork of Ben's colab which fixes the conversion error issue plus allows you to add .safetensors files: https://colab.research.google.com/github/theovercomer8/sd-playground/blob/main/fast_DreamBooth_TO8_Fork.ipynb https://github.com/theovercomer8/sd-playground/blob/main/fast_DreamBooth_TO8_Fork.ipynb

Unfortunately that version doesn't seem to work with the Delibrate model.

**Comment by CodilX** [comment]
> For the other people who have the same issue, someone on reddit made this fork of Ben's colab which fixes the conversion error issue plus allows you to add .safetensors files: https://colab.research.google.com/github/theovercomer8/sd-playground/blob/main/fast_DreamBooth_TO8_Fork.ipynb https://github.com/theovercomer8/sd-playground/blob/main/fast_DreamBooth_TO8_Fork.ipynb

Unfortunately that still doesn't work the Deliberate model.
