### ISSUE TITLE
DeepDanbooru i can't make it work

### ISSUE THREAD

**Issue by Juan-Cruz-Iturrioz** [TheLastBen/fast-stable-diffusion#160]
I want to work with DeepDanbooru to doing Preprocess images but i can't get it to work,

<img width="823" alt="Captura de pantalla 2022-10-16 a las 10 09 12" src="https://user-images.githubusercontent.com/89535004/196037175-b475959d-10b0-4932-b13c-dcf47e3801f9.png">

How can I see I don't have the "Use DeepDanbooru"

modify webui-user.bat add --deepdanbooru but no working 

someone give me a hand with this problem

**Comment by TheLastBen** [comment]
add --deepdanbooru in the last cell of the colab

**Comment by Juan-Cruz-Iturrioz** [comment]
> 
<img width="830" alt="Captura de pantalla 2022-10-16 a las 10 16 39" src="https://user-images.githubusercontent.com/89535004/196037618-0fe4ba25-679c-408b-87b1-4ad27825119d.png">

Thanks it's working

**Comment by Juan-Cruz-Iturrioz** [comment]
Problem solved and a new one begins

<img width="1124" alt="Captura de pantalla 2022-10-16 a las 10 21 56" src="https://user-images.githubusercontent.com/89535004/196037811-e640bc15-8c0f-4d30-b773-d0c6b2abfd98.png">

where do i get the deepbooru.py

**Comment by TheLastBen** [comment]
are you using the latest colab, if so check the box "update_repo" in the second cell and run it

**Comment by Juan-Cruz-Iturrioz** [comment]
> 
<img width="508" alt="Captura de pantalla 2022-10-16 a las 10 35 16" src="https://user-images.githubusercontent.com/89535004/196038386-80b72033-ae37-4730-bed9-0bfdfc015eba.png">

I did it and he is not deepbooru.py

**Comment by TheLastBen** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2558

**Comment by TheLastBen** [comment]
try this : 
`!pip install git+https://github.com/KichangKim/DeepDanbooru.git@edf73df4cdaeea2cf00e9ac08bd8a9026b7a7b26#egg=deepdanbooru deepdanbooru`

if it works, i'll add it

**Comment by Juan-Cruz-Iturrioz** [comment]
> 
Thanks you for all help me

<img width="1332" alt="Captura de pantalla 2022-10-16 a las 12 59 24" src="https://user-images.githubusercontent.com/89535004/196045452-338d25cf-e886-47cc-aa92-5f3ee4270031.png">

I'm leaving it for someone else who has the same problem as me, you have to put this for it to work

```
pip install tensorflow
pip install tensorflow-io
pip install git+https://github.com/KichangKim/DeepDanbooru.git@edf73df4cdaeea2cf00e9ac08bd8a9026b7a7b26#egg=deepdanbooru deepdanbooru
```

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/07b2dfda9a14b59d1da7be651216b162d14bba70

**Comment by TheLastBen** [comment]
try hypernetwork in general if it works now

**Comment by Juan-Cruz-Iturrioz** [comment]
> try hypernetwork in general if it works now

I have the same problem as https://github.com/TheLastBen/fast-stable-diffusion/issues/158

i'm use `!python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share  --hypernetwork-dir "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/hypernetworks" --embeddings-dir "/content/gdrive/MyDrive/sd/stable-diffusion-webui/embeddings" --xformers --deepdanbooru --listen --disable-safe-unpickle --ckpt "$model"` in last line

but i get this
<img width="1253" alt="Captura de pantalla 2022-10-16 a las 18 48 03" src="https://user-images.githubusercontent.com/89535004/196059845-fc93cddd-46d8-46c8-ac04-06c77280333a.png">

give me a hand?

**Comment by TheLastBen** [comment]
I think that's related to the attention.py (for xformers), I'll check it out

**Comment by Juan-Cruz-Iturrioz** [comment]
> I think that's related to the attention.py (for xformers), I'll check it out

also use this
<img width="1630" alt="Captura de pantalla 2022-10-16 a las 18 58 47" src="https://user-images.githubusercontent.com/89535004/196060241-df1a46cf-dda4-4758-8cbc-8d82b15b6955.png">

**Comment by TheLastBen** [comment]
I integrated that in the colab now

**Comment by TheLastBen** [comment]
try it without xformers, right before running the last cell, run this : 

```
%cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules
!wget -O attention.py https://raw.githubusercontent.com/CompVis/stable-diffusion/main/ldm/modules/attention.py
```

**Comment by Juan-Cruz-Iturrioz** [comment]
> try it without xformers, right before running the last cell, run this :
> 
> ```
> %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules
> !wget -O attention.py https://raw.githubusercontent.com/CompVis/stable-diffusion/main/ldm/modules/attention.py
> ```

<img width="1635" alt="Captura de pantalla 2022-10-16 a las 19 14 32" src="https://user-images.githubusercontent.com/89535004/196060887-096c0ba8-1ca1-42da-ac5b-34f6bc840b80.png">

`Unloading hypernetwork
  0% 0/20 [00:03<?, ?it/s]
Error completing request
Arguments: ('1girl, mesterpiece,hikage \\(senran kagura\\), ', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, False, False, None, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 212, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 44, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 403, in process_images
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 547, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 409, in sample
    samples = self.func(self.model_wrap_cfg, x, extra_args={'cond': conditioning, 'uncond': unconditional_conditioning, 'cond_scale': p.cfg_scale}, disable=False, callback=self.callback_state, **extra_params_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/src/k-diffusion/k_diffusion/sampling.py", line 80, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 239, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=cond_in)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/src/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/src/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/openaimodel.py", line 732, in forward
    h = module(h, emb, context)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/openaimodel.py", line 85, in forward
    x = layer(x, context)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py", line 258, in forward
    x = block(x, context=context)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py", line 209, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/util.py", line 127, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py", line 212, in _forward
    x = self.attn1(self.norm1(x)) + x
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 227, in xformers_attention_forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)
  File "/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 624, in memory_efficient_attention
    query=query, key=key, value=value, attn_bias=attn_bias, p=p
  File "/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 251, in forward_no_grad
    causal=isinstance(attn_bias, LowerTriangularMask),
  File "/usr/local/lib/python3.7/dist-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Expected query.dim() == 3 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)`

**Comment by Juan-Cruz-Iturrioz** [comment]
Unloading hypernetwork
  0% 0/20 [00:03<?, ?it/s]
Error completing request
Arguments: ('1girl, mesterpiece,hikage \\(senran kagura\\), ', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, False, False, None, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 212, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 44, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 403, in process_images
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 547, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 409, in sample
    samples = self.func(self.model_wrap_cfg, x, extra_args={'cond': conditioning, 'uncond': unconditional_conditioning, 'cond_scale': p.cfg_scale}, disable=False, callback=self.callback_state, **extra_params_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/src/k-diffusion/k_diffusion/sampling.py", line 80, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 239, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=cond_in)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/src/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/src/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/openaimodel.py", line 732, in forward
    h = module(h, emb, context)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/openaimodel.py", line 85, in forward
    x = layer(x, context)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py", line 258, in forward
    x = block(x, context=context)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py", line 209, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/util.py", line 127, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py", line 212, in _forward
    x = self.attn1(self.norm1(x)) + x
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 227, in xformers_attention_forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)
  File "/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 624, in memory_efficient_attention
    query=query, key=key, value=value, attn_bias=attn_bias, p=p
  File "/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 251, in forward_no_grad
    causal=isinstance(attn_bias, LowerTriangularMask),
  File "/usr/local/lib/python3.7/dist-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Expected query.dim() == 3 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

**Comment by TheLastBen** [comment]
`!pip uninstall xformers`
then retry

**Comment by Juan-Cruz-Iturrioz** [comment]
> !pip uninstall xformers

<img width="1140" alt="Captura de pantalla 2022-10-16 a las 19 42 47" src="https://user-images.githubusercontent.com/89535004/196061938-40d00669-7e22-4501-86ea-a3b66d057ebb.png">

There are no change

**Comment by TheLastBen** [comment]
you need to uninstall xformers, then directly try to run the webui without reinstalling xformers, apparently it is causing some sort of conflict with the whole hypernetwork system

**Comment by Juan-Cruz-Iturrioz** [comment]
> you need to uninstall xformers, then directly run the webui without reinstalling xformers, apparently it is causing some sort of conflict with the whole hypernetwork system

<img width="697" alt="Captura de pantalla 2022-10-16 a las 19 54 04" src="https://user-images.githubusercontent.com/89535004/196062329-e161a42f-610d-419e-ae23-8accb532202e.png">

is working 

for 3 times thanks you for all help me

I'm aradecion but I don't want to see you for today

**Comment by AIShank** [comment]
Popping in to ask if this ended up fixing the problem with hypernetworks?

**Comment by TheLastBen** [comment]
> Popping in to ask if this ended up fixing the problem with hypernetworks?

By disabling xformers it works, I will implement a fix in the colab shortly

**Comment by Juan-Cruz-Iturrioz** [comment]
> Popping in to ask if this ended up fixing the problem with hypernetworks?

![descarga (3)](https://user-images.githubusercontent.com/89535004/196062664-5c89ae92-3852-4474-b5ca-5b9b91b5add4.png)

mesterpiece,1girl, leone (agk)
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 770235466, Size: 512x512, Model hash: 925997e9, Clip skip: 2

![descarga (4)](https://user-images.githubusercontent.com/89535004/196062691-de20c4a9-e554-468b-84cc-d67ebca6d0a8.png)
mesterpiece,1girl, leone (agk)
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 770235466, Size: 512x512, Model hash: 925997e9, Hypernet: h-artist-greatmosu-v03, Clip skip: 2

YES

**Comment by AIShank** [comment]
Awesome, glad we could figure it out!

So I would just run the colab as normal but skip the installing xformers step then?

**Comment by TheLastBen** [comment]
Right now I'm implementing an option, a simple checkbox for hypernetwork compatibility, it will be ready in a few minutes

**Comment by AIShank** [comment]
Good stuff man, thanks for your hard work; this is by far the easiest colab to use, appreciate you being so dedicated to improving it.

**Comment by TheLastBen** [comment]
@AIShank Thanks, you can now load the latest colab from the main page and check the box "hypernetwork_compatiblity", it should work now.

**Comment by Juan-Cruz-Iturrioz** [comment]
also a  "DeepDanbooru_compatiblity", ?

**Comment by TheLastBen** [comment]
> also a "DeepDanbooru_compatiblity"?

https://github.com/TheLastBen/fast-stable-diffusion/commit/07b2dfda9a14b59d1da7be651216b162d14bba70

**Comment by Juan-Cruz-Iturrioz** [comment]
for 4 times thanks you for all help to this community, 
it is a like to use your colab

**Comment by TheLastBen** [comment]
happy to help
