### ISSUE TITLE
modules problems

### ISSUE THREAD

**Issue by rewixx** [TheLastBen/fast-stable-diffusion#1603]
Error loading script: controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 34, in <module>
    from svglib.svglib import svg2rlg
ModuleNotFoundError: No module named 'svglib'

**Comment by Rb-diff** [comment]
this is an easy fix fortunately. search google for svglib and download the directed svglib.tar.gz file. I just unzipped it twice and extracted the file and placed it in the "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules"-folder.

now I'm instead wrestling with other little gremlins but hope this helps

**Comment by TheLastBen** [comment]
try `!pip install svglib`

**Comment by Rb-diff** [comment]
> try `!pip install svglib`

tried and it worked. you have to run it on every startup though.

somehow controlnet has now broken all my embeddings and I get error codes saying they have multiple terms.

hmm... should probably open new issue about that

**Comment by TheLastBen** [comment]
I'll add the dependencies to avoid reinstalling svglib everytime
