### ISSUE TITLE
Can't make images while anything is in the lora folder

### ISSUE THREAD

**Issue by jorymo** [TheLastBen/fast-stable-diffusion#1605]
Everything starts up fine, and I'm able to view and select loras in the webui, but when I try to generate images, it stops.

`Error completing request
Arguments: ('task(20axz6z16rmkjiu)', '', '', ['test'], 37, 0, False, False, 3, 2, 17.5, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 584, in process_images_inner
    extra_networks.activate(p, extra_network_data)
UnboundLocalError: local variable 'extra_network_data' referenced before assignment`

**Comment by FollowMarcos** [comment]
I am not getting any errors, apart from the loras not working. They are there, when I refresh the lora tab they show up, but they don't work.
