### ISSUE TITLE
Error when starting SD

### ISSUE THREAD

**Issue by Barry-Bot1** [TheLastBen/fast-stable-diffusion#1608]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 278, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 197, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 97, in initialize
    modules.sd_models.setup_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model
    list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 110, in list_models
    if shared.cmd_opts.no_download_sd_model or cmd_ckpt != shared.sd_model_file or os.path.exists(cmd_ckpt):
AttributeError: 'Namespace' object has no attribute 'no_download_sd_model'

**Comment by TheLastBen** [comment]
update your A1111 repo by running the repo cell
