### ISSUE TITLE
Controlnet not working?

### ISSUE THREAD

**Issue by Topzie** [TheLastBen/fast-stable-diffusion#1611]
Is it just me or is controlnet not working (yet) ?
I have installed the extensions and uploaded the (722Mb*) files for canny, normal and depth.

(*These safetensors files https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main)

Controlnet model files in sd-webui-controlnet/models.
sd 1.5 
It gets activated when enabled, but its producing just white masks or a simple gradient. No  lines , shapes or depth map.

**Comment by TheLastBen** [comment]
try the full models

**Comment by Topzie** [comment]
Not working, it said loading but nothing happened.
This is the second try. I thought I could open the img2img tab but gradio stopped.

Btw, the first try i waited over 10 minutes and then I entered the Generate button again which also stopped gradio.
Here's the output ⤵️

2023-02-20 13:41:54.073733: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-20 13:41:57.790287: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-20 13:41:57.790526: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-20 13:41:57.790550: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 25.1s (load weights from disk: 19.4s, create model: 1.2s, apply weights to model: 2.7s, apply half(): 1.1s, move model to device: 0.6s).
Running on public URL: https://27506803-29dd-4489.gradio.live/
✔ Connected
Loading preprocessor: canny, model: control_sd15_canny [fef5e48e]
Loaded state_dict from [/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_sd15_canny.pth]
^C

**Comment by TheLastBen** [comment]
update your A1111 colab, I integrated the extension, make sure you remove all the controlnet models from your gdrive before that.

**Comment by Topzie** [comment]
Getting this now. It got stuck after the 'Model loaded' and after a few minutes it broke.

Error running preload() for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet (1)/preload.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 28, in preload_extensions
    module.preload(parser)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet (1)/preload.py", line 2, in preload
    parser.add_argument("--controlnet-dir", type=str, help="Path to directory with ControlNet models", default=None)
  File "/usr/lib/python3.8/argparse.py", line 1398, in add_argument
    return self._add_action(action)
  File "/usr/lib/python3.8/argparse.py", line 1761, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python3.8/argparse.py", line 1602, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python3.8/argparse.py", line 1412, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.8/argparse.py", line 1551, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.8/argparse.py", line 1560, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --controlnet-dir: conflicting option string: --controlnet-dir

Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 39.6s (load weights from disk: 30.6s, create model: 3.3s, apply weights to model: 3.9s, apply half(): 1.1s, move model to device: 0.7s).
^C

**Comment by TheLastBen** [comment]
run this in a new cell: 
`!rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet*`

then run the controlnet cell

**Comment by Topzie** [comment]
Ok found another weird thing: it creates a mask from the img2img picture instead of the ControlNet one.

The ControlNet can make a picture from scribbles, though.

So it aeems the colab just doesn't look at the right place for the ControlNet image.

**Comment by cerarslan** [comment]
> 

Same for me, preprocess or whatever is that working properly imo. Can't generate maps from Controlnet. Always black or white squares.

**Comment by Topzie** [comment]
Yeah, only img2img with an image in the img2img field  can make a mask as long as you don't put one in the controlnet field.

Looks to me this is the culprit:

**File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 555, in postprocess
is_img2img_batch_tab = is_img2img and img2img_tab_tracker.submit_img2img_tab == 'img2img_batch_tab'
NameError: name 'img2img_tab_tracker' is not defined**

**Comment by Topzie** [comment]
I have figured it out, it's a browser issue.
It needs canvas access, which apparently is denied in Brave.

It's working in Chrome.
