### ISSUE TITLE
Error on starting interface

### ISSUE THREAD

**Issue by Light-Danube** [TheLastBen/fast-stable-diffusion#1613]
Loading weights [5be8a7781a] from /content/model.safetensors
thread '<unnamed>' panicked at 'range end index 4212856397 out of range for slice of length 4202692608', src/lib.rs:606:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 286, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 197, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 383, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 217, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
pyo3_runtime.PanicException: range end index 4212856397 out of range for slice of length 4202692608

This occurs from launching last cell in Fast-Stable-Diffusion.

**Comment by Light-Danube** [comment]
However problem was solved when I launched through local tunnel. Hm.
