### ISSUE TITLE
webui.py: error: unrecognized arguments: --no-download-sd-model

### ISSUE THREAD

**Issue by codestuff001** [TheLastBen/fast-stable-diffusion#1621]
Getting this error when running the latest notebook:
`webui.py: error: unrecognized arguments: --no-download-sd-model`

When I delete the `--no-download-sd-model` argument in the script, it gives me this error:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 278, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 197, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 97, in initialize
    modules.sd_models.setup_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model
    list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 110, in list_models
    if shared.cmd_opts.no_download_sd_model or cmd_ckpt != shared.sd_model_file or os.path.exists(cmd_ckpt):
AttributeError: 'Namespace' object has no attribute 'no_download_sd_model'
```

**Comment by codestuff001** [comment]
Nevermind, I was able to resolve it by backing up my model files, deleting the sd folder, then re-running the notebook with a fresh install. It's working now ¯\_(ツ)_/¯

**Comment by TheLastBen** [comment]
it should work without deleting the sd folder, the repo updates automatically, unless you disabled that

**Comment by TheLastBen** [comment]
you can also run the notebook by skipping the first cell, it will use the colab temporary storage in case you don't want to use gdrive.
