### ISSUE TITLE
ModuleNotFoundError: No module named 'taming'

### ISSUE THREAD

**Issue by imJunaidAfzal** [TheLastBen/fast-stable-diffusion#1646]
Gives error in colab "**fast_stable_diffusion_AUTOMATIC1111.ipynb**"  on `Start Stable-Diffusion`
```
Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/taming-transformers/taming
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/codeformer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/blip/models/blip.py
Warning: k_diffusion not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
100% 5.10M/5.10M [00:00<00:00, 64.4MB/s]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 7, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ModuleNotFoundError: No module named 'taming'
```

When I installed the taming library using `pip install taming-transformers`, then, it changed the error to:
```
Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/taming-transformers/taming
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/codeformer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/blip/models/blip.py
Warning: k_diffusion not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 7, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ImportError: cannot import name 'VectorQuantizer2' from 'taming.modules.vqvae.quantize' (/usr/local/lib/python3.8/dist-packages/taming/modules/vqvae/quantize.py)```

**Comment by TheLastBen** [comment]
There is a problem with your SD folder, try a test run without running the first (gdrive) cell

**Comment by kyl822** [comment]
pip install taming-transformers-rom1504
