### ISSUE TITLE
Various errors in last step

### ISSUE THREAD

**Issue by bennitheblog** [TheLastBen/fast-stable-diffusion#1651]
Upon starting the last cell to start SD, I receive the following error each time I have tried, including after disconnecting and re-running the cells:

`Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
100% 5.10M/5.10M [00:00<00:00, 258MB/s]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 14, in <module>
    from ldm.models.diffusion.sampling_util import norm_thresholding
ModuleNotFoundError: No module named 'ldm.models.diffusion.sampling_util'`

**Comment by TheLastBen** [comment]
Test run the colab without the first cell and see if the error persists

**Comment by bennitheblog** [comment]
Notebook works when first cell is not run. Thanks!

**Comment by TheLastBen** [comment]
that means the sd folder in your gdrive is messed up, rename/remove it, then you can run the first cell
