### ISSUE TITLE
pyo3_runtime.PanicException when loading models from Drive link to temp_storage

### ISSUE THREAD

**Issue by FabianCGBerg** [TheLastBen/fast-stable-diffusion#1666]
hey y'all, 
Recently I've been having issues loading models from a Gdrive link downloaded to the temp-storage.
I notice it happens more reliably with the larger models (5GB or 7GB), both with Gradio and Localtunnel

It's probably a downloading or size issue, since it doesn't happen with smaller 2-3GB models. 
 
My workflow is: 

- I have the models in a different Gdrive folder (so multiple people can share)
- I load them using the Model-Link and it downloads the model just fine.
- I download to temp so my gdrive doesn't fill up and errors out (especially with 7GB models)
- Then run SD

It loads control net, but halts when loading the model.

Unfortunately it's not a yes/no thing. Just now I couldn't load it, but after loading a couple smaller models and then loading a larger 7Gb model it did work, so not sure what exactly is causing this. Like I said, I suspect it's something in the download cell.

`Loading weights [56c106895c] from /content/model.safetensors
thread '<unnamed>' panicked at 'range end index 7788643087 out of range for slice of length 7751073792', src/lib.rs:606:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 286, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 197, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 383, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 217, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
pyo3_runtime.PanicException: range end index 7788643087 out of range for slice of length 7751073792`

**Comment by TheLastBen** [comment]
if you have the models in your gdrive, use the direct path, not the link

**Comment by FabianCGBerg** [comment]
They're in a different Gdrive so multiple people can access them. Hoping I can get it to work reliably so we can keep models in one place.

**Comment by TheLastBen** [comment]
have you tried with a different model, maybe the ones in the gdrive are corrupt

**Comment by FabianCGBerg** [comment]
I did yes, .safetensor and .ckpt files work. The smaller ones reliably load. The larger ones fail, but not always which is why I think the downloading cell messes up with larger files. 

There might be an interrupt during the download, causing the transfer to the temp folder to corrupt. But not sure what is causing it, if it has to do with the file checks or maybe the !gdown function itself.

**Comment by TheLastBen** [comment]
the cell uses gdown to download the file
try downloading it independently from the cell, create a new cell and run this : 

```
%cd /content
!gdown linktogdrive
```

**Comment by FabianCGBerg** [comment]
From a separate cell it looks like it runs better, hasn't corrupted with the files I tested, looks like it downloads fully each time.

Think it has to do with the gdown package?

**Comment by TheLastBen** [comment]
it also uses gdown in the models cell
