### ISSUE TITLE
Training step - Something went wrong

### ISSUE THREAD

**Issue by Xaltyn** [TheLastBen/fast-stable-diffusion#1695]
Training the UNet...
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 800, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 443, in main
    accelerator = Accelerator(
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 286, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/BSA69', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/BSA69/instance_images', '--output_dir=/content/models/BSA69', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/BSA69/captions', '--instance_prompt=', '--seed=131725', '--resolution=768', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=5e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=5000']' returned non-zero exit status 1.
Something went wrong

Any suggestions on how to fix this? I was able to make a model 2 hours before this with no issues.

**Comment by Xaltyn** [comment]
I may be out of compute units?

**Comment by TheLastBen** [comment]
> I may be out of compute units?

yep, no more GPU for you

**Comment by Xaltyn** [comment]
> > I may be out of compute units?
> 
> yep, no more GPU for you

does it refill over time? or will I have to purchase more?

**Comment by TheLastBen** [comment]
it will refill, in 12 or 24 hours
