### ISSUE TITLE
Conversion error  while Converting to Diffusers

### ISSUE THREAD

**Issue by Zurilo** [TheLastBen/fast-stable-diffusion#1703]
Hey! I'm trying to do DreamBooth with the [Deliberate v2.ckpt](https://huggingface.co/XpucT/Deliberate/tree/main) model from Hugging Face, but I get this conversion error when trying to convert to diffusers.

Is there a workaround you can do about this, or is this a Deliberate model issue?

Thank you!

```
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1130, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1081, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 846, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
	Missing key(s) in state_dict: "up_blocks.0.upsamplers.0.conv.weight", "up_blocks.0.upsamplers.0.conv.bias", "up_blocks.1.upsamplers.0.conv.weight", "up_blocks.1.upsamplers.0.conv.bias", "up_blocks.2.upsamplers.0.conv.weight", "up_blocks.2.upsamplers.0.conv.bias". 
	Unexpected key(s) in state_dict: "up_blocks.0.attentions.2.conv.bias", "up_blocks.0.attentions.2.conv.weight". 
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error
Conversion error
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-5-c3ccfb24c5ee> in <module>
    226           while not os.path.exists('/content/stable-diffusion-custom/unet/diffusion_pytorch_model.bin'):
    227             print('Conversion error')
--> 228             time.sleep(5)
    229       else:
    230         while os.path.getsize('/content/model.ckpt') < 1810671599:

KeyboardInterrupt: 
```

![image](https://user-images.githubusercontent.com/127267501/223594995-f11ca1d5-51f4-40a6-a06f-c50c89685e63.png)

**Comment by hidecreature** [comment]
I had the same problem for weeks

**Comment by Dreason8** [comment]
Pretty sure Dreambooth is busted right now, been getting errors all day.

**Comment by Excalibro1** [comment]
> 

Try putting `XpucT/Deliberate` in path_to_huggingface instead.

**Comment by z339008256** [comment]
100% same here when I put the model link instead of HF link, just wondering what's the conditions to meet when only loading a ckpt file, I know I can just train a lora model instead, but still wanna use the model training workflow.

**Comment by Omenizer** [comment]
There's a fork of Fast DB by TheOvercomer08 that can train all models, I've been using it successful for some time now

**Comment by Dreason8** [comment]
> There's a fork of Fast DB by TheOvercomer08 that can train all models, I've been using it successfully for some time now
> 
> https://github.com/theovercomer8/sd-playground

Even that one has the ModuleNotFoundError
Dreambooth is cooked atm
