### ISSUE TITLE
ModuleNotFoundError: No module named 'wget'

### ISSUE THREAD

**Issue by yoshihirosakamoto** [TheLastBen/fast-stable-diffusion#1711]
Is that mean google is banned for fast-stable-diffusion?

Thanks

**Comment by SDPDVADER** [comment]
no thelast ben is updating the book

**Comment by yoshihirosakamoto** [comment]
Thanks, I install it by myself !pip install wget

**Comment by Super-zapper** [comment]
For me worked run all of this:

!pip install "fastapi[all]"
!pip install "gradio[all]"
!pip install "lpips[all]"
!pip install "basicsr[all]"
!pip install GitPython
!pip install safetensors
!pip install omegaconf
!pip install transformers
!pip install open_clip
!pip install diffusers
!pip install triton
!pip install bitsandbytes
!pip install wget
!pip install -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/requirements_versions.txt
!pip install open_clip_torch
!pip install git+https://github.com/openai/CLIP.git
!pip install xformers

**Comment by yoshihirosakamoto** [comment]
> For me worked run all of this:
> 
> !pip install "fastapi[all]" !pip install "gradio[all]" !pip install "lpips[all]" !pip install "basicsr[all]" !pip install GitPython !pip install safetensors !pip install omegaconf !pip install transformers !pip install open_clip !pip install diffusers !pip install triton !pip install bitsandbytes !pip install wget !pip install -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/requirements_versions.txt !pip install open_clip_torch !pip install git+https://github.com/openai/CLIP.git !pip install xformers

Thank you for your help

**Comment by ElThunasFBI** [comment]
> Para mí funcionó ejecutar todo esto:
> 
> !pip install "fastapi[all]" !pip install "gradio[all]" !pip install "lpips[all]" !pip install "basicsr[all]" !pip install GitPython !pip install safetensors !pip install omegaconf !pip instalar transformadores ! pip instalar open_clip ! pip instalar difusores ! pip instalar triton ! pip instalar bits y bytes ! pip instalar wget ! pip instalar -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/requirements_versions.txt ! pip instala git+ https://github.com/openai/CLIP.git !pip instala xformers

how do you download that?

**Comment by yoshihirosakamoto** [comment]
> > Para mí funcionó ejecutar todo esto:
> > !pip install "fastapi[all]" !pip install "gradio[all]" !pip install "lpips[all]" !pip install "basicsr[all]" !pip install GitPython !pip install safetensors !pip install omegaconf !pip instalar transformadores ! pip instalar open_clip ! pip instalar difusores ! pip instalar triton ! pip instalar bits y bytes ! pip instalar wget ! pip instalar -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/requirements_versions.txt ! pip instala git+ https://github.com/openai/CLIP.git !pip instala xformers
> 
> how do you download that?

just add a code line and run it

**Comment by yoshihirosakamoto** [comment]
> For me worked run all of this:
> 
> !pip install "fastapi[all]" !pip install "gradio[all]" !pip install "lpips[all]" !pip install "basicsr[all]" !pip install GitPython !pip install safetensors !pip install omegaconf !pip install transformers !pip install open_clip !pip install diffusers !pip install triton !pip install bitsandbytes !pip install wget !pip install -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/requirements_versions.txt !pip install open_clip_torch !pip install git+https://github.com/openai/CLIP.git !pip install xformers

Thanks, I just try it, but when it go to unet step and got this error
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/instance_images', '--output_dir=/content/models/cutecorgi', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/captions', '--instance_prompt=', '--seed=389667', '--resolution=1024', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=6000']' returned non-zero exit status 1.
Something went wrong

**Comment by Super-zapper** [comment]
shit, that's not enough
text encoder works fine, but unet crushes because of out of memory. I think it's because of this at start
maybe someone could manage this
![image](https://user-images.githubusercontent.com/112967133/223897350-bce52f08-ed7d-42a0-9238-5743668033ed.png)

**Comment by lamwilton** [comment]
At least the above works for inference

**Comment by longlivebigcat** [comment]
> For me worked run all of this:
> 
> !pip install "fastapi[all]" !pip install "gradio[all]" !pip install "lpips[all]" !pip install "basicsr[all]" !pip install GitPython !pip install safetensors !pip install omegaconf !pip install transformers !pip install open_clip !pip install diffusers !pip install triton !pip install bitsandbytes !pip install wget !pip install -r /content/gdrive/MyDrive/sd/stable-diffusion-webui/requirements_versions.txt !pip install open_clip_torch !pip install git+https://github.com/openai/CLIP.git !pip install xformers
----------------------------------------------------------------
This temp solution works for me. Thank you very much!

**Comment by kieuvinh2412** [comment]
> r: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/instance_images', '--output_dir=/content/models/cutecorgi', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/captions', '--instance_prompt=', '--seed=389667', '--resolution=1024', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=6000']' returned non-zero exit status 1.

not enough, still missing other modules
!pip install einops
!pip install git+https://github.com/PyTorchLightning/pytorch-lightning 
!pip install piexif
...

**Comment by yoshihirosakamoto** [comment]
> > r: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/instance_images', '--output_dir=/content/models/cutecorgi', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/captions', '--instance_prompt=', '--seed=389667', '--resolution=1024', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=6000']' returned non-zero exit status 1.
> 
> not enough, still missing other modules !pip install einops !pip install git+https://github.com/PyTorchLightning/pytorch-lightning !pip install piexif ...

yes, when you try to traning your model and go to unet part.... you will got error too

**Comment by Super-zapper** [comment]
Do you get something like this? 

![image](https://user-images.githubusercontent.com/112967133/223919897-fae4e097-c65f-4594-b4be-3669bb6fa417.png)

**Comment by yoshihirosakamoto** [comment]
> Do you get something like this?
> 
> ![image](https://user-images.githubusercontent.com/112967133/223919897-fae4e097-c65f-4594-b4be-3669bb6fa417.png)

I got this:
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/instance_images', '--output_dir=/content/models/cutecorgi', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cutecorgi/captions', '--instance_prompt=', '--seed=389667', '--resolution=1024', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=6000']' returned non-zero exit status 1.

**Comment by KoningWouter** [comment]
Not working for me either.

Crap I should had stored a copy to my Google Drive :(

**Comment by kieranxsomer** [comment]
Yea i'm in the middle of streaming and some of this stuff was just not working, it wasn't even just THIS notebook, i had three KohyaSS notebooks bomb on me

**Comment by KoningWouter** [comment]
> Yea i'm in the middle of streaming and some of this stuff was just not working, it wasn't even just THIS notebook, i had three KohyaSS notebooks bomb on me

Yup me too. KoyhaSS is also nuked. 

Does anybody have a copy of the old notebooks? LoRA or Checkpoint?

**Comment by kieranxsomer** [comment]
The only notebook that SOMEWHAT worked for me was an NGROK Saigodev one, i'm manually doing the commands but open clip won't install and any other versions just install old torch

**Comment by KoningWouter** [comment]
I checked the revision history of this colab and nothing has changed. It must be something else.

**Comment by kieranxsomer** [comment]
This is the notebook i use as a backup: https://colab.research.google.com/github/sagiodev/stablediffusion_webui/blob/master/StableDiffusionUI_ngrok_sagiodev.ipynb NOW KEEP IN MIND this is not my local drive copy XD this is not the one i ahve running at extra credits per hour XD

**Comment by kieranxsomer** [comment]
> I checked the revision history of this colab and nothing has changed. It must be something else.

It's likely google. XD Cause even the saigodev one has a xformers error and tensorflow

**Comment by kieranxsomer** [comment]
Final attack : Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 151, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 286, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 197, in webui
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 98, in initialize
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 126, in list_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 46, in __init__
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 152, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

I give up, i'm going to my back up notebook XD lemme know when this one's fixed!

**Comment by KoningWouter** [comment]
> Final attack : Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 151, in model_hash OSError: [Errno 107] Transport endpoint is not connected
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 286, in File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 197, in webui File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 98, in initialize File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 126, in list_models File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 46, in **init** File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 152, in model_hash OSError: [Errno 107] Transport endpoint is not connected
> 
> I give up, i'm going to my back up notebook XD lemme know when this one's fixed!

Could you share your backup notebook. I'm stupid and did not make copies. :(

**Comment by kieranxsomer** [comment]
> > Final attack : Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 151, in model_hash OSError: [Errno 107] Transport endpoint is not connected
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 286, in File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 197, in webui File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 98, in initialize File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 126, in list_models File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 46, in **init** File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 152, in model_hash OSError: [Errno 107] Transport endpoint is not connected
> > I give up, i'm going to my back up notebook XD lemme know when this one's fixed!
> 
> Could you share your backup notebook. I'm stupid and did not make copies. :(

No, LOL because i don't have a last ben copy- i only have the saigodev one which i linked before

**Comment by kieranxsomer** [comment]
> This is the notebook i use as a backup: https://colab.research.google.com/github/sagiodev/stablediffusion_webui/blob/master/StableDiffusionUI_ngrok_sagiodev.ipynb NOW KEEP IN MIND this is not my local drive copy XD this is not the one i ahve running at extra credits per hour XD

This is the one i linked lol

**Comment by KoningWouter** [comment]
> [kieranxsomer](/kieranxsomer)

That's not a training notebook :( But thanks for sharing. I'll sit on my hands until it's fixed xD

**Comment by kieranxsomer** [comment]
> > [kieranxsomer](/kieranxsomer)
> 
> That's not a training notebook :( But thanks for sharing. I'll sit on my hands until it's fixed xD

Yea you COULD get dreambooth extension to work it's been updated but that one i'd suggest not to use with THIS notebook because YOLO it never keeps things in the same place twice

**Comment by basti484** [comment]
Default runtime has changed to Python version 3.9. You can switch to the old runtime (3.8) using the fallback runtime version in colab. More here: https://medium.com/google-colab/colab-updated-to-python-3-9-2593f8b1eb79

**Comment by kieranxsomer** [comment]
> Default runtime has changed to Python version 3.9. You can switch to the old runtime (3.8) using the fallback runtime version in colab. More here: https://medium.com/google-colab/colab-updated-to-python-3-9-2593f8b1eb79

Sweet, thank you for this!

**Comment by yoshihirosakamoto** [comment]
> > I checked the revision history of this colab and nothing has changed. It must be something else.
> 
> It's likely google. XD Cause even the saigodev one has a xformers error and tensorflow

yes, I'm sure google did it, for now... all users can't run it anymore and need to wait for update

**Comment by kieranxsomer** [comment]
> https://medium.com/google-colab/colab-updated-to-python-3-9-2593f8b1eb79

or you do this? https://medium.com/google-colab/colab-updated-to-python-3-9-2593f8b1eb79

**Comment by kieranxsomer** [comment]
Which basti pasted earlier, XD

**Comment by lamwilton** [comment]
Its google updated Python 3.9 from 3.8, and idk why thelastben is so slow this time

**Comment by davvoz** [comment]
This works->https://github.com/TheLastBen/fast-stable-diffusion/issues/1706#issuecomment-1460708635

**Comment by TheLastBen** [comment]
fixed

**Comment by Dreason8** [comment]
> fixed

Legend

**Comment by hobocow** [comment]
> fixed

still no wget error for me :/

**Comment by Dreason8** [comment]
> > fixed
> 
> still no wget error for me :/

Did you try a fresh install?

**Comment by Dreason8** [comment]
Still getting a ton of errors after a fresh install, but the UI seems to be running somehow.

eg:
Error loading script: api.py
ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers'
ModuleNotFoundError: No module named 'dreambooth.dreambooth'
ModuleNotFoundError: No module named 'dreambooth.dreambooth'
Error loading script: main.py

**Comment by TheLastBen** [comment]
is this the dreambooth extension ? if so, it doesn't work well with the UI, I suggest the dreambooth notebook.

**Comment by Dreason8** [comment]
Yeah I added the Dreambooth extension to the UI. Will go back to using the notebook.
cheers
