### ISSUE TITLE
Error training Unet

### ISSUE THREAD

**Issue by tinirusta10** [TheLastBen/fast-stable-diffusion#1718]
hello guys, i have this error in the train unet

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 14.75 GiB total capacity; 13.17 GiB already allocated; 216.81 MiB free; 13.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Progress:|                         |:   0% 1/4700 [00:10<13:18:38, 10.20s/it, loss=0.0911, lr=2e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ari', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ari/instance_images', '--output_dir=/content/models/ari', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ari/captions', '--instance_prompt=', '--seed=193333', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=4700']' returned non-zero exit status 1.
Something went wrong

someone have a fix?

**Comment by RubenGres** [comment]
Colab updated to Python 3.9 and it broke everyone colab's. We have to wait for TheLastBen to update dependencies...
https://github.com/TheLastBen/fast-stable-diffusion/issues/1706#issuecomment-1460745037

**Comment by TheLastBen** [comment]
fixed
