### ISSUE TITLE
Asgi Error, controlnet and inpaint not working

### ISSUE THREAD

**Issue by aipanda88** [TheLastBen/fast-stable-diffusion#1744]
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred
```

The inpaint and controlnet makes the application freeze. Sometimes they work, sometimes they do not work at all, sometimes when you try to use them the whole application will freeze and you have to constantly disconnect and reconnect to get it to work.

**Comment by aipanda88** [comment]
Issues went away when I deleted the SD folders and reinstalled (for the third time since using this notebook). Not sure if there could have been another solution or simply deleting a particular folder/file instead (if so, knowing that ahead of time would be great for people who are not coding experts) but everything is now working as it should. Not trying to sound rude, very grateful for the work and notebook, but if there is a more simple process than deleting the entire thing, would love to know.
