### ISSUE TITLE
UnboundLocalError: local variable 'extra_network_data' referenced before assignment

### ISSUE THREAD

**Issue by Ai-Artsca** [TheLastBen/fast-stable-diffusion#1746]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 716, in process_images_inner
    extra_networks.deactivate(p, extra_network_data)
UnboundLocalError: local variable 'extra_network_data' referenced before assignment

**Comment by TheLastBen** [comment]
probably your sd folder is corrupt, try the notebook without running the first cell

**Comment by Ai-Artsca** [comment]
I had to install unprompted before installing controlnet to fix this issue
