### ISSUE TITLE
Img2Img and Controlnet not working

### ISSUE THREAD

**Issue by materosx** [TheLastBen/fast-stable-diffusion#1756]
Ever since the fastapi error I cant get it to run correctly, whenever I try to use Img2Img it works at first, but the next time I click the generate button it does nothing, I've reinstalled it and used the most up to date notebook but nothing works. Sometimes, only sometimes, pressing shift+enter makes it run, but after that it's the same again. It's almost the same with controlnet, sometimes it will start loading the model and complete the request, sometimes it does nothing. Only solution was restarting the cell but nothing really changes, works at first if lucky, then it doesnt. I would really appreciate some help on this, it's driving me crazy, thank you.

**Comment by hameleon-ed** [comment]
I have the same problem. Sometimes Img2Img works shift+enter when focus on the text field.

**Comment by KatyaKlein** [comment]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 24, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 51, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 334, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 81, in app
    await func(session)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 283, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 436, in join_queue
    session_info = await websocket.receive_json()
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
