### ISSUE TITLE
img2img and inpaint don't work

### ISSUE THREAD

**Issue by Sooty001** [TheLastBen/fast-stable-diffusion#1757]
Img2img and inpaint work with 1 or 2 images, and that's it. Stops working. I am using the latest version of notepad, I also deleted the sd folder. Doesn't help, please tell me what to do?

**Comment by KatyaKlein** [comment]
Me, too:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/base.py", line 24, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 51, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 334, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 81, in app
    await func(session)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 283, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 436, in join_queue
    session_info = await websocket.receive_json()
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by bayoumedic** [comment]
problems with upscaling too. just not doing anything

**Comment by TheLastBen** [comment]
are you using localtunnel or gradio server ?

**Comment by Sooty001** [comment]
> are you using localtunnel or gradio server ?

I don't know, I just launch notepad without pressing anything in it

**Comment by TheLastBen** [comment]
can you generate a batch size of 4 images in txt2img ?

**Comment by materosx** [comment]
> can you generate a batch size of 4 images in txt2img ?

I'm not the guy you were talking to but we seem to have the same issue, and yeah I can generate a 4 image batch in txt2img, that works normally

**Comment by Sooty001** [comment]
> can you generate a batch size of 4 images in txt2img ?

Yes, I can create 4 images in txt2img

**Comment by personxyz** [comment]
I'm having the same problems. Txt2img works perfectly but img2img and inpaint are completely broke.

I can upload an image into these parts but the moment I enter my prompt/settings and click generate nothing happens. I wait and wait but no image is generated and no error messages are shown in automatic1111 or the terminal.

The moment I switch to txt2img and use that instead I get an image in seconds.

**Comment by personxyz** [comment]
OK, I tried going back to an older auto1111 commit from the 2nd of March and that seems to have fixed the issue, I've just spent the last 90 minutes inpainting with absolutely no problems. For anyone who wants to try this, the commit I used was: fc3063d9b924c094b59229269f4afe722b120d88

It's obviously not a perfect solution but until the root cause is figured out this is likely the best option.

**Comment by personxyz** [comment]
> OK, I tried going back to an older auto1111 commit from the 2nd of March and that seems to have fixed the issue, I've just spent the last 90 minutes inpainting with absolutely no problems. For anyone who wants to try this, the commit I used was: fc3063d9b924c094b59229269f4afe722b120d88
> 
> It's obviously not a perfect solution but until the root cause is figured out this is likely the best option.

Update: Now this older commit isn't working for me! I'm starting to go insane trying to fix this damn problem. I guess I'll try a different commit but I don't hold out much hope.

**Comment by personxyz** [comment]
Gradio is the problem. Since switching to something different I've had zero problems.

The LastBen notebook has a box you can tick to use "localtunnel" instead of Gradio.

There's also [this colab notebook](https://github.com/camenduru/stable-diffusion-webui-colab/issues/172) that has multiple Gradio alternatives.

I also think ngrok is allowed on colab so you could switch to that. It's pretty simple, here's a [tutorial](https://github.com/JingShing/Ngrok-in-StableDiffusion-tutorial).

**Comment by Sooty001** [comment]
> Gradio is the problem. Since switching to something different I've had zero problems.
> 
> The LastBen notebook has a box you can tick to use "localtunnel" instead of Gradio.
> 
> There's also [this colab notebook](https://github.com/camenduru/stable-diffusion-webui-colab/issues/172) that has multiple Gradio alternatives.
> 
> I also think ngrok is allowed on colab so you could switch to that. It's pretty simple, here's a [tutorial](https://github.com/JingShing/Ngrok-in-StableDiffusion-tutorial).
> 

Thanks, I'll try

**Comment by TheLastBen** [comment]
I added ngrok

**Comment by Sardelka9515** [comment]
I'm still have this problem sometimes even using ngrok. I swicthed to cloudflare tunnel and it works perfectly so far

You can run it like this
```python
import re
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb
!sudo pkill cloudflared
!rm "nohup.out"
!nohup cloudflared tunnel --url http://localhost:7860 &
p = re.compile('https://[\w-]+\.trycloudflare\.com')
time.sleep(6)
f=open("nohup.out", "r")
output=f.read()
f.close()
urlObj=p.search(output)
print("Webui url is "+urlObj.group(0))
```

**Comment by Sooty001** [comment]
> I'm still have this problem sometimes even using ngrok. I swicthed to cloudflare tunnel and it works perfectly so far
> 
> You can run it like this
> ```python
> import re
> !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb
> !sudo pkill cloudflared
> !rm "nohup.out"
> !nohup cloudflared tunnel --url http://localhost:7860 &
> p = re.compile('https://[\w-]+\.trycloudflare\.com')
> time.sleep(6)
> f=open("nohup.out", "r")
> output=f.read()
> f.close()
> urlObj=p.search(output)
> print("Webui url is "+urlObj.group(0))
> ```

Where exactly should this be added? before what?

**Comment by Sooty001** [comment]
> I'm still have this problem sometimes even using ngrok. I swicthed to cloudflare tunnel and it works perfectly so far
> 
> You can run it like this
> ```python
> import re
> !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && dpkg -i cloudflared-linux-amd64.deb
> !sudo pkill cloudflared
> !rm "nohup.out"
> !nohup cloudflared tunnel --url http://localhost:7860 &
> p = re.compile('https://[\w-]+\.trycloudflare\.com')
> time.sleep(6)
> f=open("nohup.out", "r")
> output=f.read()
> f.close()
> urlObj=p.search(output)
> print("Webui url is "+urlObj.group(0))
> ```

Where exactly should this be added? before what?
