### ISSUE TITLE
Upscaling

### ISSUE THREAD

**Issue by Sadrahel** [TheLastBen/fast-stable-diffusion#1767]
Hi, i often have this problem using realesrgan : 

Upscaling raw output PNGs using realesrgan-x4plus at x4...Error completing request
Arguments: #masked
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 164, in run_deforum
    make_upscale_v2(upscale_factor = video_args.r_upscale_factor, upscale_model = video_args.r_upscale_model, keep_imgs = video_args.r_upscale_keep_imgs, imgs_raw_path = args.outdir, imgs_batch_id = args.timestring, fps = video_args.fps, deforum_models_path = root.models_path, current_user_os = root.current_user_os, ffmpeg_location=video_args.ffmpeg_location, stitch_from_frame=0, stitch_to_frame=max_video_frames, ffmpeg_crf=video_args.ffmpeg_crf, ffmpeg_preset=video_args.ffmpeg_preset, add_soundtrack = video_args.add_soundtrack ,audio_path=real_audio_track)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/upscaling.py", line 179, in make_upscale_v2
    process = subprocess.run(cmd, capture_output=True, check=True, text=True, cwd=(os.path.join(deforum_models_path, 'realesrgan_ncnn') if current_user_os == 'Mac' else None))
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Deforum/realesrgan_ncnn/realesrgan-ncnn-vulkan'

Thank you if somebody can tell me who to fix it

**Comment by TheLastBen** [comment]
I think the issue is related to deforum, not the colab notebook

**Comment by Gryphan1** [comment]
same problem

**Comment by Gryphan1** [comment]
> Hi, i often have this problem using realesrgan :
> 
> Upscaling raw output PNGs using realesrgan-x4plus at x4...Error completing request Arguments: #masked Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f res = list(func(*args, **kwargs)) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f res = func(*args, **kwargs) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 164, in run_deforum make_upscale_v2(upscale_factor = video_args.r_upscale_factor, upscale_model = video_args.r_upscale_model, keep_imgs = video_args.r_upscale_keep_imgs, imgs_raw_path = args.outdir, imgs_batch_id = args.timestring, fps = video_args.fps, deforum_models_path = root.models_path, current_user_os = root.current_user_os, ffmpeg_location=video_args.ffmpeg_location, stitch_from_frame=0, stitch_to_frame=max_video_frames, ffmpeg_crf=video_args.ffmpeg_crf, ffmpeg_preset=video_args.ffmpeg_preset, add_soundtrack = video_args.add_soundtrack ,audio_path=real_audio_track) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/upscaling.py", line 179, in make_upscale_v2 process = subprocess.run(cmd, capture_output=True, check=True, text=True, cwd=(os.path.join(deforum_models_path, 'realesrgan_ncnn') if current_user_os == 'Mac' else None)) File "/usr/lib/python3.9/subprocess.py", line 505, in run with Popen(*popenargs, **kwargs) as process: File "/usr/lib/python3.9/subprocess.py", line 951, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) PermissionError: [Errno 13] Permission denied: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Deforum/realesrgan_ncnn/realesrgan-ncnn-vulkan'
> 
> Thank you if somebody can tell me who to fix it

im delete all on google disk and install all again - now it work

**Comment by Sadrahel** [comment]
Yes, but every time I restart, the problem comes back.
That's why I thought the problem was with the fast-sd colab.
No possibility to avoid that ?

**Comment by bosezhou** [comment]
Same issue

**Comment by bosezhou** [comment]
I'm still struggling with the same error... is there any alternative way to upscale a video?

**Comment by Sadrahel** [comment]
> I'm still struggling with the same error... is there any alternative way to upscale a video?

You should try video2x colab

**Comment by amota511** [comment]
same issue
