### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules'

### ISSUE THREAD

**Issue by dqweryyi** [TheLastBen/fast-stable-diffusion#1784]
It works in a fresh install, but as soon as I put any lora in the drive folder, it show this  following error multiple times for all loras, all extensions and for modules

reading lora /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/shirtTug.safetensors: OSError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 53, in __init__
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 216, in read_metadata_from_safetensors
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/shirtTug.safetensors'

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py'

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 230, in webui
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 126, in initialize
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 152, in load_upscalers
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules'

**Comment by TheLastBen** [comment]
an issue with gdrive lately

**Comment by dqweryyi** [comment]
I managed to fix it by reuploading the LoRAs to drive instead of just moving from the old folder

**Comment by alpkabac** [comment]
> I managed to fix it by reuploading the LoRAs to drive instead of just moving from the old folder

Can you elaborate?

**Comment by rishabhrana3006** [comment]
The solution that worked for me
1. The Lora folder of your mounted drive, delete all files from googe drive [Don't worry they will go to trash]
2. Now restart the stable diffusion last cell
3. Now go to trash of your drive and start restoring the files, lets say first you restored 25 files
4. Now rerun the cell
5. Now restore another 25 files and rerun the cell
Keep doing till you have restored all files
This worked for me

**Comment by thejohnd0e** [comment]
works for me, tnx!
