### ISSUE TITLE
Instruct-Pix2Pix Broken

### ISSUE THREAD

**Issue by Gushousekai195** [TheLastBen/fast-stable-diffusion#1787]
Today, I tried to use Instruct-Pix2Pix but it wouldn't work. I'm using the instruct-pix2pix-00-22000 model like I'm supposed to.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-instruct-pix2pix/scripts/instruct-pix2pix.py", line 310, in generate
    raise e
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-instruct-pix2pix/scripts/instruct-pix2pix.py", line 253, in generate
    in_image = ImageOps.fit(input_image, (width, height), method=Image.Resampling.LANCZOS)
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 77, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

**Comment by firstvanq** [comment]
bro how did you solve it?
