### ISSUE TITLE
I'm getting UnboundLocalError: local variable 'text_encoder' referenced before assignment after completing model training

### ISSUE THREAD

**Issue by aaiguy** [TheLastBen/fast-stable-diffusion#179]
While training dreambooth model on colab I'm getting below error.
```
Steps: 100% 1500/1500 [23:03<00:00,  1.09it/s, loss=0.297, lr=5e-6]Traceback (most recent call last):
  File "train_dreambooth.py", line 677, in <module>
    main()
  File "train_dreambooth.py", line 665, in main
    text_encoder=accelerator.unwrap_model(text_encoder),
UnboundLocalError: local variable 'text_encoder' referenced before assignment
Steps: 100% 1500/1500 [23:03<00:00,  1.08it/s, loss=0.297, lr=5e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_p
```

why am I getting this ?

**Comment by TheLastBen** [comment]
make sure you use the latest colab notebook
