### ISSUE TITLE
error launching dreambooth on colab

### ISSUE THREAD

**Issue by HuanchengHu** [TheLastBen/fast-stable-diffusion#1793]
the error is ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers', I have tried reinstalling diffusers package or downgrade to 12.1, not working. Please help thank!

Exception importing api
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 27, in <module>
    from dreambooth.dataclasses.db_config import from_file, DreamboothConfig
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers' (/usr/local/lib/python3.9/dist-packages/diffusers/schedulers/__init__.py)
Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 7, in <module>
    from dreambooth.dataclasses.db_config import (
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dataclasses/db_config.py", line 10, in <module>
    from dreambooth.utils.image_utils import get_scheduler_names  # noqa
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils/image_utils.py", line 11, in <module>
    from diffusers.schedulers import KarrasDiffusionSchedulers
ImportError: cannot import name 'KarrasDiffusionSchedulers' from 'diffusers.schedulers' (/usr/local/lib/python3.9/dist-packages/diffusers/schedulers/__init__.py)

**Comment by TheLastBen** [comment]
The extension doesn't work, use the db notebook instead

**Comment by Azemar** [comment]
> The extension doesn't work, use the db notebook instead

a little off-topic, but still:
is it possible to create unique unknown file identifiers that are not numbered in a row?
Something like "qwerty (009).png, qwerty (034).png", etc.

Or does everything have to start with "qwerty (001).png, qwerty (002).png"?

**Comment by TheLastBen** [comment]
yes it is possible, you can number them however you want
