### ISSUE TITLE
why lora dosen't work 

### ISSUE THREAD

**Issue by rewixx** [TheLastBen/fast-stable-diffusion#1800]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7f9d4570d580>]: RuntimeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 170, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 132, in load_lora
    module.weight.copy_(weight)
RuntimeError: output with shape [4, 320] doesn't match the broadcast shape [4, 320, 4, 320]

**Comment by TheLastBen** [comment]
what type of lora are you using ? the kohya version ?

**Comment by rewixx** [comment]
yes

**Comment by TheLastBen** [comment]
use this extension https://github.com/kohya-ss/sd-webui-additional-networks
