### ISSUE TITLE
lora dont work

### ISSUE THREAD

**Issue by lolosso** [TheLastBen/fast-stable-diffusion#1802]
here its the problem he gives me

Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
[AddNet] Updating model hashes...
  1% 4/354 [01:07<2:20:44, 24.13s/it]Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/zoneTan_v1.safetensors: [Errno 107] Transport endpoint is not connected
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/a2NierAutomataLora_1.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/a2NierAutomataLora_1.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/aquaKonosubaLora_1.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/aquaKonosubaLora_1.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/2bNierAutomataLora_v2b.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/2bNierAutomataLora_v2b.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/shirtliftALORAFor_shirtliftv1.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/shirtliftALORAFor_shirtliftv1.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/shingekiNoKyojinAnime_v1.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/shingekiNoKyojinAnime_v1.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/afrobullStyleLora_afrobull.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/afrobullStyleLora_afrobull.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/bocchiEdStyleLora_bocchiEdStyle.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/bocchiEdStyleLora_bocchiEdStyle.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/sinonGGO_sinonGGO.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/sinonGGO_sinonGGO.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/TsumasakyCCCodeGeass_v1.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/TsumasakyCCCodeGeass_v1.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/darkMagicianGirlLora_1.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/darkMagicianGirlLora_1.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/melinaEldenRingLora_v1.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/melinaEldenRingLora_v1.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/samdoesartsSamYang_normal.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/samdoesartsSamYang_normal.safetensors'
Failed to read model file /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/ratatatat74StyleLora_ratatatat7470.safetensors: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/ratatatat74StyleLora_ratatatat7470.safetensors'
  5% 17/354 [01:07<22:10,  3.95s/it] 
Error loading script: additional_networks.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/additional_networks.py", line 12, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/model_util.py", line 334, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/model_util.py", line 318, in update_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/model_util.py", line 210, in get_all_models
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/model_util.py", line 179, in hash_model_file
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/model_util.py", line 101, in get_model_hash
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hashes.py", line 42, in calculate_sha256
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/fischlGenshinImpact_fischlGenshinImpact.pt'

Error loading script: lora_compvis.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/lora_compvis.py'

Error loading script: metadata_editor.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/metadata_editor.py'

Error loading script: model_util.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/model_util.py'

Error loading script: safetensors_hack.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/safetensors_hack.py'

Error loading script: util.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/util.py'

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/scripts/xyz_grid_support.py'

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 230, in webui
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 126, in initialize
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 152, in load_upscalers
OSError: [Errno 107] Transport endpoint is not connected: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules'

**Comment by kieranxsomer** [comment]
That's not a LORA issue that's google drive being a dork, no joke lol - your "ENDPOINT NOT CONNECTED " is drive kicking a fit, it REALY only does it with last ben's notebook and it's driving me up a wall XD - Reccomendation, copy a new one to your drive, rename the folder stuff that had the previous install, and just redo it.

**Comment by kieranxsomer** [comment]
Wait nope, it is a LORA issue, huh WEIRD - it's also google drive disconnecting from the lora folder I THINK, because ben's said this is an ongoing issue and that Runpod is more stable, and sadlyi t is but i'm not .... XD ALLM Y CONTENT IS ON DRIVE THANK YOU MUCHLY LMAO and uploading directly to runpod is an ightmare....

COLAB get your shiz together pls xD (Aka: I was ablt to train like 6 lora to day why is it being a dork with ONE INSTALL of stuff0
