### ISSUE TITLE
Why does this appear?

### ISSUE THREAD

**Issue by ElThunasFBI** [TheLastBen/fast-stable-diffusion#1805]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 151, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 230, in webui
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 111, in initialize
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 126, in list_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 46, in __init__
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 152, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

**Comment by ElThunasFBI** [comment]
> an issue with google drive, I'm investigating

Trank You!!!

**Comment by kieranxsomer** [comment]
It seems to be an issue when you have way too many files , i'm testing it now to see if that's the problem because mine broke as soon as i dumped liek 100+ lora into a folder XD

**Comment by lolosso** [comment]
It's now working?

**Comment by thejohnd0e** [comment]
I have same issue:
Is there any solution?

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 151, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 340, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 233, in webui
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 114, in initialize
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 126, in list_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 46, in __init__
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 146, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

**Comment by TheLastBen** [comment]
if you have many lora models, put them in subfolders

**Comment by thejohnd0e** [comment]
yes, i found thi solution https://github.com/TheLastBen/fast-stable-diffusion/issues/1784, works now!
