### ISSUE TITLE
ModuleNotFoundError: No module named 'fastapi'

### ISSUE THREAD

**Issue by kopyl** [TheLastBen/fast-stable-diffusion#1809]
Why? Why did you have the same issue 2 weeks ago and it is still an issue? :(

How to fix it?

**Comment by TheLastBen** [comment]
A1111 ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Dreambooth : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

use these links regularly to get the updated notebooks

**Comment by Gushousekai195** [comment]
> A1111 ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> 
> Dreambooth : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
> 
> use these links regularly to get the updated notebooks

Done that. Still broken.

`ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'`

**Comment by boginski345** [comment]
> > A1111 ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> > Dreambooth : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
> > use these links regularly to get the updated notebooks
> 
> Done that. Still broken.
> 
> ```
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
>     from fastapi import FastAPI
> ModuleNotFoundError: No module named 'fastapi'
> ```
> 
> Fix immediately!

Man! You are using this project for free! The author of this project is constantly improving his product and fixing all the bugs. What right do you have to write "Fix immediately!" ? If something doesn't suits you, write your own version of the colab and do it as fast as you can!

**Comment by Gushousekai195** [comment]
> > > A1111 ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> > > Dreambooth : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
> > > use these links regularly to get the updated notebooks
> > 
> > 
> > Done that. Still broken.
> > ```
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > Traceback (most recent call last):
> >   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
> >     from fastapi import FastAPI
> > ModuleNotFoundError: No module named 'fastapi'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Fix immediately!
> 
> Man! You are using this project for free! The author of this project is constantly improving his product and fixing all the bugs. What right do you have to write "Fix immediately!" ? If something doesn't suits you, write your own version of the colab and do it as fast as you can!

If I knew how to code my own version of the colab, I would. But I don't.

I don't even know how to fix this issue.

**Comment by boginski345** [comment]
> > A1111 ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> > Dreambooth : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
> > use these links regularly to get the updated notebooks
> 
> Done that. Still broken.
> 
> ```
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
>     from fastapi import FastAPI
> ModuleNotFoundError: No module named 'fastapi'
> ```
> 
> Fix immediately!

Is it really that hard to delete all the files from your google drive and reinstall everything? Before you get people with stupid requests!

**Comment by boginski345** [comment]
> > > > A1111 ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> > > > Dreambooth : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
> > > > use these links regularly to get the updated notebooks
> > > 
> > > 
> > > Done that. Still broken.
> > > ```
> > > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > > Traceback (most recent call last):
> > >   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
> > >     from fastapi import FastAPI
> > > ModuleNotFoundError: No module named 'fastapi'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Fix immediately!
> > 
> > 
> > Man! You are using this project for free! The author of this project is constantly improving his product and fixing all the bugs. What right do you have to write "Fix immediately!" ? If something doesn't suits you, write your own version of the colab and do it as fast as you can!
> 
> If I knew how to code my own version of the colab, I would. But I don't.
> 
> I don't even know how to fix this issue.

Everything works, you just need to completely delete all files from Google Drive and reinstall from the latest version of notepad

**Comment by Gushousekai195** [comment]
> > > A1111 ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> > > Dreambooth : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
> > > use these links regularly to get the updated notebooks
> > 
> > 
> > Done that. Still broken.
> > ```
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> > Traceback (most recent call last):
> >   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
> >     from fastapi import FastAPI
> > ModuleNotFoundError: No module named 'fastapi'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Fix immediately!
> 
> Is it really that hard to delete all the files from your google drive and reinstall everything? Before you get people with stupid requests!

It's not hard, it's tedious. I have to move all my models, LoRA, VAE, hypernetworks, textual embeddings, etc., reinstall ControlNet, reinstall all my Extensions

**Comment by TheLastBen** [comment]
you're not using the latest colab from the link you're likely using an old saved version of the notebook
