### ISSUE TITLE
got an error from colab "AttributeError: 'Slider' object has no attribute 'elem_classes'"

### ISSUE THREAD

**Issue by kaz9112** [TheLastBen/fast-stable-diffusion#1826]
`Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/22meinamix_meinaV8.safetensors: 30953ab0def62b5d0e90b8f84bd40f0af6048426c5f851535563e28fdee0684a
Loading weights [30953ab0de] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/22meinamix_meinaV8.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading100% 961k/961k [00:00<00:00, 6.39MB/s]
Downloading100% 525k/525k [00:00<00:00, 3.83MB/s]
Downloading100% 389/389 [00:00<00:00, 463kB/s]
Downloading100% 905/905 [00:00<00:00, 1.02MB/s]
Downloading100% 4.52k/4.52k [00:00<00:00, 6.89MB/s]
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): easynegative
Model loaded in 65.3s (calculate hash: 41.1s, load weights from disk: 15.0s, create model: 3.2s, apply weights to model: 3.9s, apply half(): 1.0s, move model to device: 0.8s, load textual inversion embeddings: 0.2s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 457, in create_ui
    modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 290, in initialize_scripts
    script = script_class()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 127, in __init__
    self.txt2img_w_slider = gr.Slider()
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 662, in __init__
    IOComponent.__init__(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 536, in IOComponent_init
    add_classes_to_gradio_component(self)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 521, in add_classes_to_gradio_component
    comp.elem_classes = ["gradio-" + comp.get_block_name(), *(comp.elem_classes or [])]
AttributeError: 'Slider' object has no attribute 'elem_classes'`

ive been using these for a month, got this error...

**Comment by HorrySheet** [comment]
Similar Error here - used this just 30 minutes ago.. must be a fresh error - 

Model loaded in 19.3s (load weights from disk: 13.7s, create model: 1.0s, apply weights to model: 2.9s, apply half(): 1.0s, move model to device: 0.7s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 457, in create_ui
    modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 290, in initialize_scripts
    script = script_class()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 229, in __init__
    self.txt2img_w_slider = gr.Slider()
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 662, in __init__
    IOComponent.__init__(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 536, in IOComponent_init
    add_classes_to_gradio_component(self)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 521, in add_classes_to_gradio_component
    comp.elem_classes = ["gradio-" + comp.get_block_name(), *(comp.elem_classes or [])]
AttributeError: 'Slider' object has no attribute 'elem_classes'

**Comment by umishima** [comment]
Same here

**Comment by stradanie** [comment]
same problem

**Comment by EstiNew** [comment]
in typo we are all fluent, same goes about developers ;)

**Comment by hrs97** [comment]
same problem,how to solve it

**Comment by kaz9112** [comment]
the problem is automatic1111 just upgrade the gradio to 3.23, i rolled it back to 3.16.2 it worked.

**Comment by Archon332** [comment]
How to roll it back?

**Comment by umishima** [comment]
> the problem is automatic1111 just upgrade the gradio to 3.23, i rolled it back to 3.16.2 it worked.

please share how to do it, thanks!

**Comment by kaz9112** [comment]
you could just change requirements.txt and requiremetns version.txt gradio == 3.23 to gradio == 3.16.2, but it will always be overwritten on the install/update auto111 cell.

**Comment by umishima** [comment]
> you could just change requirements.txt and requiremetns version.txt on sd-webui folder, gradio == 3.23 to gradio == 3.16.2, but it will always be overwritten on the install/update auto111 cell. what i did is replace auto1111 repo to mine, if you know how to clone past commit that's better, but idk how to do it lol, so i cloned his old commit to mine, and then clone it to the colab.
> 
> DISCLAIMER: i'm not responsible on what's going to happen to your shit, i suggest you people wait until next update from lastben, but if you can't wait for whatever reason well here goes:
> 
> 1. backup your output model or whatever history you had in your SD folder in gdrive
> 2. delete your SD folder
> 3. replace your update/install auto1111 cell with: (i don't know how to clone from older commits so i clone it manually then upload it to my github, i apologize for my stupidity)
> 
> #@markdown # Install/Update AUTOMATIC1111 repo from IPython.utils import capture from IPython.display import clear_output from subprocess import getoutput import ipywidgets as widgets import sys import fileinput import os import time
> 
> if not os.path.exists("/content/gdrive/MyDrive/"): print('�[1;31mGdrive not connected, using colab storage ...') time.sleep(4) !mkdir -p /content/gdrive/MyDrive/ with capture.capture_output() as cap: def inf(msg, style, wdth): inf = widgets.Button(description=msg, disabled=True, button_style=style, layout=widgets.Layout(min_width=wdth));display(inf) fgitclone = "git clone --depth 1" %mkdir -p /content/gdrive/MyDrive/sd %cd /content/gdrive/MyDrive/sd !$fgitclone -q --branch main https://github.com/kaz9112/stable-diffusion-webui !mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/cache/huggingface !ln -s /content/gdrive/MyDrive/sd/stable-diffusion-webui/cache/huggingface /root/.cache/
> 
> with capture.capture_output() as cap: %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/ !git reset --hard time.sleep(1) !rm webui.sh print('�[1;32m') !git pull clear_output() inf('\u2714 Done','success', '50px')
> 
> 4. run all

Thanks a lot ;)

**Comment by Archon332** [comment]
Replaced code, but it didn't worked.
![image](https://user-images.githubusercontent.com/119755850/227707889-cbf2b8de-08b6-4f7b-8180-55081e35ad80.png)

**Comment by TheLastBen** [comment]
will fix shortly

**Comment by Archon332** [comment]
You are awesome!

**Comment by kaz9112** [comment]
> Replaced code, but it didn't worked. ![image](https://user-images.githubusercontent.com/119755850/227707889-cbf2b8de-08b6-4f7b-8180-55081e35ad80.png)

indentations got efed, might want to wait lastben.
or you can just copy my colab:
https://colab.research.google.com/drive/1g6S-Hx0kUuX3LyaxZD_j_XCZe1M3lx4k?usp=sharing

**Comment by TheLastBen** [comment]
should work now

**Comment by davvoz** [comment]
@TheLastBen 
`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 22, in <module>
    import gradio
  File "/usr/local/lib/python3.9/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 35, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 27, in <module>
    from gradio.helpers import EventData, create_tracker, skip, special_args
ImportError: cannot import name 'EventData' from 'gradio.helpers' (/usr/local/lib/python3.9/dist-packages/gradio/helpers.py)`

**Comment by kaz9112** [comment]
> 

can confirm it works, i did get an error tho

`
#@markdown # Start Stable-Diffusion
from IPython.utils import capture
import time
import sys
import fileinput

Use_localtunnel = True #@param {type:"boolean"}

User = "sor" #@param {type:"string"}
Password= "sor" #@param {type:"string"}

Start Stable-Diffusion
Use_localtunnel:

User:
sor
Password:
sor
Add credentials to your Gradio interface (optional).
Error loading script: loopback.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/loopback.py", line 57
    match denoising_curve:
          ^
SyntaxError: invalid syntax`

still it does works

**Comment by TheLastBen** [comment]
that's a syntax issue from the A1111 repo's side, they will fix it surely

**Comment by Onesens** [comment]
I'm having the same problem, I'm a huge noob can't program anything. SD was working yesterday night so it started doing this today, please addvise how to fix?

**Comment by PuDood** [comment]
> will fix shortly 很快就会修好
> 
> keep in mind this ; [AUTOMATIC1111/stable-diffusion-webui#8894](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8894)记住这一点;AUTOMATIC 1111/稳定-扩散-webui#8894

Is this feedback submitted? Whether it has been resolved at present, I don't know what to do, I don't understand

**Comment by PuDood** [comment]
> it's all fixed 都搞定了

What shall I do?

**Comment by TheLastBen** [comment]
use the latest notebooks by clicking on their thumbnails in the main page of the repo
