### ISSUE TITLE
textbox' object has no attribute 'type' error

### ISSUE THREAD

**Issue by Tshxzdow** [TheLastBen/fast-stable-diffusion#1827]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 460, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 288, in create_toprow
    prompt = gr.Textbox(label="Prompt", elem_id=f"{id_part}_prompt", show_label=False, lines=3, placeholder="Prompt (press Ctrl+Enter or Alt+Enter to generate)")
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 300, in __init__
    IOComponent.__init__(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 536, in IOComponent_init
    add_classes_to_gradio_component(self)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 521, in add_classes_to_gradio_component
    comp.elem_classes = ["gradio-" + comp.get_block_name(), *(comp.elem_classes or [])]
AttributeError: 'Textbox' object has no attribute 'elem_classes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 654, in create_ui
    ui_extra_networks.setup_ui(extra_networks_ui, txt2img_gallery)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1097, in __exit__
    self.config = self.get_config_file()
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1073, in get_config_file
    "props": utils.delete_none(block.get_config())
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 322, in get_config
    "type": self.type,
AttributeError: 'Textbox' object has no attribute 'type'

**Comment by Gryphan1** [comment]
same error today

**Comment by Gryphan1** [comment]
some problem with versions on a colab i think

**Comment by dazaibsd** [comment]
same!!

**Comment by Tshxzdow** [comment]
I comply with reporting to see if I'm not the only one who had the error, thanks guys, i will wait for some fix or if someone can explain the matter, anyway if Ben reads this I want to thank you for all your work, especially for those of us who do not have a high-end PC

**Comment by loboere** [comment]
same

**Comment by Archon332** [comment]
The error of mine.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 457, in create_ui
    modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 290, in initialize_scripts
    script = script_class()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 229, in __init__
    self.txt2img_w_slider = gr.Slider()
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 662, in __init__
    IOComponent.__init__(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 536, in IOComponent_init
    add_classes_to_gradio_component(self)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 521, in add_classes_to_gradio_component
    comp.elem_classes = ["gradio-" + comp.get_block_name(), *(comp.elem_classes or [])]
AttributeError: 'Slider' object has no attribute 'elem_classes'

**Comment by Omenizer** [comment]
Here too.

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by Gryphan1** [comment]
> use the latest notebook

working but this

Error loading script: loopback.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/loopback.py", line 57
    match denoising_curve:
          ^
SyntaxError: invalid syntax

**Comment by TheLastBen** [comment]
that's not caused by the notebook, it's caused by A1111 repo

**Comment by kihalsame** [comment]
I'm doing this locally on my PC and the same thing is happening.

**Comment by SiyuanLi-SYSUSOB** [comment]
SD-Webui API layer loaded
Loading weights [fc2511737a] from E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\models\Stable-diffusion\final-pruned.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 2.1s (create model: 0.3s, apply weights to model: 0.6s, apply half(): 0.7s, load VAE: 0.4s).
Traceback (most recent call last):
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\modules\ui.py", line 460, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\modules\ui.py", line 288, in create_toprow
    prompt = gr.Textbox(label="Prompt", elem_id=f"{id_part}_prompt", show_label=False, lines=3, placeholder="Prompt (press Ctrl+Enter or Alt+Enter to generate)")
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\components.py", line 300, in __init__
    IOComponent.__init__(
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\modules\scripts.py", line 544, in IOComponent_init
    add_classes_to_gradio_component(self)
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\modules\scripts.py", line 529, in add_classes_to_gradio_component
    comp.elem_classes = ["gradio-" + comp.get_block_name(), *(comp.elem_classes or [])]
AttributeError: 'Textbox' object has no attribute 'elem_classes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\webui.py", line 343, in <module>
    webui()
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\webui.py", line 243, in webui
    shared.demo = modules.ui.create_ui()
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\modules\ui.py", line 459, in create_ui
    with gr.Blocks(analytics_enabled=False) as txt2img_interface:
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\blocks.py", line 1097, in __exit__
    self.config = self.get_config_file()
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\blocks.py", line 1073, in get_config_file
    "props": utils.delete_none(block.get_config())
  File "E:\Projects\AIpaint\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\components.py", line 322, in get_config
    "type": self.type,
AttributeError: 'Textbox' object has no attribute 'type'. Did you mean: 'style'?

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by Archon332** [comment]
> 

I do, but there is still error with loopback.py. After replacing code, just like in recomendation, UI started to work, but hard and very slow, not genereation, but UI itself. PNG info and placing in frompt field don't wark at all. And UI became, don't even know how to write this... more narrow.

**Comment by kihalsame** [comment]
I moved all the extensions to a different directory and it started working.

**Comment by Vinnieassaulter** [comment]
Same error with me

**Comment by huaishuiweizhu** [comment]
Same to me. But it goes smoothly just few weeks before, how would it be such troublesome now? I guess there's something wrong with the version.
![capture](https://user-images.githubusercontent.com/89005670/227753584-4a27edb4-f019-48a0-a526-67ead75ec5f6.PNG)

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by Goratrix6666** [comment]
> use the latest notebook

Would you please tell me/us how to use the last notebook. I am sure a lot of users like me just followed a step-by-step procedure to install A1111 without an idea of what is going on.

**Comment by TheLastBen** [comment]
Click on the thumbnails in the main page of the repo

**Comment by Goratrix6666** [comment]
Thank you
