### ISSUE TITLE
ImportError: cannot import name 'EventData' from 'gradio.helpers' 

### ISSUE THREAD

**Issue by davvoz** [TheLastBen/fast-stable-diffusion#1829]
```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 22, in <module>
    import gradio
  File "/usr/local/lib/python3.9/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 35, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 27, in <module>
    from gradio.helpers import EventData, create_tracker, skip, special_args
ImportError: cannot import name 'EventData' from 'gradio.helpers' (/usr/local/lib/python3.9/dist-packages/gradio/helpers.py)
```

**Comment by brovador** [comment]
same here

**Comment by ll2pakll** [comment]
I have the same problem

**Comment by TheLastBen** [comment]
upgraded to gradio 3.23, use the latest notebook

**Comment by Shadhil-Imcapsule** [comment]
> upgraded to gradio 3.23, use the latest notebook

still having the issue

**Comment by TheLastBen** [comment]
use a fresh sd folder
