### ISSUE TITLE
Error loading script: loopback.py 

### ISSUE THREAD

**Issue by wth153** [TheLastBen/fast-stable-diffusion#1830]
Error loading script: loopback.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/loopback.py", line 57
    match denoising_curve:
          ^
SyntaxError: invalid syntax

**Comment by ll2pakll** [comment]
The server starts up, but I get the same error when I start the server

**Comment by eccehobo111** [comment]
Same. 

UI loads at the gradio url but clicking "generate" on txt2img does nothing

**Comment by amokiller** [comment]
Same here

**Comment by gururaj-bhat** [comment]
I got the same error in colab console , but at the URL atleast tx2img is working

**Comment by davvoz** [comment]
there are javascript errors and various issues

**Comment by TheLastBen** [comment]
that's A1111 repo, not from my side

**Comment by blindiff** [comment]
same issue here too

**Comment by summernon** [comment]
As a **quick and dirty workaround** I did the following:
1. Open /content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/loopback.py
2. Edit lines 57-63 from:
```
            match denoising_curve:
                case "Aggressive":
                    strength = math.sin((progress) * math.pi * 0.5)
                case "Lazy":
                    strength = 1 - math.cos((progress) * math.pi * 0.5)
                case _:
                    strength = progress
```
to
```
            if denoising_curve == "Aggressive":
                strength = math.sin((progress) * math.pi * 0.5)
            elif denoising_curve == "Lazy":
                strength = 1 - math.cos((progress) * math.pi * 0.5)
            else:
                strength = progress
```

I don't know what caused the original problem and I can't vouch for this patch long-term or promise that it won't break anything, all I'll say is that my colab Stable Diffusion is now running and generating images again 👍

**Comment by f4cyw** [comment]
> As a **quick and dirty workaround** I did the following:
> 
> 1. Open /content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/loopback.py
> 2. Edit lines 57-63 from:
> 
> ```
>             match denoising_curve:
>                 case "Aggressive":
>                     strength = math.sin((progress) * math.pi * 0.5)
>                 case "Lazy":
>                     strength = 1 - math.cos((progress) * math.pi * 0.5)
>                 case _:
>                     strength = progress
> ```
> 
> to
> 
> ```
>             if denoising_curve == "Aggressive":
>                 strength = math.sin((progress) * math.pi * 0.5)
>             elif denoising_curve == "Lazy":
>                 strength = 1 - math.cos((progress) * math.pi * 0.5)
>             else:
>                 strength = progress
> ```
> 
> I don't know what caused the original problem and I can't vouch for this patch long-term or promise that it won't break anything, all I'll say is that my colab Stable Diffusion is now running and generating images again 👍

I can't find this code in the same file you mentioned, can you share this?

**Comment by Archon332** [comment]
> 

I made this and UI is opening now, but still not working.
Well, there is no longer that error during starting. UI opens but nothing work.
For example, when I trying to get PNG data. Place image to prompt field doesn't work too.
![image](https://user-images.githubusercontent.com/119755850/227718302-d8dd5842-8437-47c7-a08a-4b6cfb4846b7.png)
There is the error.
Task exception was never retrieved
future: <Task finished name='9yynkazrcye_235' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.9/dist-packages/gradio/queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 347, in process_events
client_awake = await self.gather_event_data(event)
File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 220, in gather_event_data
data, client_awake = await self.get_message(event, timeout=receive_timeout)
File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 453, in get_message
data = await asyncio.wait_for(
File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
return fut.result()
File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json
self._raise_on_disconnect(message)
File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
![image](https://user-images.githubusercontent.com/119755850/227718281-82393307-6973-4117-97a4-36ab3d707e45.png)

**Comment by summernon** [comment]
> I can't find this code in the same file you mentioned, can you share this?
Here's the original and my edit:
https://gist.github.com/summernon/cfe04809075432567900b12930ee9fae

Please use with caution, I can't vouch for this code, it's just a suggestion to help you fix your local setup!

**Comment by Archon332** [comment]
> > I can't find this code in the same file you mentioned, can you share this?
> 
> Here's the original and my edit: https://gist.github.com/summernon/cfe04809075432567900b12930ee9fae
> 
> Please use with caution, I can't vouch for this code, it's just a suggestion to help you fix your local setup!

Another time I'm trying to run UI and it's starting without errors, just like usual, but when I try to do something, nothing works. And there is another error.
![image](https://user-images.githubusercontent.com/119755850/227719420-d51771f8-7068-40f8-be6a-86a514edbf90.png)

**Comment by spmadv** [comment]
same problem here @TheLastBen

**Comment by zox010** [comment]
Error loading script: loopback.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/loopback.py", line 57
    match denoising_curve:
          ^
SyntaxError: invalid syntax

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 51, in <module>
    from dreambooth.webhook import save_and_test_webhook
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/webhook.py", line 6, in <module>
    import discord_webhook
ModuleNotFoundError: No module named 'discord_webhook'

**Comment by TheLastBen** [comment]
drambooth extension doesn't work with the A1111 notebook, you can use the dreambooth notebook instead
