### ISSUE TITLE
Does not work with lora

### ISSUE THREAD

**Issue by eccehobo111** [TheLastBen/fast-stable-diffusion#1831]
I have a new lora trained on cloneofsimo/lora on replicate. This notebook doesn't seem to like it:

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7febaf70ed60>]: ValueError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 170, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 108, in load_lora
    key, lora_key = fullkey.split(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

Is there a fix or an extension for this??

(Tx for all your work btw ;) )

**Comment by eccehobo111** [comment]
As a test, I tried a lora trained on FastBen notebook. After I click generate nothing happens, it seems to hang the WebUI

Please, any thoughts?
