### ISSUE TITLE
ImportError: cannot import name 'EventData' from 'gradio.helpers' (/usr/local/lib/python3.9/dist-packages/gradio/helpers.py)

### ISSUE THREAD

**Issue by kopyl** [TheLastBen/fast-stable-diffusion#1834]
???

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by potbelliedconan** [comment]
Im definitely  using the latest version,

  os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
  !pip install gradio==3.23 -qq

Still having this problem, do I need delete my old install ?

**Comment by jtran-developer** [comment]
It loads up for me though, even though there's a syntax error along the way

```
Error loading script: loopback.py
Traceback (most recent call last):
  File "/content/gdrive/.shortcut-targets-by-id/1S33CUH0-cqG4EkR8r0vGFnH9aECswn4r/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/.shortcut-targets-by-id/1S33CUH0-cqG4EkR8r0vGFnH9aECswn4r/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/.shortcut-targets-by-id/1S33CUH0-cqG4EkR8r0vGFnH9aECswn4r/sd/stable-diffusion-webui/scripts/loopback.py", line 57
    match denoising_curve:
          ^
SyntaxError: invalid syntax`
```

**Comment by jtran-developer** [comment]
That said, error messages seem to have gotten pretty colorful.

[https://cdn.discordapp.com/attachments/1064534615441809450/1089186664087289906/image.png](url)

**Comment by xmalina** [comment]
I'm getting the same issue @jtran-developer  -- any workaround ideas?

**Comment by jtran-developer** [comment]
Do you need a workaround?  It's running and generating images properly.  I just can't click to expand the image.  You can still right click and save.

**Comment by xmalina** [comment]
Mine aren't working and can't right click and save -- I tried restarting, no go. will let you know if anything changes..

<img width="866" alt="image" src="https://user-images.githubusercontent.com/5224095/227722977-65128b72-05d5-4064-8049-09976dc69d8d.png">

<img width="605" alt="image" src="https://user-images.githubusercontent.com/5224095/227722926-bf350ad2-93a6-4afa-8abc-634056545759.png">

**Comment by josefelix82** [comment]
the same problem!! 
something new¿?

**Comment by loboere** [comment]
I think I'm going to make my own stable diffusion ui already has me tired automatic1111 gradio
