### ISSUE TITLE
Error while loading a session

### ISSUE THREAD

**Issue by gururaj-bhat** [TheLastBen/fast-stable-diffusion#1835]
Session found, loading the trained model ...  
Session found, loading the trained model ...  
/usr/local/lib/python3.9/dist-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1138, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1103, in convert
    key_count = save_stable_diffusion_checkpoint(v2_model, args.model_to_save, text_encoder, unet,
  File "/content/convertodiff.py", line 1038, in save_stable_diffusion_checkpoint
    torch.save(new_ckpt, output_file)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/models does not exist.
Conversion error, if the error persists, remove the CKPT file from the current session folder

Using SD 2.1-768

**Comment by TheLastBen** [comment]
did you choose v2-768 in the dropdown ?

**Comment by dinilvalsan** [comment]
before yesterday update, i was able to train with this model.
error i getting now is

/usr/local/lib/python3.9/dist-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(
Converting to Diffusers ...
usage: convert_original_stable_diffusion_to_diffusers.py
       [-h]
       --checkpoint_path
       CHECKPOINT_PATH
       [--original_config_file ORIGINAL_CONFIG_FILE]
       [--num_in_channels NUM_IN_CHANNELS]
       [--scheduler_type SCHEDULER_TYPE]
       [--pipeline_type PIPELINE_TYPE]
       [--image_size IMAGE_SIZE]
       [--prediction_type PREDICTION_TYPE]
       [--extract_ema]
       [--upcast_attention]
       [--from_safetensors]
       [--to_safetensors]
       --dump_path
       DUMP_PATH
       [--device DEVICE]
       [--stable_unclip STABLE_UNCLIP]
       [--stable_unclip_prior STABLE_UNCLIP_PRIOR]
       [--clip_stats_path CLIP_STATS_PATH]
       [--controlnet]
convert_original_stable_diffusion_to_diffusers.py: error: unrecognized arguments: models/REDLABEL.ckpt
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error

**Comment by TheLastBen** [comment]
are you using the latest colab ?

**Comment by dinilvalsan** [comment]
yes, https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by TheLastBen** [comment]
what session name did you use ?
