### ISSUE TITLE
Are you updating right now?

### ISSUE THREAD

**Issue by vaclav-kyle** [TheLastBen/fast-stable-diffusion#1840]
생성 버튼이 작동하지 않아. 종료 후 재시작 중인데 이런 메시지가 나오네? 혹시 지금 업데이트 중인가? 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by vaclav-kyle** [comment]
ah! It's because I didn't update!!! Sorry. I solved this.
But since this afternoon (I'm Korean here), the message below keeps appearing while running, can't this be solved?

Error loading script: loopback.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/loopback.py", line 57
    match denoising_curve:
          ^
SyntaxError: invalid syntax

**Comment by TheLastBen** [comment]
will fix soon

**Comment by HorrySheet** [comment]
> will fix soon

Awesome! Thanks for this colab and your hard work Mr. Sir!

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/1ea1f33b4f42bea98b9584bd79e33e82c24e520a

**Comment by vaclav-kyle** [comment]
> 

모두 해결된 것 같군요!! 감사합니다.!!!

**Comment by vaclav-kyle** [comment]
> will fix soon

Looks like all of these issues have been resolved!! Except the wild card list doesn't appear in the dynamic wild card menu! It's nice to be able to bring it up with the automatic prompt function!! Thank you for your effort thank you

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
Your wild card extension is out of date, update it or simply remove it then reinstall it

**Comment by vaclav-kyle** [comment]
> Your wild card extension is out of date, update it or simply remove it then reinstall it

i got it! THX!!!! : )

**Comment by Dreason8** [comment]
Not resolved here. 
Like others have posted on other threads, after 1 or 2 generations in TXT2IMG it stops working and the page needs to be refreshed, even then you get maybe one generation and it just stops working again. This is using the latest notebook.

Also the full screen preview of the generation no longer works when you click on the thumbnail.

**Comment by TheLastBen** [comment]
@Dreason8 ngrok solves the freezing issue
