### ISSUE TITLE
I’m having this error while starting my Stable Diffusion

### ISSUE THREAD

**Issue by DanoGL** [TheLastBen/fast-stable-diffusion#1849]
The colab gives me this error:

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-locon/scripts/main.py", line 10, in <module>
    import lora
ModuleNotFoundError: No module named 'lora'

it doesn’t seem to affect my generations, I can use LoRA, but, how can I fix this so it doesn’t show up?

**Comment by Holymittens** [comment]
Your A1111 SD Webui LoCon extension is out of date. Go to the Extensions tab, click "Check for Updates", wait for it to finish, then click Apply and Restart UI. That should get rid of this error.

**Comment by modulator** [comment]
I'm having this error with the latest version - but I don't have SD Webui LoCon extension installed...
