### ISSUE TITLE
When i try to star this error appears Traceback (most recent call last):   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>     from modules import paths, timer, import_hook, errors   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>     from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir ModuleNotFoundError: No module named 'modules.paths_internal'

### ISSUE THREAD

**Issue by qwert190** [TheLastBen/fast-stable-diffusion#1852]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by TheLastBen** [comment]
that was fixed, try renaming/removing your sd folder

**Comment by modulator** [comment]
Same error. I'm getting this error on this latest Colab version.

**Comment by TheLastBen** [comment]
if that specific error persists, do a manual git pull to the webui folder and see if it updates

**Comment by Dnkbacker** [comment]
@TheLastBen Hi, new here. Can you explain step-by-step how to do that in the fast_stable_diffusion_AUTOMATIC1111.ipynb colab notebook? Including where to input the code on the page? Thank you!
