### ISSUE TITLE
Clean install, still a lot of problems

### ISSUE THREAD

**Issue by Topzie** [TheLastBen/fast-stable-diffusion#1862]
Hi Ben, I had the same errors yesterday so I decided to wait for the update.
Unfortunately there's still a problem.
The only thing that works is txt2img.
As aI mentioned I did a clean install, no extensions embeddings or whatsoever.
Here's the output:

Error loading script: lora_script.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 4, in <module>
    import lora
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 238, in <module>
    def lora_apply_weights(self: torch.nn.Conv2d | torch.nn.Linear | torch.nn.MultiheadAttention):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Calculating sha256 for /content/gdrive/MyDrive/extraModels/mangledMerge_v2.safetensors: af471673eccbeb98c72a59bb77962398cf0d5fcb2b6fc2d638a0d9989d8dacde
Loading weights [af471673ec] from /content/gdrive/MyDrive/extraModels/mangledMerge_v2.safetensors
Creating model from config: /content/gdrive/MyDrive/extraModels/mangledMerge_v2.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 61.1s (calculate hash: 37.3s, load weights from disk: 14.9s, load config: 0.5s, create model: 0.8s, apply weights to model: 4.5s, apply half(): 2.0s, move model to device: 0.9s, load textual inversion embeddings: 0.1s).
Running on public URL: https://9d3641aa985265fec2.gradio.live/
✔ Connected
Startup time: 91.6s (import torch: 6.7s, import gradio: 1.4s, import ldm: 1.0s, other imports: 5.5s, list SD models: 0.6s, setup codeformer: 0.4s, load scripts: 1.5s, load SD checkpoint: 61.1s, create ui: 1.0s, gradio launch: 12.0s, scripts app_started_callback: 0.2s).
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/aspectRatioOverlay.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/script.js?1679834073.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/progressbar.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/notification.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/localization.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/dragdrop.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/extensions.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/imageviewer.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/contextMenus.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/imageMaskFix.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/extraNetworks.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/textualInversion.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/ui.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/edit-attention.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/generationParams.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/hints.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/prompt-bracket-checker/javascript/prompt-bracket-checker.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/imageParams.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/hires_fix.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='d5ry4ijyw9_149' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.9/dist-packages/gradio/queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006

**Comment by Topzie** [comment]
Also this (after initiating another txt2img:

API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/progressbar.js {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/extensions.js?1679834072.0 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/imageviewer.js {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/progressbar.js {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: https://9d3641aa985265fec2.gradio.live/file=/content/gdrive/MyDrive/sd/stable-diffusion-webui/javascript/extraNetworks.js {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
100% 20/20 [00:06<00:00,  2.98it/s]
WARNING:  Invalid HTTP request received.
WARNING:uvicorn.error:Invalid HTTP request received.

**Comment by Topzie** [comment]
Update: In the end I was able to create 5 images and then it didn't respond anymore.

**Comment by amokiller** [comment]
same as me, I installed a clean notebook (deleted all files from the DRIVE previously) and I got the same error as OP. :(

**Comment by zeallat** [comment]
Check this https://github.com/TheLastBen/fast-stable-diffusion/issues/1857#issuecomment-1484084940

**Comment by TheLastBen** [comment]
@Topzie Use ngrok

**Comment by Topzie** [comment]
> @Topzie Use ngrok

I'd rather not so I'll wait a bit
Will use kaggle for the time being
Thanks anyway, I'm sure it will work again soon enough 😊

**Comment by Topzie** [comment]
> Check this [#1857 (comment)](https://github.com/TheLastBen/fast-stable-diffusion/issues/1857#issuecomment-1484084940)

@zeallat I did, but I have no idea what I'm supposed to do next. I have tried the latest, the lora error is gone but that was the least of my problems.  I tried to load the 1.5 model (somebody suggested it could be a SD v2 issue) and see if it made any difference. No luck.

**Comment by Topzie** [comment]
It's not getting any better yet, at least not to me.

**Comment by aleqniko** [comment]
after the SD on google colab update it works very badly, it constantly crashes, models and PNG info take a long time, extensions crushes
ONE ANSWER
Why was it necessary to spoil something that worked well?

**Comment by TheLastBen** [comment]
It's not the notebook's fault, it's the A1111 repo which I don't control. I added the option to use the latest working commit which reverts to the previous working commit, use it. also use the latest notebook

**Comment by aleqniko** [comment]
> Это не вина ноутбука, это репозиторий A1111, который я не контролирую. Я добавил возможность использовать последнюю рабочую фиксацию, которая возвращается к предыдущей рабочей фиксации, используйте ее. также используйте последнюю версию ноутбука

dear friend, I do not blame you for this, but those who are involved in this
And thank you so much for solving all these problems so quickly.
