### ISSUE TITLE
When doing inpaint

### ISSUE THREAD

**Issue by Ai-Artsca** [TheLastBen/fast-stable-diffusion#1879]
Task exception was never retrieved
future: <Task finished name='2zr4ea7gxae_632' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.9/dist-packages/gradio/queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.9/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006

**Comment by CottonTales** [comment]
I'm getting this as well, whenever I try to use img2img or Inpainting. Text2img works totally fine, but anything in the img2img tab just does not generate anything and gives this error in the console. I've tried both localtunnel and ngrok, neither changed anything at all, sadly.

**Comment by treepen** [comment]
I am having the same problem, and I reach the topic you mentioned, but I'm a real noob, with this **(!pip install -r requirements.txt) and (!pip install --upgrade gradio==3.23.0)** Do I have to type it in cmd or the webui-User.bat?

**Comment by Wite905** [comment]
have there been any results? same problem when using in google collab

**Comment by treepen** [comment]
Thank you so much @Billiva. I tried and unfortunately, it does not work, the model tab keeps loading and the img2img, inpainting, extra, still do not work @Wite905

**Comment by TheLastBen** [comment]
use ngrok

**Comment by Ai-Artsca** [comment]
how can we go back to previous version this new update broke alot of things

**Comment by WildNullPointer** [comment]
> use ngrok

why does ngrok work better than localtunnel here? Using ngrok fixed my issues.

**Comment by ffdown** [comment]
> 

more instuction please

**Comment by Wite905** [comment]
> I just input "**--no-gradio-queue**" into _webui-user_ and everything went back to normal. (img2img, inpaint, etc.)
> 
> Just edit the file webui-user.bat and input the command there.
> 
> set COMMANDLINE_ARGS= **--no-gradio-queue**

so it usable without ngrok?

**Comment by treepen** [comment]
@Billiva it works, thank you, my friend
