### ISSUE TITLE
WebSocketDisconnect img2img

### ISSUE THREAD

**Issue by i-zet** [TheLastBen/fast-stable-diffusion#1886]
I ran into a problem today after the upgrade. Through the web interface img2img stopped working.
I created a new directory and re-downloaded the repository and ran it, but the problem persists.
What's interesting is that everything works fine through the discord aiyabot bot. The error is only through the web interface.

```
Arguments: ('task(7ypj03v4sots3fp)', 0, 'dadadad', '', [], None, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\img2img.py", line 87, in img2img
    image = init_img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

Task exception was never retrieved
future: <Task finished name='78n8tf1oajc_149' coro=<Queue.process_events() done, defined at D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "C:\Users\Zet\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
```

Using windows 11

**Comment by blutenval** [comment]
+ does not work since lunch, does not generate images, only after restarting does one generation and that's it. I processed it with a common package, but now I have stopped doing this too.

**Comment by Sooty001** [comment]
Yes, I have exactly the same error and the same problem

**Comment by SDPDVADER** [comment]
same here same issue

**Comment by loboere** [comment]
sometimes I start and it does not generate any image, I have to execute the colab cell several times

**Comment by digital-soul18** [comment]
Yeah same

**Comment by TheLastBen** [comment]
use ngrok

**Comment by Sooty001** [comment]
> use ngrok

I am using ngrok. In principle, everything works, but the picture appears only in Google Drive, it is not displayed on the screen

**Comment by Sooty001** [comment]
> use ngrok

I am using ngrok. In principle, everything works, but the picture appears only in Google Drive, it is not displayed on the screen

**Comment by TheLastBen** [comment]
I'll check it out
