### ISSUE TITLE
Can't load models

### ISSUE THREAD

**Issue by Dijasnnn** [TheLastBen/fast-stable-diffusion#1890]
Someone can help me? After the issue #1857 i can't load models, loras or anything, just show the loading symbol and i don't know how to solve it
![1](https://user-images.githubusercontent.com/122062359/228360835-f446bb1c-6fc9-4109-8b7c-2b06d7b52729.PNG)

**Comment by RabblerouserGT** [comment]
I can confirm I'm getting this as well. Though I don't think I had the lora issue? Tried with the newest version as of this writing. It also affects the Settings tab:

![image](https://user-images.githubusercontent.com/3516603/228369731-5c765cfb-5b1d-439c-ad52-ef31880f95e8.png)

The most recent things I've done were updating extensions (which seems to cause errors when you use a username/password).

**Comment by kieranxsomer** [comment]
<img width="2454" alt="Screenshot 2023-03-29 at 1 36 54 PM" src="https://user-images.githubusercontent.com/58930427/228397014-bbfde460-703b-4699-805f-95b65a6d3472.png">
Same issue here, it's not a lora issue it's gradio.
it's nothing to do with ben's code i think it's likely the gradio update, and A1111' s breaking from it

**Comment by kieranxsomer** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range\

I got this after i closed it- reloading the UI doesn't do anything

**Comment by AzaradoChan** [comment]
Same here

![image](https://user-images.githubusercontent.com/65982758/228431833-8b978a3c-f3f9-4522-981a-00a6c78e9153.png)
