### ISSUE TITLE
ImportError: cannot import name 'models_path' from 'modules.paths'

### ISSUE THREAD

**Issue by irrationalforest** [TheLastBen/fast-stable-diffusion#19]
Hi there,
First, please allow me to thank you for your work on this project. Much appreciated!

I'm running into an error when trying to run the final cell in the colab for Automatic1111:

/content/gdrive/MyDrive/sd/stable-diffusion
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 9, in <module>
    import modules.codeformer_model as codeformer
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/codeformer_model.py", line 8, in <module>
    import modules.face_restoration
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/face_restoration.py", line 1, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 13, in <module>
    import modules.sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 11, in <module>
    from modules import shared, modelloader
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 9, in <module>
    from modules.upscaler import Upscaler
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/upscaler.py", line 13, in <module>
    from modules.paths import models_path
ImportError: cannot import name 'models_path' from 'modules.paths' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py)

Excuse my ignorance if this is something I'm doing wrong - this is the first time I've used colab and most of my containerisation experience is just local server/linux-related things in Docker.
Any tips on what I should be troubleshooting?

Kind regards,
Irrational

**Comment by TheLastBen** [comment]
Hello, working on a fix, should work in a few minutes, make sure you used the latest colab after the fix

**Comment by irrationalforest** [comment]
Wow, that was fast!
Many thanks, I'll give it a shot once I see the commit.

**Comment by TheLastBen** [comment]
AUTOMATIC1111 made a big update on their paths system, so before you run the colab, you will have to delete the "sd" folder from your drive to update the paths.

**Comment by irrationalforest** [comment]
Thanks again, will do.
