### ISSUE TITLE
lora faild , haw to fix this ?

### ISSUE THREAD

**Issue by YassineMenai** [TheLastBen/fast-stable-diffusion#1901]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7f7cc87197f0>]: RuntimeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 176, in load_lora
    module.weight.copy_(weight)
RuntimeError: output with shape [4, 320, 1, 1] doesn't match the broadcast shape [4, 320, 3, 3]

**Comment by TheLastBen** [comment]
use this extension https://github.com/kohya-ss/sd-webui-additional-networks

**Comment by YassineMenai** [comment]
> > use this extension https://github.com/kohya-ss/sd-webui-additional-networks
> 
> Don't work

just follow the steps on that link , its work fine for me

**Comment by lolosso** [comment]
> > > use this extension https://github.com/kohya-ss/sd-webui-additional-networks
> > 
> > 
> > Don't work
> 
> just follow the steps on that link , its work fine for me

thx man
