### ISSUE TITLE
Suddenly today this error occurred

### ISSUE THREAD

**Issue by kennethyoon** [TheLastBen/fast-stable-diffusion#1912]
/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Installing openmim
Installing mmcv-full
Installing mmdet
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 14, in <module>
    from dynamicprompts.wildcards import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts.wildcards'

I haven't touched anything since yesterday
After the error occurred, I checked only this part of Use_localtunnel just in case

**Comment by TheLastBen** [comment]
Try running the notebook without the first cell, if it works, then your extensions folder needs cleaning

**Comment by PhoenixSOFF** [comment]
I'm also having the same issue. I tried running it without connecting to Google Drive and while It's downloading the v.2.1-768px model in the converting to CKPT stage i get this error and also get it when trying to start.

**Comment by harryoac** [comment]
same error

**Comment by kieranxsomer** [comment]
I got MOST of that error, yeeted a few plugins, got it again SOMEWHAT butttt.... this is the FIRST TIME i've loaded A1111 and it's loaded a model, and DIDNT crap out on me (I also cleaned up my models folder lmao)

**Comment by Mossbraker** [comment]
I've also been getting that dynamic_prompting.py error for over a week now.
>Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 3, in <module>
    from sd_dynamic_prompts.dynamic_prompting import Script
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 14, in <module>
    from dynamicprompts.wildcards import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts.wildcards'

If I remove and reinstall the Dynamic Prompts extension, it will work for as long as I'm connected to the runtime - including interrupting and rerunning the last cell. The next time I connect to a runtime, however, the error always returns and I have to remove and reinstall the extension again.
