### ISSUE TITLE
Error in Colab, I tried to reinstall but no effect.

### ISSUE THREAD

**Issue by Toshik-One** [TheLastBen/fast-stable-diffusion#1915]
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by HonestDeng** [comment]
I met this problem also. Anyone can help?

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by CorpusLurkerVB** [comment]
> I met this problem also. Anyone can help?

I'm having the same error, as well as this one with different combinations:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

```
After trying near everything, Somehow I made it work like this

1. Paste the Link of the folder where my Models are  in "Connect Google Drive", 
2. Checked and unchecked the "Use_Latest_Working_Commit"  
3. Added the Path_to_Model 
4. Left everything else empty, no ControlNet
5. Entered through LocalTunnel. 

I hope this helps

**Comment by digital-soul18** [comment]
I'm still getting the same error. Even after doing the above steps, removing my previous install also.

**Comment by TheLastBen** [comment]
fixed, use the latest notebook
