### ISSUE TITLE
Suddenly got error

### ISSUE THREAD

**Issue by fernando122** [TheLastBen/fast-stable-diffusion#1918]
/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")

**Comment by TheLastBen** [comment]
it doesn't affect the training or inference though

**Comment by blindiff** [comment]
same error here and cant load a1111 after this, tried deleting extensions folder and all

**Comment by mvcxgem** [comment]
i couldn't get it to load either 
Textual inversion embeddings loaded(0): 
Model loaded in 68.7s (calculate hash: 43.9s, load weights from disk: 14.5s, create model: 5.2s, apply weights to model: 3.2s, apply half(): 1.1s, move model to device: 0.8s).
Error executing callback after_component_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 191, in after_component_callback
    c.callback(component, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 860, in on_after_component_callback
    component.click(fn=self.save_submit_img2img_tab, inputs=gr.State(component.elem_id), outputs=[])
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

Error executing callback after_component_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 191, in after_component_callback
    c.callback(component, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 860, in on_after_component_callback
    component.click(fn=self.save_submit_img2img_tab, inputs=gr.State(component.elem_id), outputs=[])
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by TheLastBen** [comment]
is the box "use_lastest_working_commit" checked

**Comment by iammvc** [comment]
@TheLastBen yes it is.  i read through some other discussions.  

i've removed the folders and reinstalled the SD by checking "use latest working commit"

P.S. appreciate your work as always

**Comment by pcrii** [comment]
after i had this error i unchecked the commit box and changed the run line in the last cell to include "--no-gradio-queue" as advised in comments of the lastest a1111 commit and it worked for me

**Comment by iammvc** [comment]
if i add that no-gradio into the webui user file, it shows a different type of error

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by pcrii** [comment]
idk i was able to get running. here's a link to that post that helped me (i also took the lastest A1111 updates, didnt check the box to keep the old commit)
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81#commitcomment-106866386

**Comment by TheLastBen** [comment]
@iammvc use the latest colab

**Comment by iammvc** [comment]
@TheLastBen if i check the box "use latest working commit", it gives the original long error code.  

not sure how to check if i'm using the latest colab, but the python version is 3.9.16

**Comment by pcrii** [comment]
think Use_Latest_Working_Commit is breaking the install. adding --no-gradio-queue didnt fix anything for me it was just not using the check mark

**Comment by pcrii** [comment]
think Use_Latest_Working_Commit is breaking the install. adding --no-gradio-queue didnt fix anything for me it was just not using the check mark

i quit and loaded the colab twice to verify it just broke with Use_Latest_Working_Commit

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by iammvc** [comment]
thank you! it is now working very well!
