### ISSUE TITLE
Inpaint issue

### ISSUE THREAD

**Issue by methodicalculator** [TheLastBen/fast-stable-diffusion#1921]
In the last couple of days I have problems with the inpainting. Every time I try I have this problem popping up. No problems with text2image or image2image

`Traceback (most recent call last):
  File "/content/drive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/drive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/drive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 172, in img2img
    processed = process_images(p)
  File "/content/drive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "/content/drive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 711, in process_images_inner
    image_mask_composite = Image.composite(image.convert('RGBA').convert('RGBa'), Image.new('RGBa', image.size), p.mask_for_overlay.convert('L')).convert('RGBA')
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 3090, in composite
    image.paste(image1, None, mask)
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 1586, in paste
    self.im.paste(im, box, mask.im)
ValueError: images do not match`

**Comment by WeebBeyondRedemption** [comment]
Another issue with inpainting
```
Error completing request
Arguments: ('task(14e6sry9e8h33yb)', 2, 'sword, 1girl, red hair, ((ponytail)), armor, field, woman,', 'EasyNegative, nsfw', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x7F612C4CA4F0>, None, {'image': <PIL.Image.Image image mode=RGBA size=512x512 at 0x7F612C4CA5B0>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=512x512 at 0x7F612C4CAAC0>}, None, None, None, None, 20, 17, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, 1830299947.0, -1.0, 0, 0, 0, False, 512, 512, 0, 1, 32, 0, '', '', '', [], 0, <scripts.external_code.ControlNetUnit object at 0x7f612c6f6640>, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', False, '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, 50) {}
Traceback (most recent call last):
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/img2img.py", line 171, in img2img
    processed = process_images(p)
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/processing.py", line 991, in init
    image = images.resize_image(2, image, self.width, self.height)
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/images.py", line 295, in resize_image
    resized = resize(im, src_w, src_h)
  File "/content/gdrive/.shortcut-targets-by-id/11QL_d8PRd2OuP5zaVS4H5VTwvV_gGdsA/sd/stable-diffusion-webui/modules/images.py", line 264, in resize
    assert len(upscalers) > 0, f"could not find upscaler named {upscaler_name}"
AssertionError: could not find upscaler named 

```
