### ISSUE TITLE
No module named 'modules.textual_inversion.textual_inversion'

### ISSUE THREAD

**Issue by o0DiSaSter0o** [TheLastBen/fast-stable-diffusion#1925]
I don't know what the problem is, I seem to have reinstalled everything, the server is not being created.
a possible reason is that I share a folder from my main account to another one, where I have more space and the neural network itself is located
But then I didn't fully understand how to share a Google drive

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 31, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/ui_extra_networks.py", line 8, in <module>
    from modules.images import read_info_from_image
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/images.py", line 21, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
    from modules import sd_samplers_common, prompt_parser, shared
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
    from modules import devices, processing, images, sd_vae_approx
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
ModuleNotFoundError: No module named 'modules.textual_inversion.textual_inversion'

**Comment by o0DiSaSter0o** [comment]
I also clicked on installing several add-ons at some point, and it looks like they somehow conflicted

**Comment by o0DiSaSter0o** [comment]
I am also interested in the possibility of using Google drive as a place to store a neural network, and using the local colab server to use its power for calculations.Since I caught the limits of colab.But when I connect from a local server, notepad does not see google drive.I would be very grateful if you could tell me how to solve this problem.Will the Internet connection greatly affect the generation time?

**Comment by TheLastBen** [comment]
you can't use a shared folder, use the default folder` /content/gdrive/MyDrive/sd/stable-diffusion-webui`

**Comment by vaclav-kyle** [comment]
> you can't use a shared folder, use the default folder` /content/gdrive/MyDrive/sd/stable-diffusion-webui`

same issue in here. 
Same symptom even if the default folder is used. The same symptoms appear when connecting using ngroc, and the same symptoms appear when using a local tunnel.
Checking Use_Latest_Working_Commit, using ngroc, checking Use_Cloudflare_Tunnel: Failed
Checking Use_Latest_Working_Commit, using ngroc, unchecking Use_Cloudflare_Tunnel: Failed
Checking Use_Latest_Working_Commit, not using ngroc, checking Use_Cloudflare_Tunnel: Failed
Checking Use_Latest_Working_Commit, not using ngroc, checking Use_Cloudflare_Tunnel: Failed
Use_Latest_Working_Commit checked, ngroc not used, Use_Cloudflare_Tunnel unchecked: Failed
Use_Latest_Working_Commit unchecked, ngroc not used, Use_Cloudflare_Tunnel checked: Failed
Checking Use_Latest_Working_Commit, using ngroc, unchecking Use_Cloudflare_Tunnel: Failed
Unchecking Use_Latest_Working_Commit, using ngroc, unchecking Use_Cloudflare_Tunnel: Failed
Unchecking Use_Latest_Working_Commit, not using ngroc, unchecking Use_Cloudflare_Tunnel: Failed

Are there any other cases where I should try more?

**Comment by TheLastBen** [comment]
this is the issue `/content/gdrive/.shortcut-targets-by-id/15sLV1KrOBvYzBm3Hi5zZf5M8I60szdJ-/sdапв/stable-diffusion-webui`
the notebook is hardcoded to a specific path, you're using a different path for the main sd folder

**Comment by shuaijiuwanshil** [comment]
same problem
