### ISSUE TITLE
no errors, but does not start

### ISSUE THREAD

**Issue by wth153** [TheLastBen/fast-stable-diffusion#1944]
I don't know why it suddenly didn't start today. When I forced the cell to close, I found that the program was looking for a very long path

Traceback (most recent call last):
  File "/usr/lib/python3.9/glob.py", line 124, in _iterdir
    with os.scandir(dirname) as it:
NotADirectoryError: [Errno 20] Not a directory: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/content/gdrive/MyDrive/sd/stablediffusion/src/taming-transformers/taming/data/base.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 340, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 233, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 114, in initialize
    modules.sd_models.setup_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 91, in setup_model
    list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 115, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"])
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 43, in load_models
    for file in glob.iglob(place + '**/**', recursive=True):
  File "/usr/lib/python3.9/glob.py", line 75, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/usr/lib/python3.9/glob.py", line 113, in _glob2
    yield from _rlistdir(dirname, dironly)
  File "/usr/lib/python3.9/glob.py", line 145, in _rlistdir
    for y in _rlistdir(path, dironly):
  File "/usr/lib/python3.9/glob.py", line 145, in _rlistdir
    for y in _rlistdir(path, dironly):
  File "/usr/lib/python3.9/glob.py", line 145, in _rlistdir
    for y in _rlistdir(path, dironly):
  [Previous line repeated 114 more times]
  File "/usr/lib/python3.9/glob.py", line 140, in _rlistdir
    names = _listdir(dirname, dironly)
  File "/usr/lib/python3.9/glob.py", line 136, in _listdir
    return list(it)
  File "/usr/lib/python3.9/glob.py", line 124, in _iterdir
    with os.scandir(dirname) as it:
KeyboardInterrupt
^C

**Comment by Lucas-Chen-10** [comment]
the same problem, how to solve it..
