### ISSUE TITLE
Training Hypernetwork - RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by cosmiclantern** [TheLastBen/fast-stable-diffusion#1969]
Every time I run the trainer it stops after 0 steps:

"Training finished at 0 steps."
Embedding saved to ............

I've tried changing the hypernetwork settings, unchecking dropout, changing the structure, learning rate etc. but it's the same result. Attempting to train an embedding also results in the same.

The traceback:

Preparing dataset...
100% 108/108 [00:08<00:00, 12.46it/s]
  0% 0/120000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 655, in train_hypernetwork
    loss = shared.sd_model.forward(x, c)[0] / gradient_step
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 846, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 886, in p_losses
    model_output = self.apply_model(x_noisy, t, cond)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 768, in forward
    emb = self.time_embed(t_emb)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 305, in lora_Linear_forward
    lora_apply_weights(self)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 268, in lora_apply_weights
    self.weight.copy_(weights_backup)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Comment by TheLastBen** [comment]
I think that's an issue with A1111, probably will fix soon

**Comment by cosmiclantern** [comment]
Thanks for your reply. I got it to work by starting the notebook in a high ram/premium GPU environment, as opposed to the T4 with the standard ram option. I dunno if that helps.

**Comment by hazmatai7** [comment]
> Thanks for your reply. I got it to work by starting the notebook in a high ram/premium GPU environment, as opposed to the T4 with the standard ram option. I dunno if that helps.

what do you mean? i have the same issue with an old 1080 8gb
