### ISSUE TITLE
ImportError: cannot import name 'ModuleAvailableCache' from 'lightning_utilities.core.imports' (/usr/local/lib/python3.9/dist-packages/lightning_utilities/core/imports.py)

### ISSUE THREAD

**Issue by BLABZ** [TheLastBen/fast-stable-diffusion#1973]
Just as the Title states, apparently I'm dealing with an 'InputError' of some kind here. This is just the newest in the long series of issues I've been encountering. 
Here's the full code it gives:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 21, in <module>
    import pytorch_lightning # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/core/__init__.py", line 15, in <module>
    from pytorch_lightning.core.datamodule import LightningDataModule
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/core/datamodule.py", line 21, in <module>
    from pytorch_lightning.core.mixins import HyperparametersMixin
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/core/mixins/__init__.py", line 16, in <module>
    from pytorch_lightning.core.mixins.hparams_mixin import HyperparametersMixin  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/core/mixins/hparams_mixin.py", line 20, in <module>
    from pytorch_lightning.core.saving import ALLOWED_CONFIG_TYPES, PRIMITIVE_TYPES
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/core/saving.py", line 34, in <module>
    from pytorch_lightning.utilities.migration import pl_legacy_patch
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/migration/__init__.py", line 15, in <module>
    from pytorch_lightning.utilities.migration.utils import migrate_checkpoint  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/migration/utils.py", line 23, in <module>
    from lightning_fabric.utilities.imports import _IS_WINDOWS
  File "/usr/local/lib/python3.9/dist-packages/lightning_fabric/__init__.py", line 23, in <module>
    from lightning_fabric.fabric import Fabric  # noqa: E402
  File "/usr/local/lib/python3.9/dist-packages/lightning_fabric/fabric.py", line 32, in <module>
    from lightning_fabric.plugins import Precision  # avoid circular imports: # isort: split
  File "/usr/local/lib/python3.9/dist-packages/lightning_fabric/plugins/__init__.py", line 14, in <module>
    from lightning_fabric.plugins.environments.cluster_environment import ClusterEnvironment
  File "/usr/local/lib/python3.9/dist-packages/lightning_fabric/plugins/environments/__init__.py", line 20, in <module>
    from lightning_fabric.plugins.environments.xla import XLAEnvironment  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/lightning_fabric/plugins/environments/xla.py", line 18, in <module>
    from lightning_fabric.accelerators.tpu import _XLA_AVAILABLE, TPUAccelerator
  File "/usr/local/lib/python3.9/dist-packages/lightning_fabric/accelerators/__init__.py", line 18, in <module>
    from lightning_fabric.accelerators.tpu import TPUAccelerator  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/lightning_fabric/accelerators/tpu.py", line 21, in <module>
    from lightning_utilities.core.imports import ModuleAvailableCache
ImportError: cannot import name 'ModuleAvailableCache' from 'lightning_utilities.core.imports' (/usr/local/lib/python3.9/dist-packages/lightning_utilities/core/imports.py)

I was hoping someone may know of a fix for this!

**Comment by TheLastBen** [comment]
how to reproduce the error ?

**Comment by BLABZ** [comment]
Oh? Okay I'll not mess with that bit of the code then or just remove it entirely perhaps..... I think I had to use that though to fix something that wasn't working after I installed one new model from CivitAI. Without that bit, Stable Diffusion just wouldn't start for an entirely other reason. .. The  

As for the folders, I'll try that, but I never wanted to mess much with adding folders because Stable Diffusion wouldn't work after I moved or touched anything directly in the files for some reason..... That's why I was using the 'Load Element From Web' Script I got from the discord mod... I was also not too sure that The notebook would be able to read/register that the LoRA models were separated into different folders. 

I'll try both options though and get back to you here when I can!

**Comment by BLABZ** [comment]
UPDATE: I DID in fact get it to work btw! I apparently just have to restart the runtime once or twice on the notebook each time I get onto it! ..As for the LoRAs you mentioned.. I haven't yet started putting them in different folders and stuff, but That would essentially work?.. Like while running stable diffusion I would be able to read that they are there even when organized into additional folders? I've encountered minor issues like that before with other similar programs and all. xD

**Comment by TheLastBen** [comment]
why do you have to restart the runtime ?
