### ISSUE TITLE
can not load model

### ISSUE THREAD

**Issue by BlenderProxy** [TheLastBen/fast-stable-diffusion#1982]
Hi, I get this message after loading a model and the ui is frozen because of the high mem usage, (why am I getting this error?):

Traceback (most recent call last):
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\modules\ui.py", line 385, in update_token_counter
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\modules\ui.py", line 385, in <listcomp>
    token_count, max_length = max([model_hijack.get_prompt_lengths(prompt) for prompt in prompts], key=lambda args: args[0])
  File "D:\STABLE-DIFFUSION\stable-diffusion-webui\modules\sd_hijack.py", line 154, in get_prompt_lengths
    _, token_count = self.clip.process_texts([text])
AttributeError: 'NoneType' object has no attribute 'process_texts'

Machine				Custom Computer
	
        Operating System		Microsoft Windows 11 Pro (64-bit) 
	Memory				32 GB
	Processor			Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	Motherboard			ASRock - Z370 Extreme4
	Video Cards			NVIDIA GeForce RTX 3080   
	Hard Disk 1			ST2000DM006-2DM164 (2.0 TB)
	Hard Disk 2			Samsung SSD 960 EVO 250GB (250.0 GB)
	Network Card			Intel(R) Ethernet Connection (2) I219-V

Python 3.10.7 / SD is up-to-date

**Comment by TheLastBen** [comment]
this repo is for the notebooks only not local, I'm not sure how to fix your issue, I'm not familiar with such error
