### ISSUE TITLE
Certain Plugins break the next time I run the notebook

### ISSUE THREAD

**Issue by kieranxsomer** [TheLastBen/fast-stable-diffusion#1991]
ModuleNotFoundError: No module named 'socketio'
This is for CivitAI extension:

Civitai: API loaded
Error loading script: link.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/scripts/link.py", line 3, in <module>
    import civitai.link as link
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/civitai/link.py", line 4, in <module>
    import socketio
ModuleNotFoundError: No module named 'socketio'

Error loading script: settings.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/scripts/settings.py", line 1, in <module>
    from civitai.link import on_civitai_link_key_changed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_civitai_extension/civitai/link.py", line 4, in <module>
    import socketio
ModuleNotFoundError: No module named 'socketio'

It still loads and hashes but it wont show up on the WebUi, i've had this countless times when i've used this notebook and other notebooks that save settings and SD to the drive.

**Comment by TheLastBen** [comment]
I'll add socketio to the preinstalled dependencies
