### ISSUE TITLE
Issue with AUTOMATIC1111 SD web ui

### ISSUE THREAD

**Issue by ExaltedKuro** [TheLastBen/fast-stable-diffusion#2007]
I'm currently having this issue with the AUTOMATIC1111 Stable diffusion web UI.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

any solutions?

**Comment by PureImprov** [comment]
Try checking 'Use_Latest_Working_Commit' under 'Install/Update AUTOMATIC1111 repo and re-run that cell, worked for me.

**Comment by ExaltedKuro** [comment]
> Try checking 'Use_Latest_Working_Commit' under 'Install/Update AUTOMATIC1111 repo and re-run that cell, worked for me.

I got a little further than before but still got an error message.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 468, in create_ui
    extra_networks_ui = ui_extra_networks.create_ui(extra_networks, extra_networks_button, 'txt2img')
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks.py", line 218, in create_ui
    page_elem = gr.HTML(page.create_html(ui.tabname))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks.py", line 95, in create_html
    items_html += self.create_html_for_item(item, tabname)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks.py", line 146, in create_html_for_item
    return self.card_page.format(**args)
KeyError: 'style'

**Comment by TheLastBen** [comment]
try a fresh sd folder

**Comment by ExaltedKuro** [comment]
> try a fresh sd folder and use the latest notebook 

Can I get a link to the latest notebook.

**Comment by TheLastBen** [comment]
yes you can simply remove the sd folder, the link to the notebook, you can get it by clicking on the thumbnails on the main page of this repo

**Comment by ExaltedKuro** [comment]
> yes you can simply remove the sd folder, the link to the notebook, you can get it by clicking on the thumbnails on the main page of this repo 

That all seemed to work I can use SD with no problems (for now). I'll make sure to update my SD folder regularly. Thank you.
