### ISSUE TITLE
Having a "bad LoRA name layer" issue.

### ISSUE THREAD

**Issue by ahsenai** [TheLastBen/fast-stable-diffusion#2033]
Hey. So when I try to generate an image with <lora:asianGirlLohaRiriz_v10:1> I get this issue:

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001A87223C8E0>, <modules.extra_networks.ExtraNetworkParams object at 0x000001A87223C2E0>]: AssertionError
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "C:\AI\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "C:\AI\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "C:\AI\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 185, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_te_text_model_encoder_layers_0_mlp_fc1.hada_w1_a - must end in lora_up.weight, lora_down.weight or alpha

How can I fix that? 
Also, suddenly I started to have broken results with the other LoRAs. 
Helps are appreciated. Thank you.

**Comment by TheLastBen** [comment]
use this extension for lora https://github.com/kohya-ss/sd-webui-additional-networks, it's got better handling of all types

**Comment by Taikakim** [comment]
I installed that extension, but still with a  LoHa which is trained on 768px and the default values and proposed network dimensions, over base SD1.5 model, I'm getting this in the Web UI:

LoRas, at least those trained 512px, work fine. So it's something with the LoHa? The training was done with the Dreambooth method, Kohya's trainer.

```
loading Lora /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/porcelain3-768-loha.ckpt: AssertionError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 215, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 185, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_te_text_model_encoder_layers_0_self_attn_k_proj.hada_w1_a - must end in lora_up.weight, lora_down.weight or alpha
```

**Comment by aso00000** [comment]
> https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris redo with this

i did the steps but the lycoris's extra network won't show.
i installed it then restarted the webui (closed it then opened it again and refreshed stable diffusion) is this how to refresh it or am i doing something wrong?

**Comment by jonk999** [comment]
I had a similar issue with a couple of Lycoris files I downloaded from Civitai. I had just been placing them in the Lora folder and never noticed any messages in the log window.
The ones that gave me a similar error I moved to the Lycoris folder and the message now no longer appears in the log window. I don't know why others work fine in that folder and these particular ones didn't.
