### ISSUE TITLE
The file may be malicious, so the program is not going to read it. You can skip this check with --disable-safe-unpickle commandline argument.

### ISSUE THREAD

**Issue by Tongol123** [TheLastBen/fast-stable-diffusion#2039]
Hello, im following a youtube tutorial on how to train your own models and create your own ckpt file, training and creating the ckpt file was a success until i tried to run my ckpt file in automatic1111 it gives me this error , please help                                                                    
 
Error verifying pickled file from E:\Users\User\Documents\stableDiffusion\models\Stable-diffusion\anelfgf.ckpt:
Traceback (most recent call last):
  File "E:\Users\User\Documents\stableDiffusion\modules\safe.py", line 97, in load
    check_pt(filename)
  File "E:\Users\User\Documents\stableDiffusion\modules\safe.py", line 77, in check_pt
    check_zip_filenames(filename, z.namelist())
  File "E:\Users\User\Documents\stableDiffusion\modules\safe.py", line 69, in check_zip_filenames
    raise Exception(f"bad file inside {filename}: {name}")
Exception: bad file inside E:\Users\User\Documents\stableDiffusion\models\Stable-diffusion\anelfgf.ckpt: anelfgf/data.pkl

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Traceback (most recent call last):
  File "E:\Users\User\Documents\stableDiffusion\venv\lib\site-packages\gradio\routes.py", line 283, in run_predict
    output = await app.blocks.process_api(
  File "E:\Users\User\Documents\stableDiffusion\venv\lib\site-packages\gradio\blocks.py", line 936, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "E:\Users\User\Documents\stableDiffusion\venv\lib\site-packages\gradio\blocks.py", line 777, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Users\User\Documents\stableDiffusion\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Users\User\Documents\stableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Users\User\Documents\stableDiffusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Users\User\Documents\stableDiffusion\modules\ui.py", line 1644, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "E:\Users\User\Documents\stableDiffusion\modules\ui.py", line 1485, in run_settings_single
    opts.data_labels[key].onchange()
  File "E:\Users\User\Documents\stableDiffusion\webui.py", line 42, in f
    res = func(*args, **kwargs)
  File "E:\Users\User\Documents\stableDiffusion\webui.py", line 83, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "E:\Users\User\Documents\stableDiffusion\modules\sd_models.py", line 288, in reload_model_weights
    load_model_weights(sd_model, checkpoint_info)
  File "E:\Users\User\Documents\stableDiffusion\modules\sd_models.py", line 174, in load_model_weights
    if "global_step" in pl_sd:
TypeError: argument of type 'NoneType' is not iterable

**Comment by TheLastBen** [comment]
this repo is for the notebooks, not local installation
