### ISSUE TITLE
Training on latest 1.5 VAE seems to overfit compared to 1.4

### ISSUE THREAD

**Issue by alejobrainz** [TheLastBen/fast-stable-diffusion#204]
Hi.  I updated the notebook to the latest changes which include using the 1.5 model and the VAE usage improvements, but when I trained a model (tried 1500 and 3000 steps), the resulting inferences tend to overfit to the supplied photos. 

Character trained on 1.4, 3000 steps, 20 source pictures
![grid-0004-1025863238-A mid angle camera shot of a ca-whisperer as a Rockstar, based on KISS, with beard, horns, wings, tail, anime 3 D realistic shad](https://user-images.githubusercontent.com/6945663/197352425-266f5d31-6996-4f04-9234-757ef1251969.jpeg)

Character trained on 1.5 latest notebook, 3000, 20 same source pictures, same training seed and same 200 pics training data
![grid-0002-2790290571-A mid angle camera shot of a ca-whisperer as a Rockstar, based on KISS, with beard, horns, wings, tail, anime 3 D realistic shad](https://user-images.githubusercontent.com/6945663/197352452-5fec2db0-74e0-46af-bc82-b7e59754edd8.jpeg)

The resulting images have the same cameras and look as the photos supplied, overfitting them.  I tried the same prompt with a person (my son)

Person trained on 1.4, 3000 steps, 20 source pictures
![grid-0009-1406060766-A mid angle camera shot of SebastianG2022 as a rockstar from KISS, anime 3 D realistic shaded; by makoto shinkai and jeremy lipk](https://user-images.githubusercontent.com/6945663/197352498-a0410355-fdee-4551-aae9-cff457bd5e37.jpeg)

Same Person trained on 1.5, 3000 steps, 20 same source pictures, same training seed and same 200 pics training data
![grid-0010-1394774983-A mid angle camera shot of SebastianG2022 as a rockstar from KISS, anime 3 D realistic shaded; by makoto shinkai and jeremy lipk](https://user-images.githubusercontent.com/6945663/197352503-d2e929c4-66a8-4150-94a6-541ad3455d62.jpeg)

I have not been able to not overfit them.  I tried training on 1500 steps too.  Any ideas?

**Comment by TheLastBen** [comment]
Thanks for the detailed explanation, I will work on that immediately

**Comment by alejobrainz** [comment]
BTW, Your notebook is absolutely Excellent.  A small tip would be to allow you to specify an path to save the rendered class pictures, so we can store them on the drive and save them for future trainings.  I've resorted to creating an additional step to copy them, but might be useful for others:

`%cp -r "/content/data/$SUBJECT_TYPE" "/content/gdrive/MyDrive/sd/data"`

**Comment by TheLastBen** [comment]
Thanks, I will add that option as a checkbox

**Comment by TheLastBen** [comment]
Did you check your class images, it seems like the script didn't take in consideration the class pictures.

I tried it and it works well, 1500 steps, 28 instance and 200 class : 

studio portrait of **emlclrkc**, natural colors, beautiful, attractive, natural skin, [[[freckles]]], [[skin pores]], realistic lighting, shot on nikon canon hasselblad, medium shot

![download (5)](https://user-images.githubusercontent.com/110583491/197358897-30f35510-6ae7-4914-a7dd-69042264b3a0.png)

same seed with the default model : 

studio portrait of **emilia clarke**, natural colors, beautiful, attractive, natural skin, [[[freckles]]], [[skin pores]], realistic lighting, shot on nikon canon hasselblad, medium shot

![download (4)](https://user-images.githubusercontent.com/110583491/197358915-a3e55e93-fe24-4bb0-ab2a-a184fee9507e.png)

**Comment by alejobrainz** [comment]
Interesting.  Giving it another go including class image creation.

**Comment by TheLastBen** [comment]
Option to save class_images to gdrive added https://github.com/TheLastBen/fast-stable-diffusion/commit/c1e97d3550e5ad49e67a3935eb72f339be92ae6b

**Comment by Krolitian** [comment]
Also having an issue with v1.5. My v1.4 model worked perfectly with any style I applied to it, but the v1.5 model that's being created by this Colab no longer gives results beyond just my photorealistic face. I mean to be fair, it did a REALLY good job at replicating my face compared to v1.4, but now can ONLY do that. Can't apply any styles like "cartoon" in the prompt, always just returns me as a real-life picture. Even not putting myself in the prompt gives characters that share my features, and putting in animals results in it putting the animal's head on my body.

Some were thinking I overtrained it at 2k steps, but not only is it what I used for v1.4, but at 1k steps it's definitely undertrained. Not sure what changed to the Colab in the last couple days, but it seems to be causing all my attempts to just completely overwrite the .ckpt with just the training data.

**Comment by TheLastBen** [comment]
@Krolitian 
 How many steps do you use at inference ? if you keep them blew 50, the style will apply, give it a try, it might by the learning rate changed to 2e-6.

**Comment by Kenrithh** [comment]
> Also having an issue with v1.5. My v1.4 model worked perfectly with any style I applied to it, but the v1.5 model that's being created by this Colab no longer gives results beyond just my photorealistic face. I mean to be fair, it did a REALLY good job at replicating my face compared to v1.4, but now can ONLY do that. Can't apply any styles like "cartoon" in the prompt, always just returns me as a real-life picture. Even not putting myself in the prompt gives characters that share my features, and putting in animals results in it putting the animal's head on my body.
> 
> Some were thinking I overtrained it at 2k steps, but not only is it what I used for v1.4, but at 1k steps it's definitely undertrained. Not sure what changed to the Colab in the last couple days, but it seems to be causing all my attempts to just completely overwrite the .ckpt with just the training data.

Apologies beforehand, English isn't my first language. 

I'm having the same problem. I've tried multiple subjects, going through my instance images and getting rid of any that aren't good, generating my own class images, training on different seeds, training on 1000, 1250, 1500 and 3000 steps, and no matter what I do, I get photorealistic interpretations of the subject. I can't apply styles or modify the subject in any meaningful way that doesn't look almost exactly to the training data. If I write in a prompt that does not have anything to do with the subject I trained, it'll generate images, so I know the cptk file isn't _just_ the trained subject, I just can't make the trained subject with the rest of the model interact, if that makes sense.

**Comment by Krolitian** [comment]
> @Krolitian How many steps do you use at inference ? if you keep them blew 50, the style will apply, give it a try, it might by the learning rate changed to 2e-6.

Tried steps from 20 to 150, all same result. Even doing stuff like (((((art by Greg Rutkowski))))) just keeps the photorealism until I add too many ()'s to the point it corrupts. And I tried changing it to 1e-6 as someone suggested and that didn't solve the issue either.



> > Also having an issue with v1.5. My v1.4 model worked perfectly with any style I applied to it, but the v1.5 model that's being created by this Colab no longer gives results beyond just my photorealistic face. I mean to be fair, it did a REALLY good job at replicating my face compared to v1.4, but now can ONLY do that. Can't apply any styles like "cartoon" in the prompt, always just returns me as a real-life picture. Even not putting myself in the prompt gives characters that share my features, and putting in animals results in it putting the animal's head on my body.
> > Some were thinking I overtrained it at 2k steps, but not only is it what I used for v1.4, but at 1k steps it's definitely undertrained. Not sure what changed to the Colab in the last couple days, but it seems to be causing all my attempts to just completely overwrite the .ckpt with just the training data.
> 
> Apologies beforehand, English isn't my first language.
> 
> I'm having the same problem. I've tried multiple subjects, going through my instance images and getting rid of any that aren't good, generating my own class images, training on different seeds, training on 1000, 1250, 1500 and 3000 steps, and no matter what I do, I get photorealistic interpretations of the subject. I can't apply styles or modify the subject in any meaningful way that doesn't look almost exactly to the training data. If I write in a prompt that does not have anything to do with the subject I trained, it'll generate images, so I know the cptk file isn't _just_ the trained subject, I just can't make the trained subject with the rest of the model interact, if that makes sense.

Yup, exactly my experience. Just looks like my training data, but it's not. Anything I try to change to it, even without the dreambooth token or class in it still gives a result 90% or more what the token is.

**Comment by TheLastBen** [comment]
In the prompt don't add the class_name (person, guy, woman ...),  use only the instance name (unique identifier).

I trained it on 28 instance and autogenerated 200, I couldn't reproduce the problem:

![download (1)](https://user-images.githubusercontent.com/110583491/197380646-13049a42-801e-464d-9b99-f8ec758d39b5.png)
![download (2)](https://user-images.githubusercontent.com/110583491/197380651-a2dc1181-0676-492d-9cfc-e427c18e297f.png)
![download (3)](https://user-images.githubusercontent.com/110583491/197380653-123d6039-a9e2-466d-8148-5c402361c974.png)
![download (6)](https://user-images.githubusercontent.com/110583491/197380657-c31aede6-8ba5-45ad-bc3f-d17597fdc317.png)
![download (7)](https://user-images.githubusercontent.com/110583491/197380661-4f551a7f-b7da-42ba-9a00-90a03b247e72.png)
![download](https://user-images.githubusercontent.com/110583491/197380663-bf83c242-c4c9-4bb2-b302-9ee59b25eca2.png)
![eml](https://user-images.githubusercontent.com/110583491/197380665-dbc02b15-3fa0-4e53-b221-a59d2dd3b49f.png)

**Comment by Kenrithh** [comment]
> In the prompt don't add the class_name (person, guy, woman ...), use only the instance name (unique identifier). make sure you're using the latest colab notebook
> 
> I trained it on 28 instance and autogenerated 200, I couldn't reproduce the problem:
> 
> ![download (1)](https://user-images.githubusercontent.com/110583491/197380646-13049a42-801e-464d-9b99-f8ec758d39b5.png) ![download (2)](https://user-images.githubusercontent.com/110583491/197380651-a2dc1181-0676-492d-9cfc-e427c18e297f.png) ![download (3)](https://user-images.githubusercontent.com/110583491/197380653-123d6039-a9e2-466d-8148-5c402361c974.png) ![download (6)](https://user-images.githubusercontent.com/110583491/197380657-c31aede6-8ba5-45ad-bc3f-d17597fdc317.png) ![download (7)](https://user-images.githubusercontent.com/110583491/197380661-4f551a7f-b7da-42ba-9a00-90a03b247e72.png) ![download](https://user-images.githubusercontent.com/110583491/197380663-bf83c242-c4c9-4bb2-b302-9ee59b25eca2.png) ![eml](https://user-images.githubusercontent.com/110583491/197380665-dbc02b15-3fa0-4e53-b221-a59d2dd3b49f.png)

I understand, just wanted to update I tried making a new install of the Automatic111 webui and generated a new cptk with 35 instance, letting the colab generate the class images and leaving the number of subject images to 200 but I still have the same issues. I also generated 500 class images and tried generating a model with that but no dice, same issue. I don't know what else to try.

**Comment by giteeeeee** [comment]
> 

Just a side question about learning rate. Is it a setting that you suppose to manually adjust like in textual inversion training? Or has it already been set up in dreambooth/colab and requires no attention?

**Comment by TheLastBen** [comment]
@giteeeeee there were experiments with various learning rates, and so far the 2e-6 appears to be the most balanced

**Comment by r8200** [comment]
I confirm the presence of the problem described above. I did a new training on old photos from which I was already preparing a model. And the result completely erases all styles and stylizations. Checked on today's colab and yes the problem is still there. It is worth adding a word to the prompt, as all styles go away.

I taught the model for 100 subject photos, 500 additional selected photos and 2000 steps, tried with a different number of steps but the result is the same.

A simple promt with styling:
Dreambooth man portrait, slightly smiling, disney, pixar, render, renderman, vray, cellsshading, cinematic lights
![grid-1525](https://user-images.githubusercontent.com/62480609/197405106-737dd286-1ad3-49a6-a8d4-f5d5c4583f7f.png)

Promt without keyword same model same seed:
man portrait, slightly smiling, disney, pixar, render, renderman, vray, cellsshading, cinematic lights
![grid-1526](https://user-images.githubusercontent.com/62480609/197405354-7ac3d06a-8269-422b-8afb-0cab30a0dad2.png)

The old model trained on October 15 does not have this problem. Trained on the same photos
![grid-1529](https://user-images.githubusercontent.com/62480609/197405528-65f3f842-862c-4748-bcce-f0e3747bc947.png)

**Comment by TheLastBen** [comment]
@r8200 
in the cell "Start Dreambooth", change the setting "--gradient_accumulation_steps=1 --gradient_checkpointing \" to

--gradient_accumulation_steps=2 --gradient_checkpointing \

and try the same training (it will be slower)

**Comment by r8200** [comment]
> @r8200 in the cell "Start Dreambooth", change the setting "--gradient_accumulation_steps=1 --gradient_checkpointing " to
> 
> --gradient_accumulation_steps=2 --gradient_checkpointing \
> 
> and try the same training (it will be slower)

the result is the same except for the time =(

here are some more examples that show the difference

Model : Trained 2000 step, 100/500 photos, v1.5
Promt: **Dreambooth** epic portrait, 42 years old, by Alex Grey and Lebbeus Woods, psychodelic dream, dispertion colors, vibration
![grid-1581](https://user-images.githubusercontent.com/62480609/197415380-c203e92e-c5eb-49e3-a543-25f25fa4caf7.png)

Model : Trained 2000 step, 100/500 photos, v1.5
Promt: **Man** epic portrait, 42 years old, by Alex Grey and Lebbeus Woods, psychodelic dream, dispertion colors, vibration
![grid-1583](https://user-images.githubusercontent.com/62480609/197415422-01afb5ba-170e-47f7-a1f1-2fee29adf040.png)

Model : No Trained, v1.5
Promt: **Man** epic portrait, 42 years old, by Alex Grey and Lebbeus Woods, psychodelic dream, dispertion colors, vibration
![grid-1584](https://user-images.githubusercontent.com/62480609/197415469-26e064dc-700b-4135-89c2-a911ebda5f59.png)

Model : Trained 3000 step, 100/500 photos, v1.4 - 15 Oct
Promt: **Dreambooth** epic portrait, 42 years old, by Alex Grey and Lebbeus Woods, psychodelic dream, dispertion colors, vibration
![grid-1587](https://user-images.githubusercontent.com/62480609/197415493-504cccfe-f60f-4f43-8fc1-52c54f142ca5.png)

Model : Trained 3000 step, 100/500 photos, v1.4 - 15 Oct
Promt: **Man** epic portrait, 42 years old, by Alex Grey and Lebbeus Woods, psychodelic dream, dispertion colors, vibration
![grid-1588](https://user-images.githubusercontent.com/62480609/197415519-68bd528e-3e4e-44b1-940a-5a549fa8f54e.png)

**Comment by TheLastBen** [comment]
try 30 instance images, and 200 autogenerated class images at 1500 steps, make sure the instance images are 1:1

**Comment by r8200** [comment]
I do not use this word, I just entered it so that it would be clear where it should be in the description. The SUBJECT_TYPE I use is "man". I'll try tomorrow with fewer images, but in the old build everything worked with the same content

**Comment by TheLastBen** [comment]
I strongly believe that the cause of this issue is overtraining, either with the steps or class/instance images, try also using a multi-word subject_type

emlclrkc epic portrait, 42 years old, by Alex Grey and Lebbeus Woods, psychodelic dream, dispertion colors, vibration

![download (5)](https://user-images.githubusercontent.com/110583491/197416932-67f55938-a29c-47ce-adab-40c5ec9e07d5.png)

**Comment by r8200** [comment]
Tried with recommended settings, 100 shots, 200 CLASS photo, 2000 steps, fp16 - the result is exactly the same.
the second attempt 20 shots 200 CLASS photo, 2000 steps, fp16 - it got a little bit better, but very far from what it used to be.

Test with last model
promt with key word
![grid-1629](https://user-images.githubusercontent.com/62480609/197423543-cf0513d7-c83b-4d9a-8287-0a3f9c998894.png)

promt without
![grid-1630](https://user-images.githubusercontent.com/62480609/197423545-dc338fe4-4303-4ea3-b364-da22513be3f7.png)

In my opinion, the problem now is not in the accuracy of recognition, but in how the weights are redistributed to the model file. Their influence on the model is now redundant.

**Comment by TheLastBen** [comment]
it's the new option text encoder training that might've changed things, but the results are actually better, keep the steps as low as 1500 and then play with the positive-negative prompts

**Comment by Krolitian** [comment]
I think I figured out my issue with my latest run on the Shivam colab. Cut my training images from 14 to 8 and it worked perfectly now. (the same issue happened on his colab with 14 images too so not your fault, seems to be an issue with v1.5 and a high amount of training images.) Gonna try again on your colab once Google removes my GPU limit.

**Comment by Krolitian** [comment]
Turns out I was wrong. Doing exactly what I did on Shivam's colab to yours still results in images that only show photorealistic depictions of me with no ability to change with a prompt. Seems something is still existing in the Fast colab that's causing this.

**Comment by TheLastBen** [comment]
I will train more models an see if I can reproduce the issue

**Comment by TheLastBen** [comment]
I tried the leaning rate 1e-6, I'm getting great results, it is imperative to cap the training steps below 1600, the new text encoder method improves greatly the training and there is no need to go too much over 1600 steps, especially for a single person/object, the secret is to not over-train.

I trained a model on 2 persons at the same time with 400 good quality class images (200 for each gender) and 30 instance images for each person, 1600 steps 1e-6 lr : 

![download (1)](https://user-images.githubusercontent.com/110583491/197549872-3c2a55a6-2368-42aa-9d25-044c4c6e638e.png)
![download (2)](https://user-images.githubusercontent.com/110583491/197549906-bcd855ed-abb5-4eda-a664-06913a0e2f8a.png)
![download (3)](https://user-images.githubusercontent.com/110583491/197549929-90a7b797-6e39-465d-bce2-e68ae3534cdc.png)
![download (4)](https://user-images.githubusercontent.com/110583491/197549955-4094a3d8-6bde-4975-8572-8d325dc80400.png)
![download](https://user-images.githubusercontent.com/110583491/197549983-b51af427-01b0-481d-8228-293bac8bd31b.png)
![download (6)](https://user-images.githubusercontent.com/110583491/197555739-de04d8d1-f7be-40a5-975d-c7ddd26006a4.png)
![download (7)](https://user-images.githubusercontent.com/110583491/197555777-f800de14-f6fe-475b-adf5-a3aa3363dbe6.png)

**Comment by mauzus** [comment]
Yeah, I had the same results as others, but once I stopped using the same huge amount of pictures and steps I used to use before, now everything works great, even much better than before.

Used to need 5000 steps and 50 pictures for decent results before, now just 10 pictures and 1500 steps and everything is even much better. 👍

**Comment by TheLastBen** [comment]
it's because of the feature "--train_text_encoder", it gives much better results with much less effort, but susceptible to overtraining and overfitting because of the old method habit.

**Comment by r8200** [comment]
I tried the latest version on default settings, 18 photos for training.

According to the results, there are slight improvements on the return of the style transfer. But unfortunately part of the "style" now looks like a glitch, perhaps this is due to an increase in the accuracy of 1e-6. You can also add to the problems that a very large number of photos turn out to be black and white, or with almost no colors.

Examples, note the chaotic lines in the trained model, they are present on different requests and are not related to the style.

Trained model, keyword query
![grid-1680](https://user-images.githubusercontent.com/62480609/197595397-ce760861-4fee-4ff9-8bcd-f1da4e419d0b.png)

Trained model, query without keyword
![grid-1694](https://user-images.githubusercontent.com/62480609/197595487-890502e1-090e-48f8-a99e-26ca67c0d6de.png)

Not trained model, query without keyword
![grid-1679](https://user-images.githubusercontent.com/62480609/197595515-70ae67f6-8d5f-4b28-8675-3afce1abe673.png)

Another one
Trained model, keyword query
![grid-1686](https://user-images.githubusercontent.com/62480609/197596649-d794d283-278f-4587-ac35-4aec10434c03.png)

Trained model, query without keyword
![grid-1687](https://user-images.githubusercontent.com/62480609/197596687-9de3df75-5742-456f-b620-086facae41e7.png)

All these new improvements are certainly interesting, but without a normal style transfer, they are not essential.

Is it possible to use the old version somehow? What does that require?

**Comment by mauzus** [comment]
Chaotic lines and unsaturated colors are exactly some of the same issues I had when I was overtraining with the new method.

Maybe try using just 10 photos for training and 200 for your class, and then start tweaking from there...

If you still want to go back to the old method, just remove --train_text_encoder and change --learning_rate to 5e-6 in the Start DreamBooth cell. I think that should give you the same old results...

**Comment by r8200** [comment]
In my experience, retraining looks different. It is also worth bearing in mind that the training was performed on the default settings (recommended settings). Again, how then to raise the quality, if there is already too much?

And speaking of the old version, it's not about train_text_encoder and sampling accuracy, the problem is complex and did not appear yesterday with the latest improvements. A good solution was at the time of October 15, at which time I have several well-trained models that are free from the problems that we are discussing.

Overtrained examples
![model](https://user-images.githubusercontent.com/62480609/197603224-896066bb-344f-4532-afcc-d7690b5557da.png)

**Comment by r8200** [comment]
> it's the new option text encoder training that might've changed things, but the results are actually better, keep the steps as low as 1500 and then play with the positive-negative prompts

Experimenting with keyword weights does not give the desired effect. At zero weight, similarity goes away, but style does not return. Strengthening other words does not give enough effect, rather causes glitches and chaos.
Negative descriptions lead the result somewhere to the side, again not affecting the return of the desired style.

**Comment by mauzus** [comment]
> Overtrained examples ![model](https://user-images.githubusercontent.com/62480609/197603224-896066bb-344f-4532-afcc-d7690b5557da.png)

Yes, I know very well about those issues of overtrained models, but yesterday I only had the other issues you mentioned, because I was training with too many images and/or too many steps.

Once I started training with just 10 pictures and 1500 steps, everything went back to normal, with much better results than I ever had before.

**Comment by r8200** [comment]
I tested the model on a small number of photos. 10/200 photo 1500 steps 1e-6. The problem has not gone anywhere, the character recognition has fallen, all the artifacts remain, the styles still disappear. I would like to finally be heard, it's not about the samples and their number, it's not overtraining, it's more like overweight. Because what is happening has nothing to do with the number of samples and the problem is not in the new 1.5 model, the problem appeared earlier.

You can do a simple test with your model.
Promt: <dreambooth> epic portrait, by Alex Gray and Lebbeus Woods, psychodelic dream, dispertion colors, vibration
CFG Scale 15

And that's the kind of result you should expect.
Model 1.5 without training
![grid-1709](https://user-images.githubusercontent.com/62480609/197627318-832fa387-5c1a-49fa-a09e-8028d8c0558e.png)

What happened on the old colab model dated 15 Oct
Model 1.4 training, 100/300 photos 6000 steps, accuracy 5e-7
![grid-1711](https://user-images.githubusercontent.com/62480609/197627370-aa8d2469-2f39-4790-b7c9-29a7d80281f3.png)

What happens at the current colab model dated 24 Oct
Model 1.5 training, 10/200 photos 1500 steps, accuracy 1e-6 (there are more examples with more samples and photos in the discussion above)
![grid-1705](https://user-images.githubusercontent.com/62480609/197627512-c9087b3e-63be-41d4-b56a-e6c3482da4d7.png)

**Comment by GuruVirus** [comment]
Thanks for everyone's insight. I thought I was going crazy with my new 1.5 training and mediocre to poor results.

What I think is happening is the training is putting a much higher vector token value on the trained model with 1.5 so using your invoke string has a high default weight. Try adding a ton of weight to your other prompt elements and reducing weight of the primary model. There's a fine balance before it will mesh for me.

When I was doing facial merging, what worked the best for me was this prompt: [myToken:faceToMerge:0.75].

**Comment by TheLastBen** [comment]
@r8200 
I'll experiment more with the learning rate, if it makes a big difference, I will simply add a dropdown menu to choose different learning rates

**Comment by giteeeeee** [comment]
@TheLastBen

Just a quick question on when has the "--train_text_encoder" been added to this colab notebook? Because I checked on a copy of the notebook (sd1.4) from three days ago, the "--train_text_encoder" is still in the code. But you guys have been saying that it's newly added in 1.5 so I'm a bit confused.

**Comment by TheLastBen** [comment]
it was added a day before 1.5 was released, there is also the vae which was added after

**Comment by giteeeeee** [comment]
> it was added a day before 1.5 was released, there is also the vae which was added after

Then is there also a way to disable the vae just to experiment?

**Comment by giteeeeee** [comment]
> it was added a day before 1.5 was released, there is also the vae which was added after

@TheLastBen Then is there also a way to disable the vae?

**Comment by TheLastBen** [comment]
@giteeeeee 
create a new cell and use this code to download the model without the vae:

```
import os
from IPython.display import clear_output

Huggingface_Token = "" #@param {type:"string"}
token=Huggingface_Token

if token !="":
  if os.path.exists('/content/stable-diffusion-v1-5'):
    !rm -r /content/stable-diffusion-v1-5   
  clear_output()
  %cd /content/
  clear_output()
  !mkdir /content/stable-diffusion-v1-5
  %cd /content/stable-diffusion-v1-5
  !git init
  !git lfs install --system --skip-repo
  !git remote add -f origin  "https://USER:{token}@huggingface.co/runwayml/stable-diffusion-v1-5"
  !git config core.sparsecheckout true
  !echo -e "feature_extractor\nsafety_checker\nscheduler\ntext_encoder\ntokenizer\nunet\nmodel_index.json" > .git/info/sparse-checkout
  !git pull origin main
  if os.path.exists('/content/stable-diffusion-v1-5/unet/diffusion_pytorch_model.bin'):
    !rm -r /content/stable-diffusion-v1-5/.git
    %cd /content/    
    print('[1;32mDONE !')
```

**Comment by r8200** [comment]
@TheLastBen Tell me how to run the old colab from the version archive, when I try to run it in the cloud, it gives an error.
Can the old version be used at all?

`Steps:   0% 1/2000 [00:09<5:09:36,  9.29s/it, loss=0.37, lr=5e-6]Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 694, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 654, in main
    if args.save_n_steps >= 200:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
Steps:   0% 1/2000 [00:09<5:14:28,  9.44s/it, loss=0.37, lr=5e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-4', '--instance_data_dir=/content/temnikova', '--class_data_dir=/content/class_female', '--output_dir=/content/models/elenatemnikova', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of a elenatemnikova person', '--class_prompt=photo of a person', '--seed=1125', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=2000', '--num_class_images=300']' returned non-zero exit status 1.
Something went wrong`

**Comment by TheLastBen** [comment]
you can use the new colab, just remove  `--train_text_encoder \` in the "start dreambooth cell" and change back the leaning rate to 5e-6

**Comment by r8200** [comment]
> you can use the new colab, just remove `--train_text_encoder \` in the "start dreambooth cell" and change back the leaning rate to 5e-6

I can’t, there are also errors, I just deleted the line about which they wrote
`Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 694, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 521, in main
    train_dataset, batch_size=args.train_batch_size, shuffle=True, collate_fn=collate_fn
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 108, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=500', '--save_n_steps=0', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/data/pohui', '--output_dir=/content/models/pohui', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--center_crop', '--lr_warmup_steps=0', '--max_train_steps=2000']' returned non-zero exit status 1.
Something went wrong`

**Comment by TheLastBen** [comment]
make sure there are no spaces after the arguments --image_captions_filename \ and so on

**Comment by r8200** [comment]
> you can use the new colab, just remove `--train_text_encoder \` in the "start dreambooth cell" and change back the leaning rate to 5e-6

This method gives the same bad result as yesterday and the day before yesterday. Therefore, I will repeat my question for the third time, how can I run the old version of the colab? Or has one of the components been updated and the work of the old colab is impossible?

**Comment by giteeeeee** [comment]
> > you can use the new colab, just remove `--train_text_encoder \` in the "start dreambooth cell" and change back the leaning rate to 5e-6
> 
> This method gives the same bad result as yesterday and the day before yesterday. Therefore, I will repeat my question for the third time, how can I run the old version of the colab? Or has one of the components been updated and the work of the old colab is impossible?

Make sure you use the newest colab notebook from https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

then change:

![Untitled233-2](https://user-images.githubusercontent.com/89521447/197915746-89b87e32-01fe-4f36-8250-46c348a43ac9.png)


I've been running the old settings like this without any problem.

I understand your frustration as I've experienced similar issues with the new text encoder thing. But maybe we can be a little less demanding? He's been working hard on the repo and been doing this for free.

Really appreciate your work. @TheLastBen

**Comment by alejobrainz** [comment]
Agreed.  The notebook is absolutely fantastic! @TheLastBen is a superstar! I will give the above a shot.  I suppose that change requires using class images and the old workflow, right?  To that effect is there any way to use the old workflow to train various subjects of the same class?

**Comment by giteeeeee** [comment]
> Agreed. The notebook is absolutely fantastic! @TheLastBen is a superstar! I will give the above a shot. I suppose that change requires using class images and the old workflow, right?

Yes that's correct.

**Comment by TheLastBen** [comment]
> I'm experiencing the same problems, unfortunately. Is there a way to use the 1.4 model with the new method?

Use the this to download the 1.4 model : 

```
import os
from IPython.display import clear_output

Huggingface_Token = "" #@param {type:"string"}
token=Huggingface_Token

if token !="":
  if os.path.exists('/content/stable-diffusion-v1-5'):
    !rm -r /content/stable-diffusion-v1-5   
  clear_output()
  %cd /content/
  clear_output()
  !mkdir /content/stable-diffusion-v1-5
  %cd /content/stable-diffusion-v1-5
  !git init
  !git lfs install --system --skip-repo
  !git remote add -f origin  "https://USER:{token}@huggingface.co/runwayml/stable-diffusion-v1-5"
  !git config core.sparsecheckout true
  !echo -e "feature_extractor\nsafety_checker\nscheduler\ntext_encoder\ntokenizer\nunet\nmodel_index.json" > .git/info/sparse-checkout
  !git pull origin main
  if os.path.exists('/content/stable-diffusion-v1-5/unet/diffusion_pytorch_model.bin'):
    !rm -r /content/stable-diffusion-v1-5/.git
    %cd /content/    
    print('[1;32mDONE !')
```
