### ISSUE TITLE
Traceback Error: ImportError: cannot import name 'EventData'

### ISSUE THREAD

**Issue by Bez22** [TheLastBen/fast-stable-diffusion#2047]
I've been using Stable diffusion on PaperSpace for a few days and all of a sudden this error has stopped both the gradio and local tunnel interface from opening:

Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 25, in <module>
    import gradio
  File "/usr/local/lib/python3.9/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 35, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 27, in <module>
    from gradio.helpers import EventData, create_tracker, skip, special_args
ImportError: cannot import name 'EventData' from 'gradio.helpers' (/usr/local/lib/python3.9/dist-packages/gradio/helpers.py)

I've deleted the sd folder several times over now. Does anyone know of any other solutions to this problem?

**Comment by Bez22** [comment]
I just tried opening an entirely new notebook via the original Paperspace link and it seems to be working now so I'm closing this issue.
