### ISSUE TITLE
TypeError: load_scripts() missing 1 required positional argument: 'basedir'

### ISSUE THREAD

**Issue by 78978978** [TheLastBen/fast-stable-diffusion#205]
![Uploading 屏幕截图 2022-10-23 005131.jpg…]()

**Comment by 78978978** [comment]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 164, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 124, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 83, in initialize
    modules.scripts.load_scripts()
TypeError: load_scripts() missing 1 required positional argument: 'basedir'

**Comment by TheLastBen** [comment]
check the box "update_repo" in the second cell and see if the problem persists

**Comment by dhsusf** [comment]
Ran into the problem with the fast-DreamBooth.ipynb, which doesn't include the following code:

Update_repo = True #@param {type:"boolean"}
if Update_repo:
  !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.sh  
  !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py
  !rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py  
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/
  clear_output()
  print('[1;32m')
  !git pull

As you can guess, I cut and pasted it into the notebook and it solved the problem.

**Comment by TheLastBen** [comment]
I'll add it

**Comment by dpbrinkm** [comment]
I must be blind, i cant find any "update_repo" box in the second cell. I ended up adding the above snippet from @dhsusf to the dependencies code box but it didn't do much after I ran it. Am I adding it to the right spot?

**Comment by TheLastBen** [comment]
you'll find it here : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by TheLastBen** [comment]
option added, refresh the notebook to see it https://github.com/TheLastBen/fast-stable-diffusion/commit/73c628763864b063432ed5ebd8112c1fbd84b969

**Comment by 78978978** [comment]
> check the box "update_repo" in the second cell and see if the problem persists

Thank you for your reply

**Comment by 78978978** [comment]
> check the box "update_repo" in the second cell and see if the problem persists

Thank you for your reply
