### ISSUE TITLE
ControlNet issue.

### ISSUE THREAD

**Issue by iqddd** [TheLastBen/fast-stable-diffusion#2064]
When applying the preprocessor "seg_ofade20k" or "seg_ofcoco" I get an error (see the log below).
```
Preview Resolution = 512
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 486, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 499, in oneformer_ade20k
    from annotator.oneformer import OneformerDetector
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/oneformer/__init__.py", line 4, in <module>
    from .api import make_detectron2_model, semantic_run
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/oneformer/api.py", line 6, in <module>
    from annotator.oneformer.detectron2.config import get_cfg
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/oneformer/detectron2/config/__init__.py", line 2, in <module>
    from .compat import downgrade_config, upgrade_config
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/oneformer/detectron2/config/compat.py", line 27, in <module>
    from .config import CfgNode as CN
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/oneformer/detectron2/config/config.py", line 7, in <module>
    from fvcore.common.config import CfgNode as _CfgNode
ModuleNotFoundError: No module named 'fvcore'
```

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
fixed
