### ISSUE TITLE
I keep getting this "Bad LoRA layer name."

### ISSUE THREAD

**Issue by Nojarosann** [TheLastBen/fast-stable-diffusion#2067]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7f51d24727d0>]: AssertionError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 185, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_te_text_model_encoder_layers_0_mlp_fc1.hada_w1_a - must end in lora_up.weight, lora_down.weight or alpha

i have downloaded the link The developer gave to the user on this link but that idn't resolve the issue

Link: https://github.com/TheLastBen/fast-stable-diffusion/issues/2033

**Comment by g2asell2019** [comment]
what did you put in prompt?

**Comment by Nojarosann** [comment]
I don't have the prompt saved but i'm sure it was something like this.

1girl, grayscale, warrior, <lora:FoF-06:0.7>

Though i've renamed the LoRA to "FoF06" but it still didn't work

**Comment by Taikakim** [comment]
I just made a LoHa, using the suggested network dimension values, also getting:

It's a 768px base SD 1.5 model, 20 images, 20 repeats, 30 epochs, default learning rates etc.

```
100% 40/40 [00:04<00:00,  8.32it/s]
loading Lora /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/porcelain3-768-loha.ckpt: AssertionError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 215, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 185, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_te_text_model_encoder_layers_0_self_attn_k_proj.hada_w1_a - must end in lora_up.weight, lora_down.weight or alpha
```
