### ISSUE TITLE
Error when starting Stable Diffusion.

### ISSUE THREAD

**Issue by iqddd** [TheLastBen/fast-stable-diffusion#2071]
The last cell crashes.
```
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 4c618792b5a84cd0e4453ae815d32a59f3bee6794240c40a10ee004db7486bb3
Loading weights [4c618792b5] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 23.4s (calculate hash: 8.2s, load weights from disk: 5.2s, find config: 4.6s, create model: 0.3s, apply weights to model: 2.8s, apply half(): 1.4s, move model to device: 0.9s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 413, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 316, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'ssl_verify'
```

**Comment by guagua981** [comment]
The same situation

**Comment by newptcai** [comment]
Same here. Removed `sd` folder but it still does not work.

**Comment by iqddd** [comment]
It seems to work if you set the check to Use_Latest_Working_Commit.

**Comment by cosmicoxytocin** [comment]
Check "Use_Latest_working_Commit"
Webui received a fairly large update a few hours ago.

**Comment by Difooooser** [comment]
Where do I check this?

**Comment by guagua981** [comment]
The problem is solved, thank you all

**Comment by eskaviam** [comment]
Open `webui.py` it should be on `/content/gdrive/MyDrive/sd/stable-diffusion-webui/`

search for `ssl_verify=cmd_opts.disable_tls_verify,` using ctrl+f

delete the line, and ctrl+s to save, it should start normally now.

And I don't know if its necessary i think you need to update to gradio 3.28.1
add a new code cells and run this code below
`!pip install gradio==3.28.1 --no-deps`

**Comment by 1111dontworryaboutit** [comment]
Thank you so much.

**Comment by slooi** [comment]
> Check "Use_Latest_working_Commit"
Works like a charm

**Comment by 1111dontworryaboutit** [comment]
Thank you!

**Comment by BLABZ** [comment]
I just got this same error above and just tried searching for search for `ssl_verify=cmd_opts.disable_tls_verify, ` using ctrl+f in the webui.py... and nothing comes up for some reason.

**Comment by eskaviam** [comment]
> I just got this same error above and just tried searching for `ssl_verify=cmd_opts.disable_tls_verify, ` using ctrl+f in the webui.py... and nothing comes up for some reason.

The way i do it is to ctrl+a and copying to visual studio code and searching `ssl_verify=cmd_opts.disable_tls_verify` there

**Comment by BLABZ** [comment]
webui.py .. (at least mine) already doesn't seem to have `ssl_verify=cmd_opts.disable_tls_verify` or even `ssl_verify` anywhere in it, but I still am strangely getting that error... hmmm..

**Comment by BLABZ** [comment]
Update: I redownloaded a separate 'webui.py' file and replaced the one I had.... Then went and deleted the line from the new one and now it works.... That's kinda strange! I never messed with that file at all until now..

Thanks for the assistance though!! It's appreciated!

**Comment by jihocult** [comment]
> Check "Use_Latest_working_Commit" Webui received a fairly large update a few hours ago.

Where do i see this "Use_Latest_working_Commit"? sorry if the question is kind of dumb.

**Comment by moxumbic** [comment]
> > Check "Use_Latest_working_Commit" Webui received a fairly large update a few hours ago.
> 
> Where do i see this "Use_Latest_working_Commit"? sorry if the question is kind of dumb.

![Screenshot_1816](https://user-images.githubusercontent.com/125979010/235479215-011c8926-e4a7-4d33-a2f0-f43d98c6d058.jpg)

**Comment by thejohnd0e** [comment]
"Use_Latest_working_Commit" works for me, tnx.

**Comment by Archon332** [comment]
What to do if you are Paperspace user? We don't have "Use_Latest_working_Commit" button.

**Comment by TheLastBen** [comment]
@Archon332 will fix paperspace and runpod shortly

**Comment by okeymmloo** [comment]
remove the ssl_verify=cmd_opts.disable_tls_verify from webui.py but now I get another error : File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
     webui()
   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
     shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
     txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_to ken_button = create_toprow(is_img2img=False)
   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
     skip.click(
   File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
     dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by okeymmloo** [comment]
mistake after mistake ;(

**Comment by Archon332** [comment]
Deleted **ssl_verify=cmd_opts.disable_tls_verify** on paperspace. It started to work somehow.

**Comment by TheLastBen** [comment]
no need to modify any file, it's fixed now

**Comment by 1111dontworryaboutit** [comment]
I tried many many different things and I keep getting different errors again and again no matter which model I load nor if I have the "Use_Latest_working_Commit" checked

**Comment by 1111dontworryaboutit** [comment]
So with everything reinstalled, making sure I am using the latest version of the notebook - this is about the cleanest error I got so far:


*File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'*

**Comment by TheLastBen** [comment]
use the latest notebook
