### ISSUE TITLE
Error in last cell

### ISSUE THREAD

**Issue by noha2310** [TheLastBen/fast-stable-diffusion#2072]
Hi.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 35, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 629, in <module>
    gradio_theme = gr.themes.Base()
AttributeError: module 'gradio' has no attribute 'themes'

What should I do?
Please help me.

**Comment by SDPDVADER** [comment]
tried that and no bueno.  probably needs to be updated again @TheLastBen .  i will just wait.

**Comment by noha2310** [comment]
I re-ran all the cells and it resolved the issue.

Thanks to @Gamemaster2930. ^_^

**Comment by Paul1909** [comment]
I re-ran the cells, unticked the "Use_Cloudflare_Tunnel". That fixed it for me
