### ISSUE TITLE
TypeError: Blocks.launch() got an unexpected keyword argument 'ssl_verify'というエラーが発生した。Help me.

### ISSUE THREAD

**Issue by emodoran1293dora** [TheLastBen/fast-stable-diffusion#2073]

**Comment by Ninkurk** [comment]
I got that too!
I was running it on runpod.

Here's the issure:
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 413, in <module>
    webui()
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 316, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'ssl_verify'

**Comment by okeymmloo** [comment]
I even asked gpt chat for help to fix it and guess what, it didn't work ;(

**Comment by TheLastBen** [comment]
new A1111 update, will fix shortly

**Comment by AIidols** [comment]
Thank you so much!

**Comment by moon47usaco** [comment]
Will the run pod notebook update automatically when fixed?

Trying the fix from here (delete line 322 webui.py) does not work on run pod:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9972

**Comment by TheLastBen** [comment]
run it again now, it should work

**Comment by moon47usaco** [comment]
Working again =]
Running off to buy Ben another Coffee...

**Comment by leejinkyeong** [comment]
!pip install --upgrade gradio

**Comment by leejinkyeong** [comment]
The Coreb user is configured in the start stable-diffusion edit 
Record and update 
!pip install --upgrade gradio
