### ISSUE TITLE
No module named 'gradio_client'

### ISSUE THREAD

**Issue by Sotonya** [TheLastBen/fast-stable-diffusion#2076]
Deleted all folders and installed them again. Gradio or Ngrok_token - the result is the same.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 29, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 34, in <module>
    from gradio_client import media_data
ModuleNotFoundError: No module named 'gradio_client'

**Comment by Fronscavenger** [comment]
!pip install gradio_client
!pip install -U gradio

**Comment by kokakin** [comment]
> !pip install gradio_client !pip install -U gradio

This worked for me. Thanks!

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by dilectiogames** [comment]
but why it worked yesterday?

every time I open google colab they break something. why they keep breaking my setups? I swear they do it on purpose.

is like someone scrambling all your apps on your computer each day just to mess with you.

they even want money for it. I pay money to work one hour and lose four hours to fix the notebook every time I open it

**Comment by dilectiogames** [comment]
> !pip install gradio_client !pip install -U gradio

that didn't work. yet again using the latest notebook, fixed the issue.

till tomorrow,
