### ISSUE TITLE
Error while starting up Stable-Diffusion

### ISSUE THREAD

**Issue by UselessTrafficCone** [TheLastBen/fast-stable-diffusion#2088]
Hi I'll preface this by saying that i know almost nothing about coding. Since yesterday Stable-Diffusion has not been able to launch on Colab for me, everything seems to run fine until the last cell "Start Stable-Diffusion" then it just gives me this text: 

ControlNet v1.1.130
ControlNet v1.1.130
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 61.3s (load weights from disk: 51.2s, create model: 5.0s, apply weights to model: 3.2s, apply half(): 1.0s, move model to device: 0.8s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 413, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 316, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'ssl_verify'

After this it just says the cell has completed running and does not start Stable-Diffusion

**Comment by TheLastBen** [comment]
use the latest notebook from the official link

**Comment by ShunKaiser** [comment]
> use the latest notebook from the official link

I believe I still had the same problem with the latest notebook. 

TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by Sooty001** [comment]
> > use the latest notebook from the official link
> 
> I believe I still had the same problem with the latest notebook.
> 
> TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

Same error, nothing works, already reinstalled sd

**Comment by TheLastBen** [comment]
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

run it without the first cell to see that the notebook isn't the issue

**Comment by TruthSearchers** [comment]
Not working
same issue still

**Comment by mdlieber99** [comment]
I get this same error: TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'. and I tried running without the first cell, but it won't run the next cell without a shared drive activated.  get this error: 

NameError                                 Traceback (most recent call last)
[<ipython-input-1-d2faf141141a>](https://localhost:8080/#) in <cell line: 25>()
     23   Shared_Drive=""
     24 
---> 25 if Shared_Drive!="" and not os.path.exists("/content/gdrive/Shareddrives"):
     26   print('Shared drive not detected, using default MyDrive')
     27   mainpth="MyDrive"

NameError: name 'Shared_Drive' is not defined

**Comment by mdlieber99** [comment]
Did something change between yesterday and today?  I got it to work yesterday but today I did the same thing and it does not work.

**Comment by Olymmpia** [comment]
I had the same problem since yesterday. All of the above didn't work. I just deleted all from my drive. Opened this link, copied and run, and now it worked.

**Comment by brunojorgemartinho** [comment]
yeah it's not working, you need to pay now

**Comment by Olymmpia** [comment]
> yeah it's not working, you need to pay now

Yeah, I know. It's been a few days since then. It is not working anymore. I found out and subscribed on paid colab, and SD is working perfectly now.
