### ISSUE TITLE
This problem keeps pop up every single time.

### ISSUE THREAD

**Issue by MrAshbury20** [TheLastBen/fast-stable-diffusion#2093]
ControlNet v1.1.130
ControlNet v1.1.130
Loading weights [f20c91bd27] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 50.2s (load weights from disk: 42.3s, create model: 1.8s, apply weights to model: 3.9s, apply half(): 1.2s, move model to device: 0.9s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by MrAshbury20** [comment]
whenever I upload a model it doesn't work as well !

**Comment by maloadjav** [comment]
i have the problem too

**Comment by TheLastBen** [comment]
if the model is safetensors, you need to tick the box "safetensors"
