### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by Gamemaster2930** [TheLastBen/fast-stable-diffusion#2095]
Running last cell results in this error. Who knows what can be the issue, send help:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 413, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 302, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 463, in create_ui
    with gr.Blocks(analytics_enabled=False) as txt2img_interface:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 486, in __init__
    super().__init__(render=False, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 561, in BlockContext_init
    add_classes_to_gradio_component(self)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 529, in add_classes_to_gradio_component
    comp.elem_classes = ["gradio-" + comp.get_block_name(), *(comp.elem_classes or [])]
AttributeError: 'Blocks' object has no attribute 'elem_classes'

**Comment by TheLastBen** [comment]
try running the notebook without the first cell and let me know how it goes

**Comment by mistertexxx** [comment]
> you used this link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb ?

yep, the last one

**Comment by nonoes125** [comment]
same thing for me

**Comment by 32sivilao** [comment]
exactly the same error for me to

**Comment by metzo007** [comment]
same error here

**Comment by Gamemaster2930** [comment]
> try running the notebook without the first cell and let me know how it goes

Same problem

**Comment by TheLastBen** [comment]
not sure what changed, working on it

**Comment by podolyanbogdan** [comment]
works now

**Comment by nikjir** [comment]
same problem here. going to recheck

**Comment by podolyanbogdan** [comment]
i turned Use_Latest_Working_Commit to positive, and everything worked

**Comment by nikjir** [comment]
seems like that did it for now!

**Comment by sajjadalis** [comment]
yep. working now.

**Comment by TheLastBen** [comment]
fixed

**Comment by Gamemaster2930** [comment]
Everything working now. Thank you!
