### ISSUE TITLE
Can't run Deforum plugin at all anymore

### ISSUE THREAD

**Issue by Taikakim** [TheLastBen/fast-stable-diffusion#2098]
This is what I get with any request to the (up to date) Deforum plugin. I'm running the latest commit of the Automatic notebook.

```
Error completing request
Arguments: ('task(r95mfhf31ri4ujc)', None, False, None, 'Video Input', 120, 'replicate', '0:(0)', '0:(1)', '0:(0)', '0:(0)', '0:(1.75)', '0:(0.5)', '0:(0.5)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(0)', '0:(0)', '0:(53)', '0: (0.065)', '0: (0.65)', '0: (1.0)', '0: (7)', '0:(1.5)', False, '0:(1)', '0:(0)', False, '0: (25)', '0: (70)', '0: (1)', False, '0: (200)', '0: (10000)', '0:(s), 1:(-1), "max_f-2":(-1), "max_f-1":(s)', False, '0: ("Euler a")', '0: ("{video_mask}")', False, '0: ("{video_mask}")', False, '0: ("model1.ckpt"), 100: ("model2.safetensors")', False, '0: (2)', True, '0: (1.05)', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', 'LAB', '', 1.0, False, '2', 'None', '0: (1)', 'None', '0: (1)', '0', 'perlin', 8, 8, 4, 0.5, True, False, 0.2, 'border', 'bicubic', False, '/content/gdrive/MyDrive/sd/stable-diffusion-webui/outputs/img2img-images/text2video/20230503095421/vid.mp4', 1, 0, -1, False, False, 'https://deforum.github.io/a1/VM1.mp4', False, '20230129210106', '{\n    "0": "a beautiful video of an art nouveau dancer dancing on stage"\n}\n    ', 'cellular automata, generative art, [seashell], pearlescent, alabaster, iridescent, porcelain, translucent materials, flawless, sculpture, [emerald]', '', 512, 512, False, False, -1, 'Euler a', False, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Deforum_{timestring}', '{timestring}_{index}_{prompt}.png', 'iter', 1, False, False, True, 0.8, 'https://deforum.github.io/a1/I1.png', False, False, False, True, 'https://deforum.github.io/a1/M1.jpg', 1.0, 1.0, 4, 1, True, 4, 'reroll', 10.0, False, 15, False, False, 'FFMPEG mp4', 'None', 'https://deforum.github.io/a1/A1.mp3', False, 'realesr-animevideov3', 'x2', True, False, 'x0_pred', 'C:/SD/20230124234916_%09d.png', 'testvidmanualsettings.mp4', False, 'RIFE v4.6', 3, True, 3, False, None, True, False, 'None', True, 'None', False, False, 2, 'RAFT', 'None', False, 'None', False, 'None', False, False, '0:(0.5)', '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://deforum.github.io/a1/Gi1.png",\n    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",\n    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",\n    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",\n    "max_f-20": "https://deforum.github.io/a1/Gi1.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced') {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 48, in run_deforum
    p = StableDiffusionProcessingImg2Img(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 977, in __init__
    self.image_cfg_scale: float = image_cfg_scale if shared.sd_model.cond_stage_key == "edit" else None
AttributeError: 'NoneType' object has no attribute 'cond_stage_key'

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1206, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1181, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [gallery, textbox, textbox, html, html]
Received outputs:
    [None, "", "", "<div class='error'>AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;cond_stage_key&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>0.01s</p><p class='vram'>Torch active/reserved: 9/22 MiB, <wbr>Sys VRAM: 1531/16151 MiB (9.48%)</p></div>"]
Error completing request
Arguments: ('task(cfp35o7tokwdo3x)', None, False, None, '2D', 35, 'replicate', '0:(0)', '0:(1)', '0:(0)', '0:(0)', '0:(1.75)', '0:(0.5)', '0:(0.5)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(0)', '0:(0)', '0:(53)', '0: (0.065)', '0: (0.65)', '0: (1.0)', '0: (7)', '0:(1.5)', False, '0:(1)', '0:(0)', False, '0: (25)', '0: (70)', '0: (1)', False, '0: (200)', '0: (10000)', '0:(s), 1:(-1), "max_f-2":(-1), "max_f-1":(s)', False, '0: ("Euler a")', '0: ("{video_mask}")', False, '0: ("{video_mask}")', False, '0: ("model1.ckpt"), 100: ("model2.safetensors")', False, '0: (2)', True, '0: (1.05)', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', 'LAB', '', 1.0, False, '2', 'None', '0: (1)', 'None', '0: (1)', '0', 'perlin', 8, 8, 4, 0.5, True, False, 0.2, 'border', 'bicubic', False, '/content/gdrive/MyDrive/sd/stable-diffusion-webui/outputs/img2img-images/text2video/20230503095421/vid.mp4', 1, 0, -1, False, False, 'https://deforum.github.io/a1/VM1.mp4', False, '20230129210106', '{\n    "0": "a beautiful video of an art nouveau dancer dancing on stage"\n}\n    ', 'cellular automata, generative art, [seashell], pearlescent, alabaster, iridescent, porcelain, translucent materials, flawless, sculpture, [emerald]', '', 512, 512, False, False, -1, 'Euler a', False, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Deforum_{timestring}', '{timestring}_{index}_{prompt}.png', 'iter', 1, False, False, True, 0.8, 'https://deforum.github.io/a1/I1.png', False, False, False, True, 'https://deforum.github.io/a1/M1.jpg', 1.0, 1.0, 4, 1, True, 4, 'reroll', 10.0, False, 15, False, False, 'FFMPEG mp4', 'None', 'https://deforum.github.io/a1/A1.mp3', False, 'realesr-animevideov3', 'x2', True, False, 'x0_pred', 'C:/SD/20230124234916_%09d.png', 'testvidmanualsettings.mp4', False, 'RIFE v4.6', 3, True, 3, False, None, True, False, 'None', True, 'None', False, False, 2, 'RAFT', 'None', False, 'None', False, 'None', False, False, '0:(0.5)', '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://deforum.github.io/a1/Gi1.png",\n    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",\n    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",\n    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",\n    "max_f-20": "https://deforum.github.io/a1/Gi1.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced', True, '', '', False, False, False, 'none', 'None', 1, 0, 1, 64, 64, 64, 'Inner Fit (Scale to Fit)', 'Balanced') {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 48, in run_deforum
    p = StableDiffusionProcessingImg2Img(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 977, in __init__
    self.image_cfg_scale: float = image_cfg_scale if shared.sd_model.cond_stage_key == "edit" else None
AttributeError: 'NoneType' object has no attribute 'cond_stage_key'
```

**Comment by TheLastBen** [comment]
try removing the extension and installing it again

**Comment by Taikakim** [comment]
Ok, I'll try that. I'm hesitant to do a full reinstall of the whole SD Web UI notebook although it might help, since there's my saved prompts, custom models, and whatnot, which would be hard to back up since I don't remember everything which is changed from the base installation. Last time I forgot to save the file with my saved prompts and lost a lot of good stuff :/

**Comment by TheLastBen** [comment]
instead of removing the old sd folder, just rename it, then find out where the issue lies, then bring back your files
