### ISSUE TITLE
Dataset directory doesn't exist

### ISSUE THREAD

**Issue by Ninkurk** [TheLastBen/fast-stable-diffusion#2102]
Hey, I am trying to train a TI but when I click on "Train TI", I get "waiting" written in the menu but when I check the script, it says this:
Arguments: ('task(bhodf4455geew2p)', 'Latina2371Minka', '0.002:25, 0.001', 1, 1, 'workspace/sd/stable-diffusion-webui/Latina2371Minka', 'textual_inversion', 512, 512, False, 150, 'disabled', '0.1', False, 0, 'once', False, 5, 3, 'subject_filewords_double.txt', True, True, '', '', 20, 16, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/textual_inversion/ui.py", line 33, in train_embedding
    embedding, filename = modules.textual_inversion.textual_inversion.train_embedding(*args)
  File "/workspace/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 368, in train_embedding
    validate_train_inputs(embedding_name, learn_rate, batch_size, gradient_step, data_root, template_file, template_filename, steps, save_embedding_every, create_image_every, log_directory, name="embedding")
  File "/workspace/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 348, in validate_train_inputs
    assert os.path.isdir(data_root), "Dataset directory doesn't exist"
AssertionError: Dataset directory doesn't exist

This is on runpod. I am able to train TI with no errors on colab. 
Please let me know what the issue might be.
Thank you!

**Comment by DanoGL** [comment]
Same issue... unlucky...

**Comment by TheLastBen** [comment]
did you input the directory manually ? if so, the path must start with "/" : 
`/workspace/....` instead of `workspace/...`
