### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'themes'

### ISSUE THREAD

**Issue by Naikkusu** [TheLastBen/fast-stable-diffusion#2109]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 35, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 629, in <module>
    gradio_theme = gr.themes.Base()
AttributeError: module 'gradio' has no attribute 'themes'

**Comment by TheLastBen** [comment]
use a fresh sd folder with the latest noteobok

**Comment by karchip** [comment]
I have the same problem, can you please explain what you mean by the above suggestion? I am not a coder and have limited understanding of the process. Thank you.

**Comment by lyric025** [comment]
I have the same issue..... re-installed stable diffusion and no luck.. can anyone pls advise..

**Comment by TheLastBen** [comment]
use this link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
