### ISSUE TITLE
I got that too!

### ISSUE THREAD

**Issue by forestandy** [TheLastBen/fast-stable-diffusion#2112]
I got that too!
I was running it on runpod.

Here's the issure:
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 413, in <module>
    webui()
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 316, in webui
    app, local_url, share_url = shared.demo.launch(
TypeError: Blocks.launch() got an unexpected keyword argument 'ssl_verify'

_Originally posted by @Ninkurk in https://github.com/TheLastBen/fast-stable-diffusion/issues/2073#issuecomment-1529839881_

**Comment by TheLastBen** [comment]
does the issue persist ?
