### ISSUE TITLE
Spacestage?

### ISSUE THREAD

**Issue by RONNYKHALIL** [TheLastBen/fast-stable-diffusion#2120]
I set force_reinstall Dependencies to 'true' in an effort to troubleshoot an issue with SD 2.1 768 model, after which I get this error about 'Spacestage':

Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 29, in <module>
    import gradio
  File "/usr/local/lib/python3.9/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 35, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 20, in <module>
    from gradio_client import serializing
  File "/usr/local/lib/python3.9/dist-packages/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/usr/local/lib/python3.9/dist-packages/gradio_client/client.py", line 21, in <module>
    from huggingface_hub import SpaceStage
ImportError: cannot import name 'SpaceStage' from 'huggingface_hub' (/usr/local/lib/python3.9/dist-packages/huggingface_hub/__init__.py)

Second time this happened after force reinstalling dependencies, first time was resolved by starting from scratch with a new notebook, rebuilding, reimporting etc. I won't make that mistake again, but wondering if there is an easy way to resolve this without rebuilding from scratch again.

**Comment by TheLastBen** [comment]
in the workspace, you will find a folder named "latest_notebooks", always copy those to the main folder

**Comment by RONNYKHALIL** [comment]
ahh brilliant. thank you!

**Comment by brunojorgemartinho** [comment]
Didn't work for me too
