### ISSUE TITLE
RunPod error when starting Stable-Diffusion and loading the model

### ISSUE THREAD

**Issue by qazaqazaq** [TheLastBen/fast-stable-diffusion#2130]
"safetensors= True" doesn't help. Another path too. Thanks in advance.

```
Loading weights [9a31b5be29] from /workspace/sd/auto-models/realisticVisionV20_v20.safetensors
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 195, in initialize
    modules.sd_models.load_model()
  File "/workspace/sd/stable-diffusion-webui/modules/sd_models.py", line 424, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/workspace/sd/stable-diffusion-webui/modules/sd_models.py", line 271, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/workspace/sd/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: self.size(-1) must be divisible by 2 to view Byte as Half (different element sizes), but got 964589


Stable diffusion model failed to load, exiting
```

**Comment by TheLastBen** [comment]
Make sure you set the disk size of the pod higher than 20gb

**Comment by qazaqazaq** [comment]
Thank you, and could you say please what is the difference between "container disk" and "volume disk"? Which size should be higher than 20gb?

**Comment by TheLastBen** [comment]
Set the temp disk to 20 and the volume to 50
