### ISSUE TITLE
Paperspace Last cell error

### ISSUE THREAD

**Issue by Wyeel** [TheLastBen/fast-stable-diffusion#2132]
Hello, I keep getting this error in the paperspace version:

ControlNet v1.1.150
ControlNet v1.1.150
Loading weights [a09b824f36] from /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/Soyou_Anime_25D.safetensors
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 195, in initialize
    modules.sd_models.load_model()
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 424, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 271, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[77, 768]' is invalid for input of size 0

Stable diffusion model failed to load, exiting

**Comment by Wyeel** [comment]
Wait, nvm. It seems I have issue with my model. I think something to do with Paperspace unable to upload files from outside US.

**Comment by TheLastBen** [comment]
check your disk space limits

**Comment by tamiko992** [comment]
Is meant disk space C

**Comment by HelpANewbie** [comment]
ControlNet v1.1.150
ControlNet v1.1.150
Calculating sha256 for /models/model.safetensors: f6cbc1d7302d08737dd4686c0a6455e2c2918d4c2ea09d7af1cdf877b9a864cc
Loading weights [f6cbc1d730] from /models/model.safetensors
Creating model from config: /notebooks/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0): 
Model loaded in 14.0s (calculate hash: 7.2s, create model: 1.1s, apply weights to model: 1.7s, apply half(): 1.4s, load VAE: 2.2s, move model to device: 0.5s).


This cell shows running and after waiting for a long time I'm not getting the webui link. Yesterday it worked fine for me but today not getting the link and the cell shows its running....Any idea what's the issue here ? Please help

**Comment by hugo-k-m** [comment]
> This cell shows running and after waiting for a long time I'm not getting the webui link. Yesterday it worked fine for me but today not getting the link and the cell shows its running....Any idea what's the issue here ? Please help

I started having the same issue just now.
