### ISSUE TITLE
Paperspace: Not loading models

### ISSUE THREAD

**Issue by fe-quirino** [TheLastBen/fast-stable-diffusion#2157]
Any model I try to load gives me a different error. I tried with safetensor true and false with different results. Lates with safetensos set to true was this error with realisticvision2.0

loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 195, in initialize
    modules.sd_models.load_model()
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 424, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 271, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 250, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[1280, 1280]' is invalid for input of size 65536

Stable diffusion model failed to load, exiting

**Comment by TheLastBen** [comment]
if the model is safetensors, you set "safetensors" to True, otherwise set it to false, make sure the model is downloaded correctly

**Comment by fe-quirino** [comment]
downloaded from the source, also tried uploaded, safetensors set to true, tried several of the famous models on civtai, always this same message

**Comment by TheLastBen** [comment]
does the default model work ?
