### ISSUE TITLE
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'

### ISSUE THREAD

**Issue by justtrane** [TheLastBen/fast-stable-diffusion#2159]
Why does this message always appear when I try to use Stable Diffusion? I have done the same steps as always, but now that error always 

> appears

Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.safetensors: fe06753eeeda3a5ea92a211945a6004fa999d6e7058adda2b7eb44f08a047a0e
Loading weights [fe06753eee] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inpainting-inference.yaml
LatentInpaintDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.54 M params.
Downloading (…)olve/main/vocab.json100% 961k/961k [00:00<00:00, 6.05MB/s]
Downloading (…)olve/main/merges.txt100% 525k/525k [00:00<00:00, 6.01MB/s]
Downloading (…)cial_tokens_map.json100% 389/389 [00:00<00:00, 502kB/s]
Downloading (…)okenizer_config.json100% 905/905 [00:00<00:00, 1.13MB/s]
Downloading (…)lve/main/config.json100% 4.52k/4.52k [00:00<00:00, 4.70MB/s]
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 22.4s (calculate hash: 7.1s, load weights from disk: 7.4s, create model: 2.5s, apply weights to model: 3.7s, apply half(): 0.9s, move model to device: 0.7s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
    with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 44, in __init__
    super().__init__(visible=visible, elem_id=elem_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in __init__
    self.render()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
    if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'

>

**Comment by Jboby1** [comment]
This issue's been happening over the last couple days. Colab upgraded to a new version of Gradio that SD doesn't support (yet).

[Try following this temporary fix](https://github.com/TheLastBen/fast-stable-diffusion/issues/2139#issuecomment-1542409621). If it doesn't work, try doing a fresh SD install as well.
