### ISSUE TITLE
AttributeError: module 'gradio.components' has no attribute 'TempFileManager' ISSUE

### ISSUE THREAD

**Issue by podolyanbogdan** [TheLastBen/fast-stable-diffusion#2163]
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/meinapastel_V4 (1).safetensors: 771c8fd970894e049d55a911cfa8764eca671dabbba994903d4f666337df52e6
Loading weights [771c8fd970] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/meinapastel_V4 (1).safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json100% 961k/961k [00:00<00:00, 4.49MB/s]
Downloading (…)olve/main/merges.txt100% 525k/525k [00:00<00:00, 822kB/s]
Downloading (…)cial_tokens_map.json100% 389/389 [00:00<00:00, 380kB/s]
Downloading (…)okenizer_config.json100% 905/905 [00:00<00:00, 876kB/s]
Downloading (…)lve/main/config.json100% 4.52k/4.52k [00:00<00:00, 4.19MB/s]
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 82.1s (calculate hash: 65.8s, load weights from disk: 9.3s, create model: 4.3s, apply weights to model: 1.6s, apply half(): 0.4s, move model to device: 0.7s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
    with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 44, in __init__
    super().__init__(visible=visible, elem_id=elem_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in __init__
    self.render()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
    if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'

**Comment by SorenTruelsen** [comment]
It can be solved by using Ngrok. And it actually seems to be faster, at least for me, when loading the grid image

**Comment by FozeAhmad9999** [comment]
i got a ngrok token but the probel remains when i use it, maybe i am skipping a step, can some guide me through this, thanks

**Comment by potbelliedconan** [comment]
clean install and ngrok fixed this for me. 

Perhaps try a clean install?

**Comment by FozeAhmad9999** [comment]
> clean install and ngrok fixed this for me.
> 
> Perhaps try a clean install?

Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/darkrevpikas_v10.safetensors: 8742b08647e2c1e849b6fd18469669da23441c478516e489118ab71c59601835
Loading weights [8742b08647] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/darkrevpikas_v10.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json100% 961k/961k [00:00<00:00, 1.14MB/s]
Downloading (…)olve/main/merges.txt100% 525k/525k [00:00<00:00, 2.48MB/s]
Downloading (…)cial_tokens_map.json100% 389/389 [00:00<00:00, 382kB/s]
Downloading (…)okenizer_config.json100% 905/905 [00:00<00:00, 909kB/s]
Downloading (…)lve/main/config.json100% 4.52k/4.52k [00:00<00:00, 4.53MB/s]
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 53.2s (calculate hash: 30.9s, load weights from disk: 11.5s, create model: 6.3s, apply weights to model: 2.8s, apply half(): 0.9s, move model to device: 0.7s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
    with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 44, in __init__
    super().__init__(visible=visible, elem_id=elem_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in __init__
    self.render()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
    if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'
