### ISSUE TITLE
lora_layer_mapping issue

### ISSUE THREAD

**Issue by 3dw1nz0n3** [TheLastBen/fast-stable-diffusion#2164]
Did anyone encounter similar issue?

I just found that Lora is not properly loaded with below error message. 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 218, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 137, in load_lora
    is_sd2 = 'model_transformer_resblocks' in shared.sd_model.lora_layer_mapping
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'lora_layer_mapping'

**Comment by hbwjhbwj** [comment]
me too,after --reinstall-torch,
with these reinstall err:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.17 requires pyre-extensions==0.0.23, which is not installed.
clean-fid 0.1.29 requires requests==2.25.1, but you have requests 2.30.0 which is incompatible.
image-reward 1.2 requires timm==0.6.13, but you have timm 0.6.7 which is incompatible.
image-reward 1.2 requires transformers==4.27.4, but you have transformers 4.25.1 which is incompatible.
xformers 0.0.17 requires torch==2.0.0, but you have torch 2.0.1+cu118 which is incompatible.

**Comment by TheLastBen** [comment]
do not reinstall torch or any other dependency

**Comment by hbwjhbwj** [comment]
Sorry, there is a same error (no attribute 'lora_layer_mapping')that caused me to think this is SDwebui project. This error was reported after I upgraded SDwebui and is not related to your project, sorry。

**Comment by qcrocknet2020** [comment]
I have the same issue mentioned initially after updating today. All was good with a previous version, think 1-2 months ago. Hope there is a simple solution, thanks.

**Comment by qcrocknet2020** [comment]
Ok, I fixed the issue by enabling in settings:
Lora: use old method that takes longer when you have multiple Loras active and produces same results as kohya-ss/sd-webui-additional-networks extension

Then no more errors and my Loras work! Yea!

**Comment by Th3c00ldud3** [comment]
> Ok, I fixed the issue by enabling in settings: Lora: use old method that takes longer when you have multiple Loras active and produces same results as kohya-ss/sd-webui-additional-networks extension
> 
> Then no more errors and my Loras work! Yea!

This worked for me as well! Thank you!!!

**Comment by uwidev** [comment]
Switching to another checkpoint seems to have fixed it for me. Of course, change it back to the actual checkpoint you want to use.

**Comment by AugmentedRealityCat** [comment]
> Switching to another checkpoint seems to have fixed it for me

This worked for me as well. Sometimes the solution is simple, but the hard thing is to find it !
