### ISSUE TITLE
`UnboundLocalError` with Dreambooth on Runpod

### ISSUE THREAD

**Issue by feesta** [TheLastBen/fast-stable-diffusion#2169]
I'm getting an error on Dreambooth on Runpod when saving a checkpoint. Running on a 3090 on the latest default template offered by Runpod.

```
Traceback (most recent call last):
  File "/workspace/diffusers/examples/dreambooth/train_dreambooth_rnpd.py", line 889, in <module>
    main()
  File "/workspace/diffusers/examples/dreambooth/train_dreambooth_rnpd.py", line 836, in main
    text_encoder=accelerator.unwrap_model(text_encoder),
UnboundLocalError: local variable 'text_encoder' referenced before assignment
```

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by feesta** [comment]
Seems to be only when using `Save_Checkpoint_Every_n_Steps` that it fails.
