### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'freeze_settings'

### ISSUE THREAD

**Issue by BigSharkZ** [TheLastBen/fast-stable-diffusion#217]
Hello, this is my first time posting an issue on Github, hopefully I'm doing this right.
I used the AUTOMATIC1111 version just fine for the first time yesterday, but today I get an issue when launching the model.
I also noticed that the "xformers" install is no longer an option. HLKY worked once then stopped generating images.

**LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [a2a802b2] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 166, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 127, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call) 
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1592, in create_ui
    if k in quicksettings_names and not shared.cmd_opts.freeze_settings:
AttributeError: 'Namespace' object has no attribute 'freeze_settings'**

**Comment by TheLastBen** [comment]
check the option "update_repo" in the second cell

xformers is integrated in the cell "requirements"
