### ISSUE TITLE
please fix this still the same error almost burnt 9 units of gpu

### ISSUE THREAD

**Issue by rajdeepjaiswall** [TheLastBen/fast-stable-diffusion#2172]
Loading weights [43c90409bd] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 74.1s (load weights from disk: 62.1s, find config: 4.3s, load config: 1.9s, create model: 0.4s, apply weights to model: 3.1s, apply half(): 1.3s, move model to device: 1.0s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
    with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 44, in __init__
    super().__init__(visible=visible, elem_id=elem_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in __init__
    self.render()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
    if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'....... i tried everything itsnot working the other altrnative is also crashing

**Comment by TheLastBen** [comment]
I could not reproduce the error

**Comment by rajdeepjaiswall** [comment]
so how can it get fixed

**Comment by TheLastBen** [comment]
have you tried ngrok ?

**Comment by rajdeepjaiswall** [comment]
yes i did but nothing happened

**Comment by rajdeepjaiswall** [comment]
i tried unistalling gratio and re installing it but it gives this error now 
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/126091035/fc40bf31-693d-4d83-8ae4-a518df86d921)
