### ISSUE TITLE
problem with segment anything

### ISSUE THREAD

**Issue by hanzheg** [TheLastBen/fast-stable-diffusion#2185]
After installing segment anything, restart UI will get this, can I get some help? Thanks:

Restarting UI...
ControlNet v1.1.178
Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/api.py", line 10, in <module>
    from scripts.sam import sam_predict, dino_predict, update_mask, cnet_seg, categorical_mask
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 18, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

Error loading script: auto.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/auto.py", line 10, in <module>
    from segment_anything import SamAutomaticMaskGenerator
ModuleNotFoundError: No module named 'segment_anything'

Error loading script: sam.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-segment-anything/scripts/sam.py", line 18, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

**Comment by hanzheg** [comment]
Thanks!!!!!!!! :)
