### ISSUE TITLE
Dreambooth v1.5 Paperspace, Instance Images error

### ISSUE THREAD

**Issue by Rauferp** [TheLastBen/fast-stable-diffusion#2200]
In Dreambooth v1.5 Paperspace Notebook, when i run the Instance Images cell it gives me this error:

[Open Browser Console for more detailed log - Double click to close this message]
Model class 'OutputModel' from module '@jupyter-widgets/output' is loaded but can not be instantiated
TypeError: Cannot read properties of undefined (reading 'sessionContext')
    at u.initialize (https://console.paperspace.com/ide/vendors-f64a56cf.aaf460c3d73209440ef5.js:2:159546)
    at new e.Model (https://console.paperspace.com/ide/vendors-c30f4496.aaf460c3d73209440ef5.js:2:483011)
    at new u (https://console.paperspace.com/ide/vendors-f64a56cf.aaf460c3d73209440ef5.js:2:159298)
    at z._make_model (https://console.paperspace.com/ide/vendors-f64a56cf.aaf460c3d73209440ef5.js:2:11894)

I don't know how to fix this

**Comment by TheLastBen** [comment]
use the jupyter interface by clicking on the jupyter icon on the left panel

**Comment by Rauferp** [comment]
thank you
