### ISSUE TITLE
No module named 'modules.paths_internal'

### ISSUE THREAD

**Issue by profcat2** [TheLastBen/fast-stable-diffusion#2208]
Google Colab Ver:
You only get this error if you run with the 1st cell (connect to google drive)

- The workaround is by just ignoring the cell, not checking 'use latest working commit' and using the "model link" to just paste the URL to your checkpoint

- However it's a bit of a pain to use if you have tons of different loras and checkpoints in google drive

- Drive was working last week, I wonder what changed

Error message:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by profcat2** [comment]
Nevermind, everything works "just don't click use latest working commit"...

You just have to delete the old sd folder in drive and let the new one propagate.
Sorry for the false alarm!
