### ISSUE TITLE
Error in last cell in paperspace

### ISSUE THREAD

**Issue by hugo-k-m** [TheLastBen/fast-stable-diffusion#2210]
This just started happening now, everything was running fine earlier today.

```
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 49, in <module>
    from modules import shared, sd_samplers, upscaler, extensions, localization, ui_tempdir, ui_extra_networks, config_states
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
    from modules import sd_samplers_common, prompt_parser, shared
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
    from modules import devices, processing, images, sd_vae_approx, sd_samplers, sd_vae_taesd
  File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "/notebooks/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 17, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 20, in <module>
    import tomesd
ModuleNotFoundError: No module named 'tomesd'
```

**Comment by hugo-k-m** [comment]
Another issue's been opened that covers this issue, I'll close this one.

A workaround for now is to run `pip install tomesd` in the environment/platform you're using.

**Comment by TheLastBen** [comment]
fixed

**Comment by hugo-k-m** [comment]
@TheLastBen Thanks!
