### ISSUE TITLE
ModuleNotFoundError: No module named 'tomesd' (Paperspace)

### ISSUE THREAD

**Issue by Rauferp** [TheLastBen/fast-stable-diffusion#2212]
I have this error on Paperspace:
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 49, in <module>
    from modules import shared, sd_samplers, upscaler, extensions, localization, ui_tempdir, ui_extra_networks, config_states
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
    from modules import sd_samplers_common, prompt_parser, shared
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
    from modules import devices, processing, images, sd_vae_approx, sd_samplers, sd_vae_taesd
  File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "/notebooks/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 17, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 20, in <module>
    import tomesd
ModuleNotFoundError: No module named 'tomesd'

**Comment by TheLastBen** [comment]
A1111 updated their repo, I'll fix it

**Comment by Rauferp** [comment]
thank you

**Comment by Olymmpia** [comment]
I am having the same problem today 
ModuleNotFoundError: No module named 'tomesd'

**Comment by Olymmpia** [comment]
> I am having the same problem today ModuleNotFoundError: No module named 'tomesd'

Ok, !pip install tomesd  worked :)

**Comment by TheLastBen** [comment]
@TSSMARTiNVEST just use the latest notebook

**Comment by TSSMARTiNVEST** [comment]
> the latest notebook

Sorry, I'm new to all this, I don't have any programming knowledge. Please tell me where to get the latest notebook

**Comment by TheLastBen** [comment]
@TSSMARTiNVEST this link will always get you the latest notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by TSSMARTiNVEST** [comment]
> @TSSMARTiNVEST this link will always get you the latest notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

thank you!

**Comment by Olymmpia** [comment]
> > the latest notebook
> 
> Sorry, I'm new to all this, I don't have any programming knowledge. Please tell me where to get the latest notebook. I use google colab pro.

Hi! I am new too and zero in coding. In this case, if I understood correctly, I just removed all SD from my Colab, opened this notebook and copied, and installed it all again. It works fine now. Also, when I have errors like this, when some module is missing, I ask chatgpt to explain me as I am dummie what to do in steps. Usually it is needed to install this kind of module, I do it in the Requiremens section (cell). I copy suggested by Chat GPT code line and paste it somewhere in the Requirenent cell, then restart. It usually looks like this !pip install <modulename>
