### ISSUE TITLE
Isssue after no update after 4 months

### ISSUE THREAD

**Issue by GurweX** [TheLastBen/fast-stable-diffusion#2219]
Thats the long line of issues. 👍 

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 9, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: batch_hijack.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
    from scripts import external_code
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 12, in <module>
    from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

ControlNet v1.1.202
Error loading script: external_code.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-auto-translate-language/scripts/main.py", line 8, in <module>
    from lru import LRU
ModuleNotFoundError: No module named 'lru'

Error loading script: trans_google.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-auto-translate-language/scripts/trans_google.py", line 2, in <module>
    from pygoogletranslation import Translator
ModuleNotFoundError: No module named 'pygoogletranslation'

Error loading script: trans_tp.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-auto-translate-language/scripts/trans_tp.py", line 1, in <module>
    import translators as ts
ModuleNotFoundError: No module named 'translators'

Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 4c86efd062ea772972dd068c3870773f1fd9a37ba9a288ee79ec848448ce7785
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/VAE/BerrysMix.vae.safetensors
Applying scaled dot product cross attention optimization.
Error loading embedding Anything-V3.0.vae.pt:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 178, in load_from_file
    raise Exception(f"Couldn't identify {filename} as neither textual inversion embedding nor diffuser concept.")
Exception: Couldn't identify Anything-V3.0.vae.pt as neither textual inversion embedding nor diffuser concept.

Error loading embedding orangemix.vae.pt:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 178, in load_from_file
    raise Exception(f"Couldn't identify {filename} as neither textual inversion embedding nor diffuser concept.")
Exception: Couldn't identify orangemix.vae.pt as neither textual inversion embedding nor diffuser concept.

Error loading embedding grapefruitV2_3.vae.pt:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 178, in load_from_file
    raise Exception(f"Couldn't identify {filename} as neither textual inversion embedding nor diffuser concept.")
Exception: Couldn't identify grapefruitV2_3.vae.pt as neither textual inversion embedding nor diffuser concept.

Error loading embedding 2DN.vae.pt:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 178, in load_from_file
    raise Exception(f"Couldn't identify {filename} as neither textual inversion embedding nor diffuser concept.")
Exception: Couldn't identify 2DN.vae.pt as neither textual inversion embedding nor diffuser concept.

Textual inversion embeddings loaded(230): Team Rocket Jessie, GLCynthia, TronBonneTI, PokemonLilie, NiijimaMakotoTI, Moooo, breastonglass, slingshotkini, MidnaNoCap, MidnaCap, TallMidna, nakedribbon, yamashiro, BeelstarmonTI, megu1000, CharTurner, Cheelai, mothgirl, doggystyle, deep penetration missionary, breastcurtains, draenei, reversebunny, hades-8500, yuudachi, lalappland, Amber, honolulu, Abigail Jones, Albedo, Mipha, Fi, Atago, nahida, rosa, sonia, ayanami, griseo, Roll Caskett, May, Reze, Rise Kujikawa, juri, Iono, arthur1, cindlop, cyberpunk-lucy, david-martinez-cyberpunk, ganyu-genshin-impact, goku, hd-emoji, lucario, moxxi, nazuna, ori, osrstiny, renalla, shenhe-genshin-impact, spider-gwen, zero-suit-samus, zoroark, hellhound-40000, bunyip-30000, senran kagura new-3000, Morded, Power, Ilulu, Mirko, Ranni, GGMayFinal, MirkoV1, elin-10000, Klee, HildaFE B, lysitheaB, CerebellaSkull, Yor, FranIsekai, BronyaSilverwing, laMudrock, Shylily, ilyaPC-4000, AtsukoLWA-8700, Kei_Shirogane, zerotwoo, GenshinEula, KaguyaMiko, kaguya_9, centaur-120, Baobhan_Sith, GenshinArlecchino, MarinKit, SulettaMercury, NaotoEmbed, GenshinLumine, char_ai_hayasaka, AtagoRQ, SunoharaShunLoli, bremertonSummer, IllustriousMaiden, kashino, siriusAzure, taihou, StLouisLux, Genshinkukishinobu, izumi-konata-12100, hiiragi_tsukasa, hiiragi_kagami, RyuMat, char_nezuko, futabaTI, shirosaki_hana-6000, rice-shower-3000, KuroneKI, Jibril, Yelan - Genshin Impact, LaPlus, Ghislaine Dedoldia TI, YumekoTI, lexington-8000, speedl00ver-8000, natsume-iroha, NanahiraTI, Yoko_embed, HifumiTI, eris_8, HuTaoTI, HinaTI, SucroseTI, kokkoro_character, KurumiTI, RZBeatriceTI, SataniaTI, elbe-7k, FaruzanTI, MayushiTI, YamiTI, BarbaraGenshin, PaimonTI, SubaruVtuberTI, GuraTI, roxy-migurdiaTI, AyanamiTI, PrinzEugenTI, fischl-9200, lamia-73778, KyaruTI, KeqingTI, UnicornTI, BocchiTI, sakamata-chloeTI, OkayuTI, SenkoTI, fumoWDSD5050-15000, Yukari Takeba TI, Haru Okumura TI, AnnTakamakiTI, nami_3000, hitoribocchi-4000, takagiC-8500, ShinobuTI, RebeccaEdgerunners, yamatoOP_5500, PenisOverEyes, NeoRWBY, KobeniTI, shortstackTI, marisa-4500, makima, MinervaTI, ahegao_12000, AkatsukiKirika, KazanariTsubasa, KohinataMiku, MariaCadenzavnaEve, TachibanaHibiki, TsukuyomiShirabe, YukineChris, ElizabethPersona, virgin killer sweater, ayakagenshin, lucoa_9, alice-nikke_11, toga_7, char-leafa-5.5K, raiden_shogun-pt-20, char_lavenza, tifa_6, genshin_yae-mikoV2-9, hasegawakobato_9, pose_upshirt_11, EmotesStacie_E2_8000, beatrice_9, tohru_9, spitroast_92a, Chocola, MomoToLoveRu, Sagiri, C.C, Laffey, Tomimi, Shamiko, Kanna, Fubuki, Formidable, Eldridge, Becky, Anya, pronebone_9, MitsukiBakugouTI-9000, corneo_cowgirl, GenshinSangonomiya_Kokomi, corneo_night_elf, 177013, bukkakAI, bad-artist, bad-hands-5, bad_prompt_version2, felixos8100, standing splitTI, Rukia, EMB_sksmakimatest, corneo_side_doggy, corneo_paizuri, corneo_pov_oral, corneo_widowmaker, corneo_dva, robin_v2_3000, yamato_7000, corneo_runny_makeup
Textual inversion embeddings skipped(2): fumostyle-24000, Apoc768
Model loaded in 109.4s (calculate hash: 9.6s, load weights from disk: 14.3s, create model: 7.6s, apply weights to model: 3.8s, apply half(): 1.7s, load VAE: 10.3s, move model to device: 0.9s, load textual inversion embeddings: 60.8s, scripts callbacks: 0.5s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
    with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 43, in __init__
    super().__init__(visible=visible, elem_id=elem_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in __init__
    self.render()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
    if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'

**Comment by TheLastBen** [comment]
use the latest notebook and a fresh sd folder (rename the old one to sd-old)

**Comment by GENIYAMA** [comment]
> use the latest notebook and a fresh sd folder (rename the old one to sd-old)

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 9, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: batch_hijack.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
    from scripts import external_code
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 12, in <module>
    from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

ControlNet v1.1.204
Error loading script: external_code.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Loading weights [abcaf14e5a] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.safetensors
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 230, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 136, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 407, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 262, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 241, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 261, in load_file
    result[k] = f.get_tensor(k)
KeyboardInterrupt

This error still pops up

**Comment by TheLastBen** [comment]
@GENIYAMA this is the latest notebook, always use this link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by GENIYAMA** [comment]
Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 9, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: batch_hijack.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
    from scripts import external_code
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 12, in <module>
    from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

ControlNet v1.1.204
Error loading script: external_code.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Checkpoint model.safetensors [7f96a1a9ca] not found; loading fallback model.safetensors [abcaf14e5a]
Loading weights [abcaf14e5a] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Couldn't find VAE named Counterfeit-V2.5.vae.pt; using None instead
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(2): easynegative, bad-hands-5
Model loaded in 49.1s (load weights from disk: 42.1s, load config: 0.4s, create model: 1.4s, apply weights to model: 3.0s, apply half(): 0.9s, move model to device: 0.7s, load textual inversion embeddings: 0.5s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
    with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 43, in __init__
    super().__init__(visible=visible, elem_id=elem_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in __init__
    self.render()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
    if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'
 this is the whole message

**Comment by TheLastBen** [comment]
rename the sd folder to sd_old and try again

**Comment by GENIYAMA** [comment]
> rename the sd folder to sd_old and try again

Nope

rror loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 9, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: batch_hijack.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
    from scripts import external_code
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 12, in <module>
    from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

ControlNet v1.1.205
Error loading script: external_code.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)




This error still. pops up 

i deleted the sd folder redownloaded it again and again 

The automatic 111 cell seems to have some issues cuz sometimes it can download all of the files whereas sometimes it can't
