### ISSUE TITLE
Hires.fix not working

### ISSUE THREAD

**Issue by blindiff** [TheLastBen/fast-stable-diffusion#2222]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1023, in sample
    image = images.resize_image(0, image, target_width, target_height, upscaler_name=self.hr_upscaler)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 279, in resize_image
    res = resize(im, width, height)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 271, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/upscaler.py", line 62, in upscale
    img = self.do_upscale(img, selected_model)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/realesrgan_model.py", line 53, in do_upscale
    upsampler = RealESRGANer(
  File "/usr/local/lib/python3.10/dist-packages/realesrgan/utils.py", line 63, in __init__
    loadnet = torch.load(model_path, map_location=torch.device('cpu'))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 107, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

I am getting this error when trying Hires.fix on GoogleColab

**Comment by TheLastBen** [comment]
try a different model, your model looks corrupt
