### ISSUE TITLE
Google Colab problem

### ISSUE THREAD

**Issue by GurweX** [TheLastBen/fast-stable-diffusion#2225]
I've bought google colab pro and changed sd-old and made new one. I have repeatable errors constantly. I have no idea how to fix that issue.

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 9, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: batch_hijack.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
    from scripts import external_code
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 12, in <module>
    from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version, utils
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

ControlNet v1.1.210
Error loading script: external_code.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/api/api.py", line 8, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py)

Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 4c86efd062ea772972dd068c3870773f1fd9a37ba9a288ee79ec848448ce7785
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 36.0s (calculate hash: 8.0s, load weights from disk: 13.7s, create model: 9.0s, apply weights to model: 3.3s, apply half(): 1.0s, move model to device: 0.8s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 284, in create_toprow
    with gr.Row(elem_id=f"{id_part}_toprow", variant="compact"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts.py", line 43, in __init__
    super().__init__(visible=visible, elem_id=elem_id, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 79, in __init__
    self.render()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 94, in render
    if isinstance(self, components.TempFileManager):
AttributeError: module 'gradio.components' has no attribute 'TempFileManager'

**Comment by GurweX** [comment]
Now I can only see this 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by GurweX** [comment]
After deleting this files and re-download it started working
