### ISSUE TITLE
Run time error in Stable Diffusion in Paperspace

### ISSUE THREAD

**Issue by michaelalw** [TheLastBen/fast-stable-diffusion#2230]
So sorry, I am totally new to SD in paperspace. I am getting this error each time I trying to logging. I cant think what's the issue is.
Really appreciated your help to sort this error. 

Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
ControlNet v1.1.214
ControlNet v1.1.214
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 478, in <module>
    webui()
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 366, in webui
    initialize()
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 251, in initialize
    initialize_rest(reload_script_modules=False)
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 291, in initialize_rest
    modules.sd_hijack.list_optimizers()
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack.py", line 38, in list_optimizers
    new_optimizers = [x for x in new_optimizers if x.is_available()]
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack.py", line 38, in <listcomp>
    new_optimizers = [x for x in new_optimizers if x.is_available()]
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 51, in is_available
    return shared.cmd_opts.force_enable_xformers or (shared.xformers_available and torch.version.cuda and (6, 0) <= torch.cuda.get_device_capability(shared.device) <= (9, 0))
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py", line 357, in get_device_capability
    prop = get_device_properties(device)
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py", line 371, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by TheLastBen** [comment]
you need to use a vm that has a GPU, not only CPU

**Comment by michaelalw** [comment]
Many thanks.. Let me try that as well

**Comment by dreamer1048576** [comment]
I have no GPU can be used.
And I run stable diffusion with parameter "--skip-torch-cuda-test --use-cpu all" 
So, it should NOT trying to call cuda , shouldn't it?
