### ISSUE TITLE
Collab pro problem

### ISSUE THREAD

**Issue by Ardoggy** [TheLastBen/fast-stable-diffusion#2232]
After removing the cell "Use last Commit" had to update my SD, then it began to give the following error:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 42, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared, progress
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 699, in <module>
    opts.load(config_filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 631, in load
    self.data = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I checked on another account (without the PRO version) - it gave the same thing, although previously it disconnected after ten minutes of use.

**Comment by Ardoggy** [comment]
Also it working with collab storage, Maybe somone know the reason?

**Comment by TheLastBen** [comment]
try with a fresh sd folder

**Comment by Ardoggy** [comment]
> try with a fresh sd folder

Its fixed with fresh folder. Problem was in old extension that needed to update. ty

**Comment by TheLastBen** [comment]
great!
