### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'convert'

### ISSUE THREAD

**Issue by sajoukourckan** [TheLastBen/fast-stable-diffusion#2235]
What happened when I used img2img:
//Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
Error completing request
//Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 87, in img2img
    image = init_img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'
//Task exception was never retrieved
future: <Task finished name='3ijmk6yna74_280' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006

**Comment by Ardoggy** [comment]
Also, I do not know if it is related, but I catch the following errors at startup:
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
[-] ADetailer initialized. version: 23.6.1.post0, num models: 8
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
2023-06-05 14:02:10,006 - ControlNet - INFO - ControlNet v1.1.215
2023-06-05 14:02:12,421 - ControlNet - INFO - ControlNet v1.1.215
No module named 'dotenv'
Loading weights [7f96a1a9ca] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/anythingV5Anything_anythingV5PrtRE.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/VAE/vaeFtMse840000Ema_v10.safetensors
Applying optimization: sdp... done.
Textual inversion embeddings loaded(4):bad-hands-3, bad_prompt_version2, easynegative, kkw-comicp
Textual inversion embeddings skipped(3): nfixer, nartfixer, nrealfixer
Model loaded in 34.2s (load weights from disk: 17.7s, load config: 0.6s, create model: 7.5s, apply weights to model: 2.9s, apply half(): 0.9s, load VAE: 1.9s, move model to device: 0.8s, load textual inversion embeddings: 2.0s).
Create LRU cache (max_size=16) for preprocessor results.

**Comment by sajoukourckan** [comment]
I also encountered this issue when using ngrok. After deleting the embeddings that reported an error, it still did not solve the problem. Later, I used cloudlfare and still couldn't solve it. The error I reported above was after using cloudlfare, so I think using cloudlfare may not solve this problem.
