### ISSUE TITLE
Loras not loading colab

### ISSUE THREAD

**Issue by dankchocolate** [TheLastBen/fast-stable-diffusion#2277]
I tried starting a new notebook but no luck. The error is...
"activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7feb49972590>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49972830>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb499713f0>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49971a50>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49971360>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49970bb0>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb499726b0>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49972530>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49971b40>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49973ac0>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49970580>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb499729e0>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb499700d0>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49972620>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49972da0>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49973e80>, <modules.extra_networks.ExtraNetworkParams object at 0x7feb49970df0>]: ValueError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 89, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 22, in activate
    multipliers.append(float(params.items[1]) if len(params.items) > 1 else 1.0)
ValueError: could not convert"

**Comment by dankchocolate** [comment]
I'm dumb
