### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/tmpba40hg4p.png'

### ISSUE THREAD

**Issue by skjcs355062** [TheLastBen/fast-stable-diffusion#2285]
There was an error like this.
 I also want to ask, how to cancel the display of the temp file and display the actual file instead, thanks.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "/content/gdrive/.shortcut-targets-by-id/1sa0Ccm-QmVPOCQUjZKiCm_L2qzbNTnQ5/sd/stable-diffusion-webui/modules/ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/tmpba40hg4p.png'

**Comment by profcat2** [comment]
I'm also getting this issue, here's my error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/tmp1qjuxcga.png'

**Comment by penngwynXVII** [comment]
I am getting the same error related to grid tmp files when running in paperspace, happens after every generation with a batch size larger that 1, does not happen if batch size = 1

**Comment by profcat2** [comment]
In colab it can't even generate one :(

**Comment by penngwynXVII** [comment]
I set the "always save grids" to true, resolved issue for me.

**Comment by profcat2** [comment]
Thanks penguin, that narrowed it down a bit.
It looks like if I have "always save all generated images" checkmarked, it seems to go through okay.
However..
It doesn't really work for me to save every single image that generated. I normally tinker around a bit until I get the artwork just right, now my drive will be cluttered with tons of junk images. lol
I'm trying to get it how it used to be where I would just be able to manually save images that turn out good. I hope someone has a good workaround for not having to save everything. Thanks!
