### ISSUE TITLE
Error but still runs?

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2293]
I switched to the new version of your notebook (thanks!).  Even though it runs, I get this error during the startup process.  Is that likely to negatively affect anything?

*** Failed reading extension data from Git repository (sd-dynamic-prompts)
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 63, in do_read_info_from_repo
        commit = repo.head.commit
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 217, in _get_commit
        obj = self._get_object()
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 210, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "/usr/local/lib/python3.10/dist-packages/git/objects/base.py", line 85, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/usr/local/lib/python3.10/dist-packages/git/db.py", line 43, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/gitpython_hack.py", line 18, in get_object_header
        ret = subprocess.check_output(
      File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.10/subprocess.py", line 505, in run
        stdout, stderr = process.communicate(input, timeout=timeout)
      File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/lib/python3.10/subprocess.py", line 2022, in _communicate
        self._check_timeout(endtime, orig_timeout, stdout, stderr)
      File "/usr/lib/python3.10/subprocess.py", line 1198, in _check_timeout
        raise TimeoutExpired(
    subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds

**Comment by TheLastBen** [comment]
that's not a critical error, just ignore it
