### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Dropdown'

### ISSUE THREAD

**Issue by tinirusta10** [TheLastBen/fast-stable-diffusion#2294]
when i try to execute the last celd i have this error, what can i do?

**Comment by Azura-13** [comment]
Same ^^

**Comment by ds1straightup** [comment]
yep, was just about to get into some more roop tests and 2nite just like last night it won't start but this time a new error message. the one above. its usually resolved within a few hours though.

**Comment by ds1straightup** [comment]
just found this on another thread they said to install by running it in a code cell before starting Stable Diffusion, if it works i wont be back so I came here to bless the gang 1st lol  

!pip install gradio==3.32 -q

**Comment by profcat2** [comment]
It seems like the new SD commit is like super fragile, here's how I got mine to work:

1) delete old SD folder
2) run new notebook (google drive and all that, I didn't install control net, I'll tell you why in a sec)
3) If you run it now it will work.. but.. it create two big errors (IMO):

3a) If you try to turn off saving every image it won't generate. So you have to delete all the path where it saves it to and it just create some random folder (/temporary) or something. I caches the image to RAM (I guess, I'm dunno) rather than your drive, at least my drive isn't being filled with test images now.

3b) If I even try to add any extensions it gives me the dropdown error, also if I try to shortcut my gdrive lora folder to replace the lora folder in the sd-webui or VAEs or any of that it crashes and gives me the gradio dropdown error. (never did this before). What I had to do is just make copies of loras/vaes, etc.. and then put the copies in the root of the respective folders they go in.

This is my work around just to get the basic functions working  with some lora/vae support and not having to save ever single image. I'm afraid if I add any control net or fancy stuff, it'll give me the gradio dropdown error and I have to start all over from step 1 (I tried adding some extensions and that's what happened). 

Anywho, I "kinda" got it to a reasonable working point, my just scared that sneezing will break the whole thing.  Maybe in the next commit these issues will get resolved

**Comment by ds1straightup** [comment]
bro my solution above works without any problems

> It seems like the new SD commit is like super fragile, here's how I got mine to work:
> 
> 1. delete old SD folder
> 2. run new notebook (google drive and all that, I didn't install control net, I'll tell you why in a sec)
> 3. If you run it now it will work.. but.. it create two big errors (IMO):
> 
> 3a) If you try to turn off saving every image it won't generate. So you have to delete all the path where it saves it to and it just create some random folder (/temporary) or something. I caches the image to RAM (I guess, I'm dunno) rather than your drive, at least my drive isn't being filled with test images now.
> 
> 3b) If I even try to add any extensions it gives me the dropdown error, also if I try to shortcut my gdrive lora folder to replace the lora folder in the sd-webui or VAEs or any of that it crashes and gives me the gradio dropdown error. (never did this before). What I had to do is just make copies of loras/vaes, etc.. and then put the copies in the root of the respective folders they go in.
> 
> This is my work around just to get the basic functions working with some lora/vae support and not having to save ever single image. I'm afraid if I add any control net or fancy stuff, it'll give me the gradio dropdown error and I have to start all over from step 1 (I tried adding some extensions and that's what happened).
> 
> Anywho, I "kinda" got it to a reasonable working point, my just scared that sneezing will break the whole thing. Maybe in the next commit these issues will get resolved

bro my solution above works without any problems

**Comment by sajoukourckan** [comment]
> 
**It happened when I use this solution,do I need any other code operations?**

Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
2023-06-29 05:14:12,874 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 13, in <module>
        from scripts.controlnet_ui import controlnet_ui_group
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 27, in <module>
        class ToolButton(gr.Button, gr.components.FormComponent):
    AttributeError: module 'gradio.components' has no attribute 'FormComponent'

---
2023-06-29 05:14:12,910 - ControlNet - INFO - ControlNet v1.1.227
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 382, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 423, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button, restore_progress_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 311, in create_toprow
    with gr.Row(elem_id=f"{id_part}_tools"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 360, in __exit__
    self.fill_expected_parents()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 340, in fill_expected_parents
    expected_parent = child.get_expected_parent()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_components.py", line 6, in get_expected_parent
    return gr.components.Form
AttributeError: module 'gradio.components' has no attribute 'Form'
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/VAE/pastelMixStylizedAnime_pastelMixPrunedFP16.vae.pt
Applying attention optimization: sdp... done.
Textual inversion embeddings loaded(12): 852style-girl, bad-hands-5, bad-picture-chill-75v, bad_prompt_version2, Da-Mao-Banlangen-76500, EasyNegative, gustavedore, juzhang, negativeembed, sora72iro, style-donadona, verybadimagenegative_v1.2-6400
Textual inversion embeddings skipped(3): badquality, negmutation-200, 21charturnerv2
Model loaded in 30.8s (load weights from disk: 19.3s, create model: 1.5s, apply weights to model: 3.3s, apply half(): 2.2s, load VAE: 2.8s, move model to device: 1.5s, calculate empty prompt: 0.2s).

**Comment by sajoukourckan** [comment]
It happened when used the code !pip install importlib-metadata !pip install gradio==3.35.2 -q,What should I do?Do I need any other code operations?



Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
2023-06-29 05:14:12,874 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 13, in <module>
        from scripts.controlnet_ui import controlnet_ui_group
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 27, in <module>
        class ToolButton(gr.Button, gr.components.FormComponent):
    AttributeError: module 'gradio.components' has no attribute 'FormComponent'

---
2023-06-29 05:14:12,910 - ControlNet - INFO - ControlNet v1.1.227
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 382, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 423, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button, restore_progress_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 311, in create_toprow
    with gr.Row(elem_id=f"{id_part}_tools"):
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 360, in __exit__
    self.fill_expected_parents()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 340, in fill_expected_parents
    expected_parent = child.get_expected_parent()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_components.py", line 6, in get_expected_parent
    return gr.components.Form
AttributeError: module 'gradio.components' has no attribute 'Form'
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/VAE/pastelMixStylizedAnime_pastelMixPrunedFP16.vae.pt
Applying attention optimization: sdp... done.
Textual inversion embeddings loaded(12): 852style-girl, bad-hands-5, bad-picture-chill-75v, bad_prompt_version2, Da-Mao-Banlangen-76500, EasyNegative, gustavedore, juzhang, negativeembed, sora72iro, style-donadona, verybadimagenegative_v1.2-6400
Textual inversion embeddings skipped(3): badquality, negmutation-200, 21charturnerv2
Model loaded in 30.8s (load weights from disk: 19.3s, create model: 1.5s, apply weights to model: 3.3s, apply half(): 2.2s, load VAE: 2.8s, move model to device: 1.5s, calculate empty prompt: 0.2s).
