### ISSUE TITLE
I have error and i can't run

### ISSUE THREAD

**Issue by aarvndhNG** [TheLastBen/fast-stable-diffusion#2296]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [gallery, textbox, textbox, html]
Received outputs:
    [None, "", "<div class='error'>AttributeError: &#x27;NoneType&#x27; object has no attribute &#x27;cond_stage_key&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr>0.02s</p><p class='vram'>Torch active/reserved: 9/20 MiB, <wbr>Sys VRAM: 1341/15102 MiB (8.88%)</p></div>"]

**Comment by aarvndhNG** [comment]
@TheLastBen

**Comment by TheLastBen** [comment]
have you tried different models ?

**Comment by aarvndhNG** [comment]
> have you tried different models ?

Its now fix but i have one issue 😕

**Comment by aarvndhNG** [comment]
Its disconnect everytime when i start rendering

**Comment by aarvndhNG** [comment]
![Screenshot_20230630-155328](https://github.com/TheLastBen/fast-stable-diffusion/assets/107058543/1e7fe0f4-e5b6-4fb6-9fa9-13512cf03fbf)

**Comment by TheLastBen** [comment]
if you're using free colab, it will disconnect you every 5 minutes and you'll have to restart all the cells from the top

**Comment by aarvndhNG** [comment]
😢😢
