### ISSUE TITLE
FileNotFoundError and subprocess.CalledProcessError in dreambooth colab

### ISSUE THREAD

**Issue by loliana232** [TheLastBen/fast-stable-diffusion#2299]
I'm trying to use dreambooth on colab, I use SD 1.5 as a base model and 1024px for resolution,  suddenly I got this error during the training process (I tried many times) 

Traceback (most recent call last): File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 803, in <module> main() File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 665, in main for step, batch in enumerate(train_dataloader): File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 357, in __iter__ next_batch = next(dataloader_iter) File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 633, in __next__ data = self._next_data() File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 677, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp> data = [self.dataset[idx] for idx in possibly_batched_index] File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 356, in __getitem__ instance_image = Image.open(path) File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 2975, in open fp = builtins.open(filename, "rb") FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/TheFuturee/instance_images/owalnfiwp-(495).png' ' Progress:|███████ | 27% 1610/6000 [2:15:28<6:09:25, 5.05s/it, loss=0.00444, lr=1.46e-6] Traceback (most recent call last): File "/usr/local/bin/accelerate", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main args.func(args) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 837, in launch_command simple_launcher(args) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--offset_noise', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/TheFuturee', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/TheFuturee/instance_images', '--output_dir=/content/models/TheFuturee', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/TheFuturee/captions', '--instance_prompt=', '--seed=278227', '--resolution=1024', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=6000']' returned non-zero exit status 1

Note* when I changed the resolution to be 512px for example I didn't get this error, so I need to know what is the problem

**Comment by chepy21** [comment]
@loliana232 hi I wonder if you know what went wrong and how to fix it now. I ran into the same problem but my setting has been 512 px resolution all the time.

**Comment by TheLastBen** [comment]
check your instance images and make sure you have enough drive space

**Comment by MRINFINITE0** [comment]
@TheLastBen @ShashankInteli @chepy21 any solution ?? , I am into same problem I have been using image of 512px, 512 px but same issue please help!!
