### ISSUE TITLE
maybe I clicked on whatsoever but... from a fresh install on paperspace it looks like can not start

### ISSUE THREAD

**Issue by CoqueTornado** [TheLastBen/fast-stable-diffusion#2301]
User = ""

 Password= ""
 
# Add credentials to your Gradio interface (optional).
 
#-----------------

 
configf=sdui(User, Password, model) if 'model' in locals() else sdui(User, Password, "")
 

!python /notebooks/sd/stable-diffusion-webui/webui.py $configf --no-gradio-queue 

2023-06-29 19:40:38,322 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: /notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-06-29 19:40:38,473 - ControlNet - INFO - ControlNet v1.1.227
Calculating sha256 for /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/model.safetensors: Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 390, in webui
    app, local_url, share_url = shared.demo.launch(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1745, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
TypeError: start_server() got an unexpected keyword argument 'app_kwargs'
preload_extensions_git_metadata for 8 extensions took 0.18s
4199bcdd147e11328d5f3560301d5a7ab4ac7eeefbf49dc3eb663cb3e772b9ac
Loading weights [4199bcdd14] from /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/model.safetensors
Creating model from config: /notebooks/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(0): 
Model loaded in 14.8s (calculate hash: 6.7s, load weights from disk: 4.4s, create model: 0.5s, apply weights to model: 2.4s, apply half(): 0.4s, move model to device: 0.3s).
------------

that is all. No link, not anything. Tried to remove the sd folder to sdold and play all. Same thing. 
Tried the force_reinstall= True
Tried to place the --no-gradio-queue  and the --share...  nothing

any idea?

**Comment by TheLastBen** [comment]
try `pip install gradio==3.32` though it is already included in the deps

**Comment by CoqueTornado** [comment]
The error message you provided suggests that there is an issue with the gradio library's components module. Specifically, it indicates that the FormComponent and Form attributes are not found in the gradio.components module.

This error can occur if you are using an outdated version of the gradio library that does not include these attributes. The FormComponent class was introduced in gradio version 2.0.0, and the Form class was introduced in version 2.2.0.

To resolve this issue, you can try upgrading your gradio library to a version that includes these attributes. You can use the following command to upgrade gradio:

css
Copy code
pip install --upgrade gradio
After upgrading, make sure to restart your application to ensure that the updated gradio library is used.

If you're using a specific version of gradio for compatibility reasons or upgrading doesn't resolve the issue, you may need to modify your code or seek assistance from the developers of the application you're running to address the compatibility issue with the specific version of gradio you are using.




[love the future]
already solved doing that stuff!


anyway, thank you for your fast support!!! I will try to not annoy you and help somehow to the community
