### ISSUE TITLE
Getting the issue the port 3001 is in use(on runpod)

### ISSUE THREAD

**Issue by Ninkurk** [TheLastBen/fast-stable-diffusion#2312]
This was the issue. No other program runs on the runpod, just this

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/networking.py", line 121, in start_server
    s.bind((LOCALHOST_NAME, server_port))
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 477, in <module>
    webui()
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 390, in webui
    app, local_url, share_url = shared.demo.launch(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1745, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/usr/local/lib/python3.10/dist-packages/gradio/networking.py", line 124, in start_server
    raise OSError(
OSError: Port 3001 is in use. If a gradio.Blocks is running on the port, you can close() it or gradio.close_all().
preload_extensions_git_metadata for 10 extensions took 0.32s

**Comment by TheLastBen** [comment]
there was a template update, either create a fresh pod or add the port 3001 to the pod
