### ISSUE TITLE
Paper Space wont launch Test the Trained model

### ISSUE THREAD

**Issue by Jituro** [TheLastBen/fast-stable-diffusion#2326]
After a clean install, it seems it won't launch after installing Adetailer, it says,
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from fastapi import FastAPI, Response
  File "/usr/local/lib/python3.9/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/usr/local/lib/python3.9/dist-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.9/dist-packages/pydantic/fields.py)

Any help?

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
try stopping the machine and start it again
