### ISSUE TITLE
Codeformer has disappeared

### ISSUE THREAD

**Issue by SDPDVADER** [TheLastBen/fast-stable-diffusion#2356]
@TheLastBen hey great work still.  Just noticed something that Codeformer is no longer an option for face restoration and the Restore Faces options is completely gone.

**Comment by RebelCat90** [comment]
> @TheLastBen hey great work still. Just noticed something that Codeformer is no longer an option for face restoration and the Restore Faces options is completely gone.
> 
> EDIT Never mind just did a refresh and removed some extensions and working again

Hi, one question then the SD interface already gives you the option to restore face? I have the same problem running SD and not recognizing codeformer. I hope you can help me.

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/131417164/cbe8951f-90d1-4679-8262-7c0dd526c7b0)

**Comment by HaikenEdge** [comment]
> ![image](https://user-images.githubusercontent.com/131417164/254978079-cbe8951f-90d1-4679-8262-7c0dd526c7b0.png)

I've got this going on too.

**Comment by TheLastBen** [comment]
Try the latest notebook

**Comment by KyotoLion** [comment]
Here, the error persists:

"Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/CodeFormer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/BLIP/models/blip.py"

and the 'restore faces' option has disappeared

**Comment by KyotoLion** [comment]
Now these errors keep appearing one after the other:

Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/CodeFormer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/BLIP/models/blip.py
2023-07-20 22:38:44,851 - ControlNet - INFO - ControlNet v1.1.233
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-07-20 22:39:23,209 - ControlNet - INFO - ControlNet v1.1.233
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
*** Failed reading extension data from Git repository (sd-webui-controlnet)
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 63, in do_read_info_from_repo
        commit = repo.head.commit
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 217, in _get_commit
        obj = self._get_object()
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 210, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "/usr/local/lib/python3.10/dist-packages/git/objects/base.py", line 85, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/usr/local/lib/python3.10/dist-packages/git/db.py", line 43, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/gitpython_hack.py", line 18, in get_object_header
        ret = subprocess.check_output(
      File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.10/subprocess.py", line 503, in run
        stdout, stderr = process.communicate(input, timeout=timeout)
      File "/usr/lib/python3.10/subprocess.py", line 1152, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/lib/python3.10/subprocess.py", line 2004, in _communicate
        self._check_timeout(endtime, orig_timeout, stdout, stderr)
      File "/usr/lib/python3.10/subprocess.py", line 1196, in _check_timeout
        raise TimeoutExpired(
    subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds

---

It even generates the Gradio link, but the "restore faces" option no longer appears, and even if it manages to generate an image, it produces an error and no longer works.

To use the updated notebook, wouldn't you just need to click on the link? https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

What can I do?

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
Fixed in the latest notebook

**Comment by KyotoLion** [comment]
It worked, thank you very much! And congratulations on your excellent work @TheLastBen
