### ISSUE TITLE
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by hey12344321** [TheLastBen/fast-stable-diffusion#2357]
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
z
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 35, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1754
    self.server_name = "d.so: object 'libtcmalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
                       ^
SyntaxError: unterminated string literal (detected at line 1754)

**Comment by TheLastBen** [comment]
Use the latest notebook

**Comment by denisbetsi** [comment]
the latest as of Jul 27th has these errors:
/usr/local/lib/python3.10/dist-packages/einops/einops.py:711: DeprecationWarning: invalid escape sequence '\s'
  """
/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/prompt_parser.py:346: DeprecationWarning: invalid escape sequence '\('
  """
/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py:15: DeprecationWarning: invalid escape sequence '\('
  re_hypernet_hash = re.compile("\(([0-9a-f]+)\)$")
/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/models/diffusion/uni_pc/uni_pc.py:15: DeprecationWarning: invalid escape sequence '\h'
  """Create a wrapper class for the forward SDE (VP type).
/usr/local/lib/python3.10/dist-packages/basicsr/metrics/niqe.py:5: DeprecationWarning: Please use `convolve` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import convolve

**Comment by TheLastBen** [comment]
these are not errors, they are deprecation messages, A1111 forgot to hide them
