### ISSUE TITLE
Error on fast dreambooth

### ISSUE THREAD

**Issue by cboRD181** [TheLastBen/fast-stable-diffusion#236]
Edit: Thought I'd already accepted terms for 1.5, apologies.  Issue closed.

I ran the "NEW FAST METHOD" cell, skipped the "Setting Up" and "[Optional]" cells, jumping directly to the "Start Dreambooth" cell, as per my understanding of the directions, but saw this error.  Tried twice.  Images are labeled and uploaded in accordance with directions.  Any help?

"Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 694, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 439, in main
    tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1760, in from_pretrained
    f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "
OSError: Can't load tokenizer for '/content/stable-diffusion-v1-5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/content/stable-diffusion-v1-5' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=500', '--save_n_steps=0', '--train_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/data/safusny', '--output_dir=/content/models/safusny', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=1e-6', '--lr_scheduler=constant', '--center_crop', '--lr_warmup_steps=0', '--max_train_steps=400']' returned non-zero exit status 1.
Something went wrong"

**Comment by TheLastBen** [comment]
you didn't run the download model cell
