### ISSUE TITLE
Conversion error when loading a model from google drive

### ISSUE THREAD

**Issue by WalidAliAlfaid** [TheLastBen/fast-stable-diffusion#2361]
As the title 
tried to download a model from MODEL_PATH i get this error

1.5 Detected
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 128, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1318, in download_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 765, in convert_ldm_clip_checkpoint
    text_model.load_state_dict(text_model_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
	Missing key(s) in state_dict: "text_model.embeddings.position_ids". 
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
[<ipython-input-3-2a3f7204540e>](https://localhost:8080/#) in <cell line: 114>()
    210       while not os.path.exists('/content/stable-diffusion-custom/unet/diffusion_pytorch_model.bin'):
    211         print('Conversion error')
--> 212         time.sleep(5)
    213   else:
    214     while not os.path.exists(str(MODEL_PATH)):

KeyboardInterrupt:

**Comment by TheLastBen** [comment]
try a different model
