### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by KyotoLion** [TheLastBen/fast-stable-diffusion#2365]
Hello!
Using the Colab notebook today, I noticed some errors, but the main one that prevents it from generating the Gradio link is this:

Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 159, in model_hash
ConnectionAbortedError: [Errno 103] Software caused connection abort

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 477, in <module>
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 372, in webui
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 252, in initialize
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 270, in initialize_rest
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 134, in list_models
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 48, in init
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 154, in model_hash
OSError: [Errno 107] Transport endpoint is not connected

I was disconnecting and deleting the runtime, and it would connect normally, but after generating 2 or 3 images, an error would always appear with ^C at the end.

Now it's stuck on "OSError: [Errno 107] Transport endpoint is not connected" and won't connect.

What can be done?

**Comment by TheLastBen** [comment]
try using the latest notebook
