### ISSUE TITLE
How to train dreambooth without class_dir?

### ISSUE THREAD

**Issue by josemerinom** [TheLastBen/fast-stable-diffusion#2375]
I cloned thelastben's diffuser repository to learn how to train on my pc and I followed the steps of cloning, installing req, converting my model to diffuser and creating the list of arguments, but when executing it asks me for "class_dir" "class_prompt", how can I avoid using regularization images and avoid auto-generating images

**Comment by TheLastBen** [comment]
Mâle sure you clone my fork of diffusers

**Comment by josemerinom** [comment]
my steps:
-clone .../TheLastBen/diffusers
-config.yaml 
-requirements.txt
-model
-convert_original
-accelerate config
-launch train_dreambooth.py
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  
when executing the train, it sends me a message: missing --class_data_dir

I know that the huggingface/diffuser asks you for regulation images, but your dreambooth colab does not use images, but when executing your diffuser from my pc it asks me :/

**Comment by TheLastBen** [comment]
you need to reproduce the notebook training cell

**Comment by josemerinom** [comment]
MODEL_NAME="/content/model_diffuser"
INSTANCE_DIR="/content/zjmz"
INSTANCE_PROMPT="zjmz"
OUTPUT_DIR="/content/train"
LOGGING_DIR="/content/logs"
%cd /content/
def train_only_unet(MODEL_NAME, INSTANCE_DIR, INSTANCE_PROMPT, OUTPUT_DIR, LOGGING_DIR):
  !accelerate launch /content/diffusers/examples/dreambooth/train_dreambooth.py \
    --train_only_unet \
    --pretrained_model_name_or_path=$MODEL_NAME \
    --instance_data_dir=$INSTANCE_DIR \
    --instance_prompt=$INSTANCE_PROMPT \
    --with_prior_preservation --prior_loss_weight=1.0 \
    --output_dir=$OUTPUT_DIR \
    --resolution=512 \
    --train_batch_size=1 \
    --sample_batch_size=1 \
    --max_train_steps=1000 \
    --gradient_accumulation_steps=1 --gradient_checkpointing \
    --learning_rate=1e-6 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --use_8bit_adam \
    --logging_dir=$LOGGING_DIR \
    --mixed_precision="fp16" \
    --seed=1234 \
    --save_starting_step=1000 \
    --save_n_steps=1000 
train_only_unet(MODEL_NAME, INSTANCE_DIR, INSTANCE_PROMPT, OUTPUT_DIR, LOGGING_DIR)

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 297, in <module>
    class DreamBoothDataset(Dataset):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 353, in DreamBoothDataset
    def __getitem__(self, index, args=parse_args()):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 290, in parse_args
    raise ValueError("You must specify a data directory for class images.")
ValueError: You must specify a data directory for class images.

**Comment by TheLastBen** [comment]
remove --with_prior_preservation, look at the cell in the notebook and reproduce the same arguments for `accelerate launch`

**Comment by josemerinom** [comment]
I love you (not gay) now if I can train, thank you very much
