### ISSUE TITLE
Stopped working  (traceback) 

### ISSUE THREAD

**Issue by Clicli99** [TheLastBen/fast-stable-diffusion#2379]
Good morning, I’m getting this problem. 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 49, in <module>
    from modules import shared, sd_samplers, upscaler, extensions, localization, ui_tempdir, ui_extra_networks, config_states
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
    from modules import sd_samplers_common, prompt_parser, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
    from modules import devices, processing, images, sd_vae_approx, sd_samplers, sd_vae_taesd
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 16, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 15, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet, sd_models_xl
ImportError: cannot import name 'sd_models_xl' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
rename the current sd folder to sd_old

**Comment by Dinolee1048** [comment]
I just got the same error, can you tell me how to solve it :(

**Comment by SadSAYA** [comment]
renaming the folder name works for me.

**Comment by peofrosteus** [comment]
I had the same problem, so I tried to rename the folder to sd_old. But I got a different error during _Model Download/Load
`Converting to CKPT ...
Traceback (most recent call last):
  File "/content/convertosd.py", line 228, in <module>
    torch.save(state_dict, checkpoint_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion does not exist.

---------------------------------------------------------------------------

UnboundLocalError                         Traceback (most recent call last)

[<ipython-input-5-8a47c1c97465>](https://localhost:8080/#) in <cell line: 148>()
    189 
    190 else:
--> 191    model=inpmdl()

[<ipython-input-5-8a47c1c97465>](https://localhost:8080/#) in inpmdl()
    144       get_ipython().system('rm -r /content/stable-diffusion-inpainting')
    145 
--> 146     return model
    147 
    148 if (Path_to_MODEL !=''):

UnboundLocalError: local variable 'model' referenced before assignment`

Does anyone have a solution, plz?

**Comment by TheLastBen** [comment]
@peofrosteus the model you're using is corrupt

**Comment by peofrosteus** [comment]
@TheLastBen That is very likely. I downloaded fast_stable_diffusion_AUTOMATIC1111.ipynb from Github and then added it to Colab, but the error presists. 

I've chosen Model_Version 1.5 from the drop-down menu, is it this model that is corrupt? If so, do I need to specify my own or something else?

**Comment by peofrosteus** [comment]
I got it working. I just manually specifed the path to another model from civit.ai in that step :-)

**Comment by TheLastBen** [comment]
@larinius use the latest notebook
