### ISSUE TITLE
Lora tab is missing

### ISSUE THREAD

**Issue by BenCMH** [TheLastBen/fast-stable-diffusion#2380]
### The Issue:

As of today I tried to generate some images using my Loras when I found that the Lora tab is missing. I pretty much have the same issue as this person on Reddit, although there's no solution I could find to resolve this issue:

https://www.reddit.com/r/StableDiffusion/comments/12rwf4z/lora_not_showing_in_extra_tab_how_to_fix_it/

I use TheLastBen on a Paperspace Gradient notebook. Has anybody faced a similar issue? Do you have any suggestions how to fix this?

Thanks a lot in advance

### When runing SD I receive the following error messages:

*** Error loading script: evaluate_model.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/Dreambooth-Stable-Diffusion/scripts/evaluate_model.py", line 16, in <module>
        from ldm.data.personalized import PersonalizedBase
    ModuleNotFoundError: No module named 'ldm.data.personalized'

---
*** Error loading script: inpaint.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/Dreambooth-Stable-Diffusion/scripts/inpaint.py", line 7, in <module>
        from main import instantiate_from_config
      File "/notebooks/sd/stable-diffusion-webui/extensions/Dreambooth-Stable-Diffusion/main.py", line 21, in <module>
        from ldm.data.base import Txt2ImgIterableBaseDataset
    ModuleNotFoundError: No module named 'ldm.data.base'

---
2023-07-25 10:01:54,068 - ControlNet - INFO - ControlNet v1.1.233
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body.py:5: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/hand.py:6: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
ControlNet preprocessor location: /notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(version("gradio")) < LooseVersion("3.10"):
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(version("gradio")) < LooseVersion("3.10"):
2023-07-25 10:01:54,267 - ControlNet - INFO - ControlNet v1.1.233
*** Error loading script: lora_script.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 7, in <module>
        import network
      File "/notebooks/sd/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 101, in <module>
        class ModuleType:
      File "/notebooks/sd/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 102, in ModuleType
        def create_module(self, net: Network, weights: NetworkWeights) -> Network | None:
    TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by BenCMH** [comment]
Okay, I just opened the latest notebooks folder and run SD there. It resolved my issue!
