### ISSUE TITLE
error at paperspace

### ISSUE THREAD

**Issue by juone06** [TheLastBen/fast-stable-diffusion#2389]
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu116. You might want to consider upgrading.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /notebooks/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
2023-07-26 04:07:06,160 - ControlNet - INFO - ControlNet v1.1.233
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body.py:5: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/hand.py:6: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
ControlNet preprocessor location: /notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(version("gradio")) < LooseVersion("3.10"):
/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(version("gradio")) < LooseVersion("3.10"):
2023-07-26 04:07:06,505 - ControlNet - INFO - ControlNet v1.1.233
Civitai: API loaded
Loading weights [18ed2b6c48] from /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/xxmix9realistic_v40.safetensors
Creating model from config: /notebooks/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/notebooks/sd/stable-diffusion-webui/modules/ui_extensions.py", line 517, in preload_extensions_git_metadata
    extension.read_info_from_repo()
  File "/notebooks/sd/stable-diffusion-webui/modules/extensions.py", line 60, in read_info_from_repo
    d = cache.cached_data_for_file('extensions-git', self.name, os.path.join(self.path, ".git"), read_from_repo)
  File "/notebooks/sd/stable-diffusion-webui/modules/cache.py", line 102, in cached_data_for_file
    ondisk_mtime = os.path.getmtime(filename)
  File "/usr/lib/python3.9/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/notebooks/sd/stable-diffusion-webui/extensions/.ipynb_checkpoints/.git'
Running on local URL: https://tensorboard-nzayar41ts.clg07azjl.paperspacegradient.com/
✔ Connected

**Comment by TheLastBen** [comment]
They are just deprecation warnings
