### ISSUE TITLE
KeyError: "Stable Diffusion XL"

### ISSUE THREAD

**Issue by mmehrle** [TheLastBen/fast-stable-diffusion#2391]
This started happening today - on every single model I tried:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 61, in <module>
    from modules import shared, sd_samplers, upscaler, extensions, localization, ui_tempdir, ui_extra_networks, config_states
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
    from modules import sd_samplers_common, prompt_parser, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
    from modules import devices, processing, images, sd_vae_approx, sd_samplers, sd_vae_taesd
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 16, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 16, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint, errors, hashes
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet, sd_models_xl
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models_config.py", line 9, in <module>
    sd_xl_repo_configs_path = os.path.join(paths.paths['Stable Diffusion XL'], "configs", "inference")
KeyError: 'Stable Diffusion XL'
```

**Comment by YANSANSEI** [comment]
Same error
i dont want XL

**Comment by mmehrle** [comment]
It's the new 

> Same error i dont want XL

Glad to see I'm not alone! I haven't made any changes to my script and it was working fine two days ago. Clearly an compatibility issue after Automatic1111 pushed v1.5.0 with SD XL support. It's probably not in the fast-stable-diffusion build.

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by polax007** [comment]
**https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb**
the last one is this one?

is that one support SD XL. can t see XL model on model version (1.5 to 2.1)

thanks

**Comment by TheLastBen** [comment]
use the model link for now, will add sdxl shortly

**Comment by MaxTran96** [comment]
Does that mean you will add support for SDXL lora training on colab notebook :D

**Comment by TheLastBen** [comment]
@MaxTran96 only for inference in the A1111 notebook, for training, you'll need to use RunPod or Paperspace

**Comment by TheLastBen** [comment]
yes

**Comment by mmehrle** [comment]
With the new notebook I am still having an issue when attempting to load a different model:

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/8457499/f7144c7d-3928-4aab-8027-d6cdf527cadd)

**Comment by TheLastBen** [comment]
@mmehrle put it in "MODEL_LINK" not PATH

**Comment by mmehrle** [comment]
> @mmehrle put it in "MODEL_LINK" not PATH

YES - I figured that out eventually :-)

**Comment by phephanhoang** [comment]
same, error and stop working on Colab when load SDXL1.0 model

**Comment by TheLastBen** [comment]
@phephanhoang if you're using colab pro, set the runtime to high-RAM

**Comment by phephanhoang** [comment]
> @phephanhoang if you're using colab pro, set the runtime to high-RAM
![errro](https://github.com/TheLastBen/fast-stable-diffusion/assets/5759330/1569666f-ec65-45ee-97ed-fd34804d86a7)
Still failed to load

**Comment by phephanhoang** [comment]
> 

I load SDXL very fast and use it normally on other custom builds but I still prefer to use Fast-SD but this error makes me so tired

**Comment by TheLastBen** [comment]
@phephanhoang did you changer any launching argument ? like adding --no-half ?

**Comment by phephanhoang** [comment]
> @phephanhoang did you change any launching argument ? like adding --no-half ?

No I didn't change anything
I tried to re-install anything but It still doesn't work

**Comment by TheLastBen** [comment]
remove the model and redownload it through the models cell, choose SDXL from the dropdown and run the cell

**Comment by phephanhoang** [comment]
> remove the model and redownload it through the models cell, choose SDXL from the dropdown and run the cell

![sd-erro](https://github.com/TheLastBen/fast-stable-diffusion/assets/5759330/c94dfafe-a193-4804-a74d-1413bba6bdee)

still

**Comment by TheLastBen** [comment]
you're using 12GB of RAM, change your runtime to "High-RAM"

**Comment by TheLastBen** [comment]
even in colab pro, you need to set it manually to high RAM

**Comment by phephanhoang** [comment]
> even in colab pro, you need to set it manually to high RAM

as default I always set it to High-RAM. Tried with 3 type of GPUs but still not working

**Comment by TheLastBen** [comment]
to make sure it's not some extension you installed, try running the notebooks without the first cell

**Comment by YANSANSEI** [comment]
ARIGATO😍

**Comment by darkzbaron** [comment]
I took the latest path.py to solve the issue

**Comment by mmehrle** [comment]
> > even in colab pro, you need to set it manually to high RAM
> 
> as default I always set it to High-RAM. Tried with 3 type of GPUs but still not working

That's weird - I always seem to be doing fine with a regular colab VPS. Never worked for me with TTS but with SD it's fine, go figure...
