### ISSUE TITLE
Error When Attempt to Generate And At Start Up.

### ISSUE THREAD

**Issue by The-Shadowmind** [TheLastBen/fast-stable-diffusion#2392]
Traceback (most recent call last):
      File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 673, in process_images
        res = process_images_inner(p)
      File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 793, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 1043, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 464, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 303, in launch_sampling
        return func()
      File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 464, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/workspace/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 202, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "/workspace/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/workspace/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/workspace/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 1329, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/modules/sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "/workspace/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 776, in forward
        h = module(h, emb, context)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 23, in mm_tes_forward
        x = layer(x, context)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stablediffusion/ldm/modules/attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stablediffusion/ldm/modules/attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "/workspace/sd/stablediffusion/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "/workspace/sd/stablediffusion/ldm/modules/diffusionmodules/util.py", line 129, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "/workspace/sd/stablediffusion/ldm/modules/attention.py", line 272, in _forward
        x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 534, in scaled_dot_product_attention_forward
        hidden_states = self.to_out[0](hidden_states)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/workspace/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 354, in network_Linear_forward
        network_apply_weights(self)
      File "/workspace/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 273, in network_apply_weights
        weights_backup = self.weight.to(devices.cpu, copy=True)
    RuntimeError: CUDA error: an illegal memory access was encountered
    CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
    For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
    
    
    Using Runpod template.

**Comment by TheLastBen** [comment]
have tried a different pod ?

**Comment by The-Shadowmind** [comment]
The error persisted through multiple pods.
Last night, tried two different pods, error occurred on both. This morning error didn't appear. This afternoon, error reappeared. 
Trying third pod. Error has not yet appeared. Trying each of my extensions, and loras one by one see if anything triggered it.

**Comment by TheLastBen** [comment]
it's related to the hardware assigned to the pod
