### ISSUE TITLE
Getting Error on the new DB Colab

### ISSUE THREAD

**Issue by Crimsonfart** [TheLastBen/fast-stable-diffusion#240]
Why am I getting this error? I've tried it twice already. Could you help me? THANKS
EDIT: Works now. Got a A100 befor (Premium GPU) 

2022-10-25 21:01:16.214741: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Steps:   1% 6/600 [00:14<14:19,  1.45s/it, loss=0.303, lr=1e-6] basilll  Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 694, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 629, in main
    accelerator.backward(loss)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/accelerator.py", line 884, in backward
    loss.backward(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Steps:   1% 6/600 [00:15<26:12,  2.65s/it, loss=0.303, lr=1e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=500', '--save_n_steps=0', '--train_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/data/testbasilllniquieee', '--output_dir=/content/models/testbasilllniquieee', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=1e-6', '--lr_scheduler=constant', '--center_crop', '--lr_warmup_steps=0', '--max_train_steps=600']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
it happens on A100 GPUs, I will fix it soon, in the meantime try getting a different colab GPU

**Comment by Crimsonfart** [comment]
Jep, works now.. Thanks for the hard Work!

**Comment by jvkap** [comment]
@Crimsonfart Close the issue, please.
