### ISSUE TITLE
A frequent error (runpod)

### ISSUE THREAD

**Issue by qazaqazaq** [TheLastBen/fast-stable-diffusion#2408]
Hello. After several correct generations I always get smth like this, and then there is no chance to continue without restarting of SD:
```
Task exception was never retrieved
future: <Task finished name='ex4lk9z704l_305' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```

Config:
1 x RTX A4000
6 vCPU 24 GB RAM
20 GB Disk
50 GB Pod Volume

**Comment by TheLastBen** [comment]
try adding the argument `--no-gradio-queue`

**Comment by qazaqazaq** [comment]
> try adding the argument `--no-gradio-queue`

Thank you for the answer! To the last section? I have no any coder experience.

**Comment by TheLastBen** [comment]
in the last cell, right after `$fconfig`

**Comment by qazaqazaq** [comment]
I've got the next message right after start or generation:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 25, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 25, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 287, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 517, in join_queue
    if blocks._queue.server_path is None:
AttributeError: 'Blocks' object has no attribute '_queue'
```

**Comment by TheLastBen** [comment]
use the latest A1111 notebook, you'll find it inside the folder `latest_notebooks`

**Comment by qazaqazaq** [comment]
The same thing again, now with --no-gradio-queue argument in the latest A1111 notebook from latest_notebooks.

```
✔ Connected
Startup time: 6.1s (import torch: 2.4s, import gradio: 0.9s, setup paths: 0.9s, other imports: 0.3s, load scripts: 0.7s, create ui: 0.3s, gradio launch: 0.3s, add APIs: 0.1s).
DiffusionWrapper has 859.52 M params.
Applying attention optimization: sdp... done.
Model loaded in 3.8s (load weights from disk: 0.6s, create model: 0.6s, apply weights to model: 0.8s, apply half(): 0.9s, move model to device: 0.9s).
Task exception was never retrieved
future: <Task finished name='7wf45pwaupn_305' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.10/dist-packages/gradio/queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```

**Comment by TheLastBen** [comment]
try updating controlnet extension and does the error prevent the generation ?

**Comment by qazaqazaq** [comment]
> does the error prevent the generation ?
Yes, 'cause I can't get any result today. Could it be because of a 'bad' config or unstable connection?

> try updating controlnet extension
Oh, I thought it's up to day in your adaptations. But I'm not particularly in tech theme in this case.
