### ISSUE TITLE
fast-DreamBooth

### ISSUE THREAD

**Issue by lgrkvst** [TheLastBen/fast-stable-diffusion#243]
Hi, I did a classical training (Dreambooth with class images – _not_ the new Fast Method) and tripped on __ Test the trained model__:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 171, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 132, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call) 
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1241, in create_ui
    new_hypernetwork_activation_func = gr.Dropdown(value="relu", label="Select activation function of hypernetwork", choices=modules.hypernetworks.ui.keys)
AttributeError: module 'modules.hypernetworks.ui' has no attribute 'keys'
```

**Comment by TheLastBen** [comment]
check the box "update repo"

**Comment by lgrkvst** [comment]
Upon closer inspection the real failure was that git failed to fetch/merge, since there were local changes in modules/paths.py, ui.py and webui.py. (Oddest thing as I never touched files in the repo "manually", so something in the colab or the repo code itself has rewritten those files at some point.)
