### ISSUE TITLE
ControlNet will not load - ModuleNotFoundError: No module named 'mmengine' (Colab)

### ISSUE THREAD

**Issue by 413-xx** [TheLastBen/fast-stable-diffusion#2433]
As of about an hour ago, I started getting the following error on startup:

`*** Error loading script: api.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 11, in <module>
        from scripts import external_code, global_state
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
        from scripts import external_code
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 13, in <module>
        from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version, utils
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
2023-08-04 23:26:02,053 - ControlNet - INFO - ControlNet v1.1.237
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: global_state.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: processor.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'
`

The webui will eventually start anyway, but without ControlNet (ControlNet completely missing from the interface).

Things I have tried so far:

- Switching to the latest version of the notebook.
- Deleting MyDrive/sd folder and starting with a fresh install.

Neither has solved the problem. Any guidance would be greatly appreciated.

**Comment by unexpectedly** [comment]
Same, re: ControlNet with some other scripts throwing the error as well: **"ModuleNotFoundError: No module named 'mmengine'"**

**Comment by RONNYKHALIL** [comment]
+1

**Comment by SiuLeeBoss** [comment]
+1

**Comment by jimlin1668478052** [comment]
+1

**Comment by TheLastBen** [comment]
will fix shortly

**Comment by RONNYKHALIL** [comment]
its resolved on my end now, as of like 30 min ago

**Comment by TheLastBen** [comment]
I guess they removed the requirement https://github.com/Mikubill/sd-webui-controlnet/commit/56c376a1777c7f8f53da651aa2c11d784d94366d
