### ISSUE TITLE
Error Training Embedding

### ISSUE THREAD

**Issue by ZER01D** [TheLastBen/fast-stable-diffusion#2439]
I'm having issues in training the face, i did tried most of the settings found on youtube, but then the same problem exist even if i tried  to have just a simpler settings. 

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.1

> Model loaded in 5.5s (load weights from disk: 3.1s, create model: 0.4s, apply weights to model: 0.6s, move model to device: 1.3s).
> Calculating sha256 for E:\Stable Diffusion\Git\Automatic1111\stable-diffusion-webui\embeddings\amy.pt: 4ad835908fe07896b80f95533f99965b8e700c60c8b97a28b3f60f9edf892689
> Training at rate of 0.005 until step 1000
> Preparing dataset...
> 100%|██████████████████████████████████████████| 40/40 [00:02<00:00, 18.72it/s]
> Training textual inversion [Epoch 2: 9/20] loss: 0.3831114:   5%| | 48/1000 [00*** Error training embedding
>     Traceback (most recent call last):
>       File "E:\Stable Diffusion\Git\Automatic1111\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 557, in train_embedding
>         save_embedding(embedding, optimizer, checkpoint, embedding_name_every, last_saved_file, remove_cached_checksum=True)
>       File "E:\Stable Diffusion\Git\Automatic1111\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 677, in save_embedding
>         embedding.save(filename)
>       File "E:\Stable Diffusion\Git\Automatic1111\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 65, in save
>         torch.save(embedding_data, filename)
>       File "E:\Stable Diffusion\Git\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 440, in save
>         with _open_zipfile_writer(f) as opened_zipfile:
>       File "E:\Stable Diffusion\Git\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
>         return container(name_or_buffer)
>       File "E:\Stable Diffusion\Git\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 288, in __init__
>         super().__init__(torch._C.PyTorchFileWriter(str(name)))
>     RuntimeError: Parent directory E:\Stable Diffusion\face\Amy\
> ![train](https://github.com/TheLastBen/fast-stable-diffusion/assets/11874060/cc1cdff9-a680-4e42-a982-a6609778907f)
> 2023-08-06\amy\embeddings does not exist.

I've added a screenshot as well.

Please shared some light on this.

**Comment by TheLastBen** [comment]
open the issue in this repo https://github.com/AUTOMATIC1111/stable-diffusion-webui
