### ISSUE TITLE
Colab - error installing extension

### ISSUE THREAD

**Issue by sujancok23** [TheLastBen/fast-stable-diffusion#2443]
I have an issue after installing this extension.
https://github.com/glucauze/sd-webui-faceswaplab
Tried to update and reinstall, but still same problem.

** Error loading script: faceswaplab.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab/scripts/faceswaplab.py", line 9, in <module>
        from scripts.faceswaplab_api import faceswaplab_api
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab/scripts/faceswaplab_api/faceswaplab_api.py", line 12, in <module>
        from scripts.faceswaplab_swapping import swapper
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab/scripts/faceswaplab_swapping/swapper.py", line 31, in <module>
        from scripts.faceswaplab_ui.faceswaplab_unit_settings import FaceSwapUnitSettings
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab/scripts/faceswaplab_ui/faceswaplab_unit_settings.py", line 12, in <module>
        from scripts.faceswaplab_utils import face_checkpoints_utils
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab/scripts/faceswaplab_utils/face_checkpoints_utils.py", line 17, in <module>
        import dill as pickle  # will be removed in future versions
    ModuleNotFoundError: No module named 'dill'

**Comment by TheLastBen** [comment]
in a new cell, run `!pip install dill`

**Comment by creativebusinez** [comment]
> in a new cell, run `!pip install dill`

Hello, thank you for such a great jupyter notebook. Quick question, I'm also having problems with some of the extensions not finding the needed modules. I'm rather new to Google colab, just wanted to know if the commads need to be run on a new cell or can it also be done through the terminal? Your input would be greatly appreciated. Thanks
