### ISSUE TITLE
Unable to run "Start Stable-Diffusion" step successfully cache.py/json error that doesnt make sense

### ISSUE THREAD

**Issue by O-J1** [TheLastBen/fast-stable-diffusion#2457]
Expected: SD web gui starts and I get a link

Actual: `Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/cache.py", line 66, in cache
    cache_data = json.load(file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 482, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 383, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 264, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 282, in initialize_rest
    modules.sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 127, in list_models
    checkpoint_info = CheckpointInfo(cmd_ckpt)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 51, in __init__
    self.sha256 = hashes.sha256_from_cache(self.filename, f"checkpoint/{name}")
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hashes.py", line 23, in sha256_from_cache
    hashes = cache("hashes-addnet") if use_addnet_hash else cache("hashes")
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/cache.py", line 68, in cache
    os.replace(cache_filename, os.path.join(script_path, "tmp", "cache.json"))
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/cache.json' -> '/content/gdrive/MyDrive/sd/stable-diffusion-webui/tmp/cache.json'`

Ive tried new runtimes, deleting the cache.py after this started occuring to no avail. There is enough space in my Gdrive and I have enough credits on colab

**Comment by O-J1** [comment]
Closing as looks like the maintainer has enough on their plate. Using alternate
