### ISSUE TITLE
Stable diffusion Web-UI" cannot be started after launching "https://github.com/TheLastBen/fast-stable-diffusion" on "Google Colabo".

### ISSUE THREAD

**Issue by Kaka3279** [TheLastBen/fast-stable-diffusion#2478]
I am using "Google Colabo" but "https://github.com/TheLastBen/fast-stable-diffusion" has been updated and when I run the "Start Stable-Diffusion" part, I get the following message when I start it and "Stable diffusion Web-UI" cannot be started.

"Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in
from fastapi import FastAPI
File "/usr/local/lib/python3.10/dist-packages/fastapi/init.py", line 7, in
from .applications import FastAPI as FastAPI
File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 15, in
from fastapi import routing
File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 21, in
from fastapi import params
File "/usr/local/lib/python3.10/dist-packages/fastapi/params.py", line 4, in
from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.10/dist-packages/pydantic/fields.py)"

Please let me know what to do.

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by Kaka3279** [comment]
Then all extensions you have installed so far will disappear.
Can I still use the latest notebook with the extensions I have installed?

**Comment by TheLastBen** [comment]
everything will stay the same if you update the notebook

**Comment by minggnim56** [comment]
Where/how do I update the notebook?

**Comment by TheLastBen** [comment]
by using the direct link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
