### ISSUE TITLE
Got this error today trying to run paperspace.

### ISSUE THREAD

**Issue by Nojarosann** [TheLastBen/fast-stable-diffusion#2489]
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [9], line 6
      4 import sys
      5 import fileinput
----> 6 from pyngrok import ngrok, conf
      7 import re
     10 Use_Cloudflare_Tunnel = False #@param {type:"boolean"}

ModuleNotFoundError: No module named 'pyngrok'

Just as an extra piece of info that i don't know if it matters or not but i have removed the very first cell that connects to google drive because i presumed it would use the VM's storage instead. What happened here?

**Comment by TheLastBen** [comment]
I made notebooks specifically for Paperspace, you can access them through here https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU

or create a new paperspace notebook, in advanced settings, use this as the starting repo : https://console.paperspace.com/github/TheLastBen/PPS

**Comment by Nojarosann** [comment]
I rant it and it gave me this error at the end.

*** Failed reading extension data from Git repository (sd-webui-controlnet)
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/extensions.py", line 79, in do_read_info_from_repo
        commit = repo.head.commit
      File "/usr/local/lib/python3.9/dist-packages/git/refs/symbolic.py", line 217, in _get_commit
        obj = self._get_object()
      File "/usr/local/lib/python3.9/dist-packages/git/refs/symbolic.py", line 210, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "/usr/local/lib/python3.9/dist-packages/git/objects/base.py", line 85, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/usr/local/lib/python3.9/dist-packages/git/db.py", line 43, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "/notebooks/sd/stable-diffusion-webui/modules/gitpython_hack.py", line 18, in get_object_header
        ret = subprocess.check_output(
      File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.9/subprocess.py", line 507, in run
        stdout, stderr = process.communicate(input, timeout=timeout)
      File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/lib/python3.9/subprocess.py", line 1980, in _communicate
        self._check_timeout(endtime, orig_timeout, stdout, stderr)
      File "/usr/lib/python3.9/subprocess.py", line 1178, in _check_timeout
        raise TimeoutExpired(
    subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds

---

**Comment by Nojarosann** [comment]
It Gave me this error and there's nothing happening when i click on generate using the local URL that it generated

*** Failed reading extension data from Git repository (sd-webui-controlnet)
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/extensions.py", line 79, in do_read_info_from_repo
        commit = repo.head.commit
      File "/usr/local/lib/python3.9/dist-packages/git/refs/symbolic.py", line 217, in _get_commit
        obj = self._get_object()
      File "/usr/local/lib/python3.9/dist-packages/git/refs/symbolic.py", line 210, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "/usr/local/lib/python3.9/dist-packages/git/objects/base.py", line 85, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/usr/local/lib/python3.9/dist-packages/git/db.py", line 43, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "/notebooks/sd/stable-diffusion-webui/modules/gitpython_hack.py", line 18, in get_object_header
        ret = subprocess.check_output(
      File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.9/subprocess.py", line 507, in run
        stdout, stderr = process.communicate(input, timeout=timeout)
      File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/lib/python3.9/subprocess.py", line 1980, in _communicate
        self._check_timeout(endtime, orig_timeout, stdout, stderr)
      File "/usr/lib/python3.9/subprocess.py", line 1178, in _check_timeout
        raise TimeoutExpired(
    subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds

**Comment by TheLastBen** [comment]
can you post a screenshot of the notebook cell ?

**Comment by Nojarosann** [comment]
![Screenshot_33](https://github.com/TheLastBen/fast-stable-diffusion/assets/100730490/3ed7673d-55a2-4168-9695-4fe0d683598f)
here. sorry it took long to reply

**Comment by Nojarosann** [comment]
now the message isn't showing but it still doesn't generate anything

**Comment by TheLastBen** [comment]
the cell is running fine
make sure your lora filename doesn't have spaces or special characters

**Comment by Nojarosann** [comment]
but nothing is being generated. I haven't even added any Lora or custom ckpt yet. Even with the built in models it generates nothing when i execute it

I'll try again just to be sure

**Comment by Nojarosann** [comment]
same issue

**Comment by TheLastBen** [comment]
have you tried a stronger GPU ?

**Comment by Nojarosann** [comment]
yea. though it still doesn't max out. i've tried with 8 GB and 16 GB. Same thing

**Comment by Nojarosann** [comment]
i tried to run again but instead of creating the notebook using the pytorch runtime on the top i tried the "start from scratch" and the "stable diffusion" ones(stil posting the repository's link) and all of them had teh same result. The GPU usage is still at 0%. Is it a problem on Paperspace's end then?

**Comment by TheLastBen** [comment]
what GPU are you using ?

**Comment by Nojarosann** [comment]
On Paperspace it says P5000 but i've also used the RTX4000

**Comment by TheLastBen** [comment]
Have tried v1.5 model ?

**Comment by Nojarosann** [comment]
on the model sepection on the top left there appears a 1.5 model but i can't select it. I talked about that before. it just loads infinitely too

**Comment by TheLastBen** [comment]
in the model cell, choose v1.5 before starting the webui

**Comment by Nojarosann** [comment]
it worked. thanks
