### ISSUE TITLE
Hypernetwork error on colab

### ISSUE THREAD

**Issue by alpkabac** [TheLastBen/fast-stable-diffusion#249]
I keep getting this error on Automatic1111 colab. My repo is up-to-date.
```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 171, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 132, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call) 
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1241, in create_ui
    new_hypernetwork_activation_func = gr.Dropdown(value="relu", label="Select activation function of hypernetwork", choices=modules.hypernetworks.ui.keys)
AttributeError: module 'modules.hypernetworks.ui' has no attribute 'keys'
```

**Comment by TheLastBen** [comment]
I got this error but when I checked the box "update_repo" it was fixed,
make sure you're using the latest colab from the repo
if the problem persists, remove the folder sd and try a clean run

**Comment by alpkabac** [comment]
Removing the folder solved it. Thanks.
