### ISSUE TITLE
LoRA error

### ISSUE THREAD

**Issue by mkmk0909** [TheLastBen/fast-stable-diffusion#2490]
When I add LoRA to the prompt, it displays "something went wrong" as shown in the figure. I stored Lora directly on the SD, but is this not usable?

![スクリーンショット 2023-08-17 220706](https://github.com/TheLastBen/fast-stable-diffusion/assets/141246215/f9166a21-2121-4033-8cd4-9760bc71a710)

**Comment by TheLastBen** [comment]
check the notebook cell output to see the origin of the issue

**Comment by mkmk0909** [comment]
I'm getting the following error

✔ Connected
Startup time: 129.7s (import torch: 12.4s, import gradio: 2.4s, start: 3.9s, setup paths: 11.6s, import ldm: 0.5s, other imports: 24.4s, setup codeformer: 4.8s, list SD models: 1.0s, load scripts: 10.0s, load upscalers: 0.7s, initialize extra networks: 11.0s, scripts before_ui_callback: 0.7s, create ui: 39.8s, gradio launch: 4.7s, add APIs: 1.7s).
Loading weights [bc2f30f4ad] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/beautifulRealistic_v60.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying attention optimization: xformers... done.
Model loaded in 44.3s (create model: 4.8s, apply weights to model: 30.7s, apply half(): 5.9s, apply dtype to VAE: 0.2s, load VAE: 0.1s, move model to device: 1.4s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.7s).
100% 20/20 [00:15<00:00,  1.27it/s]
Applying attention optimization: xformers... done.
Model loaded in 189.7s (load weights from disk: 51.5s, find config: 65.9s, create model: 0.3s, apply weights to model: 59.0s, apply half(): 8.7s, move model to device: 3.2s, calculate empty prompt: 0.9s).
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/JapaneseDollLikeness_v15.safetensors: 50b3f6a2ecf7a6333cc99bb7f33d3523feaba6cf525fbee3b333e7ea72c63141
*** Error completing request
*** Arguments: ('task(g3u45sw0ugmrdmq)', '(8k, best quality, masterpiece, ultra high res, highly detail face:1.3), portrait, (20 years old girl:1.3), beautiful, kawaii, dark hair, clothes, from front,Inside the room <lora:JapaneseDollLikeness_v15:1>', ' (worst quality:2),(low quality:2),(normal quality:2)\n', [], 20, 16, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x7ac6ce18f400>, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 783, in process_images_inner
        p.setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1191, in setup_conds
        super().setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 364, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, self.steps * self.step_multiplier, [self.cached_uc], self.extra_network_data)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 353, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/prompt_parser.py", line 163, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 669, in get_learned_conditioning
        c = self.cond_stage_model(c)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 234, in forward
        z = self.process_tokens(tokens, multipliers)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 271, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_open_clip.py", line 28, in encode_with_transformers
        z = self.wrapped.encode_with_transformer(tokens)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 177, in encode_with_transformer
        x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 189, in text_transformer_forward
        x = r(x, attn_mask=attn_mask)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/open_clip/transformer.py", line 242, in forward
        x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
      File "/usr/local/lib/python3.10/dist-packages/open_clip/transformer.py", line 228, in attention
        return self.attn(
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 386, in network_MultiheadAttention_forward
        network_apply_weights(self)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 311, in network_apply_weights
        self.in_proj_weight += updown_qkv
    RuntimeError: The size of tensor a (1024) must match the size of tensor b (768) at non-singleton dimension 1

---
*** Error completing request
*** Arguments: ('task(vn34yxj42l0dxos)', '(8k, best quality, masterpiece, ultra high res, highly detail face:1.3), portrait, (20 years old girl:1.3), beautiful, kawaii, dark hair, clothes, from front,Inside the room <lora:JapaneseDollLikeness_v15:07>', ' (worst quality:2),(low quality:2),(normal quality:2)\n', [], 20, 16, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x7ac6d0fc9390>, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 783, in process_images_inner
        p.setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1191, in setup_conds
        super().setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 364, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, self.steps * self.step_multiplier, [self.cached_uc], self.extra_network_data)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 353, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/prompt_parser.py", line 163, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 669, in get_learned_conditioning
        c = self.cond_stage_model(c)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 234, in forward
        z = self.process_tokens(tokens, multipliers)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 271, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_open_clip.py", line 28, in encode_with_transformers
        z = self.wrapped.encode_with_transformer(tokens)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 177, in encode_with_transformer
        x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 189, in text_transformer_forward
        x = r(x, attn_mask=attn_mask)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/open_clip/transformer.py", line 242, in forward
        x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
      File "/usr/local/lib/python3.10/dist-packages/open_clip/transformer.py", line 228, in attention
        return self.attn(
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 386, in network_MultiheadAttention_forward
        network_apply_weights(self)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 311, in network_apply_weights
        self.in_proj_weight += updown_qkv
    RuntimeError: The size of tensor a (1024) must match the size of tensor b (768) at non-singleton dimension 1

---
*** Error completing request
*** Arguments: ('task(2xc566yc7crdyo6)', '(8k, best quality, masterpiece, ultra high res, highly detail face:1.3), portrait, (20 years old girl:1.3), beautiful, kawaii, dark hair, clothes, from front,Inside the room <lora:JapaneseDollLikeness_v15:07>', ' (worst quality:2),(low quality:2),(normal quality:2)\n', [], 20, 16, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], <gradio.routes.Request object at 0x7ac6ce2dfa90>, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 783, in process_images_inner
        p.setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1191, in setup_conds
        super().setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 364, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, self.steps * self.step_multiplier, [self.cached_uc], self.extra_network_data)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 353, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/prompt_parser.py", line 163, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 669, in get_learned_conditioning
        c = self.cond_stage_model(c)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 234, in forward
        z = self.process_tokens(tokens, multipliers)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 271, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_open_clip.py", line 28, in encode_with_transformers
        z = self.wrapped.encode_with_transformer(tokens)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 177, in encode_with_transformer
        x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
      File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/encoders/modules.py", line 189, in text_transformer_forward
        x = r(x, attn_mask=attn_mask)
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/usr/local/lib/python3.10/dist-packages/open_clip/transformer.py", line 242, in forward
        x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
      File "/usr/local/lib/python3.10/dist-packages/open_clip/transformer.py", line 228, in attention
        return self.attn(
      File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 386, in network_MultiheadAttention_forward
        network_apply_weights(self)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 311, in network_apply_weights
        self.in_proj_weight += updown_qkv
    RuntimeError: The size of tensor a (1024) must match the size of tensor b (768) at non-singleton dimension 1

---

**Comment by TheLastBen** [comment]
the lora version doesn't match the model
