### ISSUE TITLE
Extract Lora not working again

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2492]
I know it's not your notebook, but you have helped me before with this.  I have used the notebook at https://colab.research.google.com/github/panguin6010/kohya_ss_google_colab/blob/master/kohya_ss_colab.ipynb?pli=1#scrollTo=IzS3hvuTtTqW many times but that has stopped working.  Now there is an updated notebook at https://colab.research.google.com/github/camenduru/kohya_ss-colab/blob/main/kohya_ss_colab.ipynb 
I set it to high ram and A100 GPU on colab.  Below is my inputs and then the error message I am getting.  Any idea how to fix?  Your help is always greatly appreciated.
![Inputs](https://github.com/TheLastBen/fast-stable-diffusion/assets/105756477/84a88fb8-c3e7-455b-901a-f27949425792)
![output](https://github.com/TheLastBen/fast-stable-diffusion/assets/105756477/29df769b-02d7-4287-8752-f044b2e1b78a)

**Comment by TheLastBen** [comment]
that's very likely an issue with the GUI, you can get help here https://github.com/bmaltais/kohya_ss/issues

**Comment by mdlieber99** [comment]
I'm not sure what to do about that.  Can you say more?  I don't see what is helpful on that issues page.

**Comment by mdlieber99** [comment]
When I go to the original repo and run it I still get this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "/content/kohya_ss/library/extract_lora_gui.py", line 44, in extract_lora
    msgbox('The provided finetuned model is not a file')
  File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/usr/local/lib/python3.10/dist-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
