### ISSUE TITLE
Paperspace - Dreambooth v1 - Javascript Error

### ISSUE THREAD

**Issue by kruttik-lab49** [TheLastBen/fast-stable-diffusion#2500]
I am using the `PPS-Dreambooth-v1.ipynb` on paperspace. When I run the `Instance Images` cell, I get a javascript error

```shell
[Open Browser Console for more detailed log - Double click to close this message]
Model class 'OutputModel' from module '@jupyter-widgets/output' is loaded but can not be instantiated
TypeError: Cannot read properties of undefined (reading 'sessionContext')
    at u.initialize (https://console.paperspace.com/ide/vendors-f64a56cf.e861fbade6f97e3a158d.js:2:159546)
    at new e.Model (https://console.paperspace.com/ide/vendors-c30f4496.e861fbade6f97e3a158d.js:2:483011)
    at new u (https://console.paperspace.com/ide/vendors-f64a56cf.e861fbade6f97e3a158d.js:2:159298)
    at z._make_model (https://console.paperspace.com/ide/vendors-f64a56cf.e861fbade6f97e3a158d.js:2:11894)

```

I tried to research online but could not really find any resource.

Here's a screenshot-
<img width="1127" alt="Screen Shot 2023-08-21 at 11 53 35 PM" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/51415807/c2550208-22ca-47d1-ba46-c98bc1fca397">

By the way, thanks a lot for putting this repo together. Its really awesome!!

**Comment by TheLastBen** [comment]
you need to click on the jupyter icon on the left panel to use jupyter interfce to avoid that error
