### ISSUE TITLE
Error installing roop and faceswaplab on colab

### ISSUE THREAD

**Issue by sujancok23** [TheLastBen/fast-stable-diffusion#2503]
Tried to update and reinstall but doesn't work.

Roop :

*** Error running install.py for extension /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-roop.
*** Command: "/usr/bin/python3" "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-roop/install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 25, in <module>
***     download(model_url, model_path)
***   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 16, in download
***     request = urllib.request.urlopen(url)
***   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "/usr/lib/python3.10/urllib/request.py", line 525, in open
***     response = meth(req, response)
***   File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
***     response = self.parent.error(
***   File "/usr/lib/python3.10/urllib/request.py", line 563, in error
***     return self._call_chain(*args)
***   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
***     result = func(*args)
***   File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
*** urllib.error.HTTPError: HTTP Error 401: Unauthorized

Faceswaplab :

*** Error running install.py for extension /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab.
*** Command: "/usr/bin/python3" "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab/install.py"
*** Error code: 1
*** stderr: *** Error verifying pickled file from /content/gdrive/MyDrive/sd/stable-diffusion-webui/cache/hub/checkpoints/checkpoint_liberty_with_aug.pth
*** *** The file may be malicious, so the program is not going to read it.
*** *** You can skip this check with --disable-safe-unpickle commandline argument.
*** *** 
***     Traceback (most recent call last):
***       File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 136, in load_with_extra
***         if not shared.cmd_opts.disable_safe_unpickle:
***     AttributeError: partially initialized module 'modules.shared' has no attribute 'cmd_opts' (most likely due to a circular import)
*** 
*** ---
*** Traceback (most recent call last):
***   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-faceswaplab/install.py", line 5, in <module>
***     from modules import shared
***   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 15, in <module>
***     import modules.interrogate
***   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 13, in <module>
***     from modules import devices, paths, shared, lowvram, modelloader, errors
***   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 61, in <module>
***     import sgm  # noqa: F401
***   File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/__init__.py", line 2, in <module>
***     from .models import AutoencodingEngine, DiffusionEngine
***   File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/models/__init__.py", line 1, in <module>
***     from .autoencoder import AutoencodingEngine
***   File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/models/autoencoder.py", line 12, in <module>
***     from ..modules.diffusionmodules.model import Decoder, Encoder
***   File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/modules/__init__.py", line 1, in <module>
***     from .encoders.modules import GeneralConditioner
***   File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/modules/encoders/modules.py", line 5, in <module>
***     import kornia
***   File "/usr/local/lib/python3.10/dist-packages/kornia/__init__.py", line 10, in <module>
***     from . import (
***   File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/__init__.py", line 43, in <module>
***     from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
***   File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/container/__init__.py", line 1, in <module>
***     from .augment import AugmentationSequential
***   File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/container/augment.py", line 17, in <module>
***     from .patch import PatchSequential
***   File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/container/patch.py", line 9, in <module>
***     from kornia.contrib.extract_patches import extract_tensor_patches
***   File "/usr/local/lib/python3.10/dist-packages/kornia/contrib/__init__.py", line 4, in <module>
***     from .image_stitching import ImageStitcher
***   File "/usr/local/lib/python3.10/dist-packages/kornia/contrib/image_stitching.py", line 7, in <module>
***     from kornia.feature import LocalFeatureMatcher, LoFTR
***   File "/usr/local/lib/python3.10/dist-packages/kornia/feature/__init__.py", line 4, in <module>
***     from .integrated import (
***   File "/usr/local/lib/python3.10/dist-packages/kornia/feature/integrated.py", line 52, in <module>
***     class LAFDescriptor(nn.Module):
***   File "/usr/local/lib/python3.10/dist-packages/kornia/feature/integrated.py", line 65, in LAFDescriptor
***     patch_descriptor_module: nn.Module = HardNet(True),
***   File "/usr/local/lib/python3.10/dist-packages/kornia/feature/hardnet.py", line 69, in __init__
***     self.load_state_dict(pretrained_dict['state_dict'], strict=True)
*** TypeError: 'NoneType' object is not subscriptable

**Comment by scorpi0n81** [comment]
Use latest workbook, delete existing Roop folder and reinstall. Roop works just fine for me.

**Comment by sujancok23** [comment]
@scorpi0n81 
I've tried many times and doesn't work. But i found the way to fix it. It's because invalid link inswapper_128, so i forked and replace a new link inside install.py. This just work for roop extension, not faceswaplab.

**Comment by arman797979** [comment]
Bro I have the same problem can you tell me more about how you solved the problem?

**Comment by TylerBizz** [comment]
> @scorpi0n81
> I've tried many times and doesn't work. But i found the way to fix it. It's because invalid link inswapper_128, so i forked and replace a new link inside install.py. This just work for roop extension, not faceswaplab.

Faceswaplab working fine for me on colab. Not sure if this will help but I believe roop and faceswaplab have their own references to inswapper_128 in their respective models folder. Have a look in stable-diffusion-webui/models/faceswaplab and stable-diffusion-webui/models/roop. If you have replaced the link - check that you have inswapper_128 added to the models folder for faceswaplab on your install.
