### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by Juansigma** [TheLastBen/fast-stable-diffusion#2507]
Hello, I got this unexpected error when I went to use Stable Diffusion: 
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/127377346/92a207b7-36bf-4059-ac17-d96f0ec6e785)

I can't create anything, I really need this error to be solved, otherwise I'm screwed, I work with Stable Diffusion.

Line code:

Startup time: 12.9s (import torch: 4.0s, import gradio: 0.6s, setup paths: 0.4s, other imports: 0.4s, setup codeformer: 0.3s, list SD models: 5.4s, load scripts: 1.1s, create ui: 0.4s, gradio launch: 0.2s).
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /notebooks/sd/stable-diffusion-webui/models/VAE/Counterfeit-V2.5.vae.pt
Applying attention optimization: InvokeAI... done.
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 318, in load_model
    shared.sd_model  # noqa: B018
  File "/notebooks/sd/stable-diffusion-webui/modules/shared.py", line 754, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 439, in get_sd_model
    load_model()
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 536, in load_model
    sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 460, in get_empty_cond
    return sd_model.cond_stage_model([""])
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 234, in forward
    z = self.process_tokens(tokens, multipliers)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 271, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 324, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 811, in forward
    return self.text_model(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 721, in forward
    encoder_outputs = self.encoder(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 650, in forward
    layer_outputs = encoder_layer(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 378, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

Stable diffusion model failed to load
Loading weights [a296d4fd62] from /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/LinkinPark2.safetensors
Creating model from config: /notebooks/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /notebooks/sd/stable-diffusion-webui/models/VAE/Counterfeit-V2.5.vae.pt
Applying attention optimization: InvokeAI... done.
*** Error completing request
*** Arguments: (my prompt) {}
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/notebooks/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 664, in process_images
        sd_models.reload_model_weights()
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 578, in reload_model_weights
        load_model(checkpoint_info, already_loaded_state_dict=state_dict)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 536, in load_model
        sd_model.cond_stage_model_empty_prompt = get_empty_cond(sd_model)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 460, in get_empty_cond
        return sd_model.cond_stage_model([""])
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 234, in forward
        z = self.process_tokens(tokens, multipliers)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 271, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_clip.py", line 324, in encode_with_transformers
        outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 811, in forward
        return self.text_model(
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 721, in forward
        encoder_outputs = self.encoder(
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 650, in forward
        layer_outputs = encoder_layer(
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/transformers/models/clip/modeling_clip.py", line 378, in forward
        hidden_states = self.layer_norm1(hidden_states)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/normalization.py", line 190, in forward
        return F.layer_norm(
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 2515, in layer_norm
        return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
    RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

---

**Comment by Juansigma** [comment]
Hello again, I solved the problem, I just restarted the virtual machine and did the normal procedures. You don't have to solve my problem, but it would be interesting to know why this happens. Do whatever you want ^^

**Comment by TheLastBen** [comment]
it's probably a GPU issue
