### ISSUE TITLE
RuntimeError while trying to train SDXL

### ISSUE THREAD

**Issue by tmaudev** [TheLastBen/fast-stable-diffusion#2517]
I get the following error when trying to train SDXL using the runpod notebook (SDXL-LoRA-RNPD.ipynb). Any idea how to fix this issue?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 109, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[320, 1280]' is invalid for input of size 406326
```

**Comment by tmaudev** [comment]
Turns out I was just using a GPU that didn't have enough VRAM.
