### ISSUE TITLE
Paperspace issue

### ISSUE THREAD

**Issue by Skeme322** [TheLastBen/fast-stable-diffusion#2518]
Start Stable-Diffusion error

No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu116. You might want to consider upgrading.
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/notebooks/sd/stable-diffusion-webui/modules/initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/notebooks/sd/stable-diffusion-webui/modules/ui.py", line 36, in <module>
    warnings.filterwarnings("default" if opts.show_gradio_deprecation_warnings else "ignore", category=gr.deprecation.GradioDeprecationWarning)
AttributeError: module 'gradio.deprecation' has no attribute 'GradioDeprecationWarning'

**Comment by TheLastBen** [comment]
fixed
