### ISSUE TITLE
i cant start colab

### ISSUE THREAD

**Issue by zx3on** [TheLastBen/fast-stable-diffusion#2519]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 28, in <module>
    from gradio import (
ImportError: cannot import name 'wasm_utils' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/gradio/__init__.py)

**Comment by KuzeyVural** [comment]
deleting sd and re downloading it solved the issue for me.

**Comment by TheLastBen** [comment]
use the latest colab

**Comment by hameleon-ed** [comment]
I have the same problem. I've deleted sd folder and reran the latest colab, but the error is the same.
