### ISSUE TITLE
creating model quickly: AttributeError

### ISSUE THREAD

**Issue by gogoldgoal** [TheLastBen/fast-stable-diffusion#2522]
the latest version commit 5606a33 seems to trigger the following errors. I am pretty sure the previous version @20230820 is totally fine. RIght now with this version we cannot do anything. Thank you.

Creating` model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml

creating model quickly: AttributeError
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 318, in load_model
    shared.sd_model  # noqa: B018
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 754, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 499, in get_sd_model
    load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 601, in load_model
    with sd_disable_initialization.InitializeOnMeta():
AttributeError: module 'modules.sd_disable_initialization' has no attribute 'InitializeOnMeta'

Failed to create model quickly; will retry using slow method.
loading stable diffusion model: AttributeError
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 318, in load_model
    shared.sd_model  # noqa: B018
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 754, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 499, in get_sd_model
    load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 610, in load_model
    with sd_disable_initialization.InitializeOnMeta():
AttributeError: module 'modules.sd_disable_initialization' has no attribute 'InitializeOnMeta'

Stable diffusion model failed to load
Applying attention optimization: xformers... done.

**Comment by skjcs355062** [comment]
Same here.

Can we build an old stable version backup notebook?
Could be used temporarily when there is a problem with the new version.
If possible, I also want a stable version of 1.4, because some extensions of 1.5 still have some problems

**Comment by TheLastBen** [comment]
something is preventing the update of your A1111 installation, rename the current sd folder to sd_old then try again
