### ISSUE TITLE
Stable diffusion model failed to load

### ISSUE THREAD

**Issue by ApchDio** [TheLastBen/fast-stable-diffusion#2525]
ControlNet v1.1.206
ControlNet v1.1.206
Loading weights [15012c538f] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV51_v51VAE.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
creating model quickly: AttributeError
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 318, in load_model
    shared.sd_model  # noqa: B018
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 754, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 499, in get_sd_model
    load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 601, in load_model
    with sd_disable_initialization.InitializeOnMeta():
AttributeError: module 'modules.sd_disable_initialization' has no attribute 'InitializeOnMeta'

Failed to create model quickly; will retry using slow method.
loading stable diffusion model: AttributeError
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 318, in load_model
    shared.sd_model  # noqa: B018
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 754, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 499, in get_sd_model
    load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 610, in load_model
    with sd_disable_initialization.InitializeOnMeta():
AttributeError: module 'modules.sd_disable_initialization' has no attribute 'InitializeOnMeta'

Stable diffusion model failed to load
Applying attention optimization: xformers... done.

**Comment by ApchDio** [comment]
Hi, Please help!!!

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by DeAiArt** [comment]
I get the same error message. I am already using the latest notebook.
