### ISSUE TITLE
Stable diffusion checkpoint is not working

### ISSUE THREAD

**Issue by SDPDVADER** [TheLastBen/fast-stable-diffusion#2527]
@TheLastBen great work again on your notebook, in regards to the new Automatic upgrade there seems to be issue with Stable Diffusion checkpoint not change models when a new model is selected.  I dont know if you have seen it yet but it is happening after i did a fresh install.

**Comment by mdlieber99** [comment]
same issue

**Comment by mr-mitt** [comment]
me too

**Comment by SDPDVADER** [comment]
Even on trying to change it on the x/y/z plot it doesnt work.

**Comment by TheLastBen** [comment]
any error message ?

**Comment by DeAiArt** [comment]
This is what is displayed for me sometimes
![Screenshot 2023-08-31 224206](https://github.com/TheLastBen/fast-stable-diffusion/assets/133396245/f5f75128-fb83-4a70-9664-ff535b3415d8)

**Comment by TheLastBen** [comment]
check the notebook output

**Comment by DeAiArt** [comment]
If it happens again, I'll take a look. But so far everything is going well.

**Comment by DeAiArt** [comment]
As soon as I wrote it, it happened again. But there was no error message in the notebook output. The connection was simply terminated....

**Comment by TheLastBen** [comment]
Are you using high-RAM ?

**Comment by DeAiArt** [comment]
Not until now. I have activated High-Ram now

**Comment by TheLastBen** [comment]
that should fix the issue

**Comment by mdlieber99** [comment]
It wouldn't let me change from the default checkpoint and then when I tried to run something with the default I got this error where it usually shows the output image "AttributeError: 'Options' object has no attribute 'sd_checkpoints_limit'".  Here is what was back in the code page:  

 File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 62, in txt2img
        processed = processing.process_images(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 664, in process_images
        sd_models.reload_model_weights()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 732, in reload_model_weights
        sd_model = reuse_model_from_already_loaded(sd_model, checkpoint_info, timer)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 697, in reuse_model_from_already_loaded
        elif shared.opts.sd_checkpoints_limit > 1 and len(model_data.loaded_sd_models) < shared.opts.sd_checkpoints_limit:
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 617, in __getattr__
        return super(Options, self).__getattribute__(item)
    AttributeError: 'Options' object has no attribute 'sd_checkpoints_limit'

**Comment by mdlieber99** [comment]
Here's the error code when trying to change to a different checkpoint:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 633, in set
    self.data_labels[key].onchange()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 14, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 238, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()), call=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 732, in reload_model_weights
    sd_model = reuse_model_from_already_loaded(sd_model, checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 697, in reuse_model_from_already_loaded
    elif shared.opts.sd_checkpoints_limit > 1 and len(model_data.loaded_sd_models) < shared.opts.sd_checkpoints_limit:
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 617, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'sd_checkpoints_limit'

**Comment by TheLastBen** [comment]
rename your sd folder to sd_old

**Comment by mdlieber99** [comment]
I did that and it kind of worked but then didn't fully.  but then when I restarted the runtime to do it again, I get this error:

 Error running preload() for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/preload.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 26, in preload_extensions
        module = load_module(preload_script)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/preload.py", line 4, in <module>
        from modules.shared import models_path
    ImportError: cannot import name 'models_path' from partially initialized module 'modules.shared' (most likely due to a circular import) (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py)

---

**Comment by TheLastBen** [comment]
the extension wd11 tagger isn't compatible with the latest A1111

**Comment by mdlieber99** [comment]
deleted that but now I am getting images that pretty much come out as complete garbage with only the slightest connection to the prompt - like first day ever using stable diffusion type images

**Comment by mdlieber99** [comment]
Sent an existing image to PNG Info and then sent those results back to txt2img, used the same checkpoint, and get nothing like the original

**Comment by mdlieber99** [comment]
Hi Ben - things have definitely improved.  I can get images that look reasonably like what I was getting before, but everything I create has just lost some of the photo realism of what I had under the older colabs.  I set all the settings the same.  Everything I do is with my own fine-tuned model (from your dream booth) based on an already fine-tuned model based on 1.5.  These created amazing images under the old colab but now everything feels flatter and more 2D.  Is this an issue for other folks?  Is there any fix for this?  And if not, is there any way to use an older archived version of all of this.  I didn't need an update personally.  I'm guessing the answer is no, but I thought it was worth asking.

**Comment by TheLastBen** [comment]
it's related to A1111, check out their repo for more insight

**Comment by mdlieber99** [comment]
Can you give me a bit of direction on that.  I'm not sure what I should be looking at to get started.

**Comment by TheLastBen** [comment]
check in the issues tab if you can find similar situations

**Comment by mdlieber99** [comment]
I went back more than a week on issues at https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?page=1&q=is%3Aissue+is%3Aopen and don't see anything similar to what I'm bringing up.  Have you seen others discussing this loss of quality with non-sdxl models?
