### ISSUE TITLE
When I start "Google Colab" with "TheLastBen / fast-stable-diffusion", I get an error message at "Start Stable-Diffusion" and cannot start it.

### ISSUE THREAD

**Issue by Kaka3279** [TheLastBen/fast-stable-diffusion#2537]
When I start "Google Colab" with "TheLastBen / fast-stable-diffusion", I get an error message at "Start Stable-Diffusion" and cannot start it.

"Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 32, in <module>
    from fastapi import UploadFile
  File "/usr/local/lib/python3.10/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 21, in <module>
    from fastapi import params
  File "/usr/local/lib/python3.10/dist-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.10/dist-packages/pydantic/fields.py)"

Please let me know what to do.

**Comment by TheLastBen** [comment]
use the latest notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by ZenDevMaster** [comment]
Would it be possible to put a version checker in the collab? So it alerts near the beginning of startup to a new version launch?

**Comment by Kaka3279** [comment]
> Would it be possible to put a version checker in the collab? So it alerts near the beginning of startup to a new version launch?

What is a version checker?

**Comment by Kaka3279** [comment]
> use the latest notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

I copied the "Google Colab" link you gave me, saved it, and ran it, but at "Start Stable-Diffusion" I got the following error.
"Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
Scan MarianMT model
No MarianMT folder, no need scan
No pyAesCrypt - won't be able to do encryption
Installing pyAesCrypt for Styles Editor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
Downloading face_yolov8n.pt100% 6.21M/6.21M [00:00<00:00, 95.5MB/s]
Downloading face_yolov8s.pt100% 22.5M/22.5M [00:00<00:00, 302MB/s]
Downloading hand_yolov8n.pt100% 6.22M/6.22M [00:00<00:00, 319MB/s]
Downloading person_yolov8n-seg.pt100% 6.75M/6.75M [00:00<00:00, 326MB/s]
Downloading person_yolov8s-seg.pt100% 23.8M/23.8M [00:00<00:00, 271MB/s]
[-] ADetailer initialized. version: 23.7.11, num models: 9
*** Error loading script: deforum.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 22, in <module>
        init_deforum()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 14, in init_deforum
        from deforum_helpers.ui_right import on_ui_tabs
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/ui_right.py", line 4, in <module>
        from webui import wrap_gradio_gpu_call
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py)

---
2023-09-03 12:04:32,164 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-09-03 12:04:44,756 - ControlNet - INFO - ControlNet v1.1.313
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_ui.py", line 12, in <module>
        from modules.ui import paste_symbol, clear_prompt_symbol, extra_networks_symbol, apply_style_symbol, save_style_symbol, \
    ImportError: cannot import name 'create_seed_inputs' from 'modules.ui' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py)

---
dirname:  /content/gdrive/MyDrive/sd/stable-diffusion-webui/localizations
localizations:  {'ja_JP': '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-localization-ja_JP/localizations/ja_JP.json', 'ks_JP': '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-localization-ja_JP/localizations/ks_JP.json', 'zh_CN': '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-localization-ja_JP/localizations/zh_CN.json', 'zh_TW': '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-localization-ja_JP/localizations/zh_TW.json'}
Loading weights [0805b136eb] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/breakdomain_M2150.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
[ERROR][Config Presets] The txt2img component 'txt2img_restore_faces' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, or you included a component ID in the custom tracked components config file that does not exist, no longer exists (if you updated an extension), or is an invalid component (if this is the case, you need to manually edit the config file at /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
[ERROR][Config Presets] The img2img component 'img2img_restore_faces' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, or you included a component ID in the custom tracked components config file that does not exist, no longer exists (if you updated an extension), or is an invalid component (if this is the case, you need to manually edit the config file at /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Config-Presets\config-img2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
Running on public URL: https://0eb6d546647b64b44c.gradio.live
✔ Connected
Startup time: 288.3s (launcher: 0.9s, import torch: 10.6s, import gradio: 1.5s, setup paths: 26.7s, import ldm: 0.7s, initialize shared: 8.0s, other imports: 37.2s, setup codeformer: 8.6s, setup gfpgan: 0.5s, list SD models: 44.7s, list localizations: 0.2s, load scripts: 94.4s, load upscalers: 0.9s, initialize extra networks: 8.2s, create ui: 36.5s, gradio launch: 8.4s, add APIs: 0.2s, app_started_callback: 0.1s).
Loading VAE weights specified in settings: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 67.9s (load weights from disk: 29.0s, load config: 0.5s, create model: 5.2s, apply weights to model: 21.2s, load VAE: 4.8s, load textual inversion embeddings: 3.6s, scripts callbacks: 0.4s, calculate empty prompt: 3.2s)."
"Stable diffusion Web-UI" was able to run.
Is this correct?
I have another question.
Did I change the "Model_Version" in "Model Download/Load" to "V2.1-768px" (default is "SDXL")?
I ran it without anything in "Download LoRA", is this correct?

Please tell me.

**Comment by Kaka3279** [comment]
I have another question.
Did I change the "Model_Version" in "Model Download/Load" to "V2.1-768px" (default is "SDXL")?
I ran it without anything in "Download LoRA", is this correct?

Please tell me.

**Comment by TheLastBen** [comment]
use the latest notebook and use a fresh sd folder
