### ISSUE TITLE
Something went wrong - training

### ISSUE THREAD

**Issue by juandavidGF** [TheLastBen/fast-stable-diffusion#254]
Hellow, Im getting this error in colab.

Steps:   3% 46/1600 [01:15<38:04,  1.47s/it, loss=0.13, lr=1e-6] Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 694, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 590, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 357, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 292, in __getitem__
    instance_image = Image.open(path)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/content/data/jdgf/.ipynb_checkpoints'
Steps:   3% 46/1600 [01:15<42:37,  1.65s/it, loss=0.13, lr=1e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--save_starting_step=500', '--save_n_steps=0', '--train_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/data/jdgf', '--class_data_dir=/content/regularization_images/person_ddim', '--output_dir=/content/models/jdgf', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of jdgf person', '--class_prompt=a photo of a person, ultra detailed', '--seed=75576', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--center_crop', '--max_train_steps=1600', '--num_class_images=500']' returned non-zero exit status 1.
**Something went wrong**

**Comment by TheLastBen** [comment]
Ru this
`!rm -r /content/data/jdgf/.ipynb_checkpoints`

**Comment by TheLastBen** [comment]
Use the latest colab from the repo to avoid such errors
