### ISSUE TITLE
Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by mmehrle** [TheLastBen/fast-stable-diffusion#2541]
This keeps happening on Google Colab when attempting to pre-load a model:

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/8457499/658080a8-6a2c-46ee-898a-e03fa8ced59b)

2023-09-02 14:29:58,614 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-09-02 14:30:04,935 - ControlNet - INFO - ControlNet v1.1.313
Loading weights [463d6a9fe8] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/absolutereality_v181.safetensors
loading stable diffusion model: SafetensorError
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 147, in load_model
    shared.sd_model  # noqa: B018
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared_items.py", line 110, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 499, in get_sd_model
    load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 584, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 315, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 291, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by djpirra** [comment]
Any solution for this?

**Comment by satya77** [comment]
same here
