### ISSUE TITLE
TypeError: _hijacked_get_learned_conditioning() got multiple values for argument 'original_function'

### ISSUE THREAD

**Issue by Basa1762** [TheLastBen/fast-stable-diffusion#2542]
When I try to generate images, the process stops. How can I make it work fine?

    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/movie2movie.py", line 146, in run
        proc = process_images(copy_p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 856, in process_images_inner
        p.setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1309, in setup_conds
        super().setup_conds()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 469, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 455, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/prompt-fusion-extension/lib_prompt_fusion/hijacker.py", line 15, in wrapper
        return function(*args, **kwargs, original_function=self.__original_functions[attribute])
    TypeError: _hijacked_get_learned_conditioning() got multiple values for argument 'original_function'

**Comment by TheLastBen** [comment]
update the extension prompt-fusion and make sure it's compatible with the latest A1111

**Comment by Basa1762** [comment]
It worked well. Thank you for your help.
