### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by PyNAABO** [TheLastBen/fast-stable-diffusion#2543]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 32, in <module>
    from fastapi import UploadFile
  File "/usr/local/lib/python3.10/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 21, in <module>
    from fastapi import params
  File "/usr/local/lib/python3.10/dist-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.10/dist-packages/pydantic/fields.py)

**Comment by SkyWatcher2019** [comment]
!pip install pydantic>=1.10.9

**Comment by TheLastBen** [comment]
Use the latest notebook
