### ISSUE TITLE
GradioDeprecationWarning: RunPod

### ISSUE THREAD

**Issue by alpha-adam** [TheLastBen/fast-stable-diffusion#2546]
When using this repo with a server less Runpod instance I get the following error. I'm following a tutorial, and from that I can see that they are using an older version of this repo. But I'm not sure which one. 

2023-09-02T11:36:56.834535124Z Service not ready yet. Retrying...
2023-09-02T11:36:56.958717299Z Traceback (most recent call last):
2023-09-02T11:36:56.958746270Z   File "/workspace/sd/stable-diffusion-webui/webui.py", line 13, in <module>
2023-09-02T11:36:56.960021971Z     initialize.imports()
2023-09-02T11:36:56.960032321Z   File "/runpod-volume/sd/stable-diffusion-webui/modules/initialize.py", line 37, in imports
2023-09-02T11:36:56.962002549Z     from modules import processing, gradio_extensons, ui  # noqa: F401
2023-09-02T11:36:56.962021260Z   File "/runpod-volume/sd/stable-diffusion-webui/modules/ui.py", line 36, in <module>
2023-09-02T11:36:56.964184372Z     warnings.filterwarnings("default" if opts.show_gradio_deprecation_warnings else "ignore", category=gr.deprecation.GradioDeprecationWarning)
2023-09-02T11:36:56.964191052Z AttributeError: module 'gradio.deprecation' has no attribute 'GradioDeprecationWarning'

**Comment by TheLastBen** [comment]
rename the folder sd to sd_old

**Comment by TheLastBen** [comment]
dreambooth serverless ?

**Comment by alpha-adam** [comment]
No, runpod serverless. I was following the tutorial linked below. The UI works when setting it up, and text to image works. But when running it in server less more and making API requests the error appears.

https://www.youtube.com/watch?v=gv6F9Vnd6io&t=466s

**Comment by TheLastBen** [comment]
are you getting the same error in-notebook ?

**Comment by TheLastBen** [comment]
it seems that blue-tomato template is out of date

**Comment by TheLastBen** [comment]
`!pip install gradio=3.41.2` will fix the issue

**Comment by alpha-adam** [comment]
Thanks for your help! Where in the notebook should I run the gradio command ?

**Comment by alpha-adam** [comment]
That version of gradio is already installed.

root@9f4686fbb586:/# pip show gradio
Name: gradio
Version: 3.41.2

**Comment by TheLastBen** [comment]
is the your A1111 repo up to date ?

**Comment by sky-admin** [comment]
i have same issue, did you resolve it?
It's wired, i can run it in jupyter but cannot success by postman with api

**Comment by sky-admin** [comment]
Okay, I've resolved this issue by commenting out the line that caused the error.
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/6292668/9e664b0f-b784-4c4b-8cef-d4aeacefaa16)
and then it success:
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/6292668/c22b61e5-e704-4357-8fc5-02da83dc2556)

**Comment by Valachio** [comment]
> Okay, I've resolved this issue by commenting out the line that caused the error. ![image](https://private-user-images.githubusercontent.com/6292668/292432403-9e664b0f-b784-4c4b-8cef-d4aeacefaa16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjAyNzksIm5iZiI6MTcwMzQxOTk3OSwicGF0aCI6Ii82MjkyNjY4LzI5MjQzMjQwMy05ZTY2NGIwZi1iNzg0LTRjNGItOGNlZi1kNGFlYWNlZmFhMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMTIxMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZkZDQwY2I1Nzg3M2Q4YTFlZmQ0OTI2MThiZTY3Zjk2ZGU3ODVkZmY4NDc3MzA1NTU2NTJhZDNhNWNmZjIzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oLXNwaLsuiiI-ePywBdkZum0e3dmvhGEm6-J9SmYW9s) and then it success: ![image](https://private-user-images.githubusercontent.com/6292668/292432726-c22b61e5-e704-4357-8fc5-02da83dc2556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjAyNzksIm5iZiI6MTcwMzQxOTk3OSwicGF0aCI6Ii82MjkyNjY4LzI5MjQzMjcyNi1jMjJiNjFlNS1lNzA0LTQzNTctOGZjNS0wMmRhODNkYzI1NTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMTIxMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY2YjQxNDMxNjg0NzMyNTRmZTI5NDhmY2ZkZGY3NzEyNmQzODA3ZGRlODcwZGFiYjFhMTcxMGZiNjBmNjQ2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M-gPpvYeazeu8RM6oKUgU6jZlcQ5vcLK6p5f2wBEaLI)

Your solution to comment out this particular line worked for me today (Dec 24, 2023). I ran into the same problem whilst following this tutorial: https://www.youtube.com/watch?v=gv6F9Vnd6io

**Comment by sky-admin** [comment]
> > Okay, I've resolved this issue by commenting out the line that caused the error. ![image](https://private-user-images.githubusercontent.com/6292668/292432403-9e664b0f-b784-4c4b-8cef-d4aeacefaa16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjAyNzksIm5iZiI6MTcwMzQxOTk3OSwicGF0aCI6Ii82MjkyNjY4LzI5MjQzMjQwMy05ZTY2NGIwZi1iNzg0LTRjNGItOGNlZi1kNGFlYWNlZmFhMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMTIxMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZkZDQwY2I1Nzg3M2Q4YTFlZmQ0OTI2MThiZTY3Zjk2ZGU3ODVkZmY4NDc3MzA1NTU2NTJhZDNhNWNmZjIzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oLXNwaLsuiiI-ePywBdkZum0e3dmvhGEm6-J9SmYW9s) and then it success: ![image](https://private-user-images.githubusercontent.com/6292668/292432726-c22b61e5-e704-4357-8fc5-02da83dc2556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MjAyNzksIm5iZiI6MTcwMzQxOTk3OSwicGF0aCI6Ii82MjkyNjY4LzI5MjQzMjcyNi1jMjJiNjFlNS1lNzA0LTQzNTctOGZjNS0wMmRhODNkYzI1NTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjRUMTIxMjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY2YjQxNDMxNjg0NzMyNTRmZTI5NDhmY2ZkZGY3NzEyNmQzODA3ZGRlODcwZGFiYjFhMTcxMGZiNjBmNjQ2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M-gPpvYeazeu8RM6oKUgU6jZlcQ5vcLK6p5f2wBEaLI)
> 
> Your solution to comment out this particular line worked for me today (Dec 24, 2023). I ran into the same problem whilst following this tutorial: https://www.youtube.com/watch?v=gv6F9Vnd6io

haha, we watch the same tutorial

**Comment by faye1225** [comment]
> Okay, I've resolved this issue by commenting out the line that caused the error. ![image](https://private-user-images.githubusercontent.com/6292668/292432403-9e664b0f-b784-4c4b-8cef-d4aeacefaa16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTU5NDYsIm5iZiI6MTcwODQxNTY0NiwicGF0aCI6Ii82MjkyNjY4LzI5MjQzMjQwMy05ZTY2NGIwZi1iNzg0LTRjNGItOGNlZi1kNGFlYWNlZmFhMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDc1NDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTg5MDg1NjY4ZWJiMTk5YTEwMDE5MGQ5NDExYmExYzgxZTY4YmQ4MTdhZTIwNDBmNjZiYmZlMzY5YWIxZTlhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XwwiYf9Mpp-jsZIppISGjuZWzpX2xoAYZscpcZRlDH4) and then it success: ![image](https://private-user-images.githubusercontent.com/6292668/292432726-c22b61e5-e704-4357-8fc5-02da83dc2556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTU5NDYsIm5iZiI6MTcwODQxNTY0NiwicGF0aCI6Ii82MjkyNjY4LzI5MjQzMjcyNi1jMjJiNjFlNS1lNzA0LTQzNTctOGZjNS0wMmRhODNkYzI1NTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDc1NDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk1Yzg3NThlNzRhM2EwY2Q5YThkMzRhYjQyYmViZjk0ZDAyYmIwZTNkMDMxNDFiNDEyMDA0YTMzZWVhNzgwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YsLDT7Lyk89UB4G3xG0nm8EZzPL8zCREmKKWjc35FZk)

I encountered the same issue, can you tell me if I should go to endurance to modify this code? Thank you very much.
