### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by PyNAABO** [TheLastBen/fast-stable-diffusion#2551]
The file has been corrupted or is not a valid notebook file.
Unexpected token '<', "
<?xml vers"... is not valid JSON
SyntaxError: Unexpected token '<', "
<?xml vers"... is not valid JSON
    at JSON.parse (<anonymous>)
    at ra.program_ (https://ssl.gstatic.com/colaboratory-static/common/6b609439a03d479f357f1b6fa578e045/external_polymer_binary.js:2287:21)
    at ta (https://ssl.gstatic.com/colaboratory-static/common/6b609439a03d479f357f1b6fa578e045/external_polymer_binary.js:21:57)
    at ra.next_ (https://ssl.gstatic.com/colaboratory-static/common/6b609439a03d479f357f1b6fa578e045/external_polymer_binary.js:19:195)
    at laa.next (https://ssl.gstatic.com/colaboratory-static/common/6b609439a03d479f357f1b6fa578e045/external_polymer_binary.js:22:48)
    at b (https://ssl.gstatic.com/colaboratory-static/common/6b609439a03d479f357f1b6fa578e045/external_polymer_binary.

**Comment by TheLastBen** [comment]
Use the official links for the notebooks
