### ISSUE TITLE
Error on loading custom model

### ISSUE THREAD

**Issue by mmehrle** [TheLastBen/fast-stable-diffusion#2569]
I am launching the interface with the default model and then attempt to select a new one from the drop down. Getting this error:

`Startup time: 42.1s (import torch: 15.7s, import gradio: 1.5s, setup paths: 2.5s, initialize shared: 0.2s, other imports: 1.2s, setup codeformer: 0.1s, load scripts: 2.5s, create ui: 1.7s, gradio launch: 16.5s, add APIs: 0.2s).
Applying attention optimization: xformers... done.
Model loaded in 39.4s (load weights from disk: 2.4s, create model: 0.9s, apply weights to model: 32.5s, calculate empty prompt: 3.3s).
Reusing loaded model v1-5-pruned-emaonly.safetensors [6ce0161689] to load absolutereality_v181.safetensors [463d6a9fe8]
Loading weights [463d6a9fe8] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/absolutereality_v181.safetensors
changing setting sd_model_checkpoint to absolutereality_v181.safetensors [463d6a9fe8]: SafetensorError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/options.py", line 140, in set
    option.onchange()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize_util.py", line 170, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 741, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 315, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 291, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer`

My extensions are all up to date:

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/8457499/617e2472-a353-462b-b553-a639eb307566)

I'm open to suggestions ;-)

**Comment by TheDevo** [comment]
I'm getting this error when I try to load a custom checkpoint:
"The future belongs to a different loop than the one specified as the loop argument"
and it repeats a dozen times

**Comment by TheLastBen** [comment]
The model seems corrupt, make sure you have enough space in your gdrive

**Comment by dlebouc** [comment]
I have these messages sometimes (especially if I have a lot of extensions installed). If I stop the execution of the cell and restart it with no change, they disappear.
