### ISSUE TITLE
Gradio ImportError on Paperspace Notebook Startup

### ISSUE THREAD

**Issue by Bez22** [TheLastBen/fast-stable-diffusion#2579]
I'm attempting to start up the Gradio interface of stable diffusion within my Paperspace notebook, but I'm encountering a specific ImportError which prevents the last cell of my notebook from finishing execution.

Error Message:
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/notebooks/sd/stable-diffusion-webui/modules/initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.9/dist-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "/usr/local/lib/python3.9/dist-packages/gradio/components/base.py", line 29, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 41, in <module>
    from gradio.deprecation import check_deprecated_parameters, warn_deprecation
ImportError: cannot import name 'warn_deprecation' from 'gradio.deprecation' (/usr/local/lib/python3.9/dist-packages/gradio/deprecation.py)

Attempts to Resolve:
Reinstalled the necessary dependencies.
Did a clean reinstall of the environment.

Unfortunately, none of these steps resolved the issue. I'd appreciate any guidance or insight into this matter. Thanks!

**Comment by TheLastBen** [comment]
you're using an old notebook, you'll find the new notebooks inside the folder "Latest_Notebook" in the main folder in paperspace

**Comment by Bez22** [comment]
Yes that was it. I hadn't updated it in a while. Thanks 😁
