### ISSUE TITLE
animatediff error

### ISSUE THREAD

**Issue by taisa443** [TheLastBen/fast-stable-diffusion#2580]
Using paperspace

*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 14, in <module>
        from scripts.animatediff_latent import AnimateDiffI2VLatent
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (/notebooks/stable-diffusion-webui/modules/sd_samplers_common.py)

---
*** Error loading script: animatediff_latent.py
    Traceback (most recent call last):
      File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_latent.py", line 5, in <module>
        from modules.sd_samplers_common import images_tensor_to_samples, approximation_indexes
    ImportError: cannot import name 'images_tensor_to_samples' from 'modules.sd_samplers_common' (/notebooks/stable-diffusion-webui/modules/sd_samplers_common.py)

**Comment by TheLastBen** [comment]
your A1111 repo is out of date, rename the sd folder to "sd_old", then install the repo again
