### ISSUE TITLE
returned non-zero exit status 1. Something went wrong

### ISSUE THREAD

**Issue by wallatomic** [TheLastBen/fast-stable-diffusion#259]
Hi, I'm trying this since yesterday an I got the same results:

subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=500', '--save_n_steps=0', '--train_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/data/jsr2', '--output_dir=/content/models/jsr2', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--center_crop', '--lr_warmup_steps=0', '--max_train_steps=1000']' returned non-zero exit status 1.
Something went wrong

**Comment by wallatomic** [comment]
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 694, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 439, in main
    tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1748, in from_pretrained
    _commit_hash=commit_hash,
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 1022, in hf_hub_download
    cache_dir, repo_folder_name(repo_id=repo_id, repo_type=repo_type)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 92, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 137, in validate_repo_id
    "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/stable-diffusion-v1-5'. Use `repo_type` argument if needed.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=500', '--save_n_steps=0', '--train_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/data/jsr2', '--output_dir=/content/models/jsr2', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--center_crop', '--lr_warmup_steps=0', '--max_train_steps=1000']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
Did you accept the terms at https://huggingface.co/runwayml/stable-diffusion-v1-5 ?

**Comment by wallatomic** [comment]
yes

**Comment by wallatomic** [comment]
there is not. Do I have to create it manually? I have to put the model inside?
I tried the same notebook yesterday and it worked. this changed?

**Comment by TheLastBen** [comment]
when you put your huggingface token in the "download model" cell and run it, it should download the model, you don't have to do it manually, did you run the cell ?

**Comment by wallatomic** [comment]
yes, i followed all the steps

**Comment by TheLastBen** [comment]
there should be a model folder, try a clean run

**Comment by TheLastBen** [comment]
and make sure you use the latest  colab notebook

**Comment by wallatomic** [comment]
How can I check if it is the latest? The link is not the same?
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by TheLastBen** [comment]
yes that is the link, just avoid saving the notebook to your gdrive

**Comment by wallatomic** [comment]
Ok, yes, it seems I was using an outdated notebook. I'm trying it now and I see that the folder with the images doesn't appear anymore under "data". it is me, or it changed? Where are the images now?

**Comment by TheLastBen** [comment]
Yes, everything is moved to your gdrive to allow resuming training easily after disconnecting from a session

**Comment by wallatomic** [comment]
Excellent! Thank you Ben! I really appreciate it ☕😉

**Comment by TheLastBen** [comment]
happy to help
