### ISSUE TITLE
UI won't run after seemingly successful startup.

### ISSUE THREAD

**Issue by norfuer** [TheLastBen/fast-stable-diffusion#2601]
So I haven't touched this for maybe a month or two. Tried to do a fresh install with the usual delete sd folder and check the latest colab.

For some reason, I'm getting this error. At first it seems to have loaded properly, but as soon as I open the UI, it starts trying to read the main model, but ends up spitting this out repeatedly.

Can't even start doing anything. :(

`Loading weights [536febf703] from /content/gdrive/MyDrive/AniPlusv2/aniplusv2-final.ckpt
Running on public URL: https://4aad85568ec17c7840.gradio.live/
✔ Connected
Startup time: 26.4s (import torch: 14.2s, import gradio: 1.5s, setup paths: 2.3s, initialize shared: 0.3s, other imports: 1.2s, setup codeformer: 0.1s, load scripts: 1.7s, create ui: 1.8s, gradio launch: 2.5s, add APIs: 0.5s).
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
Loading VAE weights found near the checkpoint: /content/gdrive/MyDrive/AniPlusv2/[aniplusv2-final.vae.pt](http://aniplusv2-final.vae.pt/)
Applying attention optimization: xformers... done.
Model loaded in 70.5s (load weights from disk: 44.4s, create model: 0.6s, apply weights to model: 16.9s, load VAE: 5.1s, calculate empty prompt: 3.2s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await [self.app](http://self.app/)(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 26, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 26, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 76, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await [self.app](http://self.app/)(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 341, in handle
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 604, in join_queue
    session_info = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006`

**Comment by norfuer** [comment]
So I can do some generations... but this keeps popping up and slows down my workflow. I don't know what I'm doing wrong...
