### ISSUE TITLE
Can't load trained model from latest dreambooth notebook

### ISSUE THREAD

**Issue by Gregorio305** [TheLastBen/fast-stable-diffusion#2631]
I got this error when load trained model from the latest notebook

hanging setting sd_model_checkpoint to msnn.ckpt: AttributeError
Traceback (most recent call last):
File "/home/studio-lab-user/content/x1101/modules/options.py", line 140, in set
option.onchange()
File "/home/studio-lab-user/content/x1101/modules/call_queue.py", line 13, in f
res = func(*args, **kwargs)
File "/home/studio-lab-user/content/x1101/modules/initialize_util.py", line 170, in
shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
File "/home/studio-lab-user/content/x1101/modules/sd_models.py", line 741, in reload_model_weights
state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
File "/home/studio-lab-user/content/x1101/modules/sd_models.py", line 315, in get_checkpoint_state_dict
res = read_state_dict(checkpoint_info.filename)
File "/home/studio-lab-user/content/x1101/modules/sd_models.py", line 301, in read_state_dict
sd = get_state_dict_from_checkpoint(pl_sd)
File "/home/studio-lab-user/content/x1101/modules/sd_models.py", line 245, in get_state_dict_from_checkpoint
pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by alexeyugn** [comment]
My Automatic 1111 is also crashing when trying to use the model created here

**Comment by AndreyKuznecov** [comment]
I got the same error when loading tomorrow trained checkpoints, reinstalling automatic1111 didn't help. Trained a week ago models are loaded fine

**Comment by narsone** [comment]
Same problem. Reinstall Automatic 1111 and update didn't help.

**Comment by poodlesarecool** [comment]
> I got the same error when loading tomorrow trained checkpoints, reinstalling automatic1111 didn't help. Trained a week ago models are loaded fine

Same here. My trainings from a few weeks ago work fine, as well. I've tried the new training on 2 different machines (Mac and PC) and same error.
