### ISSUE TITLE
Load model failed

### ISSUE THREAD

**Issue by SpiritBeast** [TheLastBen/fast-stable-diffusion#2633]
after the last notebook update the model I trained failed to load & show this error AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by TheLastBen** [comment]
I'll investigate

**Comment by SpiritBeast** [comment]
thx

**Comment by TheLastBen** [comment]
just tested it, it works fine

**Comment by SpiritBeast** [comment]
Did you tested it on local or using other notebook?
it works fine when i run Test The Trained Model cell, but it's error on other stable diffusion colab & when i load it on local stable diffusion

**Comment by TheLastBen** [comment]
then the issue is with the other notebook and your local installation, I've tested it with the latest A1111 and it works, make sure you don't have any intruding extension

**Comment by SpiritBeast** [comment]
It still doesn't works even i tried reinstall Automatic 1111 and only have controlnet extension,
it seems there're several ppl facing the same problem https://github.com/TheLastBen/fast-stable-diffusion/issues/2631

**Comment by narsone** [comment]
I have the same error on my local Automatic1111 installation. I have reinstalled and updated but it still gives the same error when I try to load a model made this week.
Console output:

changing setting sd_model_checkpoint to mirxl.ckpt: AttributeError
Traceback (most recent call last):
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\options.py", line 140, in set
    option.onchange()
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\initialize_util.py", line 170, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 741, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 315, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 301, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 245, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by TheLastBen** [comment]
have you tried with the latest notebook, there is a recent commit

**Comment by keymaster577** [comment]
I'm having the same issue. It's still happening with the latest notebook.

**Comment by narsone** [comment]
I trained a model today and the result is still the same:

changing setting sd_model_checkpoint to diaz.ckpt: AttributeError
Traceback (most recent call last):
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\options.py", line 140, in set
    option.onchange()
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\initialize_util.py", line 170, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 741, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 315, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 301, in read_state_dict
    sd = get_state_dict_from_checkpoint(pl_sd)
  File "C:\Users\pinca\OneDrive\Documentos\IA\sd.webui\webui\modules\sd_models.py", line 245, in get_state_dict_from_checkpoint
    pl_sd = pl_sd.pop("state_dict", pl_sd)
AttributeError: 'NoneType' object has no attribute 'pop'

**Comment by Gregorio305** [comment]
> have you tried with the latest notebook, there is a recent commit

It's still error with the latest notebook

**Comment by Super-zapper** [comment]
problem still here

**Comment by narsone** [comment]
The problem seems to be with Automatic 1111. I've been trying other UIs like SDNext or StableSwarmUI and they load the .ckpt file without problems. If I transform the .ckpt file to safetensors, Automatic 1111 also loads it without problems.  This is what I have been able to deduce by doing a little research. I don't know what it means but it works for me.

**Comment by mertayd0** [comment]
any update?
