### ISSUE TITLE
in paperspace... upgrading torch with only one notebook

### ISSUE THREAD

**Issue by CoqueTornado** [TheLastBen/fast-stable-diffusion#2634]
Actually my notebook has torch: 1.13.1+cu116
I would like to upgrade it to  torch: 2.0.1+cu118 without starting from scratch a new notebook due to the extensions and Loras I have installed

Is it there any kind of way? I do not understand how you made the magic to import the files so I do not know how to fix this like you did in the 

I already tried to pip install torch using the terminal of paperspace but:
"pip command is being run as the root user, which can cause issues with permissions and conflicts with the system package manager. It is recommended to use a virtual environment instead, as suggested in the warning message." 
So if you can provide me any way to make the notebook upgraded magically without having to delete this and make a new one with the newest torch it would be really nice.

I have tried this
 !pip install lmdb
!pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 torchtext==0.15.2+cpu torchdata==0.6.1 --index-url https://download.pytorch.org/whl/cu118

but I made it worse...

Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/notebooks/sd/stable-diffusion-webui/modules/initialize.py", line 16, in imports
    import pytorch_lightning  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/imports.py", line 153, in <module>
    _TORCHTEXT_LEGACY: bool = _TORCHTEXT_AVAILABLE and _compare_version("torchtext", operator.lt, "0.11.0")
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/utilities/imports.py", line 71, in _compare_version
    pkg = importlib.import_module(package)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/usr/local/lib/python3.9/dist-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/usr/local/lib/python3.9/dist-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.9/dist-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/dist-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorElN3c106SymIntE

so... here I am now. Lot of fun!

 
 Thank you for your amazing work to the world

**Comment by TheLastBen** [comment]
Paperspace is working on a new docker image that will have the latest torch and python
