### ISSUE TITLE
ModuleNotFoundError: No module named "*******"

### ISSUE THREAD

**Issue by iaclaudioia8** [TheLastBen/fast-stable-diffusion#2643]
I have issues loading some extensions, there are 3 different extensions getting the same issue: 

"ModuleNotFoundError: No module named"

First one:

Civitai Helper: Get Custom Model Folder
*** Error loading script: clip_interrogator_ext.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/clip-interrogator-ext/scripts/clip_interrogator_ext.py", line 10, in <module>
        import clip_interrogator
    **ModuleNotFoundError: No module named 'clip_interrogator'**

Second one:

*** Error loading script: iib_setup.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib_setup.py", line 1, in <module>
        from scripts.iib.api import infinite_image_browsing_api, send_img_path
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-infinite-image-browsing/scripts/iib/api.py", line 52, in <module>
        from functional import seq
    **ModuleNotFoundError: No module named 'functional'**

and the last one:

Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/inpaint_anything.py", line 20, in <module>
        from lama_cleaner.model_manager import ModelManager
    **ModuleNotFoundError: No module named 'lama_cleaner'**

Any suggestion on how could I fix it? please :)

**Comment by TheLastBen** [comment]
I'll look into it

**Comment by iaclaudioia8** [comment]
I figured out that if I delete the extension and install it again, I can make it works, if you want i can make any test o check anything let me know :)
