### ISSUE TITLE
Dynamic prompts stopped work

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2646]
The extension Dynamic Prompts has stopped working again.  I'm using Google Colab.  I've tried all the normal tricks.  I deleted the folders from my Google Drive and turned off the extension in A1111.  Then I started everything over.  Still get the same error.  Everything in brackets just gets treated like normal text (so A1111 thinks I want all the options).  I do have this line of code in the "requirements" cell:

!pip install 'dynamicprompts[attentiongrabber,magicprompt]==0.29.0'

this has helped in the past so I don't think that is a problem.  I had previously gotten an error saying I needed to run that and when I added it, it fixed things.  Otherwise my cells are all as you made them.  Below is the error I get when I try to use a prompt that has dynamic prompts in them.  Any ideas?  As usual, I am happy to support you if you can help me fix this.  Thanks.

Error running process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/dynamic_prompting.py", line 485, in process
        all_prompts, all_negative_prompts = generate_prompts(
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-dynamic-prompts/sd_dynamic_prompts/helpers.py", line 97, in generate_prompts
        all_negative_prompts = negative_prompt_generator.generate(
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/generators/randomprompt.py", line 67, in generate
        gen = self._context.sample_prompts(template, num_images)
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/sampling_context.py", line 119, in sample_prompts
        command = parse(prompt, parser_config=self.parser_config)
      File "/usr/local/lib/python3.10/dist-packages/dynamicprompts/parser/parse.py", line 454, in parse
        tokens = get_cached_parser(parser_config).parse_string(
      File "/usr/local/lib/python3.10/dist-packages/pyparsing/core.py", line 1197, in parse_string
        raise exc.with_traceback(None)
    pyparsing.exceptions.ParseException: Expected end of text, found '{'  (at char 31), (line:1, col:32)

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by mdlieber99** [comment]
Thanks!

**Comment by mdlieber99** [comment]
Any ideas on this?

**Comment by mdlieber99** [comment]
I even tried re-installing stable diffusion from scratch and it is still not accepting dynamic prompts or wildcards

**Comment by mdlieber99** [comment]
Have you been able to look into this?  My entire workflow is stopped until I resolve this and I've tried everything I can think of.  Both wildcards and dynamic prompts have stopped working.

**Comment by mdlieber99** [comment]
And now it is working again.  I have no idea why.

**Comment by ArtHommage** [comment]
I get a warning from the GUI that there is an incorrect installation. When I have removed the folder from the extensions, and reinstalled it fresh, and rebooted the GUI, it works, and will over several restarts of the UI. It seems to be something is destroyed during the install or requirements stages from my testing, that leaves it inoperable.

**Comment by GlowlightUltro** [comment]
Sorry for necro'ing, but this is one of the first results when searching for this error, and the answer is simple:
Your prompt is broken, which the last part of the error message in your command line interface window indicates.
`ParseException: Expected end of text, found '{' (at char 31), (line:1, col:32)`
You're probably missing an end bracket. I had this same problem, because I used a % sign, which is not allowed, and didn't figure it out, until I checked the command line interface window and saw the error.
