### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by norfuer** [TheLastBen/fast-stable-diffusion#2647]
Please help... I don't know anything about coding and I don't understand any of this. This keeps popping up every time I try to do something. From switching checkpoints, to saving settings, and trying to generate stuff. It's slowed down my workflow very badly. =/

What should I be doing about it? Is there anything I can do?

```
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /content/gdrive/MyDrive/sd/stable-diffusion-webui/cache/hub/checkpoints/checkpoint_liberty_with_aug.pth
100% 5.10M/5.10M [00:00<00:00, 53.2MB/s]
Calculating sha256 for /content/gdrive/MyDrive/AniPlusv2/aniplusv2-final.ckpt: Running on public URL: https://df0c77063f24b32dca.gradio.live/
✔ Connected
Startup time: 45.6s (import torch: 13.7s, import gradio: 2.3s, setup paths: 3.8s, initialize shared: 0.5s, other imports: 2.9s, setup codeformer: 0.5s, list SD models: 6.6s, load scripts: 1.8s, create ui: 1.3s, gradio launch: 11.9s, add APIs: 0.1s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 225, in run_asgi
    result = await [self.app](http://self.app/)(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 26, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 26, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 76, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 26, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await [self.app](http://self.app/)(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 341, in handle
    await [self.app](http://self.app/)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 604, in join_queue
    session_info = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
```

**Comment by TheLastBen** [comment]
that's gdrive issue not related to the notebook

**Comment by norfuer** [comment]
Ah, I see. Now I understand. Thanks for getting back to me! I guess I'll try to figure something out...
