### ISSUE TITLE
error ImportError: cannot import name 'ComponentDefinitionError' from 'gradio.exceptions'

### ISSUE THREAD

**Issue by iaclaudioia8** [TheLastBen/fast-stable-diffusion#2664]
Hi all,

Any suggestion?

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 34, in <module>
    from gradio.layouts import Column, Form, Row
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts/__init__.py", line 1, in <module>
    from .accordion import Accordion
  File "/usr/local/lib/python3.10/dist-packages/gradio/layouts/accordion.py", line 8, in <module>
    from gradio.component_meta import ComponentMeta
  File "/usr/local/lib/python3.10/dist-packages/gradio/component_meta.py", line 12, in <module>
    from gradio.exceptions import ComponentDefinitionError
ImportError: cannot import name 'ComponentDefinitionError' from 'gradio.exceptions' (/usr/local/lib/python3.10/dist-packages/gradio/exceptions.py)

I have tryed: !pip install gradio
but nothing :(

**Comment by TheLastBen** [comment]
use the latest notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
