### ISSUE TITLE
wave2lip extension

### ISSUE THREAD

**Issue by Sadrahel** [TheLastBen/fast-stable-diffusion#2667]
Hi 
Like some other extension, when relaunch the colab : 
*** Error loading script: ui.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/ui.py", line 7, in <module>
        from scripts.bark.tts import TTS
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/bark/tts.py", line 5, in <module>
        from bark.generation import (
    ModuleNotFoundError: No module named 'bark'

---
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/ui.py", line 7, in <module>
        from scripts.bark.tts import TTS
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/bark/tts.py", line 5, in <module>
        from bark.generation import (
    ModuleNotFoundError: No module named 'bark.generation'

thanx !!!

**Comment by TheLastBen** [comment]
`!pip install bark` should fix it

**Comment by Sadrahel** [comment]
Hey Ben !
I certainly don't have a high level of code, but I'm offended, I could have thought of it and tried!
Thank you it seems to work.
