### ISSUE TITLE
Paperspace - gradio queue/civitai helper

### ISSUE THREAD

**Issue by sixpt** [TheLastBen/fast-stable-diffusion#2673]
Civitai Helper can't fetch preview images or json data from Civitai when running on Paperspace. I made the switch from Colab a few weeks ago, and it worked fine on Colab.

**Upon startup of Automatic1111:**
✔ Connected
Civitai: Check resources for missing info files
Civitai: Check resources for missing preview images
Startup time: 19.8s (import torch: 4.2s, import gradio: 1.0s, setup paths: 1.1s, initialize shared: 0.1s, other imports: 1.2s, setup codeformer: 0.2s, list SD models: 0.3s, load scripts: 5.0s, initialize extra networks: 0.4s, create ui: 5.7s, gradio launch: 0.2s).
Civitai: Found 250 resources missing preview images
Civitai: Found 142 resources missing info files
Civitai: Failed to fetch preview images from Civitai
Civitai: Failed to fetch info from Civitai
Applying attention optimization: xformers... done.
Model loaded in 12.6s (load weights from disk: 5.3s, create model: 1.1s, apply weights to model: 5.0s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.9s).

**When I try to manually scan within the Civitai Helper extension tab in Automatic1111:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1115, in call_function
    raise ValueError("Need to enable queue to use generators.")
ValueError: Need to enable queue to use generators.

**Comment by TheLastBen** [comment]
using gradio queue causes issues with paperspace, but that might change in the future
