### ISSUE TITLE
fast-dreambooth colab broken

### ISSUE THREAD

**Issue by gimpycpu** [TheLastBen/fast-stable-diffusion#2683]
```
"WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 2.1.0+cu118 with CUDA 1106 (you have 2.1.0+cu121)
Python 3.9.16 (you have 3.10.12)
Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)"
```

I tried everything that was posted in the other issue but everything is mixed up between dreambooth and fast-a1111 and all solution posted there did not seem to fix the issue at all so I decided to start a new thread only for dreambooth. If anyone figure out the solution it would be amazing.

**Comment by bejaranoo** [comment]
same here, was working fine last week

**Comment by Maxpoetica** [comment]
The same here. I cant live without my colab hope its fixed soon.

**Comment by anjst** [comment]
same here as well, tried this code below, but not working. Need other solution.

!pip install lmdb
!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118 xformers

**Comment by robempire** [comment]
> > same here as well, tried this code below, but not working. Need other solution.
> > !pip install lmdb !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118 xformers
> 
> Both Automatic1111 and dreambooth are down. Im breaking into sweats.

As is the kohya Lora Dreambooth trainer, don't know if that suggests any root cause(s).

**Comment by sahilsingh2402** [comment]
```
!pip install lmdb
!pip install torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
!pip install -U clean-fid torchaudio torchdata torchvision torchtext
!pip install xformers --force --index-url https://download.pytorch.org/whl/cu121
!pip install -U bitsandbytes
```
Run this cell right before the training cell, it works for now.

**Comment by Djohnston1** [comment]
> ```
> !pip install lmdb
> !pip install torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
> !pip install -U clean-fid torchaudio torchdata torchvision torchtext
> !pip install xformers --force --index-url https://download.pytorch.org/whl/cu121
> !pip install -U bitsandbytes
> ```
> 
> Run this cell right before the training cell, it works for now.

Confirmed working on colab fast-dreambooth. Thank you!

**Comment by bboytomato** [comment]
> ```
> !pip install lmdb
> !pip install torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
> !pip install -U clean-fid torchaudio torchdata torchvision torchtext
> !pip install xformers --force --index-url https://download.pytorch.org/whl/cu121
> !pip install -U bitsandbytes
> ```
> 
> Run this cell right before the training cell, it works for now.

worked for me, thank you

**Comment by Talionic** [comment]
> ```
> !pip install lmdb
> !pip install torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
> !pip install -U clean-fid torchaudio torchdata torchvision torchtext
> !pip install xformers --force --index-url https://download.pytorch.org/whl/cu121
> !pip install -U bitsandbytes
> ```
> 
> Run this cell right before the training cell, it works for now.

This works. Thanks

**Comment by bejaranoo** [comment]
> ```
> !pip install lmdb
> !pip install torch==2.1.2+cu121 --index-url https://download.pytorch.org/whl/cu121
> !pip install -U clean-fid torchaudio torchdata torchvision torchtext
> !pip install xformers --force --index-url https://download.pytorch.org/whl/cu121
> !pip install -U bitsandbytes
> ```
> 
> Run this cell right before the training cell, it works for now.

This is the way, can close this case.

**Comment by TheLastBen** [comment]
fixed

**Comment by sabahiya** [comment]
Not sure if I'm doing it wrong. But I got these error while running the cell:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires kaleido, which is not installed.
rembg 2.0.30 requires asyncer~=0.0.2, which is not installed.
rembg 2.0.30 requires filetype~=1.2.0, which is not installed.
rembg 2.0.30 requires imagehash~=4.3.1, which is not installed.
rembg 2.0.30 requires watchdog~=2.1.9, which is not installed.
tb-nightly 2.11.0a20221004 requires tensorboard-plugin-wit>=1.6.0, which is not installed.
tensorboard 2.10.1 requires tensorboard-plugin-wit>=1.6.0, which is not installed.
gcsfs 2023.6.0 requires fsspec==2023.6.0, but you have fsspec 2023.4.0 which is incompatible.
pydantic-core 2.6.1 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.4.0 which is incompatible.
rembg 2.0.30 requires fastapi~=0.87.0, but you have fastapi 0.94.0 which is incompatible.
rembg 2.0.30 requires numpy~=1.23.5, but you have numpy 1.24.1 which is incompatible.
rembg 2.0.30 requires onnxruntime~=1.13.1, but you have onnxruntime 1.14.1 which is incompatible.
rembg 2.0.30 requires opencv-python-headless~=4.6.0.66, but you have opencv-python-headless 4.8.1.78 which is incompatible.
rembg 2.0.30 requires pillow~=9.3.0, but you have pillow 9.4.0 which is incompatible.
rembg 2.0.30 requires pooch~=1.6.0, but you have pooch 1.8.0 which is incompatible.
rembg 2.0.30 requires scipy~=1.9.3, but you have scipy 1.11.4 which is incompatible.
rembg 2.0.30 requires tqdm~=4.64.1, but you have tqdm 4.66.1 which is incompatible.
rembg 2.0.30 requires uvicorn~=0.20.0, but you have uvicorn 0.18.3 which is incompatible.
tb-nightly 2.11.0a20221004 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 1.2.0 which is incompatible.
tb-nightly 2.11.0a20221004 requires tensorboard-data-server<0.7.0,>=0.6.0, but you have tensorboard-data-server 0.7.2 which is incompatible.
tensorboard 2.10.1 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 1.2.0 which is incompatible.
tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
tensorboard 2.10.1 requires tensorboard-data-server<0.7.0,>=0.6.0, but you have tensorboard-data-server 0.7.2 which is incompatible.
tensorboardx 2.5.1 requires protobuf<=3.20.1,>=3.8.0, but you have protobuf 3.20.3 which is incompatible.
tensorflow 2.15.0 requires tensorboard<2.16,>=2.15, but you have tensorboard 2.10.1 which is incompatible.
yfinance 0.2.33 requires requests>=2.31, but you have requests 2.28.2 which is incompatible.
Successfully installed MarkupSafe-2.1.3 filelock-3.9.0 fsspec-2023.4.0 jinja2-3.1.2 mpmath-1.3.0 networkx-3.0 numpy-1.24.1 sympy-1.12 torch-2.1.2+cu121 triton-2.1.0 typing-extensions-4.4.0 xformers-0.0.23.post1
WARNING: The following packages were previously imported in this runtime:
  [numpy]
You must restart the runtime in order to use newly installed versions.

**Comment by TheLastBen** [comment]
use the default unchanged colab, it will fix the issue

**Comment by sabahiya** [comment]
> use the default unchanged colab, it will fix the issue

Which one is that? This link?

https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by TheLastBen** [comment]
yes

**Comment by josemerinom** [comment]
#
!apt-get update
!apt-get install cuda-toolkit-11-8
import os
os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11/lib64"
os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11.8/lib64"
#
!pip install lmdb==1.4.1
!pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 torchtext==0.15.2+cpu torchdata==0.6.1 --index-url https://download.pytorch.org/whl/cu118
!pip install tensorflow==2.13.0
#

google: 
Python package upgrades
CUDA 11.8 to CUDA 12.2

reinstall previous version cuda-toolkit-11-8: this makes work bitsandbytes

**Comment by LIQUIDMIND111** [comment]
> fixed

hello ben, hope you had a great xmas season.... im trying to train on a 1024x1024 model using 1.5 base, and i get this error when UNET starts training:

Training the UNet...
'########:'########:::::'###::::'####:'##::: ##:'####:'##::: ##::'######:::
... ##..:: ##.... ##:::'## ##:::. ##:: ###:: ##:. ##:: ###:: ##:'##... ##::
::: ##:::: ##:::: ##::'##:. ##::: ##:: ####: ##:: ##:: ####: ##: ##:::..:::
::: ##:::: ########::'##:::. ##:: ##:: ## ## ##:: ##:: ## ## ##: ##::'####:
::: ##:::: ##.. ##::: #########:: ##:: ##. ####:: ##:: ##. ####: ##::: ##::
::: ##:::: ##::. ##:: ##.... ##:: ##:: ##:. ###:: ##:: ##:. ###: ##::: ##::
::: ##:::: ##:::. ##: ##:::: ##:'####: ##::. ##:'####: ##::. ##:. ######:::
:::..:::::..:::::..::..:::::..::....::..::::..::....::..::::..:::......::::

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 803, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 535, in main
    import bitsandbytes as bnb
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py", line 27, in initialize
    raise Exception('CUDA SETUP: Setup Failed!')
Exception: CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ZzZaZzZha_Jannett', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ZzZaZzZha_Jannett/instance_images', '--output_dir=/content/models/ZzZaZzZha_Jannett', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ZzZaZzZha_Jannett/captions', '--instance_prompt=', '--seed=46746', '--resolution=1024', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=2000']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
Try Runpod or Paperspace, they are easier and constantly maintained

**Comment by LIQUIDMIND111** [comment]
> Try Runpod or Paperspace, they are easier and constantly maintained

Interesting facts, when using COLLAB PRO: 

Using GPU A100, it will NOT load any base model for fine-tuning, will also give errors at training, 

using GPU V100 WILL load base model but gives error at training, CUDA setup error

Using GPU t4 will load PERFECT with no errors.... BUMMER, did google just restricted the GPUs?
