### ISSUE TITLE
Illustrations are not generated when I press generate

### ISSUE THREAD

**Issue by takku217** [TheLastBen/fast-stable-diffusion#2685]
First of all, please understand that I am Japanese and therefore my English is strange in places.
I was using TheLastBen's stable diffusion and got the following sentence and could not generate illustrations.
What should I do?

Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/taming-transformers/taming
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/codeformer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/blip/models/blip.py
Traceback (most recent call last):.
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 30, in imports
    import sgm.modules.encoders.modules # noqa: F401
ModuleNotFoundError: No module named 'sgm'.

**Comment by Maximb1985** [comment]
Hello, I am a paid user of google collab and paperspace. I have the same problem in google collab, I understand I need to install some XFORMERS, but I don't know where to find it and where to download it, I'm a regular user, I'm a grandfather.
paperspace has also stopped working and I am in a stupor.
Please help me.

**Comment by elBlacksmith** [comment]
> Hello, I am a paid user of google collab and paperspace. I have the same problem in google collab, I understand I need to install some XFORMERS, but I don't know where to find it and where to download it, I'm a regular user. paperspace has also stopped working and I am in a stupor. Please help me.

Execute all the cells of the Colab, then stop the "Start Stable-Diffusion" cell, write this on a new cell and execute it: 
`!pip install --pre -U xformers`
Then execute again the "Start Stable-Diffusion" cell.

**Comment by ApchDio** [comment]
> > Hello, I am a paid user of google collab and paperspace. I have the same problem in google collab, I understand I need to install some XFORMERS, but I don't know where to find it and where to download it, I'm a regular user. paperspace has also stopped working and I am in a stupor. Please help me.
> 
> Execute all the cells of the Colab, then stop the "Start Stable-Diffusion" cell, write this on a new cell and execute it: `!pip install --pre -U xformers` Then execute again the "Start Stable-Diffusion" cell.

not work

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
basicsr 1.4.2 requires lmdb, which is not installed.
gfpgan 1.3.8 requires lmdb, which is not installed.
clean-fid 0.1.31 requires requests==2.25.1, but you have requests 2.28.2 which is incompatible.
torchaudio 2.1.0+cu121 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
torchdata 0.7.0 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
torchtext 0.16.0 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
torchvision 0.16.0+cu121 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.

**Comment by takku217** [comment]
I asked LastBen directly and received the following response, which resolved the issue successfully!

use the latest notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_ AUTOMATIC1111.ipynb
and rename the folder named "sd" in your gdrive to "sd_old
