### ISSUE TITLE
Paperspace ControlNet issue

### ISSUE THREAD

**Issue by hugo-k-m** [TheLastBen/fast-stable-diffusion#2709]
I'm getting the following error when I run the final cell in Paperspace. The WebUI runs but the ConrolNet extension is completely gone.

```
Style database not found: /notebooks/sd/stable-diffusion-webui/styles.csv
Skipping broken symlink: /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors
Skipping broken symlink: /notebooks/sd/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-nonema-pruned.safetensors
[-] ADetailer initialized. version: 23.11.1, num models: 9
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████| 6/6 [00:00<00:00, 1588.55it/s]
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████| 6/6 [00:00<00:00, 4807.23it/s]
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 15, in <module>
        from scripts import external_code, global_state
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from scripts import global_state
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in <module>
        from scripts.enums import StableDiffusionVersion
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
        from scripts import external_code
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from scripts import global_state
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in <module>
        from scripts.enums import StableDiffusionVersion
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 14, in <module>
        from scripts import global_state, hook, external_code, batch_hijack, controlnet_version, utils
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in <module>
        from scripts.enums import StableDiffusionVersion
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
2023-12-31 15:55:07,111 - ControlNet - INFO - ControlNet v1.1.425
*** Error loading script: enums.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 846, in exec_module
      File "<frozen importlib._bootstrap_external>", line 983, in get_code
      File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from scripts import global_state
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in <module>
        from scripts.enums import StableDiffusionVersion
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: global_state.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in <module>
        from scripts.enums import StableDiffusionVersion
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: hook.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 10, in <module>
        from scripts.enums import ControlModelType, AutoMachine
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: infotext.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/infotext.py", line 7, in <module>
        from scripts import external_code
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from scripts import global_state
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in <module>
        from scripts.enums import StableDiffusionVersion
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
*** Error loading script: xyz_grid_support.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py", line 7, in <module>
        from scripts.global_state import update_cn_models, cn_models_names, cn_preprocessor_modules
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in <module>
        from scripts.enums import StableDiffusionVersion
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
        match self:
              ^
    SyntaxError: invalid syntax

---
Loading weights [None] from ....
```

**Comment by Archon332** [comment]
Same here. But txt2img still works.

**Comment by TheLastBen** [comment]
probably a python version issue

**Comment by hugo-k-m** [comment]
@TheLastBen Oh I see. Is something we can resolve on our side via a workaround or do we have to wait for Paperspace/A1111 to resolve it?

**Comment by hugo-k-m** [comment]
It seems to be resolved now, I'll close the issue. Thanks for your time.
