### ISSUE TITLE
Critical: Crashes on Runpod template

### ISSUE THREAD

**Issue by aleph65** [TheLastBen/fast-stable-diffusion#2755]
Runpod fast-stable-diffusion template crashes on a new instance. Please help fix. When I open the 3001 port it does not load the interface

Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /workspace/cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
100%|██████████████████████████████████████| 5.10M/5.10M [00:00<00:00, 16.5MB/s]
ControlNet preprocessor location: /workspace/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-03-02 07:27:06,054 - ControlNet - INFO - ControlNet v1.1.440
2024-03-02 07:27:06,414 - ControlNet - INFO - ControlNet v1.1.440
Calculating sha256 for /workspace/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors: 2024-03-02 07:27:07,132 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL: https://8t99af2pn2xcw3-3001.proxy.runpod.net/
✔ Connected
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 109, in webui
    ui.setup_ui_api(app)
  File "/workspace/sd/stable-diffusion-webui/modules/ui.py", line 1242, in setup_ui_api
    app.mount("/webui-assets", fastapi.staticfiles.StaticFiles(directory=launch_utils.repo_dir('stable-diffusion-webui-assets')), name="webui-assets")
  File "/usr/local/lib/python3.10/dist-packages/starlette/staticfiles.py", line 55, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/workspace/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets' does not exist
31e35c80fc4829d14f90153f4c74cd59c90b779f6afe05a74cd6120b893f7e5b
Loading weights [31e35c80fc] from /workspace/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors
Creating model from config: /workspace/sd/stablediffusion/generative-models/configs/inference/sd_xl_base.yaml
vocab.json: 100%|████████████████████████████| 961k/961k [00:00<00:00, 3.12MB/s]
merges.txt: 100%|████████████████████████████| 525k/525k [00:00<00:00, 1.69MB/s]
special_tokens_map.json: 100%|█████████████████| 389/389 [00:00<00:00, 2.78MB/s]
tokenizer_config.json: 100%|███████████████████| 905/905 [00:00<00:00, 7.26MB/s]
config.json: 100%|█████████████████████████| 4.52k/4.52k [00:00<00:00, 5.69MB/s]
Applying attention optimization: sdp... done.
Model loaded in 9.4s (calculate hash: 4.5s, create model: 3.1s, apply weights to model: 1.4s, calculate empty prompt: 0.1s).

**Comment by aleph65** [comment]
Resolved with this:

cd into /workspace/sd/stable-diffusion-webui/
mkdir repositories
cd repositories
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git
