### ISSUE TITLE
Paperspace crash "TypeError"

### ISSUE THREAD

**Issue by Davidkon1313** [TheLastBen/fast-stable-diffusion#2757]
Have this error while trying to start machine:

No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu116. You might want to consider upgrading.
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/notebooks/sd/stable-diffusion-webui/modules/initialize.py", line 36, in imports
    shared_init.initialize()
  File "/notebooks/sd/stable-diffusion-webui/modules/shared_init.py", line 40, in initialize
    from modules import styles
  File "/notebooks/sd/stable-diffusion-webui/modules/styles.py", line 9, in <module>
    class PromptStyle(typing.NamedTuple):
  File "/notebooks/sd/stable-diffusion-webui/modules/styles.py", line 11, in PromptStyle
    prompt: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by TheLastBen** [comment]
working on it
