### ISSUE TITLE
Getting disconnected 30s after initiating web ui, even with google collab pro subscription

### ISSUE THREAD

**Issue by LoynisSilver** [TheLastBen/fast-stable-diffusion#2763]
title

**Comment by AYKIQ** [comment]
I have exactly the same problem.

**Comment by wlvchandler** [comment]
Applying attention optimization: xformers... done.
2024-03-02 19:52:46,841 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL: https://returned-implementation-bp-unsigned.trycloudflare.com/
✔ Connected
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 109, in webui
    ui.setup_ui_api(app)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1242, in setup_ui_api
    app.mount("/webui-assets", fastapi.staticfiles.StaticFiles(directory=launch_utils.repo_dir('stable-diffusion-webui-assets')), name="webui-assets")
  File "/usr/local/lib/python3.10/dist-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets' does not exist


error mesage I'm seeing, two different Colabs (both Pro), after deleting old SD directory

**Comment by LoynisSilver** [comment]
I deleted everything I had in my drive and let the colab do a clean install to see if it was some sphagetti happening, but nope....
I still get disconnected in less than 30s.

This is just like what happened during the free users crackdown in google colab, except that now I have pro....

 So there must be something going on, right? There's no way google colab is just disabling stable diffusion entirely right?

Can someone else use TheLastBen's colab right now, at all?

**Comment by LoynisSilver** [comment]
I just now got this line in the code of "start webui": terminate called without an active exception

It appeared right as the web ui got disconnected.

This time I got to start generating an image, while before I never reached that point.

**Comment by gilroff** [comment]
> I deleted everything I had in my drive and let the colab do a clean install to see if it was some sphagetti happening, but nope.... I still get disconnected in less than 30s.
> 
> This is just like what happened during the free users crackdown in google colab, except that now I have pro....
> 
> So there must be something going on, right? There's no way google colab is just disabling stable diffusion entirely right?
> 
> Can someone else use TheLastBen's colab right now, at all?

Automatic webui got updated. it broke something in the notebook I think.

**Comment by VedanthB** [comment]
I am facing the same problem

**Comment by da-art-fantasy** [comment]
I am facing the same problem
