### ISSUE TITLE
Unable to run AnimateDiff getting error "AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'"

### ISSUE THREAD

**Issue by dreamlogic-X** [TheLastBen/fast-stable-diffusion#2768]
Hi I am having an issue with running the animatediff extension in Automatic1111 in Paperspace.

The error I get within Automatic1111 is "AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'". Below is the terminal log.

Wondering if It might be an issue with the torch version, or something related to this repo?

Thanks

---
2024-03-03 14:21:37,915 - AnimateDiff - INFO - AnimateDiff process start.
2024-03-03 14:21:37,916 - AnimateDiff - INFO - Loading motion module mm_sd15_v3.safetensors from /notebooks/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/model/mm_sd15_v3.safetensors
2024-03-03 14:21:37,931 - AnimateDiff - INFO - Guessed mm_sd15_v3.safetensors architecture: MotionModuleType.AnimateDiffV3
2024-03-03 14:21:40,933 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet input blocks.
2024-03-03 14:21:40,934 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet output blocks.
2024-03-03 14:21:40,934 - AnimateDiff - INFO - Setting DDIM alpha.
2024-03-03 14:21:40,937 - AnimateDiff - INFO - Injection finished.
2024-03-03 14:21:40,937 - AnimateDiff - INFO - AnimateDiff + ControlNet will generate 16 frames.
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2024-03-03 14:21:41,122 - AnimateDiff - WARNING - Failed to get git tag for AnimateDiff: Command '['git', '-C', '/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/model', 'describe', '--tags']' returned non-zero exit status 128.
  0%|                                                    | 0/20 [00:00<?, ?it/s]2024-03-03 14:21:41,182 - AnimateDiff - INFO - inner model forward hooked
  0%|                                                    | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(08mwxvkg79dspoc)', <gradio.routes.Request object at 0x7f9e1a656520>, 'cat', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 768, 432, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.animatediff_ui.AnimateDiffProcess object at 0x7f9e1bd990a0>, UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/notebooks/sd/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/modules/txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 785, in process_images
        res = process_images_inner(p)
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 48, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 921, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 1257, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 234, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 234, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
        return func(*args, **kwargs)
      File "/notebooks/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_samplers_cfg_denoiser.py", line 237, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_infv2v.py", line 151, in mm_sd_forward
        out = self.original_forward(
      File "/notebooks/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "/notebooks/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 18, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_hijack_utils.py", line 32, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/notebooks/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 1329, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/modules/sd_unet.py", line 91, in UNetModel_forward
        return original_forward(self, x, timesteps, context, *args, **kwargs)
      File "/notebooks/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 776, in forward
        h = module(h, emb, context)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 86, in forward
        x = layer(x)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 132, in forward
        return self.temporal_transformer(x)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 190, in forward
        hidden_states = block(hidden_states)
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 244, in forward
        hidden_states = attention_block(norm_hidden_states) + hidden_states
      File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-animatediff/motion_module.py", line 341, in forward
        x = torch.nn.functional.scaled_dot_product_attention(q, k, v)
    AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'

---

**Comment by pdannell** [comment]
Yes, from what I gathered the Torch version on this repo is out of date for the newer Animatediff models like you said. I think TheLastben had posted it was a paperspace issue originally.

I know of one other Repo that currently has 2.0+ that I haven't tried, but am not sure of any other easy Paperspace ones.

**Comment by pdannell** [comment]
Note, thanks to Srage(https://github.com/TheLastBen/fast-stable-diffusion/issues/2670#issuecomment-1983323737), he has the command needed to raise the torch version to the right one to run Animated diff.

However, if you update it and use the latest module then you get stuck with the following error:
 * NansException: A tensor with all NaNs was produced in VAE. Use --disable-nan-check commandline argument to disable this check.

> Here's a workaround.
>     1) Run the notebook as usual.
>     2) Open a terminal from the icon on the left menu bar.
>     3) Paste this and press enter: pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 xformers==0.0.23post1
>     4) Restart the kernel and rerun the notebook. The updated packages will now persist.

**Comment by pdannell** [comment]
@dreamlogic-X, if you strictly just want to run AnimateDiff as a note, the versions for comfyUI don't appear to have any issues in the meantime just as a heads up.

**Comment by dreamlogic-X** [comment]
Hi @pdannell thanks for your help... I've been using the repo of Stable Diffusion/animatediff before things were broken (I had a backup) and that's working for me. Although not updating is not the best solution. 

Unfortunately now ComfyUI doesn't want to load... https://github.com/TheLastBen/fast-stable-diffusion/issues/2786

Same on your end?
