### ISSUE TITLE
ModuleNotFoundError: No module named 'spandrel'

### ISSUE THREAD

**Issue by skjcs355062** [TheLastBen/fast-stable-diffusion#2771]
happened when using Hires. fix

Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 785, in process_images
        res = process_images_inner(p)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 921, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1273, in sample
        return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1322, in sample_hr_pass
        image = images.resize_image(0, image, target_width, target_height, upscaler_name=self.hr_upscaler)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 286, in resize_image
        res = resize(im, width, height)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 278, in resize
        im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/upscaler.py", line 65, in upscale
        img = self.do_upscale(img, selected_model)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/realesrgan_model.py", line 39, in do_upscale
        model_descriptor = modelloader.load_spandrel_model(
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 149, in load_spandrel_model
        import spandrel
    ModuleNotFoundError: No module named 'spandrel'

**Comment by dazaibsd** [comment]
Same!

**Comment by DeAiArt** [comment]
Same issue with google colap pro...

Where do I have to enter "pip install spandrel"?

**Comment by KyotoLyon** [comment]
same

**Comment by A3734** [comment]
me too. Could you please provide the installation code and location.

**Comment by dazaibsd** [comment]
This is how I did it on Runpod, I'm not sure if it works the same on Colab:

1)Click on the terminal
2)Paste "pip install spandrel"
3) Press Enter
I'm almost sure that the installation path doesn't matter, as I've done it twice in random folders and it worked both times, and there didn't seem to be anything new in the folders. I suppose it's because the command updates something. I repeat, this last part I mentioned is just my assumption since I'm not an expert
![1](https://github.com/TheLastBen/fast-stable-diffusion/assets/128887388/0b52c4ab-a876-45af-9f8b-34775af606c7)
![2](https://github.com/TheLastBen/fast-stable-diffusion/assets/128887388/901e5ff7-180f-42ac-91ee-1e6b62b874ff)
![3](https://github.com/TheLastBen/fast-stable-diffusion/assets/128887388/9e82e046-a63c-49a3-a459-113152824091)

**Comment by A3734** [comment]
I believe on Google Colab, resolving it as follows would be appropriate: Install spandrel underneath the Control Net, as shown in the image.　ESRGAN folder has also been created.
![spandrel](https://github.com/TheLastBen/fast-stable-diffusion/assets/155977409/a0cf5523-337f-4039-a0ac-4deaba88fe7a)

**Comment by afill86** [comment]
IMPORTANT for win(ComfyUI). Installed folders("spadrel" and "spadrel-0.x.x.dist-info") should be placed \ComfyUI_windows_portable\python_embeded\Lib\site-packages
