### ISSUE TITLE
Stable Diffusion model failed to load

### ISSUE THREAD

**Issue by mcqx4** [TheLastBen/fast-stable-diffusion#2774]
**UI loads, but then crashes**

File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 370, in load_model_weights
    if devices.fp8:
AttributeError: module 'modules.devices' has no attribute 'fp8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 36, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 55, in txt2img
    processed = processing.process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 737, in process_images
    sd_models.apply_token_merging(p.sd_model, 0)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 238, in sd_model
    return shared.sd_model
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared_items.py", line 128, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 621, in get_sd_model
    load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 749, in load_model
    load_model_weights(sd_model, checkpoint_info, state_dict, timer)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 370, in load_model_weights
    if devices.fp8:
AttributeError: module 'modules.devices' has no attribute 'fp8'

**Comment by skjcs355062** [comment]
Deleting the entire folder may help

**Comment by mcqx4** [comment]
> Deleting the entire folder may help

it worked! Thanks!

**Comment by Azura-13** [comment]
which folder?

**Comment by HaikenEdge** [comment]
> which folder?

The whole SD folder.

**Comment by Azura-13** [comment]
Yeah, kinda guessed It'd be that, was hoping not to have to do that... lol
Thanks for the reply =)

**Comment by D-usk** [comment]
I think I have a similar issue, Lora doesn't appears but models do, because I created a separated folder for models
