### ISSUE TITLE
Error in Spandrel, Restore Faces, and ESRGAN

### ISSUE THREAD

**Issue by KyotoLyon** [TheLastBen/fast-stable-diffusion#2778]
Hi! I need help with an error that appeared tonight. It was working normally, despite the errors of the last few days.

The following errors are showing:
ModuleNotFoundError: No module named 'spandrel'

To fix this error, I used the code !pip install spandrel

However, tonight, it started showing this error:

**100% 20/20 [00:01<00:00, 10.23it/s]
2024-03-07 03:35:33 WARNING [modules.modelloader] Model '/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/RealESRGAN/RealESRGAN_x4plus.pth' is not a 'ESRGAN' model (got <spandrel.architectures.ESRGAN.ESRGANArch object at 0x79e00d2f5870>)
tiled upscale100% 15/15 [00:01<00:00, 11.29it/s]
100% 20/20 [00:11<00:00,  1.73it/s]
2024-03-07 03:35:48 WARNING [modules.face_restoration_utils] Unable to load face-restoration model
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/face_restoration_utils.py", line 150, in restore_with_helper
    self.net = self.load_net()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/codeformer_model.py", line 37, in load_net
    return modelloader.load_spandrel_model(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 150, in load_spandrel_model
    model_descriptor = spandrel.ModelLoader(device=device).load_from_file(str(path))
  File "/usr/local/lib/python3.10/dist-packages/spandrel/__helpers/loader.py", line 44, in load_from_file
    return self.load_from_state_dict(state_dict)
  File "/usr/local/lib/python3.10/dist-packages/spandrel/__helpers/loader.py", line 81, in load_from_state_dict
    return self.registry.load(state_dict).to(self.device)
  File "/usr/local/lib/python3.10/dist-packages/spandrel/__helpers/registry.py", line 184, in load
    raise UnsupportedModelError
spandrel.__helpers.registry.UnsupportedModelError**

It doesn't generate the image correctly, especially the face, even with Restore Faces activated.
Is anyone else experiencing this error?
I've already done the procedures to fix the last errors, like deleting the folder and reinstalling (it was working until tonight).
I also used the code:

**!mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets

!cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git**

But nothing works. If I don't use the above code, the program doesn't even start.

Is anyone else experiencing the same problem? How to solve it?

**Comment by TheLastBen** [comment]
use the latest notebook
