### ISSUE TITLE
ModuleNotFoundError: No module named 'diskcache'

### ISSUE THREAD

**Issue by dymension** [TheLastBen/fast-stable-diffusion#2803]
It workef yesterday night, but this morning I have a sudden error message ending by **"ModuleNotFoundError: No module named 'diskcache'"**

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 26, in imports
    from modules import paths, timer, import_hook, errors  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 60, in <module>
    import sgm  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/__init__.py", line 2, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/models/__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/models/autoencoder.py", line 12, in <module>
    from ..modules.diffusionmodules.model import Decoder, Encoder
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/modules/__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "/content/gdrive/MyDrive/sd/stablediffusion/generative-models/sgm/modules/encoders/modules.py", line 5, in <module>
    import kornia
  File "/usr/local/lib/python3.10/dist-packages/kornia/__init__.py", line 10, in <module>
    from . import (
  File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/container/__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/container/augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "/usr/local/lib/python3.10/dist-packages/kornia/augmentation/container/patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "/usr/local/lib/python3.10/dist-packages/kornia/contrib/__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "/usr/local/lib/python3.10/dist-packages/kornia/contrib/image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "/usr/local/lib/python3.10/dist-packages/kornia/feature/__init__.py", line 4, in <module>
    from .integrated import (
  File "/usr/local/lib/python3.10/dist-packages/kornia/feature/integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "/usr/local/lib/python3.10/dist-packages/kornia/feature/integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "/usr/local/lib/python3.10/dist-packages/kornia/feature/hardnet.py", line 66, in __init__
    pretrained_dict = torch.hub.load_state_dict_from_url(
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 770, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location, weights_only=weights_only)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 133, in load_with_extra
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 6, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared_items.py", line 4, in <module>
    from modules import script_callbacks, scripts, ui_components
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 11, in <module>
    from modules import errors, timer, extensions, shared, util
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 9, in <module>
    from modules import shared, errors, cache, scripts
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/cache.py", line 6, in <module>
    import diskcache
ModuleNotFoundError: No module named 'diskcache'
```

I have no idea what happened during the night

**Comment by dymension** [comment]
OK, I solved this by just adding a line code into the collab sheet and writing:
`pip install diskcache`
Then run this line
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/1997716/ad84c23f-aab3-4e29-8787-6d1e3fef709a)

Everything is solved

**Comment by 70pice** [comment]
Can't use mov2mov

**Comment by EvilClivE** [comment]
> OK, I solved this by just adding a line code into the collab sheet and writing: **`pip install diskcache`**
> 
> Then run this line
> 
> ![image](https://private-user-images.githubusercontent.com/1997716/322186218-ad84c23f-aab3-4e29-8787-6d1e3fef709a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjc1NjMsIm5iZiI6MTcxMzAyNzI2MywicGF0aCI6Ii8xOTk3NzE2LzMyMjE4NjIxOC1hZDg0YzIzZi1hYWIzLTRlMjktODc4Ny02ZDFlM2ZlZjcwOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTNUMTY1NDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzdiNDZiNjk0ZDQwMjM1YmM5ZDJhYzFiNTg5OTMzM2FlYjdhNDU2MmFiZTU2YzU3YTgzMTMwNTFjNjNjMDFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZzpaYdoQ5MkeyEtoR3x6tKxAT8JzbS-6iMiXlm3vZfo)
> 
> Everything is solved

Thank you for sharing this quick fix! 👌😎👍- I too was also puzzled this morning when it had seemingly broken overnight!

**Comment by taron37** [comment]
I got a error when I code 'pip install diskcache'
What is wrong?

**File ["<ipython-input-8-c6b04668eb9e>"](https://localhost:8080/#), line 2
    pip install diskcache
        ^
SyntaxError: invalid syntax**

**Comment by EvilClivE** [comment]
> I got a error when I code 'pip install diskcache', just before "Start Stable-Diffusion" What is wrong?
> 
> **File [""](https://localhost:8080/#), line 2 pip install diskcache ^ SyntaxError: invalid syntax**

Yeah, I also got this syntax error at first too, but I'm not sure what causes it. Try disconnecting and deleting active runtime, then remove any spaces/empty code lines before and after the `pip install diskcache` code text. The syntax error highlight magically disappeared for me.

For testing, I just created a blank/new notebook and the syntax works fine when the cell is run. 🤔

**Comment by dymension** [comment]
Are you sure you add the command line as a new code block ?
You cann add code block by hovering an hidden line above each step (it's quite tricky)
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/1997716/44db3dbb-7ce4-4f2b-86f0-837cab97c230)



You can also try to add the line upper in the script.
I set it right after Automatic Install
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/1997716/051f822e-93b8-4747-bc4a-1297b56a8cfc)

**Comment by taron37** [comment]
> Yeah, I also got this syntax error at first too, but I'm not sure what causes it. Try disconnecting and deleting active runtime, then remove any spaces/empty code lines before and after the `pip install diskcache` code text. The syntax error highlight magically disappeared for me.
> 
> For testing, I just created a blank/new notebook and the syntax works fine when the cell is run. 🤔

I solved the problem to put "!" 

`!pip install diskcache`

**Comment by mcqx4** [comment]
> I got a error when I code 'pip install diskcache', just before "Start Stable-Diffusion" What is wrong?
> 
> **File [""](https://localhost:8080/#), line 2 pip install diskcache ^ SyntaxError: invalid syntax**

Use " !pip " instead of "pip"

**Comment by A3734** [comment]
"Running !pip install diskcache upgrades the module to version 1.9, it seems. However, several errors are occurring, and 'move2move' is throwing an error in 'm2m_ui.py', causing it to disappear from the module. "

**Comment by dymension** [comment]
Post your OK message and error message
