### ISSUE TITLE
*** Error creating infotext for key "Hires negative prompt"

### ISSUE THREAD

**Issue by katouemiria** [TheLastBen/fast-stable-diffusion#2804]
*** Error creating infotext for key "Hires negative prompt"
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 809, in create_infotext
        generation_params[key] = value(**locals())
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 1263, in get_hr_negative_prompt
        hr_negative_prompt = p.all_hr_negative_prompts[index]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'all_hr_negative_prompts'

I get this error message in the export code, even though the export itself works. However, what gets exported looks a bit off from what I expected. I'm looking for a solution to this issue.
Could someone please help me?

**Comment by dymension** [comment]
It los like you have an issue with you own NEG proompt
what's inside ?

**Comment by katouemiria** [comment]
Thank you for the update. I removed the code "pip install diskcache," which I was using to fix the error that emerged yesterday, and it resolved the issue. Interestingly, the "pip install diskcache" code is no longer needed and everything seems to be working fine now.

Thank you

**Comment by Vittey** [comment]
I have the same problem. Could you tell the detail about how you solve the problem? Thanks very much!

**Comment by katouemiria** [comment]
> I have the same problem. Could you tell the detail about how you solve the problem? Thanks very much!

When starting up, add this code snippet midway to download "pip install diskcache" during startup.

That alone should get it running once. Then, when things start to feel a bit off again, remove "pip install diskcache" altogether during startup.

That completely fixed it for me. I'm not sure exactly what the cause was.

**Comment by arthurh3535** [comment]
I have no idea what they are saying to fix this? Is there a step by step instruction?

**Comment by HeyBigZam** [comment]
> I have no idea what they are saying to fix this? Is there a step by step instruction?

I changed webui-user.bat to webui-user.ini 
Copy and pasted pip install diskcache in the middle
changed webui-user back to .bat and now it works

If you run into an error with stable diffusion and reddit/comments tell you to add a line, most times this is how you do it.

**Comment by arthurh3535** [comment]
Thank you very much, I hope it works.

**Comment by gilly2020** [comment]
> Thank you very much, I hope it works.

Didn't work for me unfortunately.
