### ISSUE TITLE
ImportError: cannot import name 'Undefined' from 'pydantic.fields' 

### ISSUE THREAD

**Issue by MarkusssJ** [TheLastBen/fast-stable-diffusion#2808]
I followed the instructions on Github to download Controlnet and when I reached 6. "Go to "Installed" tab, click "Check for updates", and then click "Apply and restart UI". (The next time you can also use these buttons to update ControlNet.)" nothing happened. I pressed apply and restart UI and it kept loading forever. After trying to launch stable diffusion again this showed up
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\AI\stable-diffusion\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "C:\AI\stable-diffusion\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "C:\AI\stable-diffusion\stable-diffusion-webui\modules\launch_utils.py", line 465, in start
    import webui
  File "C:\AI\stable-diffusion\stable-diffusion-webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\AI\stable-diffusion\stable-diffusion-webui\modules\initialize.py", line 23, in imports
    import gradio  # noqa: F401
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (C:\AI\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\pydantic\fields.py)

Before this I updated pip by typing -m pip install --upgrade pip but it didn't help. Can someone please help.

**Comment by yangzi7298** [comment]
the same error

**Comment by wuyulinjyj** [comment]
我和你一样遇到了这样的问题

**Comment by PhantomBeast3** [comment]
> Check here for local issues https://github.com/AUTOMATIC1111/stable-diffusion-webui

sorry, but i don't know where to look into in that link
