### ISSUE TITLE
Error loading script: inpaint_anything.py   :( 

### ISSUE THREAD

**Issue by AlfaShot111** [TheLastBen/fast-stable-diffusion#2811]
Can't use the "Inpaint Anything" extension.
https://github.com/Uminosachi/sd-webui-inpaint-anything.git

 In Colab at the "Start Stable-Diffusion" stage, it returns an error:

*** Error loading script: inpaint_anything.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-inpaint-anything/scripts/inpaint_anything.py", line 17, in <module>
        from diffusers import (DDIMScheduler, EulerAncestralDiscreteScheduler, EulerDiscreteScheduler,
      File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 27, in <module>
        from .pipelines import OnnxRuntimeModel
      File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/__init__.py", line 18, in <module>
        from .dance_diffusion import DanceDiffusionPipeline
      File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
        from .pipeline_dance_diffusion import DanceDiffusionPipeline
      File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
        from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
      File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 39, in <module>
        from ..models.modeling_utils import _LOW_CPU_MEM_USAGE_DEFAULT
      File "/usr/local/lib/python3.10/dist-packages/diffusers/models/__init__.py", line 31, in <module>
        from .unet_2d_condition_flax import FlaxUNet2DConditionModel
      File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition_flax.py", line 25, in <module>
        from .modeling_flax_utils import FlaxModelMixin
      File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_flax_utils.py", line 45, in <module>
        class FlaxModelMixin:
      File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_flax_utils.py", line 192, in FlaxModelMixin
        def init_weights(self, rng: jax.random.KeyArray) -> Dict:
      File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 54, in getattr
        raise AttributeError(f"module {module!r} has no attribute {name!r}")
    AttributeError: module 'jax.random' has no attribute 'KeyArray'

**Comment by navin-hariharan** [comment]
Traceback (most recent call last):
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\venv\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-webui-inpaint-anything\ia_threading.py", line 165, in wrapper
    res = func(*args, **kwargs)
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-webui-inpaint-anything\ia_threading.py", line 125, in wrapper
    res = func(*args, **kwargs)
  File "D:\DEV\AI-PROJECTS\stable-diffusion-webui-forge\extensions\sd-webui-inpaint-anything\scripts\inpaint_anything.py", line 207, in run_sam
    if sam_image["image"].shape == seg_image.shape and np.all(sam_image["image"] == seg_image):
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices




https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/9cb69baf9fcd0ac2847790555fc8ab603794f1b2
