### ISSUE TITLE
Paperspace - A1111 - Error

### ISSUE THREAD

**Issue by aleeepp** [TheLastBen/fast-stable-diffusion#2841]
Hello, I share some errors that are being generated in Paperspace in today's run that are new :)!

`No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu116. You might want to consider upgrading.
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 17, in <module>
        from scripts import external_code, global_state
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 52, in <module>
        class ControlNetUnit(BaseModel):
      File "pydantic/main.py", line 188, in pydantic.main.ModelMetaclass.__new__
      File "pydantic/typing.py", line 419, in pydantic.typing.resolve_annotations
      File "/usr/lib/python3.9/typing.py", line 292, in _eval_type
        return t._evaluate(globalns, localns, recursive_guard)
      File "/usr/lib/python3.9/typing.py", line 554, in _evaluate
        eval(self.__forward_code__, globalns, localns),
      File "<string>", line 1, in <module>
    TypeError: unsupported operand type(s) for |: 'type' and 'type'

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 5, in <module>
        from scripts import external_code
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 52, in <module>
        class ControlNetUnit(BaseModel):
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 80, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 88, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 147, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
ControlNet preprocessor location: /notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 18, in <module>
        from internal_controlnet.external_code import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 52, in <module>
        class ControlNetUnit(BaseModel):
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 80, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 88, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 147, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 52, in <module>
        class ControlNetUnit(BaseModel):
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 80, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 88, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 147, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: infotext.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/infotext.py", line 7, in <module>
        from internal_controlnet.external_code import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 52, in <module>
        class ControlNetUnit(BaseModel):
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 80, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 88, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 147, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: xyz_grid_support.py
    Traceback (most recent call last):
      File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py", line 8, in <module>
        from scripts.external_code import ResizeMode, ControlMode
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 52, in <module>
        class ControlNetUnit(BaseModel):
      File "/notebooks/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 80, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 88, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 147, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True``

**Comment by TheLastBen** [comment]
update the image by clicking update on the status bar, or build a fresh workspace/notebook

**Comment by aleeepp** [comment]
thank you so much! 30 minutes ago trying to find the upate button, is it inside JupyterLab? Or should the machine be stopped first? I'm lost and creating it from scratch is a big problem :)

**Comment by TheLastBen** [comment]
not in jupyter, in the start/stop machine in paperspace gradient

**Comment by shiliboXXX** [comment]
do you 

> thank you so much! 30 minutes ago trying to find the upate button, is it inside JupyterLab? Or should the machine be stopped first? I'm lost and creating it from scratch is a big problem :)

do you fixed?

**Comment by Arijit0** [comment]
Same problem. What to do? In Sagemaker studio lab

**Comment by SRagy** [comment]
I have this same issue. It doesn't seem to matter if I stop and restart the machine, use the latest notebooks or any of the 'I have no idea what's going on' fixes I normally try. Unfortunately, it is preventing me from using controlnet in Automatic1111.
