### ISSUE TITLE
The future belongs to a different loop than the one specified as the loop argument

### ISSUE THREAD

**Issue by djwashout** [TheLastBen/fast-stable-diffusion#2855]
I have been having this issue on google colab for a while now...

[-] ADetailer initialized. version: 24.5.1, num models: 10
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-06-23 06:12:44,333 - ControlNet - INFO - ControlNet v1.1.449
Loading weights [059934ff58] from /content/gdrive/MyDrive/data/Checkpoint/SDXL/ponyRealism_v21VAE.safetensors
2024-06-23 06:13:25,823 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Settings:
Civitai Helper: max_size_preview: True
Civitai Helper: skip_nsfw_preview: False
Civitai Helper: open_url_with_js: True
Civitai Helper: proxy: 
Civitai Helper: use civitai api key: True
*** Failed reading extension data from Git repository (sd-webui-controlnet)
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 166, in do_read_info_from_repo
        commit = repo.head.commit
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 217, in _get_commit
        obj = self._get_object()
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 210, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "/usr/local/lib/python3.10/dist-packages/git/objects/base.py", line 85, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/usr/local/lib/python3.10/dist-packages/git/db.py", line 43, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/gitpython_hack.py", line 18, in get_object_header
        ret = subprocess.check_output(
      File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.10/subprocess.py", line 505, in run
        stdout, stderr = process.communicate(input, timeout=timeout)
      File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/lib/python3.10/subprocess.py", line 2022, in _communicate
        self._check_timeout(endtime, orig_timeout, stdout, stderr)
      File "/usr/lib/python3.10/subprocess.py", line 1198, in _check_timeout
        raise TimeoutExpired(
    subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds

---
Running on public URL: https://5a152c8651bfc6e94b.gradio.live/
✔ Connected
Startup time: 194.8s (import torch: 14.2s, import gradio: 1.2s, setup paths: 2.2s, initialize shared: 0.5s, other imports: 2.9s, list SD models: 24.5s, load scripts: 57.7s, load upscalers: 1.1s, reload hypernetworks: 1.0s, initialize extra networks: 15.0s, scripts before_ui_callback: 2.7s, create ui: 47.9s, gradio launch: 17.2s, add APIs: 6.5s).
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/generative-models/configs/inference/sd_xl_base.yaml
Couldn't find VAE named sdxl_vae.safetensors; using None instead
Applying attention optimization: xformers... done.
Model loaded in 174.4s (load weights from disk: 99.3s, load config: 0.5s, create model: 4.7s, apply weights to model: 53.6s, move model to device: 0.1s, hijack: 0.4s, load textual inversion embeddings: 14.6s, calculate empty prompt: 1.2s).
The future belongs to a different loop than the one specified as the loop argument
The future belongs to a different loop than the one specified as the loop argument
The future belongs to a different loop than the one specified as the loop argument
The future belongs to a different loop than the one specified as the loop argument
The future belongs to a different loop than the one specified as the loop argument

**Comment by D-usk** [comment]
Just restart the WebUI interface, it happens to me too sometime

**Comment by ShinobiiSpartan** [comment]
> Just restart the WebUI interface, it happens to me too sometime

This might be a dumb question, but how exactly do I restart the Webui interface? Do I just refresh the page?

**Comment by djwashout** [comment]
if its ran locally you would exit out of the command prompt running the repo. in my case im on a google colab notebook and have to select edit, restart and run all.

**Comment by ShinobiiSpartan** [comment]
> if its ran locally you would exit out of the command prompt running the repo. in my case im on a google colab notebook and have to select edit, restart and run all.

thank you a lot, the problem fixed
