### ISSUE TITLE
Unable to start Comfy Paperspace notebook

### ISSUE THREAD

**Issue by dreamlogic-X** [TheLastBen/fast-stable-diffusion#2879]
Hi Ben,

I'm getting this running the Comfy notebook on a A6000.

I tried a fresh install and same thing.

Thanks for your help!

---

Total VRAM 48677 MB, total RAM 45140 MB
pytorch version: 2.1.1+cu121
xformers version: 0.0.23
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
Using xformers cross attention
Traceback (most recent call last):
  File "/notebooks/ComfyUI/main.py", line 80, in <module>
    import execution
  File "/notebooks/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/notebooks/ComfyUI/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/notebooks/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/notebooks/ComfyUI/comfy/sd.py", line 17, in <module>
    from . import model_detection
  File "/notebooks/ComfyUI/comfy/model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "/notebooks/ComfyUI/comfy/supported_models.py", line 10, in <module>
    import comfy.text_encoders.aura_t5
  File "/notebooks/ComfyUI/comfy/text_encoders/aura_t5.py", line 2, in <module>
    from transformers import LlamaTokenizerFast
ImportError: cannot import name 'LlamaTokenizerFast' from 'transformers' (/usr/local/lib/python3.11/dist-packages/transformers/__init__.py

**Comment by TheLastBen** [comment]
I'll fix it shortly

**Comment by peepeepoopooman654** [comment]
> I'll fix it shortly

same with a1111 as of yesterday. Gradio starts up but timeout immediately unable to generate anything.

**Comment by aleeepp** [comment]
Hello, same issue now in paperspacegradient

Thanks for your help!
----

Traceback (most recent call last):
  File "/notebooks/ComfyUI/main.py", line 132, in <module>
    import execution
  File "/notebooks/ComfyUI/execution.py", line 13, in <module>
    import nodes
  File "/notebooks/ComfyUI/nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "/notebooks/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/notebooks/ComfyUI/comfy/sd.py", line 21, in <module>
    from . import model_detection
  File "/notebooks/ComfyUI/comfy/model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "/notebooks/ComfyUI/comfy/supported_models.py", line 15, in <module>
    import comfy.text_encoders.hunyuan_video
  File "/notebooks/ComfyUI/comfy/text_encoders/hunyuan_video.py", line 4, in <module>
    from transformers import LlamaTokenizerFast
ImportError: cannot import name 'LlamaTokenizerFast' from 'transformers' (/usr/local/lib/python3.11/dist-packages/transformers/__init__.py)

**Comment by Arrozz11** [comment]
the same happens to me

**Comment by Arrozz11** [comment]
> Hello, same issue now in paperspacegradient
> 
> ## Thanks for your help!
> Traceback (most recent call last): File "/notebooks/ComfyUI/main.py", line 132, in import execution File "/notebooks/ComfyUI/execution.py", line 13, in import nodes File "/notebooks/ComfyUI/nodes.py", line 22, in import comfy.diffusers_load File "/notebooks/ComfyUI/comfy/diffusers_load.py", line 3, in import comfy.sd File "/notebooks/ComfyUI/comfy/sd.py", line 21, in from . import model_detection File "/notebooks/ComfyUI/comfy/model_detection.py", line 1, in import comfy.supported_models File "/notebooks/ComfyUI/comfy/supported_models.py", line 15, in import comfy.text_encoders.hunyuan_video File "/notebooks/ComfyUI/comfy/text_encoders/hunyuan_video.py", line 4, in from transformers import LlamaTokenizerFast ImportError: cannot import name 'LlamaTokenizerFast' from 'transformers' (/usr/local/lib/python3.11/dist-packages/transformers/**init**.py)

I solved it with !pip install --upgrade transformers

**Comment by aleeepp** [comment]
@Arrozz11 thank you very much, solved!!
