### ISSUE TITLE
Error loading script: controlnet.py

### ISSUE THREAD

**Issue by KyotoLyon** [TheLastBen/fast-stable-diffusion#2883]
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 16, in <module>
        import scripts.preprocessor as preprocessor_init  # noqa
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/__init__.py", line 9, in <module>
        from .mobile_sam import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/mobile_sam.py", line 1, in <module>
        from annotator.mobile_sam import SamDetector_Aux
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mobile_sam/__init__.py", line 12, in <module>
        from controlnet_aux import SamDetector
    ModuleNotFoundError: No module named 'controlnet_aux'

This error is happening repeatedly. I can open the SD, but it does not activate the Controlnet extension. How can I fix it?

**Comment by slap1996** [comment]
The same error here! Controlnet no longer appears in the webui :(

ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 16, in <module>
        import scripts.preprocessor as preprocessor_init  # noqa
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/__init__.py", line 9, in <module>
        from .mobile_sam import *
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/mobile_sam.py", line 1, in <module>
        from annotator.mobile_sam import SamDetector_Aux
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mobile_sam/__init__.py", line 12, in <module>
        from controlnet_aux import SamDetector
    ModuleNotFoundError: No module named 'controlnet_aux'

**Comment by mcqx4** [comment]
Guys! Are there any solutions yet?

**Comment by slap1996** [comment]
> Use command !pip install controlnet_aux above the Start Stable Diffusion cell and it should work!

It works! Thanks :)

-For those who don't know, above start stable diffusion between lines, if you place the cursor, a "+code" button appears, click on it and add the command:

!pip install controlnet_aux

**Comment by Miga1991** [comment]
> Use command !pip install controlnet_aux above the Start Stable Diffusion cell and it should work!

Thanks 👍

**Comment by hcatGitHub** [comment]
> -For those who don't know, above start stable diffusion between lines, if you place the cursor, a "+code" button appears, click on it and add the command:
> 
> !pip install controlnet_aux

Thanks for showing how to run the command.  It works. Does it mean I need to run the command every time I start a1111?

**Comment by KyotoLyon** [comment]
It worked here. Will I need to use this command every time?

**Comment by nqdior** [comment]
I am an Admin of the Japanese Stability AI user community. One user enquired about this issue, to which I responded.
He said that he had installed controlnet-aux and received the following error.

```python
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.26.post1 requires torch==2.3.0, but you have torch 2.3.1+cu121 which is incompatible.
```

This issue relates to the following tickets
https://github.com/facebookresearch/xformers/issues/1052

Response measures:
```python
!pip install xformers==0.0.27
!pip install controlnet-aux
```

regards,

**Comment by slap1996** [comment]
> > -For those who don't know, above start stable diffusion between lines, if you place the cursor, a "+code" button appears, click on it and add the command:
> > !pip install controlnet_aux
> 
> Thanks for showing how to run the command. It works. Does it mean I need to run the command every time I start a1111?



> It worked here. Will I need to use this command every time?

Apparently yes, I don't see that they have fixed it :/

@TheLastBen  

.

**Comment by brunovianna** [comment]
They fixed it in the last commit https://github.com/TheLastBen/fast-stable-diffusion/commit/8460e97693433001c3c65e81323384cd6c9da8b4

**Comment by AI3dgraphics** [comment]
> > Use command !pip install controlnet_aux above the Start Stable Diffusion cell and it should work!
> 
> Thanks 👍

can please someone exactly explain how to do this? where is the Start Stable Diffusion cell, how and where to add the command?

Thanks

**Comment by brunovianna** [comment]
> > > Use command !pip install controlnet_aux above the Start Stable Diffusion cell and it should work!
> > 
> > 
> > Thanks 👍
> 
> can please someone exactly explain how to do this? where is the Start Stable Diffusion cell, how and where to add the command?
> 
> Thanks

I don't think this has been updated in a while... It would take some effort to get it work with Colab current version :/

**Comment by AI3dgraphics** [comment]
thanks for answer. I don´t reaööy understad: Colab current version?

**Comment by AI3dgraphics** [comment]
some people wrote here that they got ride of the issue by Use command !pip install controlnet_aux above the Start Stable Diffusion cell. i don´t know at all how to do that.

I think is the same issue independently of the version!

**Comment by danyalazarii-source** [comment]
how can do it please explain

**Comment by danyalazarii-source** [comment]
I have this problem 

ControlNet preprocessor location: D:\1software\1Ai\ok\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "D:\1software\1Ai\ok\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\1software\1Ai\ok\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\1software\1Ai\ok\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 16, in <module>
        import scripts.preprocessor as preprocessor_init  # noqa
      File "D:\1software\1Ai\ok\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\preprocessor\__init__.py", line 9, in <module>
        from .mobile_sam import *
      File "D:\1software\1Ai\ok\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\preprocessor\mobile_sam.py", line 1, in <module>
        from annotator.mobile_sam import SamDetector_Aux
      File "D:\1software\1Ai\ok\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mobile_sam\__init__.py", line 12, in <module>
        from controlnet_aux import SamDetector
      File "D:\1software\1Ai\ok\stable-diffusion-webui\venv\lib\site-packages\controlnet_aux\__init__.py", line 11, in <module>
        from .mediapipe_face import MediapipeFaceDetector
      File "D:\1software\1Ai\ok\stable-diffusion-webui\venv\lib\site-packages\controlnet_aux\mediapipe_face\__init__.py", line 9, in <module>
        from .mediapipe_face_common import generate_annotation
      File "D:\1software\1Ai\ok\stable-diffusion-webui\venv\lib\site-packages\controlnet_aux\mediapipe_face\mediapipe_face_common.py", line 16, in <module>
        mp_drawing = mp.solutions.drawing_utils
    AttributeError: module 'mediapipe' has no attribute 'solutions'

**Comment by diegoloredo3dc** [comment]
En esta página me solucionó el problema.. saludos..

https://www.oldmoon.top/post/477#google_vignette
