### ISSUE TITLE
(HELP) Cannot Launch Testing of Trained Model

### ISSUE THREAD

**Issue by attilasark** [TheLastBen/fast-stable-diffusion#2889]
So after i make all the right steps this is the response after i try to test the trained model, 
( i downloaded the 1.5 stable diffusion and trained it successfully ) : 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 22, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 34, in <module>
    from gradio import media_data, processing_utils, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 23, in <module>
    from gradio import encryptor, utils
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 38, in <module>
    import aiohttp
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 59, in <module>
    from .client_reqrep import (
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path
  File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/usr/local/lib/python3.10/dist-packages/charset_normalizer/cd.py", line 9, in <module>
    from .md import is_suspiciously_successive_range
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

**Comment by TheLastBen** [comment]
try `pip install cchardet`

**Comment by attilasark** [comment]
If you could write down the steps on how to do that , it would be really helpful, thanks.

**Comment by attilasark** [comment]
Did it and got this error now: 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 28, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 12, in <module>
    import modules.interrogate
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 7, in <module>
    from basicsr.utils.download_util import load_file_from_url
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

**Comment by emilkromminga** [comment]
Same problem here

**Comment by noiseorigin** [comment]
same here

**Comment by seandelargy** [comment]
same

**Comment by sethcwhiting** [comment]
I finally got it running after entering the following into the terminal:
```
pip install charset_normalizer==3.2.0 aiohttp==3.8.5 torch==1.12.1 torchvision==0.13.1
pip cache purge
```
Not sure if the 2nd part is necessary, but it doesn't hurt.

I get some warnings/ incompatibility errors, but I just ignored them and it does actually end up running for me. Hopefully it will run for you too.
