### ISSUE TITLE
Colab Error

### ISSUE THREAD

**Issue by Glup30** [TheLastBen/fast-stable-diffusion#2893]
Hey i'm getting this error : Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 75, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 103, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256)
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'

i tried using the pipinstall, but didn't work. I update to latest notebook and got the same error, any advice on how to fix this?

**Comment by DiegoTeCuenta** [comment]
I got errors too. I'm using the last notebook, I read Last Ben fixed it, but I still this error:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 39, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/augmentation.py", line 6, in <module>
    from skimage import transform
  File "/usr/local/lib/python3.10/dist-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/radon_transform.py", line 6, in <module>
    from ._warps import warp
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/_warps.py", line 9, in <module>
    from ..measure import block_reduce
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py", line 2, in <module>
    from ._marching_cubes_lewiner import marching_cubes
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_lewiner.py", line 7, in <module>
    from ._marching_cubes_classic import _marching_cubes_classic
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_classic.py", line 3, in <module>
    from . import _marching_cubes_classic_cy
ImportError: cannot import name '_marching_cubes_classic_cy' from partially initialized module 'skimage.measure' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py)


I installed everything from zero again, but I got the same error

**Comment by BlessedDuelOP** [comment]
I downloaded the latest version to apply it in Google Colab Pro but it doesn't work for me either, I have the same error. 
apply these two cells to correct the error while it is being fixed:

!pip install --upgrade spandrel_extra_arches spandrel
!pip install --upgrade scikit-image
![error2](https://github.com/user-attachments/assets/9e9984fd-40a6-495d-abad-acc7f6bfbb35)

**Comment by Glup30** [comment]
> I downloaded the latest version to apply it in Google Colab Pro but it doesn't work for me either, I have the same error. apply these two cells to correct the error while it is being fixed:
> 
> !pip install --upgrade spandrel_extra_arches spandrel !pip install --upgrade scikit-image ![error2](https://private-user-images.githubusercontent.com/148596300/352779182-9e9984fd-40a6-495d-abad-acc7f6bfbb35.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMTgzNjYsIm5iZiI6MTcyMjExODA2NiwicGF0aCI6Ii8xNDg1OTYzMDAvMzUyNzc5MTgyLTllOTk4NGZkLTQwYTYtNDk1ZC1hYmFkLWFjYzdmNmJmYmIzNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMjA3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzUzZTg5ZTdjNTRkNTRlNzllODMwZDMyNzU2NTMzODExODU2NzFjMzkwYTcyMmVlOTM3N2FmM2MzMzljNGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y9cfKzqqyYuM4ZXfDNG8yrZZGs35ITLBDLn6jE7xraU)

i already did that, same issue

**Comment by BlessedDuelOP** [comment]
> > I downloaded the latest version to apply it in Google Colab Pro but it doesn't work for me either, I have the same error. apply these two cells to correct the error while it is being fixed:
> > !pip install --upgrade spandrel_extra_arches spandrel !pip install --upgrade scikit-image ![error2](https://private-user-images.githubusercontent.com/148596300/352779182-9e9984fd-40a6-495d-abad-acc7f6bfbb35.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMTgzNjYsIm5iZiI6MTcyMjExODA2NiwicGF0aCI6Ii8xNDg1OTYzMDAvMzUyNzc5MTgyLTllOTk4NGZkLTQwYTYtNDk1ZC1hYmFkLWFjYzdmNmJmYmIzNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMjA3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzUzZTg5ZTdjNTRkNTRlNzllODMwZDMyNzU2NTMzODExODU2NzFjMzkwYTcyMmVlOTM3N2FmM2MzMzljNGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y9cfKzqqyYuM4ZXfDNG8yrZZGs35ITLBDLn6jE7xraU)
> 
> i already did that, same issue

I got an error when I tried to start it, but I tried to start it again and it worked

**Comment by KyotoLyon** [comment]
Here it’s the same. I tried to use:

!pip install --upgrade spandrel_extra_arches spandrel
!pip install --upgrade scikit-image

But it didn’t work

**Comment by DiegoTeCuenta** [comment]
I tried the same, more than twice and:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 75, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 103, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256)
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'

**Comment by Mortilis** [comment]
Same

**Comment by junwoochoi2** [comment]
> Hey i'm getting this error : Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in webui() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui initialize.initialize() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 75, in initialize initialize_rest(reload_script_modules=False) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 103, in initialize_rest sd_models.list_models() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256) TypeError: load_models() got an unexpected keyword argument 'hash_prefix'
> 
> i tried using the pipinstall, but didn't work. I update to latest notebook and got the same error, any advice on how to fix this?

delete or backup sd folder and totally reintall and try this again 

!pip install --upgrade spandrel_extra_arches spandrel
!pip install --upgrade scikit-image

**Comment by jhuse25** [comment]
Hi I'm triying to use : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=PjzwxTkPSPHf 

But it seems broken I'm kept getting this same error: Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 39, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/augmentation.py", line 6, in <module>
    from skimage import transform
  File "/usr/local/lib/python3.10/dist-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/radon_transform.py", line 6, in <module>
    from ._warps import warp
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/_warps.py", line 9, in <module>
    from ..measure import block_reduce
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py", line 2, in <module>
    from ._marching_cubes_lewiner import marching_cubes
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_lewiner.py", line 7, in <module>
    from ._marching_cubes_classic import _marching_cubes_classic
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_classic.py", line 3, in <module>
    from . import _marching_cubes_classic_cy
ImportError: cannot import name '_marching_cubes_classic_cy' from partially initialized module 'skimage.measure' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py)

Somebody knows how to fix it out????
![image](https://github.com/user-attachments/assets/cb303725-234a-4944-b2b5-0ec821ba32cb)

**Comment by DiegoTeCuenta** [comment]
> > Hey i'm getting this error : Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in webui() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui initialize.initialize() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 75, in initialize initialize_rest(reload_script_modules=False) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 103, in initialize_rest sd_models.list_models() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256) TypeError: load_models() got an unexpected keyword argument 'hash_prefix'
> > i tried using the pipinstall, but didn't work. I update to latest notebook and got the same error, any advice on how to fix this?
> 
> delete or backup sd folder and totally reintall and try this again
> 
> !pip install --upgrade spandrel_extra_arches spandrel !pip install --upgrade scikit-image

it works, thx

**Comment by TheLastBen** [comment]
fixed now, use the latest notebook
