### ISSUE TITLE
Colab notebook Automatic 1111 : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=PjzwxTkPSPHf

### ISSUE THREAD

**Issue by jhuse25** [TheLastBen/fast-stable-diffusion#2894]
hi everyone, I really appreciate your help with my issue:

I'm using the Colab Notebook : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=PjzwxTkPSPHf 

But it seems it's broken, I'm kept getting this error, and I don't know what happened, anybody knows how to fix it out?

**Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in
initialize.imports()
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 39, in imports
from modules import processing, gradio_extensons, ui # noqa: F401
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 18, in
import modules.sd_hijack
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in
from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in
from modules.hypernetworks import hypernetwork
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 8, in
import modules.textual_inversion.dataset
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 12, in
from modules import devices, shared, images
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 22, in
from modules import sd_samplers, shared, script_callbacks, errors
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 5, in
from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 3, in
import k_diffusion.sampling
File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/init.py", line 1, in
from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/augmentation.py", line 6, in
from skimage import transform
File "/usr/local/lib/python3.10/dist-packages/skimage/_shared/lazy.py", line 62, in getattr
return importlib.import_module(f'{package_name}.{name}')
File "/usr/lib/python3.10/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/usr/local/lib/python3.10/dist-packages/skimage/transform/init.py", line 4, in
from .radon_transform import (radon, iradon, iradon_sart,
File "/usr/local/lib/python3.10/dist-packages/skimage/transform/radon_transform.py", line 6, in
from ._warps import warp
File "/usr/local/lib/python3.10/dist-packages/skimage/transform/_warps.py", line 9, in
from ..measure import block_reduce
File "/usr/local/lib/python3.10/dist-packages/skimage/measure/init.py", line 2, in
from ._marching_cubes_lewiner import marching_cubes
File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_lewiner.py", line 7, in
from ._marching_cubes_classic import _marching_cubes_classic
File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_classic.py", line 3, in
from . import _marching_cubes_classic_cy
ImportError: cannot import name '_marching_cubes_classic_cy' from partially initialized module 'skimage.measure' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/skimage/measure/init.py)**

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by Oxymoreandmore** [comment]
Are there many structured tutorials to run SD and its tools on Colab?

**Comment by TheLastBen** [comment]
@Oxymoreandmore the notebook is pretty straightforward, simply run the cells
