### ISSUE TITLE
Colab Error

### ISSUE THREAD

**Issue by Mittoman** [TheLastBen/fast-stable-diffusion#2895]
Hello
I used the latest notebook updated on July 28th, but I'm getting following error message,

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 74, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 102, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256)
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'

**Comment by Glup30** [comment]
Same problem over here

**Comment by mcqx4** [comment]
same

**Comment by Giusemoli312** [comment]
I have the same problem, any other alternative solution to reinstall SD?  It would be a long and painful process given the amount of stuff I have in that folder...

**Comment by Giusemoli312** [comment]
> @Giusemoli312 rename the sd folder to sd_old, then once everything is working again, you can move the extensions and the models to the new sd folder

Solved! thanks!
