### ISSUE TITLE
Google colab error

### ISSUE THREAD

**Issue by ssf07eap051f** [TheLastBen/fast-stable-diffusion#2896]
I am truly grateful for always using it.
I found the following error on July 27th and have yet to resolve it.
Is there any solution?

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 75, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 103, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256)
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'

**Comment by TheLastBen** [comment]
try renaming the sd folder in your gdrive to sd_old

**Comment by ssf07eap051f** [comment]
It's solved! Thank you so much.
