### ISSUE TITLE
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'

### ISSUE THREAD

**Issue by onedayharugh** [TheLastBen/fast-stable-diffusion#2909]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 75, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 103, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256)
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'

I'm getting this error, and the script won't run. I was able to run it with the FIX version three weeks ago
sing paid version of Google CO Lab

**Comment by alexshovelton** [comment]
This still seems to be a problem.
