### ISSUE TITLE
Collab  for A1111 won't start

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2923]
when I get to the last step, "Start Stable-Diffusion", I get the following error:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 75, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 103, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 176, in list_models
    checkpoint_info = CheckpointInfo(filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 92, in __init__
    self.sha256 = hashes.sha256_from_cache(self.filename, f"checkpoint/{name}")
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hashes.py", line 23, in sha256_from_cache
    hashes = cache("hashes-addnet") if use_addnet_hash else cache("hashes")
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/cache.py", line 75, in cache
    cache_obj = make_cache(subsection)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/cache.py", line 24, in make_cache
    return diskcache.Cache(
  File "/usr/local/lib/python3.10/dist-packages/diskcache/core.py", line 456, in __init__
    sql = self._sql_retry
  File "/usr/local/lib/python3.10/dist-packages/diskcache/core.py", line 652, in _sql_retry
    sql = self._sql
  File "/usr/local/lib/python3.10/dist-packages/diskcache/core.py", line 648, in _sql
    return self._con.execute
  File "/usr/local/lib/python3.10/dist-packages/diskcache/core.py", line 636, in _con
    settings = con.execute(select).fetchall()
sqlite3.DatabaseError: database disk image is malformed

**Comment by mdlieber99** [comment]
got it fixed
