### ISSUE TITLE
X/Y/Z plot giving 'multiline_textsize' error

### ISSUE THREAD

**Issue by g-imconfused** [TheLastBen/fast-stable-diffusion#2927]
Seeing this as of this morning when using s/r, does not complete final output

*** Error completing request

...

    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 106, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 780, in run
        processed = script.run(p, *script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/xyz_grid.py", line 769, in run
        processed = draw_xyz_grid(
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/xyz_grid.py", line 380, in draw_xyz_grid
        grid = images.draw_grid_annotations(grid, grid_max_w, grid_max_h, hor_texts, ver_texts, margin_size)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 228, in draw_grid_annotations
        draw_texts(d, x, y, hor_texts[col], fnt, fontsize)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 171, in draw_texts
        while drawing.multiline_textsize(line.text, font=fnt)[0] > line.allowed_width and fontsize > 0:
    AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize'

**Comment by g-imconfused** [comment]
still getting this error, is anyone else?

**Comment by Sh3122** [comment]
Just wanted to chime in and confirm that I'm seeing the same issue on the notebook when trying to use X/Y/Z plots with "Draw Legend" enabled. Works fine without the legend, but is a lot less useful without it.
```python
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 53, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 106, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *p.script_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 780, in run
        processed = script.run(p, *script_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/xyz_grid.py", line 769, in run
        processed = draw_xyz_grid(
                    ^^^^^^^^^^^^^^
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/xyz_grid.py", line 380, in draw_xyz_grid
        grid = images.draw_grid_annotations(grid, grid_max_w, grid_max_h, hor_texts, ver_texts, margin_size)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 228, in draw_grid_annotations
        draw_texts(d, x, y, hor_texts[col], fnt, fontsize)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 171, in draw_texts
        while drawing.multiline_textsize(line.text, font=fnt)[0] > line.allowed_width and fontsize > 0:
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'ImageDraw' object has no attribute 'multiline_textsize'
```
