### ISSUE TITLE
done

### ISSUE THREAD

**Issue by cuongdex** [TheLastBen/fast-stable-diffusion#2936]
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 803, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 443, in main
    accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'logging_dir'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by cuongdex** [comment]
Can someone possibly help me? Thx in advance.

**Comment by Sanen43** [comment]
> Can someone possibly help me? Thx in advance.

open issue #2993 comments section. worked for me.

**Comment by cuongdex** [comment]
where issue #2994?
