### ISSUE TITLE
Stable Diffusion Colab doesn't work, error

### ISSUE THREAD

**Issue by Guroexe** [TheLastBen/fast-stable-diffusion#2949]
This is an error in the block Start Stable Diffusion: 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 16, in imports
    import pytorch_lightning  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 13, in <module>
    from tensorboard.compat.proto import event_pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/event_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import summary_pb2 as tensorboard_dot_compat_dot_proto_dot_summary__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.10/dist-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by KyotoLyon** [comment]
Same error

**Comment by KyotoLyon** [comment]
I used this code one cell before Start Stable Diffusion, and it connected:

!pip install protobuf==3.20.3


I'll test if everything is working correctly.

**Comment by BlessedDuelOP** [comment]
> I used this code one cell before Start Stable Diffusion, and it connected:
> 
> !pip install protobuf==3.20.3
> 
> I'll test if everything is working correctly.

It worked, thank you very much, but it doesn't seem to be the definitive solution. I hope they update it, hopefully they can update the 'fast_stable_diffusion_AUTOMATIC1111.ipynb' file, that would be really great 👍 . I also had some issues when trying to install the ADetailer extension :(

**Comment by juliagallo-mee** [comment]
Hey there. Should I add it as new step or update the !pip install controlnet_aux for !pip install protobuf==3.20.3 ??

**Comment by juliagallo-mee** [comment]
> I used this code one cell before Start Stable Diffusion, and it connected:
> 
> !pip install protobuf==3.20.3
> 
> I'll test if everything is working correctly.

Hey, can you help me? Should I add it as new step or update the !pip install controlnet_aux for !pip install protobuf==3.20.3 ??

![image](https://github.com/user-attachments/assets/11e3a11a-2f7f-4189-8ce6-8d42e95d6b0d)

**Comment by taichihara** [comment]
I had the same problem and thank you for the solution for protobuf problem...
But since then, I have another problem with xformers installation...
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.0.1+cu118)
    Python  3.10.14 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
*** Cannot import xformers
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/xformers/checkpoint.py", line 53, in <module>
        from torch.utils.checkpoint import SAC_IGNORED_OPS as _ignored_ops  # type: ignore
    ImportError: cannot import name 'SAC_IGNORED_OPS' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 160, in <module>
        import xformers.ops
      File "/usr/local/lib/python3.10/dist-packages/xformers/__init__.py", line 12, in <module>
        from .checkpoint import (  # noqa: E402, F401
      File "/usr/local/lib/python3.10/dist-packages/xformers/checkpoint.py", line 57, in <module>
        from torch.utils.checkpoint import _ignored_ops  # type: ignore
    ImportError: cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py)

Can someone help me to get out of this "dependency" maze...

**Comment by rl2test** [comment]
After adding

!pip install protobuf==3.20.3

received this warning:
WARNING: The following packages were previously imported in this runtime:
  [google]
You must restart the runtime in order to use newly installed versions.

but also this error:

Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled.

Was able to start Automatic UI, but same error appeared when attempting to generate an image.

Using A100 GPU, but also failed when using L4 and T4

**Comment by rl2test** [comment]
Tested LOLSALT fix. Everything looks good. :)

**Comment by ghsldsd** [comment]
I hope can fix it quickly.

**Comment by taichihara** [comment]
Sorry,,, what should I do with your prompts, LOLSALT? There are so many lines and I don't see how can I merge them to the main program of TheLastBen...

**Comment by ghsldsd** [comment]
I'm waiting because the problem hasn't been solved yet. I hope it's resolved quickly

**Comment by ghsldsd** [comment]
The producer here will correct it himself, right?
I don't know about yours

**Comment by LemurianArquetip** [comment]
> I used this code one cell before Start Stable Diffusion, and it connected:
> 
> !pip install protobuf==3.20.3
> 
> I'll test if everything is working correctly.

But if use stable diffusion AUTOMATIC1111 on google collab, where I must use the code?

**Comment by HaikenEdge** [comment]
> > I used this code one cell before Start Stable Diffusion, and it connected:
> > !pip install protobuf==3.20.3
> > I'll test if everything is working correctly.
> 
> But if I use stable diffusion AUTOMATIC1111 on google collab, where should I use the code?

In a new cell directly above the Start Stable-Diffusion cell.

**Comment by ghsldsd** [comment]
This doesn't work!

**Comment by htdemirci** [comment]
> > > I used this code one cell before Start Stable Diffusion, and it connected:
> > > !pip install protobuf==3.20.3
> > > I'll test if everything is working correctly.
> > 
> > 
> > But if I use stable diffusion AUTOMATIC1111 on google collab, where should I use the code?
> 
> In a new cell directly above the Start Stable-Diffusion cell.

I don't know exactly where we need to enter this code.

**Comment by htdemirci** [comment]
Can you show it with a visual?

**Comment by Mierdas1978** [comment]
> Can you show it with a visual?



> Refere

In "Start Stable-Diffusion", enter code !pip install protobuf==3.20.3

#@markdown # Start Stable-Diffusion
!pip install protobuf==3.20.3
from IPython.utils import capture
import time
import sys
import fileinput
from pyngrok import ngrok, conf
import re......................

In my case it's works

**Comment by htdemirci** [comment]
problem solved thank you

**Comment by mdlieber99** [comment]
is the problem still solved for folks?  yesterday it broke again for me.

**Comment by kkkwjr** [comment]
> is the problem still solved for folks? yesterday it broke again for me.

have you solved it ,i have the same error

**Comment by HaikenEdge** [comment]
> > is the problem still solved for folks? yesterday it broke again for me.
> 
> have you solved it ,i have the same error

I successfully got it running literally 10 minutes ago, so unless something's changed in those 10 minutes, it's fixed.

**Comment by konkin-ux** [comment]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 17, in imports
    import pytorch_lightning  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/utilities/types.py", line 28, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.11/dist-packages/torchmetrics/__init__.py", line 52, in <module>
    from torchmetrics.image import (  # noqa: E402
  File "/usr/local/lib/python3.11/dist-packages/torchmetrics/image/__init__.py", line 26, in <module>
    from torchmetrics.image.fid import FrechetInceptionDistance  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torchmetrics/image/fid.py", line 28, in <module>
    from torch_fidelity.feature_extractor_inceptionv3 import FeatureExtractorInceptionV3
  File "/usr/local/lib/python3.11/dist-packages/torch_fidelity/__init__.py", line 6, in <module>
    from torch_fidelity.metric_fid import KEY_METRIC_FID
  File "/usr/local/lib/python3.11/dist-packages/torch_fidelity/metric_fid.py", line 6, in <module>
    import scipy.linalg
  File "/usr/local/lib/python3.11/dist-packages/scipy/linalg/__init__.py", line 204, in <module>
    from ._cythonized_array_utils import *
  File "scipy/linalg/_cythonized_array_utils.pyx", line 11, in init scipy.linalg._cythonized_array_utils
  File "/usr/local/lib/python3.11/dist-packages/scipy/_lib/_util.py", line 20, in <module>
    from numpy.exceptions import AxisError
ModuleNotFoundError: No module named 'numpy.exceptions'
I don't understand anything about programming, help me, everything worked, but now I have this error
