### ISSUE TITLE
Error:  returned non-zero exit status 1. Something went wrong

### ISSUE THREAD

**Issue by WilliamLehmus** [TheLastBen/fast-stable-diffusion#2956]
This error happens whenever I try to start the training. 
I've been trying to figure out what's going wrong, but can't figure it out on my own. 
Seems to be coming from the library and dependencies. I've tried all combinations of settings, the error persists regardless  even 
with standard setting. 

Training the UNet...
'########:'########:::::'###::::'####:'##::: ##:'####:'##::: ##::'######:::
... ##..:: ##.... ##:::'## ##:::. ##:: ###:: ##:. ##:: ###:: ##:'##... ##::
::: ##:::: ##:::: ##::'##:. ##::: ##:: ####: ##:: ##:: ####: ##: ##:::..:::
::: ##:::: ########::'##:::. ##:: ##:: ## ## ##:: ##:: ## ## ##: ##::'####:
::: ##:::: ##.. ##::: #########:: ##:: ##. ####:: ##:: ##. ####: ##::: ##::
::: ##:::: ##::. ##:: ##.... ##:: ##:: ##:. ###:: ##:: ##:. ###: ##::: ##::
::: ##:::: ##:::. ##: ##:::: ##:'####: ##::. ##:'####: ##::. ##:. ######:::
:::..:::::..:::::..::..:::::..::....::..::::..::....::..::::..:::......::::

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 803, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 640, in main
    accelerator.init_trackers("dreambooth", config=vars(args))
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1067, in init_trackers
    tracker.store_init_configuration(config)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/tracking.py", line 152, in store_init_configuration
    self.writer.add_hparams(values, metric_dict={})
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/writer.py", line 330, in add_hparams
    exp, ssi, sei = hparams(hparam_dict, metric_dict, hparam_domain_discrete)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/tensorboard/summary.py", line 270, in hparams
    ssi.hparams[k].string_value = v
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/containers.py", line 70, in __getitem__
    return self._values[key]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--external_captions', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/bs-johannes', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/bs-johannes/instance_images', '--output_dir=/content/models/bs-johannes', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/bs-johannes/captions', '--instance_prompt=', '--seed=858353', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=1500']' returned non-zero exit status 1.
Something went wrong

**Comment by MatthysTruter** [comment]
i keep getting the same error.

**Comment by ParkHangah** [comment]
me too. :(

**Comment by akshay88apps** [comment]
File "/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/containers.py", line 70, in __getitem__
    return self._values[key]
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=500', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ghconfap', '--pretrained_model_name_or_path=/content/stable-diffusion-v2-512', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ghconfap/instance_images', '--output_dir=/content/models/ghconfap', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ghconfap/captions', '--instance_prompt=', '--seed=471428', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=1500']' returned non-zero exit status 1.
Something went wrong

**Comment by Talionic** [comment]
I'm having the same problem all of a sudden.

**Comment by Talionic** [comment]
I'm having the same problem all of a sudden.
