### ISSUE TITLE
I can't run Stable diffusion

### ISSUE THREAD

**Issue by taichihara** [TheLastBen/fast-stable-diffusion#2959]
This is error message:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 17, in imports
    import pytorch_lightning  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/__init__.py", line 24, in <module>
    from pytorch_lightning.loggers.wandb import WandbLogger  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/wandb.py", line 34, in <module>
    import wandb
  File "/usr/local/lib/python3.10/dist-packages/wandb/__init__.py", line 21, in <module>
    from wandb import sdk as wandb_sdk
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/__init__.py", line 28, in <module>
    from .wandb_init import _attach, init
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 39, in <module>
    from . import wandb_login, wandb_setup
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 19, in <module>
    from .wandb_settings import Settings
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_settings.py", line 25, in <module>
    from pydantic import (
  File "/usr/local/lib/python3.10/dist-packages/pydantic/__init__.py", line 418, in __getattr__
    module = import_module(module_name, package=package)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 34, in <module>
    from ._internal import (
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_decorators.py", line 16, in <module>
    from ._core_utils import get_type_ref
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_core_utils.py", line 8, in <module>
    from pydantic_core import validate_core_schema as _validate_core_schema
ImportError: cannot import name 'validate_core_schema' from 'pydantic_core' (/usr/local/lib/python3.10/dist-packages/pydantic_core/__init__.py)

ChatGPT said to install !pip install pydantic==1.10.9 but I can't:

Found existing installation: pydantic 2.10.2
Uninstalling pydantic-2.10.2:
  Successfully uninstalled pydantic-2.10.2
Found existing installation: pydantic_core 2.27.1
Uninstalling pydantic_core-2.27.1:
  Successfully uninstalled pydantic_core-2.27.1
Collecting pydantic==1.10.9
  Downloading pydantic-1.10.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 5.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic==1.10.9) (4.12.2)
Downloading pydantic-1.10.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 64.2 MB/s eta 0:00:00
Installing collected packages: pydantic
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 1.4.20 requires pydantic>=2.7.0, but you have pydantic 1.10.9 which is incompatible.
langchain 0.3.9 requires pydantic<3.0.0,>=2.7.4, but you have pydantic 1.10.9 which is incompatible.
langchain-core 0.3.21 requires pydantic<3.0.0,>=2.5.2; python_full_version < "3.12.4", but you have pydantic 1.10.9 which is incompatible.
Successfully installed pydantic-1.10.9
Requirement already satisfied: wandb in /usr/local/lib/python3.10/dist-packages (0.18.7)
Collecting wandb
  Downloading wandb-0.19.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (3.1.43)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.10/dist-packages (from wandb) (4.3.6)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (3.20.3)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (5.9.5)
Collecting pydantic<3,>=2.6 (from wandb)
  Downloading pydantic-2.10.3-py3-none-any.whl.metadata (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (2.19.0)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.10/dist-packages (from wandb) (1.3.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb) (75.1.0)
Requirement already satisfied: typing-extensions<5,>=4.4 in /usr/local/lib/python3.10/dist-packages (from wandb) (4.12.2)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.11)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3,>=2.6->wandb) (0.7.0)
Collecting pydantic-core==2.27.1 (from pydantic<3,>=2.6->wandb)
  Downloading pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2024.8.30)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.1)
Downloading wandb-0.19.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 92.6 MB/s eta 0:00:00
Downloading pydantic-2.10.3-py3-none-any.whl (456 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.0/457.0 kB 39.1 MB/s eta 0:00:00
Downloading pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 88.5 MB/s eta 0:00:00
Installing collected packages: pydantic-core, pydantic, wandb
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.9
    Uninstalling pydantic-1.10.9:
      Successfully uninstalled pydantic-1.10.9
  Attempting uninstall: wandb
    Found existing installation: wandb 0.18.7
    Uninstalling wandb-0.18.7:
      Successfully uninstalled wandb-0.18.7
Successfully installed pydantic-2.10.3 pydantic-core-2.27.1 wandb-0.19.0

Please help me...

**Comment by wlvchandler** [comment]
!pip uninstall -y albumentations langchain langchain-core wandb pydantic pydantic_core
!pip install pydantic==1.10.9
!pip install wandb==0.15.8

**Comment by aionrevenge** [comment]
no problem on me, make sure you using the latest version
