### ISSUE TITLE
error running start Stable-Difussion

### ISSUE THREAD

**Issue by danixen2** [TheLastBen/fast-stable-diffusion#2966]
**_this error has occurred when I want to initialize SD_**

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1146, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/usr/local/lib/python3.10/dist-packages/accelerate/tracking.py", line 34, in <module>
    import wandb
  File "/usr/local/lib/python3.10/dist-packages/wandb/__init__.py", line 21, in <module>
    from wandb import sdk as wandb_sdk
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/__init__.py", line 28, in <module>
    from .wandb_init import _attach, init
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 39, in <module>
    from . import wandb_login, wandb_setup
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 19, in <module>
    from .wandb_settings import Settings
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_settings.py", line 25, in <module>
    from pydantic import (
ImportError: cannot import name 'computed_field' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 17, in imports
    import pytorch_lightning  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/types.py", line 28, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 77, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1136, in __getattr__

**Comment by mothman9s** [comment]
Exact same issue.

**Comment by zassoulich** [comment]
Seems like a dependency issue.

**Comment by aionrevenge** [comment]
temporary fix, add this code before "starst stable diffusion"
!pip uninstall wandb
press Y to uninstall

!pip install wandb==0.15.12

**Comment by Guroexe** [comment]
it worked, thanks bro

> temporary fix, add this code before "starst stable diffusion" !pip uninstall wandb press Y to uninstall
> 
> !pip install wandb==0.15.12

**Comment by Azura-13** [comment]
Same ^^

**Comment by BlessedDuelOP** [comment]
Same problem but it was solved with the code that he shared, thank you very much <3

**Comment by key-key123** [comment]
I was also experiencing the same issue and was confused, but uninstalling it using his code solved the problem. Thank you.

**Comment by Nissy0922** [comment]
> 一時的な修正として、"starst stable diffusion" の前にこのコードを追加してください 。!pip uninstall wandb アンインストールするには Y を押してください
> 
> !pip インストール wandb==0.15.12

あなたのおかげで解決しました！
本当にありがとうございます！！

**Comment by Mary13-13** [comment]
> temporary fix, add this code before "starst stable diffusion" !pip uninstall wandb press Y to uninstall
> 
> !pip install wandb==0.15.12

Please tell me where to insert this, I don’t understand. can I get a screenshot?

**Comment by HexTrue** [comment]
> > temporary fix, add this code before "starst stable diffusion" !pip uninstall wandb press Y to uninstall
> > !pip install wandb==0.15.12
> 
> Please tell me where to insert this, I don’t understand. can I get a screenshot?

![a](https://github.com/user-attachments/assets/641c1881-c7b4-4d3f-9f00-9e5823e68fce)

Go to the bottom of the cells, hover the mouse cursor over the bottom center of the last cell, you will get this "code" button.
Click and add this code - 

!pip uninstall wandb
!pip install wandb==0.15.12

Then run the cell before running the "Start Stable Diffusion" cell

**Comment by Mary13-13** [comment]
Thank you!!

**Comment by mupersei** [comment]
I’m curious about why you’re using the computed_field function from version 0.19.x while working with version 0.15.x, instead of using 0.18.x, 0.17.x, or similar versions.
Is it for stability?
I’m asking purely out of curiosity.

**Comment by kaitas** [comment]
!pip install pydantic==1.10.7
!pip install wandb==0.15.5
It seems implementation for Flux...

**Comment by Kaka32793784** [comment]
Sorry.
I am using Google Colab and cannot type “Y”.
What should I do?

**Comment by mupersei** [comment]
!pip install pydantic == 1.10.7 -y

**Comment by Kaka32793784** [comment]
!pip install pydantic ==1.10.7 -y
!pip install wandb==0.15.5

Is it OK with you?

**Comment by HaikenEdge** [comment]
> !pip install pydantic ==1.10.7 -y !pip install wandb==0.15.5
> 
> Is it OK with you?
> 
> !pip uninstall wandb
> 
> is not necessary?

I've been using

```
!pip uninstall wandb -y

!pip install wandb==0.15.12
```
in a cell directly above the Start Stable-Diffusion cell and it's been working for me.

**Comment by TheLastBen** [comment]
fixed, use the latest notebook
