### ISSUE TITLE
UnPickling in Colab

### ISSUE THREAD

**Issue by walrusthief** [TheLastBen/fast-stable-diffusion#3]
Trying to run the new txt2mask feature and I'm getting a very strange error. I've tried restarting, I know I've got a GPU available, I'm not sure wtf "UnPickling" means in the context of this program >.>

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 134, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 58, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 115, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 158, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/txt2mask.py", line 175, in run
    p.image_mask =  get_mask().resize((p.init_images[0].width,p.init_images[0].height))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/txt2mask.py", line 121, in get_mask
    model.load_state_dict(torch.load(d64_file, map_location=torch.device('cuda')), strict=False);
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by TheLastBen** [comment]
it's not the colab, it's the txt2mask script, look here : https://github.com/ThereforeGames/txt2mask/issues/6
