### ISSUE TITLE
Error in dreambooth colab , last gradio cell errors 

### ISSUE THREAD

**Issue by 1blackbar** [TheLastBen/fast-stable-diffusion#30]
Gives me this, and wont work , how to fix this ? Training just ended ,, i have no way to test it now 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 233, in get_config_dict
    revision=revision,
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 1022, in hf_hub_download
    cache_dir, repo_folder_name(repo_id=repo_id, repo_type=repo_type)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 92, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 137, in validate_repo_id
    "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/gdrive/MyDrive/models/ania'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/interface.py", line 7, in <module>
    pipeline = StableDiffusionPipeline.from_pretrained('/content/gdrive/MyDrive/models/ania', torch_dtype=torch.float16).to("cuda")
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipeline_utils.py", line 297, in from_pretrained
    revision=revision,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 260, in get_config_dict
    f"We couldn't connect to '{HUGGINGFACE_CO_RESOLVE_ENDPOINT}' to load this model, couldn't find it"
OSError: We couldn't connect to 'https://huggingface.co/' to load this model, couldn't find it in the cached files and it looks like /content/gdrive/MyDrive/models/ania is not the path to a directory containing a model_index.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by liangwei191** [comment]
have accept the terms in [https://huggingface.co/CompVis/stable-diffusion-v1-4](url)
I got error(but not same)before I check the tick in this link

**Comment by 1blackbar** [comment]
long long time ago my man without it it would not run the training , this is different
