### ISSUE TITLE
UnboundLocalError: local variable 'frz_dir' referenced before assignment

### ISSUE THREAD

**Issue by SAC020** [TheLastBen/fast-stable-diffusion#311]
Using the github link (not a local copy), on google colab. Training crashes whenever I try to save intermediary checkpoints

I've made sure to run each step individually. I am using the new method. No idea what can be wrong.

TY!

2022-10-31 10:14:05.417072: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Steps:   3% 199/6600 [01:18<37:16,  2.86it/s, loss=0.00582, lr=1.94e-6] SAVING CHECKPOINT: /content/gdrive/MyDrive/cydoha_step_200.ckpt
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 733, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 701, in main
    if args.train_text_encoder and os.path.exists(frz_dir):
UnboundLocalError: local variable 'frz_dir' referenced before assignment
Steps:   3% 199/6600 [01:32<49:40,  2.15it/s, loss=0.00582, lr=1.94e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=200', '--stop_text_encoder_training=660', '--save_n_steps=200', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cydoha/instance_images', '--output_dir=/content/models/cydoha', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--center_crop', '--lr_warmup_steps=0', '--max_train_steps=6600']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
fixed a few seconds ago, you will need to disconnect and reconnect to get the update

**Comment by SAC020** [comment]
Thank you, now it works, I was able to save the first intermediary checkpoint and resume the training

TYVM!

**Comment by TheLastBen** [comment]
great !
