### ISSUE TITLE
error when trying to use SD Upscale

### ISSUE THREAD

**Issue by demosch** [TheLastBen/fast-stable-diffusion#322]
Error completing request
Arguments: (0, 'sks woman in river swamp flora by ivan aizovsky and francisco de goya, water', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=1024x640 at 0x7F42EAE3C410>, {'image': <PIL.Image.Image image mode=RGBA size=1024x640 at 0x7F42EAE3CF10>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1024x640 at 0x7F42EAE3C310>}, None, None, 0, 150, 0, 4, 1, False, False, 1, 1, 7.5, 0.15, -1.0, -1.0, 0, 0, 0, False, 832, 832, 0, True, 48, 0, '', '', 7, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, None, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 96, 4, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 135, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 282, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/scripts/sd_upscale.py", line 75, in run
    processed = processing.process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 427, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 487, in process_images_inner
    with torch.no_grad(), p.sd_model.ema_scope():
AttributeError: 'NoneType' object has no attribute 'ema_scope'

**Comment by demosch** [comment]
@TheLastBen

**Comment by TheLastBen** [comment]
did you update the repo ?

**Comment by demosch** [comment]
updated-still doenst work. im not sure if it has to do with the size of input image? its an 512 height, 832 wide picture.

**Comment by TheLastBen** [comment]
could be, try with a square image

**Comment by demosch** [comment]
tried aquare-still ema error

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by Jboby1** [comment]
Getting a similar error why trying to Loopback

**Comment by TheLastBen** [comment]
fixed, use the Colab from the official link to get the fixed version

**Comment by demosch** [comment]
thanks alot. trying out now

**Comment by Jboby1** [comment]
All works again on my end, thank you!

**Comment by Nayjest** [comment]
OMG Thanks! It works!
Wasted all day to find alternative workflow for upscale and now the best method finally works. Great!
