### ISSUE TITLE
progress of generation isnt shown anymore

### ISSUE THREAD

**Issue by demosch** [TheLastBen/fast-stable-diffusion#335]
istn shown anymore. ive set it in settings but doesnt work since yersterday.

**Comment by demosch** [comment]
alos getting this (generating works, just progress not): Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 274, in run_predict
    fn_index, raw_input, username, session_state, iterators
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 742, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 654, in call_function
    block_fn.fn, *processed_input, limiter=self.limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 526, in <lambda>
    fn=lambda: check_progress_call_initial(id_part),
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 304, in check_progress_call_initial
    return check_progress_call(id_part)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 280, in check_progress_call
    shared.state.set_current_image()
AttributeError: 'State' object has no attribute 'set_current_image'

**Comment by demosch** [comment]
@TheLastBen

**Comment by demosch** [comment]
really need the progress shown in showbar

**Comment by demosch** [comment]
> alos getting this (generating works, just progress not): Traceback (most recent call last): File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 274, in run_predict fn_index, raw_input, username, session_state, iterators File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 742, in process_api result = await self.call_function(fn_index, inputs, iterator) File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 654, in call_function block_fn.fn, *processed_input, limiter=self.limiter File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync func, *args, cancellable=cancellable, limiter=limiter File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run result = context.run(func, *args) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 526, in fn=lambda: check_progress_call_initial(id_part), File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 304, in check_progress_call_initial return check_progress_call(id_part) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 280, in check_progress_call shared.state.set_current_image() AttributeError: 'State' object has no attribute 'set_current_image'

this comes before every generation, whatever i try to generate.

**Comment by demosch** [comment]
works after updating (again)
