### ISSUE TITLE
3.97GB.ckpt but got 'Conversion error, Insufficient RAM or corrupt CKPT, use a 4.7GB CKPT instead of 7GB'

### ISSUE THREAD

**Issue by fforius** [TheLastBen/fast-stable-diffusion#341]
help `Conversion error` using **CKPT_Path**
the size file https://prnt.sc/xdVXfgMRIYK6
but got err:
`Traceback (most recent call last):
  File "/content/convert_original_stable_diffusion_to_diffusers.py", line 673, in <module>
    checkpoint = torch.load(args.checkpoint_path)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '/content/gdrive/MyDrive/modelnya'
Conversion error, Insufficient RAM or corrupt CKPT, use a 4.7GB CKPT instead of 7GB`

RAM 12GB https://prnt.sc/y5-CfZIOkdst

**Comment by TheLastBen** [comment]
use the full path not only the folder path
