### ISSUE TITLE
ImportError: cannot import name 'processing' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by tsound97** [TheLastBen/fast-stable-diffusion#376]
The error appears after I pull the webui to the latest version.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers, upscaler, extensions
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 19, in <module>
    from modules import sd_samplers, shared, script_callbacks
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 19, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 15, in <module>
    from modules import devices, processing, sd_models, shared
ImportError: cannot import name 'processing' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
run this if you don't want to update the colab (again):
```
%cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/
!wget -O processing.py https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/modules/processing.py
```

**Comment by tsound97** [comment]
Successfully solved! Thank you so much!
The "Update_repo" option will remove the processing.py
(!rm /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py)
Usually, it will pull it back……but not this time.
