### ISSUE TITLE
Old method bug

### ISSUE THREAD

**Issue by VladAndronik** [TheLastBen/fast-stable-diffusion#379]
Trying old method with default settings, got this error:

```
usage: train_dreambooth.py [-h] --pretrained_model_name_or_path
                           PRETRAINED_MODEL_NAME_OR_PATH
                           [--tokenizer_name TOKENIZER_NAME]
                           --instance_data_dir INSTANCE_DATA_DIR
                           [--class_data_dir CLASS_DATA_DIR]
                           [--instance_prompt INSTANCE_PROMPT]
                           [--class_prompt CLASS_PROMPT]
                           [--with_prior_preservation]
                           [--prior_loss_weight PRIOR_LOSS_WEIGHT]
                           [--num_class_images NUM_CLASS_IMAGES]
                           [--output_dir OUTPUT_DIR] [--seed SEED]
                           [--resolution RESOLUTION] [--center_crop]
                           [--train_text_encoder]
                           [--train_batch_size TRAIN_BATCH_SIZE]
                           [--sample_batch_size SAMPLE_BATCH_SIZE]
                           [--num_train_epochs NUM_TRAIN_EPOCHS]
                           [--max_train_steps MAX_TRAIN_STEPS]
                           [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                           [--gradient_checkpointing]
                           [--learning_rate LEARNING_RATE] [--scale_lr]
                           [--lr_scheduler LR_SCHEDULER]
                           [--lr_warmup_steps LR_WARMUP_STEPS]
                           [--use_8bit_adam] [--adam_beta1 ADAM_BETA1]
                           [--adam_beta2 ADAM_BETA2]
                           [--adam_weight_decay ADAM_WEIGHT_DECAY]
                           [--adam_epsilon ADAM_EPSILON]
                           [--max_grad_norm MAX_GRAD_NORM] [--push_to_hub]
                           [--hub_token HUB_TOKEN]
                           [--hub_model_id HUB_MODEL_ID]
                           [--logging_dir LOGGING_DIR]
                           [--mixed_precision {no,fp16,bf16}]
                           [--save_n_steps SAVE_N_STEPS]
                           [--save_starting_step SAVE_STARTING_STEP]
                           [--stop_text_encoder_training STOP_TEXT_ENCODER_TRAINING]
                           [--image_captions_filename]
                           [--dump_only_text_encoder] [--train_only_unet]
                           [--Session_dir SESSION_DIR]
                           [--local_rank LOCAL_RANK]
train_dreambooth.py: error: argument --save_starting_step: invalid int value: ''
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--save_starting_step=', '--save_n_steps=', '--Session_dir=', '--pretrained_model_name_or_path=', '--instance_data_dir=', '--class_data_dir=', '--output_dir=', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=', '--class_prompt=', '--seed=', '--resolution=512', '--mixed_precision=', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--center_crop', '--max_train_steps=', '--num_class_images=']' returned non-zero exit status 2.
Something went wrong

```

**Comment by TheLastBen** [comment]
are you using the latest colab ?

**Comment by knoopx** [comment]
confirmed broken, many undefined vars

**Comment by TheLastBen** [comment]
I'll move the old method to a new colab

**Comment by TheLastBen** [comment]
> confirmed broken, many undefined vars

which vars exactly ?

**Comment by knoopx** [comment]
every variable passed to `train_dreambooth.py` regardless prior preservation

**Comment by TheLastBen** [comment]
only one var blocked it but I can find which one

**Comment by knoopx** [comment]
confirmed 4155e9ccd7f322f70be5314f68222ca6b3f65343 as working, so it broke between this and the most recent commits. anyway splitting the "old method" into a separate notebook makes totally sense.

**Comment by AnitaKirkovska** [comment]
where can I find a notebook that works?

**Comment by TheLastBen** [comment]
> where can I find a notebook that works?

If you want to use the old method : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/Dreambooth/fast_DreamBooth-Old-Method.ipynb
new method (better one) : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by LIQUIDMIND111** [comment]
> > where can I find a notebook that works?
> 
> If you want to use the old method : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/Dreambooth/fast_DreamBooth-Old-Method.ipynb
> 
> new method (better one) : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

ok so in the NEW model, there are no CLASS images upload section....??? just asking..... i have no problem using the OLD model, since i had GREAT results using PRIOR preservation and Captionned_instance_images

**Comment by TheLastBen** [comment]
If you set "contain_faces" to male, female or both, it will use a method of prior preservation, applied only on the text encoder which yields better results in my experience. But you need to correctly rename your input images as the example photo shows.

**Comment by LIQUIDMIND111** [comment]
ok i tried the NEW method and the OLDER, BOTH with all as instructed, the results on the NEW one are a MORPHED version of me and my friend.... on the older COLLAB, i did the SAME training but using OLDER TRAINING, and the results were completely accurate...... the MORPHED version needs some PROMPT HELP to get to my actual face, but not so accurate as the older method, in BOTH i used prior preservation and captioned instances.,.... the morphed version looks NICE but its not always me, on the old version its ALWAYS ME, so please, never remove the old method page, i appreciate it.. and many others willl!!!

**Comment by LIQUIDMIND111** [comment]
> If you set "contains_faces" to male, female or both, it will use a method of prior preservation, applied only on the text encoder which yields better results in my experience. But you need to correctly rename your input images as the example photo shows.

ok i tried the NEW method and the OLDER, BOTH with all as instructed, the results on the NEW one are a MORPHED version of me and my friend.... on the older COLLAB, i did the SAME training but using OLDER TRAINING, and the results were completely accurate...... the MORPHED version needs some PROMPT HELP to get to my actual face, but not so accurate as the older method, in BOTH i used prior preservation and captioned instances.,.... the morphed version looks NICE but its not always me, on the old version its ALWAYS ME, so please, never remove the old method page, i appreciate it.. and many others willl!!!

**Comment by TheLastBen** [comment]
What did you name the I stance pictures in the new method ?

**Comment by LIQUIDMIND111** [comment]
> 

one of them is 4ZEEEddie_man_08.jpg they work flawless on the OLD model and NEW, but on the NEW it does NOT looks like me, it has characteristic of me, like glasses and beard, but NOT me..... same as my friend...... 71ZEEEstefania_woman_04.jpg works great

**Comment by TheLastBen** [comment]
You didn't follow the most important rule of the new method, never use known name or class, you used eddie and man, so you turned the new method into a bad version of the old method.

I wrote it in giant font so that no one would miss it :

`The most importent step is to rename the instance picture to the same instance unique identifier for each subject`

https://i.imgur.com/d2lD3rz.jpeg

**Comment by LIQUIDMIND111** [comment]
> I wrote it in giant font so that no one would miss it :
> 
> `The most importent step is to rename the instance picture to the same instance unique identifier for each subject`

you mean this "giant font" ??

I wrote it in giant font so that no one would miss it :

The most important step is to rename the instance picture to the same instance unique identifier for each subject

i already did that, INSTANCES and FILES are SAME NAME...... as it suggest, also says to ADD a CLASS with an UNDERSCORE to the file.... SO I DID THAT.... i follow ALL instructions.... i went BACK to the NEW collab page, and i see you REMOVED this instructions that were yesterday, so if i do thing according to instructed, and you change codes, is not my fault, LOL, but cheers, i wil not fight for a reason, since i already got good results in the OLD method...., as long as you keep that page active, MANY users will not have any problems........

**Comment by TheLastBen** [comment]
those instructions were for the old method, the new method's instruction were written in the new method cell.
![sdss](https://user-images.githubusercontent.com/110583491/200121474-882124bd-53d2-45fe-9797-d3064e97bd03.JPG)

**Comment by LIQUIDMIND111** [comment]
> those instructions were for the old method, the new method's instruction were written in the new method cell.
> 
> ![sdss](https://user-images.githubusercontent.com/110583491/200121474-882124bd-53d2-45fe-9797-d3064e97bd03.JPG)

ok dont worry about that, im fine, i now have a question about the Enable_text_encoder_training, is it necessary for CAPTIONED INSTANCES or has nothing do to with that? What is it for?

**Comment by TheLastBen** [comment]
Keep it between 10-20% if you want an easy style transfer, if you want quick results at lower steps, push it to 100%

**Comment by LIQUIDMIND111** [comment]
> Keep it between 10-20% if you want an easy style transfer, if you want quick results at lower steps, push it to 100%

ok listen, are you working on the OLD METHOD PAGE right now??? i am trying to train AGAIN the model i did yesterday, but now i get this 

/bin/bash: accelerate: command not found
Something went wrong

**Comment by TheLastBen** [comment]
you skipped the dependencies cell

**Comment by LIQUIDMIND111** [comment]
> you skipped the dependencies cell

there is none.... what is that? i have done this OLD method MANY times i not remember that

**Comment by LIQUIDMIND111** [comment]
> you skipped the dependencies cell

bro, im gonna take time and RELOAD THE PAGE and do it over again, there is soemthing wrong that was not last night.....

**Comment by TheLastBen** [comment]
the second cell is the dependencies cell

**Comment by LIQUIDMIND111** [comment]
> the second cell is the dependencies cell

ok listen, same as you, i get stressed from technology, i need a break now - but listen, THIS MORNING i started a training on the OLD method, LOOK HERE
![Screenshot 2022-11-05 092858](https://user-images.githubusercontent.com/112510084/200122331-5c8120e2-c4de-4aec-b43d-bc97e6b87981.jpg)


now on OTHER google account, im trying to make another run, as i have done before to save time, and im getting that error.... so since i am doing ALL as i ALWAYS do, i am RELOADING the OLD page and doing it again, i will inform if i get the error AGAIN even with the dependencies SECOND CELL active.....

**Comment by LIQUIDMIND111** [comment]
> the second cell is the dependencies cell

ok, it got fixed somehow, but i am running it now withthe Enable_text_encoder_training activatad at 500 steps.......

**Comment by LIQUIDMIND111** [comment]
NOTE: THE NEW TRAINING MODEL using sd_v1.5 gives AMAZING results HD SUPER!! and BOTH HE NEW and OLD methods WORKS GREAT......

**Comment by calzep** [comment]
@LIQUIDMIND111 did you end up getting better results after doing the new method correctly?

**Comment by LIQUIDMIND111** [comment]
> @LIQUIDMIND111 did you end up getting better results after doing the new method correctly?

not really, i get fat and ugly and NOT my actual face..... on the OLD model, i get perfect results, BUt i noticed that my instance names has NUMBERS, and when training, the instance names that are shown at the training moment, are missing THOSE numbers, what i believe is that you CANNOT use numbers with letters as INSTANCE NAMES.... not sure why, but got BETTER results whe NOT using numbers on the instance names like VREWGVEG(1).jpg compared to 345GFGFD43(1).jpg

**Comment by kelvinz** [comment]
Is the old collab gone? =(
Any idea where I can find it?

**Comment by TheLastBen** [comment]
Try with the new one, if you're not getting good results, I'll walk you through it.

**Comment by LIQUIDMIND111** [comment]
> Try with the new one, if you're not getting good results, I'll walk you through it.

thats really sad you removed the old one, since we were getting BETTER results than the NEW one.... ouch. that hurts

**Comment by LIQUIDMIND111** [comment]
> @LIQUIDMIND111 did you end up getting better results after doing the new method correctly?

NOT BETTER... the old method looked better, but in the new it ONLY worked SOMEWHAT if i use text encoder at 100%/////

**Comment by TheLastBen** [comment]
set "contains_faces" to "No", set the textencoder to 15% the total steps, and rename the images to one unique non-existing word, and you will get almost perfect results

**Comment by kelvinz** [comment]
@TheLastBen, I've tested on man, woman, dogs, and art styles for over 20+ models, and there's just too much trial and error to get something decent. The old method with class and reg images seems to be a lot more consistent. Wondering if you would consider implementing the class/reg back into the new method as an option so we can switch off the text encoding to it?

**Comment by TheLastBen** [comment]
using the terms man or woman or art style as instance names will ruin the training

anyway, I just added concept images feature, a more suitable regularization for sd.

**Comment by Hardtsonfire** [comment]
The new collab worked ONCE for me. I have spent the last two days going completely insane trying to troubleshoot it :( :( :(

**Comment by TheLastBen** [comment]
what issue are you facing ?

**Comment by Hardtsonfire** [comment]
Hi Ben
Thank you so much for your quick reply.
Right now I am totally baffled, but I promise I will return in a day or two with a detailed description, possibly for reproduction, maybe it can help someone else.
I actually have it working now, but I used so many sessions on Google collab, I ran out, and had to buy some.

Now I have to sleep, heh.

Thanks again!

**Comment by Hardtsonfire** [comment]
I kept getting errors before the initial generation of class images;
"dreambooth something went wrong returned non-zero exit status 1"
Couldn't see much helpful info in the rest of the error report, although there may have been.

After pulling out some 50 meters of hair and loosing 5 kg, I found it was related to the connection to Huggingface. At least that is my best guess. I'm having problems with my internet, and only have about 1,5mbit of bandwidth atm, so I cannot test.

When I removed the huggingface token, it worked. It asked for it once, and I supplied it. Next time, it didn't ask. I generated a new token before trying that, and tried a bunch of different SD models, and basically all other suggested solutions I could find on the net.

Sorry I can't get more specific right now.
