### ISSUE TITLE
Error running Colab

### ISSUE THREAD

**Issue by bennitheblog** [TheLastBen/fast-stable-diffusion#394]
Last cell in the Google Colab started failing for me today; was running on an older version but even after using the newest linked version here, still having this error:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import devices, sd_samplers, upscaler, extensions
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 14, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 19, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 433
    if (optimizer_name := hypernetwork.optimizer_name) in optimizer_dict:
                       ^
SyntaxError: invalid syntax

**Comment by JasperAlexander** [comment]
I have this error too.

**Comment by Riooad** [comment]
me too...

**Comment by TheLastBen** [comment]
A1111 probably made a syntax error, they will fix it quickly, keep to box "update_repo" checked and run it until the problem is fixed

**Comment by tridip1931** [comment]
Referencing the issue  https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4330

**Comment by nagikoru** [comment]
Open the hypernetwork.py at /content/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py then remove the code from line 428 to 455 solved the problem (for me).

**Comment by TheLastBen** [comment]
> Open the hypernetwork.py at /content/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py then remove the code from line 428 to 455 solved the problem (for me).

If you do that, you will have to remove hypernetwork.py later to allow the repo update, otherwise it won't update
