### ISSUE TITLE
tag_autocomplete_helper.py script breaks on colab, works on local. 

### ISSUE THREAD

**Issue by hashborgir** [TheLastBen/fast-stable-diffusion#409]
Reproduce: Install the automatic1111 tag completion script from extensions tab

```
Error loading script: tag_autocomplete_helper.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 77, in <module>
    write_tag_base_path()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 63, in write_tag_base_path
    f.write(TAGS_PATH.relative_to(FILE_DIR).as_posix())
  File "/usr/lib/python3.7/pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/tags' does not start with '/content/gdrive/MyDrive/sd/stable-diffusion'
```

**Comment by TheLastBen** [comment]
in the last cell, change 
```
with capture.capture_output() as cap: 
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui
```
to

```
with capture.capture_output() as cap: 
  %cd /content/gdrive/MyDrive/sd/stable-diffusion
```
let me know if it works so I'll revert the pull request

**Comment by hashborgir** [comment]
Fixed. Thank you.
