### ISSUE TITLE
Model Path set to to custom model and error when uploading images in the colab

### ISSUE THREAD

**Issue by jx1k** [TheLastBen/fast-stable-diffusion#432]
Currently the path to the model is set to the custom model "nitrosocke/redshift-diffusion" and not to the standard "runwayml/stable-diffusion-v1-5". I suspect this is a leftover from testing, but might be intentional.
When uploading the images, they get copied to the session folder, but I get this error

``` python
---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/PIL/JpegImagePlugin.py](https://localhost:8080/#) in _save(im, fp, filename)
    611     try:
--> 612         rawmode = RAWMODE[im.mode]
    613     except KeyError:

KeyError: 'RGBA'


During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)

2 frames

[/usr/local/lib/python3.7/dist-packages/PIL/JpegImagePlugin.py](https://localhost:8080/#) in _save(im, fp, filename)
    612         rawmode = RAWMODE[im.mode]
    613     except KeyError:
--> 614         raise OSError("cannot write mode %s as JPEG" % im.mode)
    615 
    616     info = im.encoderinfo

OSError: cannot write mode RGBA as JPEG
```

I tried running the training anyways, but this error gets thrown

``` python
'########:'########:::::'###::::'####:'##::: ##:'####:'##::: ##::'######:::
... ##..:: ##.... ##:::'## ##:::. ##:: ###:: ##:. ##:: ###:: ##:'##... ##::
::: ##:::: ##:::: ##::'##:. ##::: ##:: ####: ##:: ##:: ####: ##: ##:::..:::
::: ##:::: ########::'##:::. ##:: ##:: ## ## ##:: ##:: ## ## ##: ##::'####:
::: ##:::: ##.. ##::: #########:: ##:: ##. ####:: ##:: ##. ####: ##::: ##::
::: ##:::: ##::. ##:: ##.... ##:: ##:: ##:. ###:: ##:: ##:. ###: ##::: ##::
::: ##:::: ##:::. ##: ##:::: ##:'####: ##::. ##:'####: ##::. ##:. ######:::
:::..:::::..:::::..::..:::::..::....::..::::..::....::..::::..:::......::::

Progress:|                         |  0% 18/5000 [00:25<1:20:50,  1.03it/s, loss=0.029, lr=1.99e-6]Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 782, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 630, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 357, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 324, in __getitem__
    instance_image = Image.open(path)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/SD1.5_evktrg_5000_10_v1.0/instance_images/evktrg (45).jpg.png'
Progress:|                         |  0% 18/5000 [00:25<1:57:18,  1.41s/it, loss=0.029, lr=1.99e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=500', '--stop_text_encoder_training=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/SD1.5_evktrg_5000_10_v1.0', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/SD1.5_evktrg_5000_10_v1.0/instance_images', '--output_dir=/content/models/SD1.5_evktrg_5000_10_v1.0', '--instance_prompt=', '--seed=882683', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=5000']' returned non-zero exit status 1.
Something went wrong
```

**Comment by jx1k** [comment]
Sorry I can't send it, due to privacy reasons, but I found out the double extension was tripping it up. When the file is correctly renamed to "evktrg (45).png" it actually works fine. I used this image in multiple trainings, but before you added the cropping it didn't cause problems. In any case, this an error on my side, because for some reason that one png slipped in my training data.

**Comment by TheLastBen** [comment]
I thought it was due to the image format, but since it's just the double extension, then everything works as it should.

**Comment by TheLastBen** [comment]
it uses JPG format only for JPG files

```python 
if (extension.upper() == "JPG"):
  image.save(new_path_with_file, format="JPEG")
```
I'll add the `quality=100` argument, thanks
