### ISSUE TITLE
Inpainting returns the same image when using "Inpaint masked"

### ISSUE THREAD

**Issue by KShivendu** [TheLastBen/fast-stable-diffusion#434]
Hi @TheLastBen,

I have been trying to use the inpainting feature with my custom SD model (trained using this repo) but it doesn't work "Inpaint masked". It literally returns the same image back without showing any errors in Colab or the UI. 

 However, it works when "Inpaint not masked" is used, it works.

## When "Inpaint not masked" is selected 

![inpaint-not-masked](https://user-images.githubusercontent.com/47217984/200594492-8c772128-ca8b-4df3-b765-9ae03b0680ac.png)

## When "Inpaint masked" is selected

![inpainting-masked](https://user-images.githubusercontent.com/47217984/200594513-ad8b6c63-c296-4663-ab7f-73bac5cb81d2.png)

Thanks a lot!

**Comment by TheLastBen** [comment]
Hi, update the repo and use the latest notebook, I tested and it works fine, must be your repo not being up to date

**Comment by bayoumedic** [comment]
everything up to date.  still not working.  it seems like it doesnt recognize the mask exists.  
if you select inpaint not masked it will apply its result to everything.  the result is also either a black screen or noise.  i cant get anything else out of it

**Comment by TheLastBen** [comment]
@bayoumedic do you see the new samplers in the webui (DPM2++2S ...etc) ?

**Comment by bayoumedic** [comment]
yes,  i have 12 on the inpaint screen

**Comment by TheLastBen** [comment]
I'll update the gradio shortly, that should fix the issue

**Comment by bayoumedic** [comment]
now i get this

Error completing request
Arguments: (1, 'High-res photograph tesla logo on a bird, artstation,  sharp focus', '', 'None', 'None', None, {'image': <PIL.Image.Image image mode=RGBA size=512x512 at 0x7FD0F634AB50>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=512x512 at 0x7FD0F6303710>}, None, None, 0, 53, 11, 4, 2, False, False, 1, 4, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, True, 32, 0, '', '', 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 139, in img2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 423, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 485, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 767, in init
    mask = mask.crop(crop_region)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1171, in crop
    raise ValueError("Coordinate 'right' is less than 'left'")
ValueError: Coordinate 'right' is less than 'left'

**Comment by TheLastBen** [comment]
remove or rename the folder "sd" and do a clean run with the latest colab

**Comment by bayoumedic** [comment]
still the same
