### ISSUE TITLE
AttributeError: module 'modules.script_callbacks' has no attribute 'UiTrainTabParams'

### ISSUE THREAD

**Issue by Strahammer** [TheLastBen/fast-stable-diffusion#438]
Step 5 fails to complete at this point:

AttributeError: module 'modules.script_callbacks' has no attribute 'UiTrainTabParams'

All previous steps were completed without error, only the final step does not complete.

**Comment by TheLastBen** [comment]
use the latest colab and check the box "update repo"

**Comment by StripedPuppy** [comment]
> use the latest colab and check the box "update repo"

Still occurring. Latest colab, up to date.

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 203, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 149, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call) 
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1295, in create_ui
    params = script_callbacks.UiTrainTabParams(txt2img_preview_params)
AttributeError: module 'modules.script_callbacks' has no attribute 'UiTrainTabParams'
```

**Comment by TheLastBen** [comment]
remove/rename the folder sd in your gdrive and do a clean run
