### ISSUE TITLE
OSError: /content/stable-diffusion-v1-5 does not appear to have a file named config.json

### ISSUE THREAD

**Issue by nvjob** [TheLastBen/fast-stable-diffusion#440]
Progress:|█████████                | 35% 1050/3000 [17:08<31:37,  1.03it/s, loss=0.0468, lr=1.34e-6]  Freezing the text_encoder ... 
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 782, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 708, in main
    text_encoder=accelerator.unwrap_model(text_encoder),
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipeline_utils.py", line 471, in from_pretrained
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_utils.py", line 1977, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 531, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 558, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 625, in _get_config_dict
    _commit_hash=commit_hash,
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 381, in cached_file
    f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
OSError: /content/stable-diffusion-v1-5 does not appear to have a file named config.json. Checkout 'https://huggingface.co//content/stable-diffusion-v1-5/None' for available files.
Progress:|█████████                | 35% 1050/3000 [17:11<31:55,  1.02it/s, loss=0.0468, lr=1.34e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=500', '--stop_text_encoder_training=1050', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ertrt-face-test', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ertrt-face-test/instance_images', '--output_dir=/content/models/ertrt-face-test', '--instance_prompt=', '--seed=93576', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=3000']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
use the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by DimensionY** [comment]
same error with the latest colab

**Comment by TheLastBen** [comment]
Does the folder "stables-diffusion-v1-5" have alle the folders inside ?

**Comment by balintdecsi** [comment]
Hello, same here; only I get it at the end of the progress. "feature_extractor" and "safety_checker" folders are missing.

**Comment by TheLastBen** [comment]
are you using the default sd1.5 model ?

**Comment by TheLastBen** [comment]
I left by mistake a link to a different custom model, that's probably what's causing the issue, but I removed that earlier.

**Comment by balintdecsi** [comment]
I used the 1,4 model. With 1.5, it contains those folders, too. Although, I don't know it it is for a purpose, but "
v1-inference.yaml" is missing under "stable-diffusion-v1-5".

**Comment by TheLastBen** [comment]
use the latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb, reproduce the error and copy the log

**Comment by balintdecsi** [comment]
Now it works for me. Thanks!

Ben ***@***.***> ezt írta (időpont: 2022. nov. 9., Sze 16:10):

**Comment by xbbkok** [comment]
I got the same error
