### ISSUE TITLE
ImportError: cannot import name 'processing' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by slumberspirit** [TheLastBen/fast-stable-diffusion#443]
Hi. When I run this the first time it works, but if I disconnect and reconnect, I get this error when running "Start stable-diffusion." If I delete the sd folder in my drive and run it again, it needs to recreate that folder but it works.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import devices, sd_samplers, upscaler, extensions, localization
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 19, in <module>
    from modules import sd_samplers, shared, script_callbacks
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 19, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 15, in <module>
    from modules import devices, processing, sd_models, shared
ImportError: cannot import name 'processing' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
Check the box "update_repo", and always use the latest colab from the repo
