### ISSUE TITLE
SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by SAC020** [TheLastBen/fast-stable-diffusion#454]
It's a new model, did nothing different from previous trainings on other models

```
File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 475
    if os.path.exists(str(args.output_dir+"/text_encoder_trained):
                                                                 ^
SyntaxError: EOL while scanning string literal
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=1200', '--stop_text_encoder_training=540', '--save_n_steps=1200', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cydotfd_woman_hanged_with_noose_around_neck_tied_hands_naked_nude_barefoot', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/cydotfd_woman_hanged_with_noose_around_neck_tied_hands_naked_nude_barefoot/instance_images', '--output_dir=/content/models/cydotfd_woman_hanged_with_noose_around_neck_tied_hands_naked_nude_barefoot', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=3600']' returned non-zero exit status 1.
Something went wrong
```

**Comment by TheLastBen** [comment]
i'll fix it in a minute

**Comment by TheLastBen** [comment]
do this in a new cell to avoid restarting the session : 

```
%cd /content
!rm -r /content/diffusers
!git clone https://github.com/TheLastBen/diffusers
```

**Comment by SAC020** [comment]
Thanks, stopped the session already. I’ll try again later

TY!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SAC020** [comment]
I can confirm it is fixed. Thank you

**Comment by TheLastBen** [comment]
great !
