### ISSUE TITLE
Colab with usual settings new error

### ISSUE THREAD

**Issue by vgaggia** [TheLastBen/fast-stable-diffusion#458]
Hi, i'm suddenly getting this error with the google colab

 File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 785, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 636, in main
    latents = vae.encode(batch["pixel_values"].to(dtype=weight_dtype)).latent_dist.sample()
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/vae.py", line 549, in encode
    h = self.encoder(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/vae.py", line 124, in forward
    sample = self.mid_block(sample)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_blocks.py", line 279, in forward
    hidden_states = attn(hidden_states)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 82, in forward
    query_proj = self.query(hidden_states)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
  0% 0/20000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=5000', '--stop_text_encoder_training=7000', '--save_n_steps=5000', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Eeveelution512', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Eeveelution512/instance_images', '--output_dir=/content/models/Eeveelution512', '--instance_prompt=', '--seed=140667', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=20000']' returned non-zero exit status 1.

**Comment by TheLastBen** [comment]
run `!nvidia-smi` in a new cell and see which GPU you have

**Comment by TheLastBen** [comment]
so it was working this morning ?

**Comment by vgaggia** [comment]
It was on the 9th

**Comment by TheLastBen** [comment]
getting the same error even after restarting a session ?

**Comment by vgaggia** [comment]
I have tried that, i'm trying it again now, for some reason with my dataset even though i pre-cropped it, i have to let it crop the images and it takes ~20 minutes to get through the dataset, i'll let you know when it gets to training again

**Comment by TheLastBen** [comment]
20 minutes to crop ? you mean the crop feature in the colab ?

**Comment by vgaggia** [comment]
Yeah the crop feature in colab

**Comment by TheLastBen** [comment]
how many pics ? it should take seconds, not minutes

**Comment by vgaggia** [comment]
It's around 530 (66 images per subject for 8 subjects)

**Comment by vgaggia** [comment]
I do that, the first time i tried it i just got some error can't remember what it was so i just do it that way now, i'll test afterwards if i don't get the error on this retry

**Comment by vgaggia** [comment]
Ok yeah not really sure what happened, but i just restarted it again and it seems to just be working now for some reason? sorry for all that, appreciate the help though!

**Comment by TheLastBen** [comment]
happy to help, don't forget to test training on 768x768 images when you have time, your feedback will help

**Comment by vgaggia** [comment]
Absolutely i will try that, i've been thinking of trying 1024x1024 but i want to get a 512x512 model to work as expected first

**Comment by TheLastBen** [comment]
1024 results will be much better than 512
