### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by realguman** [TheLastBen/fast-stable-diffusion#459]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [e3b0c442] from /content/gdrive/MyDrive/model/v1.5.ckpt
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 203, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 146, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 82, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 254, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 183, in load_model_weights
    pl_sd = torch.load(checkpoint_file, map_location=shared.weight_load_location)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 102, in load
    return load_with_extra(filename, *args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/safe.py", line 147, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

Windows 11, find no similar situations.

**Comment by realguman** [comment]
Here's the result from search engine:
Might be caused because the file _serialization.py_ is open twice using pickle without close, and mistakenly emptied. Adding f.close().
As I have literally no coding knowledge, I'm afraid I can't put the code in the right place. Please help to fix the bug.

Hope this is helpful.
