### ISSUE TITLE
Unable to use PLMS

### ISSUE THREAD

**Issue by outhipped** [TheLastBen/fast-stable-diffusion#486]
Hi. I never tried to use PLMS before but now when I tried i get the following error:

ata shape for PLMS sampling is (1, 4, 64, 64)
Running PLMS Sampling with 20 timesteps
PLMS Sampler:   0% 0/20 [00:00<?, ?it/s]
PLMS Sampler:   5% 1/20 [00:00<00:07,  2.59it/s]
PLMS Sampler:  10% 2/20 [00:00<00:04,  3.93it/s]
PLMS Sampler:  15% 3/20 [00:00<00:03,  4.73it/s]
PLMS Sampler:  20% 4/20 [00:00<00:03,  5.22it/s]
PLMS Sampler:  25% 5/20 [00:01<00:02,  5.54it/s]
PLMS Sampler:  30% 6/20 [00:01<00:02,  5.73it/s]
PLMS Sampler:  35% 7/20 [00:01<00:02,  5.83it/s]
PLMS Sampler:  40% 8/20 [00:01<00:02,  5.92it/s]
PLMS Sampler:  45% 9/20 [00:01<00:01,  6.02it/s]
PLMS Sampler:  50% 10/20 [00:01<00:01,  6.06it/s]
PLMS Sampler:  55% 11/20 [00:02<00:01,  6.09it/s]
PLMS Sampler:  60% 12/20 [00:02<00:01,  6.11it/s]
PLMS Sampler:  65% 13/20 [00:02<00:01,  6.12it/s]
PLMS Sampler:  70% 14/20 [00:02<00:00,  6.14it/s]
PLMS Sampler:  75% 15/20 [00:02<00:00,  6.16it/s]
PLMS Sampler:  80% 16/20 [00:02<00:00,  6.15it/s]
PLMS Sampler:  85% 17/20 [00:02<00:00,  6.14it/s]
PLMS Sampler:  90% 18/20 [00:03<00:00,  6.14it/s]
PLMS Sampler:  95% 19/20 [00:03<00:00,  6.15it/s]
PLMS Sampler: 100% 20/20 [00:03<00:00,  5.77it/s]
Error completing request
Arguments: ('Party photo of Boris Johnson, photo by Stephen Shore', 'noise, hdr, ((high iso))), grainy, ((((ugly)))), (((duplicate))), ((morbid)), ((mutilated)), [out of frame], extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), blurry, ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), out of frame, ugly, extra limbs, (bad anatomy), gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck)))', 'None', 'None', 20, 16, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.7, 0, 0, 0, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 48, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 423, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 519, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 717, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, conditioning, unconditional_conditioning, steps=self.steps, image_conditioning=image_conditioning)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 230, in sample_img2img
    x1 = self.sampler.stochastic_encode(x, torch.tensor([t_enc] * int(x.shape[0])).to(shared.device), noise=noise)
AttributeError: 'PLMSSampler' object has no attribute 'stochastic_encode'

**Comment by outhipped** [comment]
had to disable hires fix
