### ISSUE TITLE
FileNotFoundError on "Test The Trained Model" cell

### ISSUE THREAD

**Issue by awwong1** [TheLastBen/fast-stable-diffusion#492]
```text
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import devices, sd_samplers, upscaler, extensions, localization
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 9, in <module>
    import ldm.models.diffusion.ddim
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
FileNotFoundError: [Errno 2] No such file or directory
```

Opening up `/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py` I see
```text
Import "ldm.models.diffusion.ddim" could not be resolvedPyright(reportMissingImports)
No quick fixes available
```

![Screen Shot 2022-11-13 at 15 27 26](https://user-images.githubusercontent.com/2760111/201547765-c91c36e8-275d-456e-88cc-d185aa3f67c7.png)

**Comment by TheLastBen** [comment]
remove the folder "sd" and rerun the cell

**Comment by awwong1** [comment]
Thanks- I think this issue was related to some Google drive issues and probably not a problem with this repo.
