### ISSUE TITLE
error with inpainting

### ISSUE THREAD

**Issue by bayoumedic** [TheLastBen/fast-stable-diffusion#500]
everything is updated to the latest

Error completing request
Arguments: (1, 'High-res photograph public park background, art by joe fenton, stanley artgerm, tom bagshaw, artstation, wlop, teletubbies, muted color, tintype, sharp focus', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=844x844 at 0x7FA900772D50>, {'image': <PIL.Image.Image image mode=RGBA size=512x512 at 0x7FA900772890>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=512x512 at 0x7FA900772950>}, None, None, 0, 48, 7, 4, 1, False, False, 1, 4, 7, 0.52, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, True, 32, 0, '', '', 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 139, in img2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 423, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 485, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 767, in init
    mask = mask.crop(crop_region)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1171, in crop
    raise ValueError("Coordinate 'right' is less than 'left'")
ValueError: Coordinate 'right' is less than 'left'

**Comment by JimZeeKing** [comment]
had this error with a wrong mask image once

**Comment by bayoumedic** [comment]
finally figured it out.  clear browser cache or use a different browser
