### ISSUE TITLE
Resuming training skips text_encoder training

### ISSUE THREAD

**Issue by ati101** [TheLastBen/fast-stable-diffusion#501]
Hey @TheLastBen 

I've successfully trained the model once with reasonable results. Wanted to do an extra 1000 steps with text_encoder enabled. But with Resume training : On; text_encoder part throws an error (the error disappears in an instant, is there a way to capture that?) and it skips to 
the unet training, which continues as expected. 

I've tried it with Contains_Faces: No, as well. Doesn't work.

Is there a way to get text_encoder working with resume training turned on?

**Comment by TheLastBen** [comment]
Hi, remove this part, run the cell, and copy the error log : 
![s](https://user-images.githubusercontent.com/110583491/201746806-e3367ef9-4722-46a0-a292-6eb9574172c7.JPG)

**Comment by ati101** [comment]
Same skips the enitre text_encoder part. 

Here's the error log.

`Traceback (most recent call last):
  File "/usr/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1653, in _wait
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 787, in <module>
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1611, in _try_wait
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 478, in main
    text_encoder = CLIPTextModel.from_pretrained(args.output_dir, subfolder="text_encoder")
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_utils.py", line 2182, in from_pretrained
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 352, in simple_launcher
    process.wait()
  File "/usr/lib/python3.7/subprocess.py", line 1032, in wait
    self._wait(timeout=sigint_timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1647, in _wait
    time.sleep(delay)
KeyboardInterrupt
    state_dict = load_state_dict(resolved_archive_file)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_utils.py", line 399, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 997, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch._UntypedStorage).storage()._untyped()
KeyboardInterrupt`

**Comment by TheLastBen** [comment]
why does it say "KeyboardInterrupt" ? did you interrupt the execution of the cell ?

**Comment by ati101** [comment]
Yes I didn't want to start the unet training again after the text-encoder got skipped.

**Comment by TheLastBen** [comment]
did you check the box "train the text encoder" ? and how much % did you input ?

**Comment by ati101** [comment]
Yes, I did. I tried it with different values ranging between 35-65. All leading to the same conclusion.

**Comment by TheLastBen** [comment]
Are you using the default 1.5 model ?

**Comment by ati101** [comment]
No, 1.4

**Comment by TheLastBen** [comment]
try with the 1.5, if it works, we will narrow the debugging to the 1.4

**Comment by ati101** [comment]
OK, I'll report back shortly with the results then!

**Comment by zlikwidart** [comment]
I'm actually having the same problem.  I am skipping the downloading of the model as it says to do in loading a previous session in the 'Downloading the model' section.  No matter what percentage I enter it just skips and goes straight to unet.

**Comment by ati101** [comment]
> I'm actually having the same problem. I am skipping the downloading of the model as it says to do in loading a previous session in the 'Downloading the model' section. No matter what percentage I enter it just skips and goes straight to unet.

So, were you using the default 1.5 model or a custom one?

**Comment by zlikwidart** [comment]
> 

I was using the default 1.5

**Comment by zlikwidart** [comment]
Hmm.  Ok.  I think it seems to be working if I just don't skip the "Downloading the model" 
![Capture](https://user-images.githubusercontent.com/83528487/201885950-4d746cb7-92c9-4ccc-baba-575cbc07e605.JPG)
![Capture 2](https://user-images.githubusercontent.com/83528487/201886161-eeb46218-2452-4abe-9597-17a747d74ecf.JPG)

**Comment by ati101** [comment]
So are you using a ckpt path that points to the Sessions folder?

**Comment by zlikwidart** [comment]
> 
I'm just inserting my Huggingface_Token and not using a CKPT_PATH.  If you leave everything blank in the "Downloading the model" section it will have a little section just asking for your token and default to 1.5 I believe.  

My sessions are loaded from my gdrive at Session_Name under the "Create/Load a Session" section.

**Comment by ati101** [comment]
In my case, I'll paste the link to my trained model under the ckpt path in the "Download Model" section, to see if that helps.
Else we can narrow it down to this *feature* being exclusive to the default 1.5 model.

**Comment by ati101** [comment]
FIXED IT!!!

The issue here was skipping the "Downloading the model" section.

![Web capture_16-11-2022_01215_colab research google com](https://user-images.githubusercontent.com/118213656/202001402-50033011-7d70-40df-9dd0-3d281cdf4095.jpeg)

This led me to believe that when resuming the model, this section could be skipped, but after @zlikwidart 's claim I decided to give it a try.

@TheLastBen, closing this issue.

Thanks!

**Comment by TheLastBen** [comment]
You skip it only if there is a model present in the previous session folder

**Comment by ati101** [comment]
> You skip it only if there is a model present in the previous session folder
I had the model in the previous session folder, and still had to do this for text_encoder to resume training. 
But what I noticed is whenever I'm running this colab the model, in my sessions folder, occupies twice the storage space on my GDrive.
[
Size:3.97GB
Storage used: 7.94 GB
]

**Comment by TheLastBen** [comment]
resuming now is fixed https://github.com/TheLastBen/fast-stable-diffusion/commit/99ecd9f83aebe922347552f91d82e10086042e53
As for the size, the intermediary checkpoints are also stored in the session folder, so that might be what is taking the space

**Comment by ati101** [comment]
Yes, I noticed that. But I'm talking about the main checkpoint file, itself occupying twice the storage.

![Web capture_16-11-2022_153634_drive google com](https://user-images.githubusercontent.com/118213656/202151623-35ce6c7b-5581-42d7-bfc5-eea943bb12f2.jpeg)

Thanks for the fix!

**Comment by TheLastBen** [comment]
That must be a google drive issue or some other app interfering with it
