### ISSUE TITLE
Checkpoint Merger error

### ISSUE THREAD

**Issue by jason-taylor-edi** [TheLastBen/fast-stable-diffusion#510]
I got the following error while trying to merge sd-v1-5-inpainting.ckpt with a dreambooth .ckpt:

Merging...
  0% 0/1131 [00:00<?, ?it/s]
Error loading/saving model file:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1681, in modelmerger
    results = modules.extras.run_modelmerger(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 293, in run_modelmerger
    if key in theta_2:
TypeError: argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 274, in run_predict
    fn_index, raw_input, username, session_state, iterators
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 746, in process_api
    predictions = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 700, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: list index out of range

**Comment by TheLastBen** [comment]
They have a different architecture, I don't think they are compatible

**Comment by TheLastBen** [comment]
there is a dropdown menu from which you chose the model

**Comment by TheLastBen** [comment]
Put all the models in one folder, then put the link to that folder into path_to_model.

**Comment by jason-taylor-edi** [comment]
I now see all the models in the drop down list, thanks. I seem to be unable to merge any of my models so I assume they are incompatible - I trained them using your Dreambooth colab. Are these models compatible for merging?

**Comment by TheLastBen** [comment]
what type of merging are you using, there are two options

**Comment by jason-taylor-edi** [comment]
I was using add difference, but weighted sum works. This issue is resolved for me, thank you.

**Comment by GuruVirus** [comment]
Probably not enough RAM to handle all 3 models.

**Comment by TheLastBen** [comment]
the add difference method doesn't work, I'm not sure if it works locally

**Comment by GuruVirus** [comment]
> the add difference method doesn't work, I'm not sure if it works locally

Do you mean in your repo, or in general? I know people that are using add diff successfully, but may not be using this.

**Comment by TheLastBen** [comment]
I'm not sure locally, I'm gonna have to try it
