### ISSUE TITLE
error dreambooth extension to load on colab --- Error loading script: api.py Error loading script: main.py  ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)

### ISSUE THREAD

**Issue by wilzamguerrero** [TheLastBen/fast-stable-diffusion#521]
Hi i have again a problem when i run automatic1111 with the extension of dreambooth on colab

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 9, in <module>
    from dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in <module>
    from dreambooth import xattention
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 8, in <module>
    from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in <module>
    from dreambooth import xattention
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 8, in <module>
    from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)

**Comment by wilzamguerrero** [comment]
Later i used

!pip install diffusers==0.7.2

and now i have [!] Not using xformers memory efficient attention.

**Comment by wilzamguerrero** [comment]
This work for me in google colab

!pip install GitPython==3.1.27
!pip install Pillow==9.2.0
!pip install accelerate==0.14.0
!pip install albumentations==1.3.0
!pip install basicsr==1.4.2
!pip install bitsandbytes==0.35.0
!pip install bitsandbytes
!pip install clean-fid==0.1.29
!pip install diffusers==0.7.2
!pip install einops==0.4.1
!pip install fairscale==0.4.9
!pip install font-roboto
!pip install fonts
!pip install ftfy==6.1.1
!pip install gfpgan==1.3.8
!pip install gradio==3.9
!pip install inflection==0.5.1
!pip install jsonmerge==1.8.0
!pip install kornia==0.6.7
!pip install lark==1.1.2
!pip install modelcards==0.1.6
!pip install numpy==1.23.3
!pip install omegaconf==2.2.3
!pip install piexif==1.1.3
!pip install pytorch_lightning==1.7.6
!pip install realesrgan==0.3.0
!pip install resize-right==0.0.2
!pip install scikit-image==0.19.2
!pip install tensorboard==2.11.0
!pip install timm==0.6.7
!pip install torch
!pip install torchdiffeq==0.2.3
!pip install tqdm==4.64.1
!pip install transformers==4.21.0

and later in automatic 1111 deactivate this 
![image](https://user-images.githubusercontent.com/110712636/202548762-b1b5f01f-4d80-401b-9a51-67bf8fd8a199.png)

and now is running 
![image](https://user-images.githubusercontent.com/110712636/202548908-1da8db32-f4a6-4f43-89a9-cdf8a33d6599.png)
