### ISSUE TITLE
Checkpoint merger error ^C

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#527]
In colab, trying to merge 3 models with add diff set to 1.0. Could be incompatible architectures as you mentioned here: , but no warnings so I'm unclear on that. Will look into that.

The colab output ends with ^C
The webUI says error next to each field.

What about f16 selection? If input is f16 does output need to be f16?
I've tried multiple times.
![image](https://user-images.githubusercontent.com/4285187/202351748-f369e9db-cd13-44ad-8033-acf0fe62978d.png)

**Comment by GuruVirus** [comment]
Reducing the variables and trying 2 of them, got this with add 1.0
Merging...
  0% 0/1133 [00:00<?, ?it/s]
Error loading/saving model file:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1681, in modelmerger
    results = modules.extras.run_modelmerger(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 293, in run_modelmerger
    if key in theta_2:
TypeError: argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 285, in run_predict
    fn_index, raw_input, username, session_state, iterators
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: list index out of range

------------------
With weighted 0.3:
Merging...
100% 1133/1133 [00:07<00:00, 142.05it/s]
Saving to /content/gdrive/MyDrive/....ckpt...
Checkpoint saved.

What's the problem here?

**Comment by GuruVirus** [comment]
I watched closely and free colab is hitting the 12GB RAM limit with three 4GB models.
