### ISSUE TITLE
Attribute Error When Testing the Trained Model

### ISSUE THREAD

**Issue by JoeBuydemDips** [TheLastBen/fast-stable-diffusion#571]
I get this error when testing the trained model.

Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 207, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 150, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 88, in initialize
    shared.opts.onchange("sd_vae_as_default", wrap_queued_call(lambda: modules.sd_vae.reload_vae_weights()), call=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 466, in onchange
    item.onchange = func
AttributeError: 'NoneType' object has no attribute 'onchange'

**Comment by jwang919** [comment]
I have this problem too

**Comment by TheLastBen** [comment]
Do a clean run by removing/renaming the folder "sd" in your gdrive

**Comment by JoeBuydemDips** [comment]
@TheLastBen That worked!!! Thank you.
