### ISSUE TITLE
Error testing trained model

### ISSUE THREAD

**Issue by ThewsyRum** [TheLastBen/fast-stable-diffusion#582]
Whenever I test my model I get errors like this:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import devices, sd_samplers, upscaler, extensions, localization
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/prompt_parser.py", line 14, in <module>
    schedule_parser = lark.Lark(r"""
AttributeError: module 'lark' has no attribute 'Lark'

I try to install the dependency but when I run it again I get another error

**Comment by TheLastBen** [comment]
try `!pip install lark==1.1.3`

**Comment by ThewsyRum** [comment]
Thanks for answering, but it still didn't solve it, when I run the command:

pip install lark==1.1.3

I get this:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting lark==1.1.3
  Downloading lark-1.1.3-py3-none-any.whl (107 kB)
     |████████████████████████████████| 107 kB 5.1 MB/s 
WARNING: Error parsing requirements for uvicorn: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/uvicorn-0.18.3.dist-info/METADATA'
WARNING: Error parsing requirements for torch-fidelity: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/torch_fidelity-0.3.0.dist-info/METADATA'
WARNING: Error parsing requirements for timm: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/timm-0.4.12.dist-info/METADATA'
WARNING: Error parsing requirements for realesrgan: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/realesrgan-0.3.0.dist-info/METADATA'
WARNING: Error parsing requirements for pynvml: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/pynvml-11.4.1.dist-info/METADATA'
WARNING: Error parsing requirements for pycocoevalcap: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/pycocoevalcap-1.2.dist-info/METADATA'
WARNING: Error parsing requirements for pudb: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/pudb-2019.2.dist-info/METADATA'
WARNING: Error parsing requirements for piexif: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/piexif-1.1.3.dist-info/METADATA'
WARNING: Error parsing requirements for orjson: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/orjson-3.8.0.dist-info/METADATA'
WARNING: Error parsing requirements for lpips: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/lpips-0.1.4.dist-info/METADATA'
WARNING: Error parsing requirements for lark: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/lark-1.1.2.dist-info/METADATA'
WARNING: Error parsing requirements for kornia: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/kornia-0.6.0.dist-info/METADATA'
Installing collected packages: lark
  Attempting uninstall: lark
    Found existing installation: lark 1.1.2
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/lark-1.1.2.dist-info/RECORD'

**Comment by TheLastBen** [comment]
This issue shouldn't happen, try doing a clean run
