### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by phananh03x** [TheLastBen/fast-stable-diffusion#604]
I run the training and it give error :
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_errors.py", line 213, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/Jack-Sparrow/resolve/main/tokenizer/vocab.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 1057, in hf_hub_download
    timeout=etag_timeout,
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 1359, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_errors.py", line 242, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: U6zThL8HnQ9JF34PecFO8)

Repository Not Found for url: https://huggingface.co/Jack-Sparrow/resolve/main/tokenizer/vocab.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 788, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 472, in main
    tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1748, in from_pretrained
    _commit_hash=commit_hash,
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 425, in cached_file
    f"{path_or_repo_id} is not a local folder and is not a valid model identifier "
OSError: Jack-Sparrow is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=600', '--stop_text_encoder_training=840', '--save_n_steps=200', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Jack', '--pretrained_model_name_or_path=Jack-Sparrow', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Jack/instance_images', '--output_dir=/content/models/Jack', '--instance_prompt=', '--seed=69', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=1200']' returned non-zero exit status 1.
Something went wrong

**Comment by phananh03x** [comment]
I typed ' Jack ' in the session name box, is it wrong ?

**Comment by nawnie** [comment]
any chance your accidently using the hugging face download option at the beginning

**Comment by TheLastBen** [comment]
make sure you use the correct model link/path

**Comment by jvkap** [comment]
> make sure you use the correct model link/path

@TheLastBen I won't create another issue and ask something right here ... I believe Dreambooth's Colab needs to be updated to use v2 and the new Stability Clips, right?

**Comment by TheLastBen** [comment]
> @TheLastBen I won't create another issue and ask something right here ... I believe Dreambooth's Colab needs to be updated to use v2 and the new Stability Clips, right?

As soon as the diffusers team make it compatible with the V2
