### ISSUE TITLE
'ScriptRunner' object has no attribute 'initialize_scripts'

### ISSUE THREAD

**Issue by Teale001** [TheLastBen/fast-stable-diffusion#613]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [a2a802b2] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 207, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 153, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call) 
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 696, in create_ui
    modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
AttributeError: 'ScriptRunner' object has no attribute 'initialize_scripts'

**Comment by TheLastBen** [comment]
if the error persists, remove/rename the folder "sd" in your gdrive and do a clean run

**Comment by Teale001** [comment]
got it ~
