### ISSUE TITLE
fast-Dreambooth not working

### ISSUE THREAD

**Issue by ShantanuJalkote** [TheLastBen/fast-stable-diffusion#621]
Getting this error tried multiple times
Progress:|████████                 | 33% 999/3000 [16:27<32:42,  1.02it/s, loss=0.0244, lr=1.37e-6] SAVING CHECKPOINT: /content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shantjaldb/shantjaldb_step_1000.ckpt
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 788, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 734, in main
    text_encoder=accelerator.unwrap_model(text_encoder),
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipeline_utils.py", line 660, in from_pretrained
    f"Pipeline {pipeline_class} expected {expected_modules}, but only {passed_modules} were passed."
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'unet', 'safety_checker', 'tokenizer', 'vae', 'scheduler', 'text_encoder', 'feature_extractor'}, but only {'unet', 'tokenizer', 'vae', 'scheduler', 'text_encoder'} were passed.
Progress:|████████                 | 33% 999/3000 [16:29<33:02,  1.01it/s, loss=0.0244, lr=1.37e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=1000', '--stop_text_encoder_training=3000', '--save_n_steps=1000', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shantjaldb', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shantjaldb/instance_images', '--output_dir=/content/models/shantjaldb', '--instance_prompt=', '--seed=895012', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=3000']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
Should work now, update your colab

**Comment by ShantanuJalkote** [comment]
Thanks, It's Working Now.
