### ISSUE TITLE
Use V2-768, traning error

### ISSUE THREAD

**Issue by clovelee** [TheLastBen/fast-stable-diffusion#633]
The config attributes {'use_linear_projection': True} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 788, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 485, in main
    unet = UNet2DConditionModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="unet")
  File "/usr/local/lib/python3.7/dist-packages/diffusers/modeling_utils.py", line 463, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 202, in from_config
    model = cls(**init_dict)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 523, in inner_init
    init(self, *args, **init_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_condition.py", line 150, in __init__
    dual_cross_attention=dual_cross_attention,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_blocks.py", line 78, in get_down_block
    dual_cross_attention=dual_cross_attention,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_blocks.py", line 554, in __init__
    out_channels // attn_num_head_channels,
TypeError: unsupported operand type(s) for //: 'int' and 'list'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=800', '--stop_text_encoder_training=4000', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/hex', '--pretrained_model_name_or_path=/content/stable-diffusion-v2-768', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/hex/instance_images', '--output_dir=/content/models/hex', '--instance_prompt=', '--seed=742569', '--resolution=768', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=8000']' returned non-zero exit status 1.
Something went wrong

**Comment by TheLastBen** [comment]
this was fixed in the latest colab, use the this link : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by pwichmann** [comment]
You sure? I just refreshed the colab link and tried...

The config attributes {'dual_cross_attention': False, 'use_linear_projection': True} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 788, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 485, in main
    unet = UNet2DConditionModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="unet")
  File "/usr/local/lib/python3.7/dist-packages/diffusers/modeling_utils.py", line 420, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 169, in from_config
    model = cls(**init_dict)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 406, in inner_init
    init(self, *args, **init_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_condition.py", line 134, in __init__
    downsample_padding=downsample_padding,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_blocks.py", line 78, in get_down_block
    attn_num_head_channels=attn_num_head_channels,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_blocks.py", line 510, in __init__
    out_channels // attn_num_head_channels,
TypeError: unsupported operand type(s) for //: 'int' and 'list'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=4999', '--stop_text_encoder_training=1499', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ctz', '--pretrained_model_name_or_path=/content/stable-diffusion-v2-512', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ctz/instance_images', '--output_dir=/content/models/ctz', '--instance_prompt=', '--seed=727714', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=14999']' returned non-zero exit status 1.
Something went wrong

**Comment by pwichmann** [comment]
(By the way, fantastic job. You're my hero now.)

**Comment by TheLastBen** [comment]
I'll check it out

> File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_blocks.py", line 78, in get_down_block

this file doesn't exist in the new updated diffusers repo implements in the latest colab, you need to use the latest colab and restart the runtime to reinstall the new diffusers repo.
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by pwichmann** [comment]
It works now. So it must have been my mistake and refreshing the notebook connected to a previous runtime or so.
Many thanks, @TheLastBen .

**Comment by TheLastBen** [comment]
A1111 added V2 support, so I had to reshape the colab (again), so the testing cell might not work until you get the latest colab (again)

**Comment by clovelee** [comment]
Thank you, The training is work. But Test The Trained Model show error:

```
Moving 0 files to the new cache system
0it [00:00, ?it/s]
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
^C
```

**Comment by TheLastBen** [comment]
Not enough RAM  (not VRAM) free colab

**Comment by clovelee** [comment]
Total 15Gb，used 9.5Gb，still can't work.

**Comment by TheLastBen** [comment]
that's the VRAM not RAM, the RAM is 12.63 with free colab

**Comment by clovelee** [comment]
Does free colab run V2?

**Comment by TheLastBen** [comment]
not at the moment

**Comment by clovelee** [comment]
Got it, thanks for your work.
