### ISSUE TITLE
v2.0 ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by Tophness** [TheLastBen/fast-stable-diffusion#662]
```
`Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 789, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 562, in main
    train_dataset, batch_size=args.train_batch_size, shuffle=True, collate_fn=collate_fn
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 108, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)`
```

**Comment by Tophness** [comment]
Training_Steps set to 2300.
Everything else set up like I used to before the 2.0 update. Not sure why this is happening.

**Comment by TheLastBen** [comment]
It seems that you didn't upload instance images.

**Comment by Tophness** [comment]
Ah right. Thought that would be the only other possible explanation and checked several times but I missed a backslash
