### ISSUE TITLE
Demo not working: "ImportError: cannot import name 'opts' from 'modules.shared'"

### ISSUE THREAD

**Issue by xITmasterx** [TheLastBen/fast-stable-diffusion#668]
I have just finished training my Dreambooth model with no problems. But when I tried to test it, this error pops out:

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 17, in <module>
    from modules import sd_samplers, sd_models, localization, sd_vae, extensions, script_loading
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 11, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 20, in <module>
    from modules.shared import opts, cmd_opts
ImportError: cannot import name 'opts' from 'modules.shared' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py)`

Where did I go wrong?

**Comment by TheLastBen** [comment]
I merged a pull request that should fix it

**Comment by xITmasterx** [comment]
Yeah... It's not working, when is the pull going to be published?

**Comment by xITmasterx** [comment]
Here's the new error:

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'`

**Comment by ClemensLode** [comment]
Same error here. That appeared before the last pull request, too.

**Comment by ClemensLode** [comment]
Now it's

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 8, in <module>
    import safetensors.torch
ModuleNotFoundError: No module named 'safetensors'

**Comment by Klaushayan** [comment]
AUTOMATIC1111 has merged a lot of PRs in the last 2 hours. I bet those are causing these issues.

Can anybody write the steps to reproduce the issue? (i cannot run the notebook atm)

**Comment by afrofail** [comment]
ModuleNotFoundError: No module named 'safetensors' as well

**Comment by luci9t** [comment]
> AUTOMATIC1111 has merged a lot of PRs in the last 2 hours. I bet those are causing these issues.
> 
> Can anybody write the steps to reproduce the issue? (i cannot run the notebook atm)
Just did a clean install from the latest repo, and got the 'safetensors' error, (using colab free), and the main auto1111 notebook.

**Comment by xITmasterx** [comment]
Just run the stable diffusion as per usual. I have my own SD 1.5 model in my google drive. And yes, I am currently getting the safetensors error now.

**Comment by Klaushayan** [comment]
In Requirements cell, if you add `!pip install safetensors` right below `!pip install -q inflection` does that change the error?

**Comment by xITmasterx** [comment]
> In Requirements cell, if you add `!pip install -q safetensors` right below `!pip install -q inflection` does that change the error?

Give me a second, I'll check if that fixed the bug

**Comment by xITmasterx** [comment]
Now it just says this error:

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'`

**Comment by TheLastBen** [comment]
@xITmasterx  did you remove the sd folder and did clean run ?

**Comment by xITmasterx** [comment]
It is done. The program is now stable.

**Comment by xITmasterx** [comment]
Yep, it looks good. I'm closing this thread.
