### ISSUE TITLE
Automatic1111 Looking for Module 'taming'

### ISSUE THREAD

**Issue by Convince54** [TheLastBen/fast-stable-diffusion#681]
Hi,

Since yesterday I have been getting the same error when I try to run the Start Stable Diffusion cell:

Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/stable-diffusion-webui/src/taming-transformers/taming
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stable-diffusion-webui/src/codeformer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stable-diffusion-webui/src/blip/models/blip.py
Warning: k_diffusion not found at path /content/gdrive/MyDrive/sd/stable-diffusion-webui/src/k-diffusion/k_diffusion/sampling.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 15, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack, should_hijack_inpainting
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 6, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ModuleNotFoundError: No module named 'taming'

The above warnings are correct, there is no folder src in stable-diffusion-webui, so there is no taming module. I have been running this for a couple of weeks and this is the first time I've seen this error. Also, I have run the "!pip install safetensors", which seems to run correctly but didn't solve the problem.

**Comment by TheLastBen** [comment]
because of the V2 major update, things have changed with the folders, rename/remove the folder "sd" in your gdrive, update the colab to the latest and do a clean run.
latest colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
