### ISSUE TITLE
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

### ISSUE THREAD

**Issue by Gushousekai195** [TheLastBen/fast-stable-diffusion#682]
When starting up the UI with V2:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'
```

What does that mean?

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/issues/657

**Comment by TheLastBen** [comment]
And use the latest colab from the repo
