### ISSUE TITLE
Can't save images to Google Drive anymore with automatic1111

### ISSUE THREAD

**Issue by Stoi84** [TheLastBen/fast-stable-diffusion#684]
Not sure if I did something wrong, but I can't seem to save images to my Google Drive anymore. Getting this error.

> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 169, in f
>     res = list(func(*args, **kwargs))
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 131, in save_files
>     image = image_from_url_text(filedata)
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py", line 40, in image_from_url_text
>     assert normfn.startswith(tempdir), 'trying to open image file not in temporary directory'
> AssertionError: trying to open image file not in temporary directory
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 285, in run_predict
>     fn_index, raw_input, username, session_state, iterators
>   File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 983, in process_api
>     data = self.postprocess_data(fn_index, result["prediction"], state)
>   File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 913, in postprocess_data
>     if predictions[i] is components._Keywords.FINISHED_ITERATING:
> IndexError: tuple index out of range

It was working earlier today with previous versions of the colab.

**Comment by Stoi84** [comment]
Nevermind. Refreshed the colab again, and it works.
