### ISSUE TITLE
automatic1111 extensions

### ISSUE THREAD

**Issue by hundkillen** [TheLastBen/fast-stable-diffusion#685]
is there a way to use auto1111 extensions when using colab?
im just getting "AssertionError: extension access disabed because of commandline flags" when trying to install a extension

**Comment by TheLastBen** [comment]
all extensions ?

**Comment by hundkillen** [comment]
everything i tried at least. 10 first in the list

**Comment by adder-gntl** [comment]
Just to add here, I'm getting the same when trying to add pretty much any of the extensions now. Before the 2.0 update I was using a few extensions, but since the update I can't.
To be exact, this is the callback in the collab:
`Error completing request
Arguments: ('https://github.com/yfszzx/stable-diffusion-webui-images-browser', ['ads', 'localization']) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 147, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 111, in install_extension_from_url
    check_access()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 20, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabed because of commandline flags"
AssertionError: extension access disabed because of commandline flags`

**Comment by TheLastBen** [comment]
are you using the gradio_server or the tunnel ?

**Comment by adder-gntl** [comment]
> are you using the gradio_server or the tunnel ?

I'm using gradio because of earlier issues getting the webui to show images after generating while on tunnel.

**Comment by TheLastBen** [comment]
when you use gradio_server, it prevents installing the extensions, use the tunnel, install the extensions, then go back to gradio server

**Comment by adder-gntl** [comment]
> when you use gradio_server, it prevents installing the extensions, use the tunnel, install the extensions, then go back to gradio server

Ah, that worked. To the OP @hundkillen, try the above. 

Thanks @TheLastBen!

**Comment by hundkillen** [comment]
@adder-gntl i have no idea what "use the tunnel" means :)

**Comment by adder-gntl** [comment]
> @adder-gntl i have no idea what "use the tunnel" means :)

On the final step, do you have "Use_Gradio_Server:" checked? If you don't, that goes through local tunnel.

**Comment by TheLastBen** [comment]
> @adder-gntl i have no idea what "use the tunnel" means :)

not checking the box "use_gradio_server" will automatically use the tunnel (proxy)
