### ISSUE TITLE
No module named 'modules.upscaler'

### ISSUE THREAD

**Issue by StripedPuppy** [TheLastBen/fast-stable-diffusion#691]
```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 13, in <module>
    from modules import shared, modelloader, devices, script_callbacks, sd_vae
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/modelloader.py", line 9, in <module>
    from modules.upscaler import Upscaler
ModuleNotFoundError: No module named 'modules.upscaler'
```

**Comment by TheLastBen** [comment]
you're repo is probably out of date, update it

**Comment by StripedPuppy** [comment]
It resolved itself an hour after the original posting.
