### ISSUE TITLE
problems with files

### ISSUE THREAD

**Issue by rewixx** [TheLastBen/fast-stable-diffusion#713]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES

**Comment by TheLastBen** [comment]
use the latest colab from the main page of the repo, click on the thumbnail of the desired notebook

**Comment by rewixx** [comment]
I used it


Dne po 28. 11. 2022 20:42 uživatel Ben ***@***.***> napsal:

**Comment by rewixx** [comment]
Still the same problem


Dne po 28. 11. 2022 21:38 uživatel Rewix x ***@***.***> napsal:

**Comment by TheLastBen** [comment]
restart the colab, it should work, the problem isn't with the dependencies, it's with google colab itself
