### ISSUE TITLE
'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

### ISSUE THREAD

**Issue by eacharya** [TheLastBen/fast-stable-diffusion#720]
With the latest notebook

https://github.com/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

the last cell produces:

```python
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'
```

**Comment by TheLastBen** [comment]
did you remove the folder sd ?

**Comment by eacharya** [comment]
Not yet. I reran the notebook with the new content. The gdrive content haven't been touched.

Which folder to be more precise?

**Comment by TheLastBen** [comment]
rename the folder sd in your gdrive if you don't want to remove it, then run the colab

**Comment by eacharya** [comment]
Renaming the `sd` folder in gdrive worked. Thank you.
