### ISSUE TITLE
ImportError: cannot import name 'paths' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by metzo007** [TheLastBen/fast-stable-diffusion#721]
Hi, 

I get this error at step "Start stable-diffusion" using a custom model I made last month using fast dreambooth. 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 12, in <module>
    import modules.interrogate
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 14, in <module>
    from modules import devices, paths, lowvram
ImportError: cannot import name 'paths' from 'modules' (unknown location)

**Comment by metzo007** [comment]
I get the same error using the huggingface 1.5 model

**Comment by TheLastBen** [comment]
try a clean run by removing/renaming the folder sd in your gdrive and use the latest colab from the link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by metzo007** [comment]
worked. thanks :-)
