### ISSUE TITLE
please help Blank webui returned from both localtunel and gradio.app server

### ISSUE THREAD

**Issue by peeterdog** [TheLastBen/fast-stable-diffusion#722]
sorry for my english

im very beguiner in pyton... all the stuff load fine buth the webui os blank. not only this notebook also all notebooks i tryed even copying the notebook to my drive and runing it fron there.

opening the page with browser console i can see that actually there  are code iside.
i find a solution in anywhere that says the i must agregate this at the top of
the file “D:\ananconda\envs\gradtest\Lib\site-packages\gradio\routes.py”

import mimetypes
 
mimetypes.init()
mimetypes.add_type('application/javascript', '.js')

but i cant find gradio package in my drive(i found the package folder inside usr\lib\site-packages\   but no gradio folder....

any solution or idea? thanks

**Comment by TheLastBen** [comment]
It looks like you're trying to run the notebook locally, these notebooks are made for google colab, not local

**Comment by peeterdog** [comment]
nop im running it in colab

**Comment by peeterdog** [comment]
i fiound this issue in gradio site 

https://github.com/gradio-app/gradio/issues/1929

and the say tahs is a version problem...
searching in my colab local pyton installation with !pip list -v i cant find gradio so i assuming you are importing it directly fron server??(remember im beginer in python).. so.. ive installed gradio in my collab...  in this moment im searching in your code the stuff thats import gradio to try the mentioned solution...  my second option is to downgrade gradio ...

**Comment by dotnetprofessional** [comment]
Are you running in Colab or local if local use the standard install from A1111 repo, ie not this one.

**Comment by peeterdog** [comment]
im in https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111-V2.ipynb

**Comment by peeterdog** [comment]
ok i can see in requeriments.txt and requeriments_version.txt gradio=3.9  also in cell requeriments :   !pip install -q gradio==3.9 I CHANGED IT ALL TO 3.1.3 AND ERROR:

LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Downloading: 100% 3.94G/3.94G [01:28<00:00, 44.7MB/s]
Loading weights [8015a14c] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 191, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 137, in webui
    shared.demo = modules.ui.create_ui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 620, in create_ui
    txt2img_prompt, roll, txt2img_prompt_style, txt2img_negative_prompt, txt2img_prompt_style2, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, token_counter, token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 375, in create_toprow
    with gr.Column(scale=6):
TypeError: __init__() got an unexpected keyword argument 'scale'
im playing with the code... i  really want to use sd v2

**Comment by peeterdog** [comment]
3.11.0 nop...
3.9.1 ....
3.10.0 nop...
3.10.1 .... nop

**Comment by peeterdog** [comment]
Ok i'm sorry for taking your time the issue is resolved... was a browser problen.. i used opera 93(so heavy and unstable) because i have a old machine... not work in my old firefox or old chrome... so i upgraded firefox to 103.. and voila...(litle heavy for my toaster) but the app run beautiful.. now im searching for info to fine tuning the stuff works super fine thanks for the effort...
