### ISSUE TITLE
unable to run the v2 training 

### ISSUE THREAD

**Issue by siperuisf** [TheLastBen/fast-stable-diffusion#731]
a100 and t4 both fail......
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 372, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 469, in _dict_from_json_file
    return json.loads(text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 3 (char 158)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 795, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 525, in main
    noise_scheduler = DDPMScheduler.from_config(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 193, in from_config
    config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 374, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/content/stable-diffusion-custom/scheduler/scheduler_config.json' is not a valid JSON file.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--save_starting_step=500', '--stop_text_encoder_training=1400', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/yangchaoyue_', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/yangchaoyue_/instance_images', '--output_dir=/content/models/yangchaoyue_', '--instance_prompt=', '--seed=290174', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=4000']' returned non-zero exit status 1

**Comment by TheLastBen** [comment]
Copy the content of "'/content/stable-diffusion-custom/scheduler/scheduler_config.json" here

**Comment by tomthefreakmusic** [comment]
I had the same issue. Here is the scheduler_config.json

{
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.8.0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  ,
  "num_train_timesteps": 1000,
  "prediction_type": "v_prediction",
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null
}

**Comment by rsomani95** [comment]
Ran into the same issue. The JSON file seems malformed.
Try removing the lone "," below the "beta_start" line.

**Comment by rsomani95** [comment]
After fixing `scheduler_config.json` above, I still run into the same issue. This is strange as I'm certain the JSON file is valid. I checked using a JSON validator to be extra sure. Perhaps the code in one of the cells is modifying it?

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 372, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 469, in _dict_from_json_file
    return json.loads(text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 3 (char 153)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 795, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 525, in main
    noise_scheduler = DDPMScheduler.from_config(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 193, in from_config
    config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 374, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/content/stable-diffusion-custom/scheduler/scheduler_config.json' is not a valid JSON file.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ava_5_images', '--save_starting_step=400', '--save_n_steps=400', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ava_5_images/instance_images', '--output_dir=/content/models/ava_5_images', '--instance_prompt=', '--seed=291511', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=1200']' returned non-zero exit status 1.
Something went wrong
```

**Comment by TheLastBen** [comment]
are you using a huggingface link to download the model ?
