### ISSUE TITLE
Error testing trained model

### ISSUE THREAD

**Issue by apaicu123** [TheLastBen/fast-stable-diffusion#734]
Hi,Ben,

After training a new model, at the testing stage, i am getting this error.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

**Comment by TheLastBen** [comment]
Remove the folder SD and try again, make sure you use the latest colab

**Comment by apaicu123** [comment]
Thx, just did it, it works.

**Comment by TheLastBen** [comment]
Great
