### ISSUE TITLE
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

### ISSUE THREAD

**Issue by Katsu2098** [TheLastBen/fast-stable-diffusion#740]
Hi I'm getting this error from 1 hour ago. how can I fix this?
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

**Comment by pedrocastellanos** [comment]
How did you fix it?

**Comment by TheLastBen** [comment]
> How did you fix it?

remove the folder sd in gdrive and do a clean run with the latest colab
