### ISSUE TITLE
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

### ISSUE THREAD

**Issue by Petavatars** [TheLastBen/fast-stable-diffusion#742]
Hi guys, I'm facing the following error when I tried to run training model,

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 31, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

I dont know how to code, can someone help me with this error?

**Comment by TheLastBen** [comment]
if you're using the same gdrive account, you only delete sd once
