### ISSUE TITLE
OLD METHOD WAS WORKING LAST NIGHT - TODAY IS BROKEN?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#760]
Hello Ben, something is happening right before training, i get this error EVERY TIME since this morning, did something changed??? Please verify 

usage: train_dreambooth.py [-h] --pretrained_model_name_or_path
                           PRETRAINED_MODEL_NAME_OR_PATH [--revision REVISION]
                           [--tokenizer_name TOKENIZER_NAME]
                           --instance_data_dir INSTANCE_DATA_DIR
                           [--class_data_dir CLASS_DATA_DIR] --instance_prompt
                           INSTANCE_PROMPT [--class_prompt CLASS_PROMPT]
                           [--with_prior_preservation]
                           [--prior_loss_weight PRIOR_LOSS_WEIGHT]
                           [--num_class_images NUM_CLASS_IMAGES]
                           [--output_dir OUTPUT_DIR] [--seed SEED]
                           [--resolution RESOLUTION] [--center_crop]
                           [--train_text_encoder]
                           [--train_batch_size TRAIN_BATCH_SIZE]
                           [--sample_batch_size SAMPLE_BATCH_SIZE]
                           [--num_train_epochs NUM_TRAIN_EPOCHS]
                           [--max_train_steps MAX_TRAIN_STEPS]
                           [--save_steps SAVE_STEPS]
                           [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                           [--gradient_checkpointing]
                           [--learning_rate LEARNING_RATE] [--scale_lr]
                           [--lr_scheduler LR_SCHEDULER]
                           [--lr_warmup_steps LR_WARMUP_STEPS]
                           [--use_8bit_adam] [--adam_beta1 ADAM_BETA1]
                           [--adam_beta2 ADAM_BETA2]
                           [--adam_weight_decay ADAM_WEIGHT_DECAY]
                           [--adam_epsilon ADAM_EPSILON]
                           [--max_grad_norm MAX_GRAD_NORM] [--push_to_hub]
                           [--hub_token HUB_TOKEN]
                           [--hub_model_id HUB_MODEL_ID]
                           [--logging_dir LOGGING_DIR]
                           [--mixed_precision {no,fp16,bf16}]
                           [--local_rank LOCAL_RANK]
train_dreambooth.py: error: unrecognized arguments: --save_starting_step=500 --save_n_steps=0 --Session_dir=/content/gdrive/MyDrive
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--train_text_encoder', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/data/AFfgsgfgDains', '--class_data_dir=/content/data/Couple', '--output_dir=/content/models/AFfgsgfgDains', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of AFfgsgfgDains Couple', '--class_prompt=a photo of a Couple, ultra detailed', '--seed=78545', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=1000', '--num_class_images=5']' returned non-zero exit status 2.
Something went wrong

**Comment by LIQUIDMIND111** [comment]
i just tried from ANOTHER account eve using incognito and still gives the same error, i even tried with only 5 photos to test and error, checkpoint save, on and off, text encoder at 50 and 100, whatever i put, does not works and last night it DID work perfectly......

**Comment by LIQUIDMIND111** [comment]
i believe the problem is this 

train_dreambooth.py: error: unrecognized arguments: --save_starting_step=500 --save_n_steps=0 --Session_dir=/content/gdrive/MyDrive
Traceback (most recent call last):

**Comment by TheLastBen** [comment]
should work now

**Comment by LIQUIDMIND111** [comment]
> should work now

ok i am using the NEW method now to see how it goes, then will try again on the OLD page, thanks buddy

**Comment by LIQUIDMIND111** [comment]
ok old method was removed..... thanks
