### ISSUE TITLE
Error when trying to run notebook all of a sudden

### ISSUE THREAD

**Issue by dillfrescott** [TheLastBen/fast-stable-diffusion#768]
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-12-55b102f3c5f0>](https://localhost:8080/#) in <module>
     44 if Use_Gradio_Server:
     45   share='--share'
---> 46   for line in fileinput.input('/usr/local/lib/python3.7/dist-packages/gradio/blocks.py', inplace=True):
     47     if line.strip().startswith('self.server_name ='):
     48         line = '            self.server_name = server_name\n'

1 frames
[/usr/lib/python3.8/fileinput.py](https://localhost:8080/#) in _readline(self)
    340                     pass
    341                 # The next few lines may raise OSError
--> 342                 os.rename(self._filename, self._backupfilename)
    343                 self._file = open(self._backupfilename, self._mode)
    344                 try:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py' -> '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py.bak'
```

Happens every single time now. Was working an hour ago...

**Comment by TheLastBen** [comment]
colab switched to python 3.8, I'm waiting for a confirmation from multiple users to adjust the colabs

**Comment by dillfrescott** [comment]
Ah, okay

**Comment by Jboby1** [comment]
> colab switched to python 3.8, I'm waiting for a confirmation from multiple users to adjust the colabs

Are you saying that you need a certain threshold of people reporting the same error? I was experiencing the same error myself, but after a few times restarting all the cells it switched to a different error (ModuleNotFoundError: No module named 'git')

**Comment by dillfrescott** [comment]
Thats what I was thinking too. You would think one would be enough...

**Comment by plambe** [comment]
My colab is at python3.8 too. Changing the paths for the patches works for me, but there are multiple other dependencies missing.

**Comment by Balerion300** [comment]
Can also confirm that I'm getting the same error on my colab.

**Comment by lgbpaiva** [comment]
> ```
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> [<ipython-input-12-55b102f3c5f0>](https://localhost:8080/#) in <module>
>      44 if Use_Gradio_Server:
>      45   share='--share'
> ---> 46   for line in fileinput.input('/usr/local/lib/python3.7/dist-packages/gradio/blocks.py', inplace=True):
>      47     if line.strip().startswith('self.server_name ='):
>      48         line = '            self.server_name = server_name\n'
> 
> 1 frames
> [/usr/lib/python3.8/fileinput.py](https://localhost:8080/#) in _readline(self)
>     340                     pass
>     341                 # The next few lines may raise OSError
> --> 342                 os.rename(self._filename, self._backupfilename)
>     343                 self._file = open(self._backupfilename, self._mode)
>     344                 try:
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py' -> '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py.bak'
> ```
> 
> Happens every single time now. Was working an hour ago...

Came here to say this, got the same problem just now.

**Comment by roberto-donext** [comment]
For me now appear this error:
```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in <module>
    from modules import localization, sd_vae, extensions, script_loading
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 5, in <module>
    import git
ModuleNotFoundError: No module named 'git'
```

**Comment by herbertwestern** [comment]
I can confirm as well

**Comment by plambe** [comment]
Here's a list of python modules that I had to install
`!pip install GitPython jsonmerge einops clean-fid clip resize_right torchdiffeq lark omegaconf lpips basicsr pytorch_lightning piexif fonts triton`

but it now fails like that

```
WARNING:root:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: module 'triton.language' has no attribute 'constexpr'
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v1.10.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/AI/thelastben_sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/AI/thelastben_sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/AI/thelastben_sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/AI/thelastben_sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/AI/thelastben_sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/AI/thelastben_sd/stable-diffusion-webui/modules/images.py", line 16, in <module>
    from fonts.ttf import Roboto
ImportError: cannot import name 'Roboto' from 'fonts.ttf' (/usr/local/lib/python3.8/dist-packages/fonts/ttf/__init__.py)
```

**Comment by MysticSpiderman** [comment]
Also getting an error on xformers

"---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-e9b5dff0518b>](https://localhost:8080/#) in <module>
      4 from IPython.display import HTML
      5 from IPython.display import clear_output
----> 6 import wget
      7 import time
      8 

ModuleNotFoundError: No module named 'wget'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below."

**Comment by plambe** [comment]
So I think I got it running by
- using colab's search and replace (menu edit), I replaced all occurrences of `python3.7` with `python3.8`
- then in the first code block I added the following to deal with the missing dependencies:
```
!pip install GitPython jsonmerge einops clean-fid clip resize_right torchdiffeq lark omegaconf lpips basicsr pytorch_lightning piexif fonts font-roboto triton==2.0.0.dev20221120 transformers facexlib gfpgan realesrgan
```

It needs a high system RAM runtime in colab but now it runs fine.

**Comment by MysticSpiderman** [comment]
> 

Can you clarify what you mean by adding the code to the first block? Which block exactly>?  The google drive  one or the Setting up The Environment one? Just want to make sure I am doing it properly. Got collab pro, so ready to run at high ram. Hoping to get it resolved.  Thanks in advance.

**Comment by plambe** [comment]
Here's where I've added the pip command that installs the dependencies:

![image](https://user-images.githubusercontent.com/5834002/204918878-a33fdb9f-ec06-4393-83d0-b245c9f4d869.png)

**Comment by MysticSpiderman** [comment]
> Here's where I've added the pip command that installs the dependencies:
> 
> ![image](https://user-images.githubusercontent.com/5834002/204918878-a33fdb9f-ec06-4393-83d0-b245c9f4d869.png)

Ah, so to confirm that is for running the Automatic1111 Collab. 
Do we have a solution for the fast-dreambooth collab yet so I can train a model to THEN use in the Automatic? Going to try running automatic now anyways.

**Comment by MysticSpiderman** [comment]
<img width="916" alt="Screen Shot 2022-11-30 at 5 19 27 PM" src="https://user-images.githubusercontent.com/119079810/204920500-51e8d1b4-c184-42ac-aec5-0ea939d7aaef.png">
I know this may seem obvious - but how do I expand my the cell to view the whole code like in the image above in order to add in the additional code? Right now mine just looks like this. Cant figure out how to expand it like the image above.

**Comment by plambe** [comment]
> I know this may seem obvious - but how do I expand my the cell to view the whole code
It's already expanded, click after the closing brace and press enter on your keyboard for a new line

**Comment by MysticSpiderman** [comment]
Thanks so much. I got automatic1111 up and running. 
Now - does the above technique also work for the fast-dreambooth collab? Have you tried it on that aswell yet? 

Thanks again. Excited to continue working on things tonight.

**Comment by plambe** [comment]
IDK if it will work on dreambooth, but the same approach is most likely to work. In your place I'd do the same (https://github.com/TheLastBen/fast-stable-diffusion/issues/768#issuecomment-1332761995) and then if some python module is missing, I'd add it to the list of modules installed via `!pip install <blabla>`

**Comment by MysticSpiderman** [comment]
I know Ben is working on things in the meantime. So hopefully it will be resolved soon enough regardless. I am curious to try it - but I am not familiar enough with knowing how to fix it if it doesnt work. 
I'll give it a shot now.

**Comment by siraxe** [comment]
> IDK if it will work on dreambooth, but the same approach is most likely to work. In your place I'd do the same ([#768 (comment)](https://github.com/TheLastBen/fast-stable-diffusion/issues/768#issuecomment-1332761995)) and then if some python module is missing, I'd add it to the list of modules installed via `!pip install <blabla>`
![image](https://user-images.githubusercontent.com/27487254/204926115-7f3d397d-c5fb-4f04-ba37-212963916b41.png)

It's still broken even after this , doesn't do `Save_Checkpoint_Every_n_Steps` skips it all together in collab

**Comment by MysticSpiderman** [comment]
> > IDK if it will work on dreambooth, but the same approach is most likely to work. In your place I'd do the same ([#768 (comment)](https://github.com/TheLastBen/fast-stable-diffusion/issues/768#issuecomment-1332761995)) and then if some python module is missing, I'd add it to the list of modules installed via `!pip install <blabla>`
> > ![image](https://user-images.githubusercontent.com/27487254/204926115-7f3d397d-c5fb-4f04-ba37-212963916b41.png)
> 
> It's still broken even after this , doesn't do `Save_Checkpoint_Every_n_Steps` skips it all together in collab

Are there any other ways for us to train models and then at least upload them from our drive into automatic1111? I tired one other collab for training by Shivam but that didnt work right now either.

**Comment by MysticSpiderman** [comment]
At this point my strategy is just being patient while Ben works on it.

**Comment by TheLastBen** [comment]
update the colab it should work now

**Comment by MysticSpiderman** [comment]
> update the colab it should work now

Trying it out now. 
When you say Update the Colab - does that just mean reload the page? 
Want to make sure I am not missing anything. Thanks Ben.

**Comment by TheLastBen** [comment]
the dreambooth colab isn't ready yet, the A1111 is

**Comment by dillfrescott** [comment]
> update the colab it should work now

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-5-e692ee13db33>](https://localhost:8080/#) in <module>
     35 if Use_Gradio_Server:
     36   share='--share'
---> 37   for line in fileinput.input('/usr/local/lib/python3.8/dist-packages/gradio/blocks.py', inplace=True):
     38     if line.strip().startswith('self.server_name ='):
     39         line = '            self.server_name = server_name\n'

1 frames
[/usr/lib/python3.8/fileinput.py](https://localhost:8080/#) in _readline(self)
    340                     pass
    341                 # The next few lines may raise OSError
--> 342                 os.rename(self._filename, self._backupfilename)
    343                 self._file = open(self._backupfilename, self._mode)
    344                 try:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/gradio/blocks.py' -> '/usr/local/lib/python3.8/dist-packages/gradio/blocks.py.bak'
```

**Comment by lhucklen** [comment]
Is this fixed? 

![C3BCBC31-7E9C-4DA2-83CC-8B27B0531A97](https://user-images.githubusercontent.com/74945062/204958998-06aa5ea4-75f4-4e3b-9c8b-b536fd7719b9.png)

**Comment by lhucklen** [comment]
> 

I can confirm there is no directory when searching for it in the path noted in the stack trace.

Any ideas on how to get this directory back in order?

**Comment by dillfrescott** [comment]
Guys, in the meanwhile I recommend using this colab: https://github.com/ddPn08/automatic1111-colab

It works fine and has been working as a good replacement till Ben fixes this one! :)

**Comment by lhucklen** [comment]
Was able to get the directory set up for python3.8 with gradio.

used pip install gradio

Pretty basic and it gave me the blocks.py file

Now I have this error

![A52B01BB-7212-4646-A905-9048E2D03DE1](https://user-images.githubusercontent.com/74945062/204965767-2718687c-3bee-4820-8934-1154cd0854a9.png)

**Comment by MysticSpiderman** [comment]
While Ben is busy working on this - do we currently have any other way to train a model right now? 

Is it possible to do it properly within automatic1111 once it is launched?

**Comment by Klaushayan** [comment]
In the last cell, add the following right below `import fileinput`:

`
!pip install -q gradio GitPython jsonmerge einops clean-fid resize-right torchdiffeq gfpgan !pip install -q git+https://github.com/openai/CLIP.git !pip install -q torchsde transformers facexlib realesrgan lark safetensors omegaconf lpips basicsr pytorch-lightning piexif fonts font-roboto open-clip-torch
`

That fixed it for me

**Comment by Weltbummler1** [comment]
> In the last cell, add the following right below `import fileinput`:
> 
> `!pip install -q gradio GitPython jsonmerge einops clean-fid resize-right torchdiffeq gfpgan ` `!pip install -q git+https://github.com/openai/CLIP.git` `!pip install -q torchsde transformers facexlib realesrgan lark safetensors omegaconf lpips basicsr pytorch-lightning piexif fonts font-roboto open-clip-torch`
> 
> That fixed it for me

added missing modules xformers and timm - works for me

**Comment by crapthings** [comment]
this is the error output

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 4, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 18, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack, should_hijack_inpainting
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 6, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/autoencoder.py", line 8, in <module>
    from ldm.modules.diffusionmodules.model import Encoder, Decoder
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/model.py", line 9, in <module>
    from ldm.modules.attention import LinearAttention
ImportError: cannot import name 'LinearAttention' from 'ldm.modules.attention' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py)
```

**Comment by TheLastBen** [comment]
remove the folder sd and use the latest colab

**Comment by webyroki** [comment]
NameError                                 Traceback (most recent call last)
[<ipython-input-7-50089bb56162>](https://localhost:8080/#) in <module>
     76   get_ipython().system("grep -o 'https[^ ]*' /content/srv.txt >srvr.txt")
     77   time.sleep(2)
---> 78   srv= getoutput('cat /content/srvr.txt')
     79 
     80   for line in fileinput.input('/usr/local/lib/python3.8/dist-packages/gradio/blocks.py', inplace=True):

NameError: name 'getoutput' is not defined

**Comment by TheLastBen** [comment]
rerun the requirements cell

**Comment by webyroki** [comment]
> rerun the requirements cell

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 23, in <module>
    import modules.extras
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 20, in <module>
    from modules.ui import plaintext_to_html
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 23, in <module>
    from modules.ui_components import FormRow, FormGroup, ToolButton, FormHTML
ImportError: cannot import name 'FormHTML' from 'modules.ui_components' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_components.py)

**Comment by Klaushayan** [comment]
@webyroki I believe you need to delete the sd folder from your google drive and reinstall everything

**Comment by steelerocky** [comment]
> @webyroki I believe you need to delete the sd folder from your google drive and reinstall everything

yesterday, it worked fine for me after I deleted sd folder from my google drive and reinstalled everything. But today I tried to connect it again, it is giving me error again 

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared, progress
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 32, in <module>
    from gradio.blocks import Block
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 23, in <module>
    from gradio import (
ImportError: cannot import name 'queueing' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/gradio/__init__.py)`

**Comment by TheLastBen** [comment]
You don't need to delete the SD folder anymore just use the latest colab

**Comment by steelerocky** [comment]
Facing the error again

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 16, in <module>
    from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_networks_textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks_hypernet.py", line 2, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 10, in <module>
    import modules.textual_inversion.dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 13, in <module>
    from modules import devices, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in <module>
    from modules import localization, extensions, script_loading, errors, ui_components, shared_items
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 10, in <module>
    extensions_dir = os.path.join(paths.data_path, "extensions")
AttributeError: module 'modules.paths' has no attribute 'data_path'`

**Comment by Sakib2263** [comment]
Facing similar error: 
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 22, in <module>
    import gradio
  File "/usr/local/lib/python3.9/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.9/dist-packages/gradio/components.py", line 33, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 23, in <module>
    from gradio import (
ImportError: cannot import name 'encryptor' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.9/dist-packages/gradio/__init__.py)

**Comment by TheLastBen** [comment]
does the issue still persist ?

**Comment by AnGoga** [comment]
2-3 days ago I had the same problem. I didn't do anything myself, just did "Install/Update AUTOMATIC1111 repo" and "Requirements" as usual before running.
![image](https://user-images.githubusercontent.com/74153908/227440416-c59adc93-14c3-4c68-b39f-65c1f7f097a4.png)


If you install this, then an error occurs

!pip install -q gradio GitPython jsonmerge einops clean-fid resize-right torchdiffeq gfpgan
!pip install -q git+https://github.com/openai/CLIP.git
!pip install -q torchsde transformers facexlib realesrgan lark safetensors omegaconf lpips basicsr pytorch-lightning piexif fonts font-roboto open-clip-torch

![image](https://user-images.githubusercontent.com/74153908/227440437-d96a6b87-d4d0-4e03-82ff-f87549524ab0.png)


Any ideas how to solve this problem?

**Comment by TheLastBen** [comment]
Simply use the latest notebook from the official link

**Comment by ansel44** [comment]
> colab switched to python 3.8, I'm waiting for a confirmation from multiple users to adjust the colabs

hello my friend ,how can we use localtunnel again,?  we need it
