### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers'

### ISSUE THREAD

**Issue by SAC020** [TheLastBen/fast-stable-diffusion#791]
Using the old method, I get the following error when trying to run the "start dreambooth" code

I have run the dependencies block twice

```
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 24, in <module>
    from transformers import CLIPTextModel, CLIPTokenizer
ModuleNotFoundError: No module named 'transformers'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

```

**Comment by alelordelo** [comment]
sam thing here @SAC020 , but using "New Method", Did you find a solution?

**Comment by SAC020** [comment]
On the new method I didn't encounter that error, and I haven't retried using the old method

**Comment by TheLastBen** [comment]
the old method colab needs updating, I'll do it as soon as I can, but you really should try, the new method by disabling the text encoder and captioning the images,

**Comment by SAC020** [comment]
> the old method colab needs updating, I'll do it as soon as I can, but you really should try, the new method by disabling the text encoder and captioning the images,

I am always captioning the images. 

Why disable the text encoder?

**Comment by TheLastBen** [comment]
> Why disable the text encoder?

to avoid overfitting, in the new method

**Comment by hectorfefrain** [comment]
I´m having the same error @SAC020 

Which is the 'new method' and the 'old method'?
