### ISSUE TITLE
no module named... git?

### ISSUE THREAD

**Issue by rlayne** [TheLastBen/fast-stable-diffusion#797]
I've seen some squirrely things on this colab but this is a new one.  Anyone else?
Recently reset the gdrive files, was working last night.  SD1.5.

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in <module>
    from modules import localization, sd_vae, extensions, script_loading
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 5, in <module>
    import git
ModuleNotFoundError: No module named 'git'
```

**Comment by redsparrowgit** [comment]
delete all and run again.

**Comment by rlayne** [comment]
ddnt delete all but prob has self resovled.
