### ISSUE TITLE
ModuleNotFoundError: No module named 'git'

### ISSUE THREAD

**Issue by norfuer** [TheLastBen/fast-stable-diffusion#810]
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
>     from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
>     from modules import shared
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in <module>
>     from modules import localization, sd_vae, extensions, script_loading
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 5, in <module>
>     import git
> ModuleNotFoundError: No module named 'git'

Just ran this a few minutes ago. It's up to date and I'd already replaced all references to 3.7 with 3.8. Not sure what the problem might be.

**Comment by TheLastBen** [comment]
you don't need to replace 3.7 with 3.8, just use the latest colab ; https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by norfuer** [comment]
Thanks, it's running now.
