### ISSUE TITLE
Colab crashes before providing link (Automatic1111)

### ISSUE THREAD

**Issue by Neverdusk** [TheLastBen/fast-stable-diffusion#830]
The Colab was working fine for me, until today. Every time I run the Colab, I get the following error:

```
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading100% 961k/961k [00:00<00:00, 1.87MB/s]
Downloading100% 525k/525k [00:00<00:00, 1.22MB/s]
Downloading100% 389/389 [00:00<00:00, 355kB/s]
Downloading100% 905/905 [00:00<00:00, 853kB/s]
Downloading100% 4.52k/4.52k [00:00<00:00, 3.91MB/s]
Downloading100% 1.71G/1.71G [00:38<00:00, 44.6MB/s]
Loading weights [4470c325] from /content/gdrive/MyDrive/Stable Diffusion/waifu-diffusion-1.3-pruned.ckpt
Applying xformers cross attention optimization.
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 192, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 138, in webui
    shared.demo.queue(concurrency_count=111500)
AttributeError: 'function' object has no attribute 'queue'
```

Just yesterday, I was able to start the Colab just fine. But now I can't get past this error. I've tried disconnecting and restarting the runtime, using Gradio server, refreshing the page, and deleting and reinstalling the sd folder in GDrive. No solution seems to work.

**Comment by ZupaCz** [comment]
getting same error

**Comment by SymboLulu** [comment]
same error

**Comment by TheLastBen** [comment]
fixed

**Comment by tushar-31093** [comment]
> fixed

How? It is still there.
