### ISSUE TITLE
Doesnt loaded

### ISSUE THREAD

**Issue by nytromen** [TheLastBen/fast-stable-diffusion#831]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 192, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 138, in webui
    shared.demo.queue(concurrency_count=111500)
AttributeError: 'function' object has no attribute 'queue'

**Comment by TheLastBen** [comment]
fixed now

**Comment by nytromen** [comment]
> fixed now

Ty bro, you are best

**Comment by nytromen** [comment]
> fixed now

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 742, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 653, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 800, in update_orig
    same_size = state is not None and state.size == image.size
AttributeError: 'dict' object has no attribute 'size'

**Comment by TheLastBen** [comment]
update your repo
