### ISSUE TITLE
'Namespace' object has no attribute 'gradio_inpaint_tool'

### ISSUE THREAD

**Issue by abvgdeabvgde2** [TheLastBen/fast-stable-diffusion#841]
```
Applying xformers cross attention optimization.
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 191, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 137, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=111500)
  File "/content/gdrive/.shortcut-targets-by-id/***/sd/stable-diffusion-webui/modules/ui.py", line 796, in create_ui
    init_img_with_mask = gr.Image(label="Image for inpainting with mask", show_label=False, elem_id="img2maskimg", source="upload", interactive=True, type="pil", tool=cmd_opts.gradio_inpaint_tool, image_mode="RGBA").style(height=480)
AttributeError: 'Namespace' object has no attribute 'gradio_inpaint_tool'
```

**Comment by abvgdeabvgde2** [comment]
A clean run solves the issue.
