### ISSUE TITLE
TypeError: click() missing 1 required positional argument: 'outputs'

### ISSUE THREAD

**Issue by wilzamguerrero** [TheLastBen/fast-stable-diffusion#846]
This happened with the extension of dreamboooth

Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [a2a802b2] from /content/gdrive/MyDrive/model/v1-5-fp16.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Error executing callback ui_tabs_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 95, in ui_tabs_callback
    res += c.callback() or []
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 199, in on_ui_tabs
    db_save_params.click(
TypeError: click() missing 1 required positional argument: 'outputs'

**Comment by TheLastBen** [comment]
you should check the A1111 repo for that

**Comment by binary-zero-one** [comment]
This is a problem with a Dreambooth extension, the outputs parameter is really missing [here](https://github.com/d8ahazard/sd_dreambooth_extension/blob/c2fc683ebcf4db23cfce22626aa6a7b565994c96/scripts/main.py#L298). "outputs" parameter must be an empty list or None: `db_save_params.click(fn=..., inputs=[...], outputs=[]`, you can manually edit the relevant file on the GDrive, better of course to create a pull request in the repository, but after successfully installing dreambooth extension, CLIP will break because the extension requires version of transformers==4.21.0 and the Interrogate CLIP requires version of transformers==4.19.* (https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2848)

**Comment by wilzamguerrero** [comment]
> This is a problem with a Dreambooth extension, the outputs parameter is really missing [here](https://github.com/d8ahazard/sd_dreambooth_extension/blob/c2fc683ebcf4db23cfce22626aa6a7b565994c96/scripts/main.py#L298). "outputs" parameter must be an empty list or None: `db_save_params.click(fn=..., inputs=[...], outputs=[]`, you can manually edit the relevant file on the GDrive, better of course to create a pull request in the repository, but after successfully installing dreambooth extension, CLIP will break because the extension requires version of transformers==4.21.0 and the Interrogate CLIP requires version of transformers==4.19.* ([AUTOMATIC1111/stable-diffusion-webui#2848](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2848))

ohhh thank you so much i try to do this, but is strange i have transformers==4.21.0, Maybe i can comment for private message and explain what i try to do, i share and if you can send message or if you can send my your contact for talk, and thank you so much again.
