### ISSUE TITLE
 I get this Error: train_dreambooth.py: error: unrecognized arguments: duchovny duchovny

### ISSUE THREAD

**Issue by Crimsonfart** [TheLastBen/fast-stable-diffusion#85]
I get the following error.
Yesterday I was able to use the Colab without any problems.
Today I use the following SUBJECT_NAME: Person INSTANCE_NAME: david duchovny
Yesterday I used Person and SKS and it went well.

DreamBooth colab From https://github.com/TheLastBen/fast-stable-diffusion, if you face any issues, feel free to discuss them.

Run this Notebook manually step by step, don't miss any, the colab is still in progress, trying to find the best settings for Dreambooth

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

Setting up the environment
Dependencies
xformers

DONE !

Downloading the model
Downloading the model
Huggingface_Token:

(Make sure you accepted the terms in https://huggingface.co/CompVis/stable-diffusion-v1-4)

DONE !

Dreambooth
Setting up
With_Prior_Preservation:

With the prior reservation method the results are more coherent and better, you will have to either upload around 200 pictures of the class you're training (dog, person, car, house ...), but more is better, if you don't upload them, it will automatically generate them at the cost of quality and time. For excellent results, manually filter around 400 images of the class and 50 pictures of the instance (a photo of yourself or your dog ...), try 2000 steps then tune it from there.
Training subject (is it a person ? a dog ? a car ? pick the correct category):
SUBJECT_NAME:
Identifier (choose a unique identifier unknown by stable diffusion ):
INSTANCE_NAME:
Number_of_subject_images:
[Optional] Upload or choose a folder of the class pictures (pictures of dogs if you're training on a dog), 200 is good, more is better, if you upload less than Number_of_subject_images, it will automatically generate the rest.
CLASS_DIR:

    To save time, if you specify a CLASS_DIR which is a folder that containes class images (eg: 200 pics of a dog), dreambooth will use this folder.
    Leave it empty if you want to upload

    Skip the cell if you want it to generate class (subject) images.

Start DreamBooth
Training_Steps:
Seed:
More steps, better results, but longer training time

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `6` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
usage: train_dreambooth.py [-h] --pretrained_model_name_or_path
                           PRETRAINED_MODEL_NAME_OR_PATH
                           [--tokenizer_name TOKENIZER_NAME]
                           --instance_data_dir INSTANCE_DATA_DIR
                           [--class_data_dir CLASS_DATA_DIR]
                           [--instance_prompt INSTANCE_PROMPT]
                           [--class_prompt CLASS_PROMPT]
                           [--with_prior_preservation]
                           [--prior_loss_weight PRIOR_LOSS_WEIGHT]
                           [--num_class_images NUM_CLASS_IMAGES]
                           [--output_dir OUTPUT_DIR] [--seed SEED]
                           [--resolution RESOLUTION] [--center_crop]
                           [--train_batch_size TRAIN_BATCH_SIZE]
                           [--sample_batch_size SAMPLE_BATCH_SIZE]
                           [--num_train_epochs NUM_TRAIN_EPOCHS]
                           [--max_train_steps MAX_TRAIN_STEPS]
                           [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                           [--gradient_checkpointing]
                           [--learning_rate LEARNING_RATE] [--scale_lr]
                           [--lr_scheduler LR_SCHEDULER]
                           [--lr_warmup_steps LR_WARMUP_STEPS]
                           [--use_8bit_adam] [--adam_beta1 ADAM_BETA1]
                           [--adam_beta2 ADAM_BETA2]
                           [--adam_weight_decay ADAM_WEIGHT_DECAY]
                           [--adam_epsilon ADAM_EPSILON]
                           [--max_grad_norm MAX_GRAD_NORM] [--push_to_hub]
                           [--use_auth_token] [--hub_token HUB_TOKEN]
                           [--hub_model_id HUB_MODEL_ID]
                           [--logging_dir LOGGING_DIR]
                           [--mixed_precision {no,fp16,bf16}]
                           [--local_rank LOCAL_RANK]
train_dreambooth.py: error: unrecognized arguments: duchovny duchovny
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-4', '--instance_data_dir=/content/data/david', 'duchovny', '--class_data_dir=/content/data/person', '--output_dir=/content/models/david', 'duchovny', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of a david duchovny person', '--class_prompt=photo of a person', '--seed=11111', '--resolution=512', '--mixed_precision=no', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=2000', '--num_class_images=200']' returned non-zero exit status 2.
Something went wrong

**Comment by TheLastBen** [comment]
don't use spaces in the names or paths

**Comment by Crimsonfart** [comment]
Okay, thank you for the quick answer. I've read over and over again that you get better results by using a celebrity name. Did I misunderstand something?

**Comment by TheLastBen** [comment]
People are still experimenting with this ne tool, nothing is certain yet until we have enough comparison data.

**Comment by Crimsonfart** [comment]
Ok it works now. Thanks again for your help. And a big thank you for the great Colab!

**Comment by TheLastBen** [comment]
Happy to help
