### ISSUE TITLE
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory Conversion error

### ISSUE THREAD

**Issue by barrand** [TheLastBen/fast-stable-diffusion#852]
I'm getting this error when in the loading model cell

Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1115, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1066, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 835, in load_models_from_stable_diffusion_checkpoint
    checkpoint = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/content/convertodiff.py", line 817, in load_checkpoint_with_text_encoder_conversion
    state_dict = checkpoint["state_dict"]
KeyError: 'state_dict'
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error

**Comment by TheLastBen** [comment]
did you choose the right model version ?

**Comment by barrand** [comment]
@TheLastBen using a link to a gdrive model I have uploaded to my google drive.

**Comment by TheLastBen** [comment]
you need to specify the version of the model

**Comment by Raz0rStorm** [comment]
may i inquire how to specify version using models other than sd?

> you need to specify the version of the model

**Comment by TheLastBen** [comment]
specify the version of the initial model used to train that custom model
