### ISSUE TITLE
Failed to Upload Model

### ISSUE THREAD

**Issue by GreatestOfAllTimee** [TheLastBen/fast-stable-diffusion#853]
First for all thank you for your awesome works! I don't know if this issues has been discuss or not. Here are what I face when try to upload Trained Model to Hugging Face:-

```console
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-7-c2f59dee36be>](https://localhost:8080/#) in <module>
     46 
     47 
---> 48 if NM=="False":
     49   with capture.capture_output() as cap:
     50     get_ipython().run_line_magic('cd', '$OUTPUT_DIR')

NameError: name 'NM' is not defined
```

![BUG_UploadHuggingFaceModels](https://user-images.githubusercontent.com/73665622/205457224-17cc8994-6770-4bdb-9969-0de1658a9328.png)

**Comment by TheLastBen** [comment]
run the testing cell first, even if for few seconds, the V2 variable needs to be set True or False

**Comment by GreatestOfAllTimee** [comment]
Thank you for your reply. but this is recent error I got after using _Model_Version_: `1.5`, not quite sure what happen.

### DETAILS 

**`Model_Version:`** 1.5
**`Custom_Model_Version:`** 1.5
**`Huggingface_Token:`** MYTOKEN
**`Path_to_HuggingFace:`** null/empty
**`CKPT_Link:`** https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.ckpt

#### Console Error Output
<details>

```console
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 797, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 557, in main
    train_dataloader = torch.utils.data.DataLoader(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/zhtpm10', '--save_starting_step=3000', '--save_n_steps=0', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/zhtpm10/instance_images', '--output_dir=/content/models/zhtpm10', '--instance_prompt=', '--seed=890101', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=3000']' returned non-zero exit status 1.
Something went wrong
```

</details>

---

NOTE: https://github.com/TheLastBen/fast-stable-diffusion/issues/853#issue-1474190562 this issue are using Model_Version V2.

**Comment by TheLastBen** [comment]
You didn't upload instance images

**Comment by GreatestOfAllTimee** [comment]
What a silly mistake
