### ISSUE TITLE
Xformers Missing

### ISSUE THREAD

**Issue by TheClownVamp** [TheLastBen/fast-stable-diffusion#88]
Hi!

I keep getting this error on the final cell:

"Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    import modules.extras
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 9, in <module>
    from modules import processing, shared, images, devices, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 13, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 13, in <module>
    import ldm.modules.attention
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py", line 10, in <module>
    import xformers
ModuleNotFoundError: No module named 'xformers'"

Tried deleting the folders and re-running but not luck. Am I missing something obvious? (I assume I am!)

**Comment by TheLastBen** [comment]
Are you using the latest colab notebook ?

**Comment by TheClownVamp** [comment]
I assume so! Which link is it?

**Comment by TheClownVamp** [comment]
I just clicked it from the Github and got the same error, so yes!

**Comment by Woahai321** [comment]
i also have this error

**Comment by Woahai321** [comment]
strange as was working all okay yesterday however i notice the colab has been updated

**Comment by TheLastBen** [comment]
will fix it in a few minutes

**Comment by Woahai321** [comment]
<3

**Comment by TheClownVamp** [comment]
Hero!

**Comment by TheLastBen** [comment]
fixed 👍
