### ISSUE TITLE
getting value coordinate error everytime also inpainting is broken 

### ISSUE THREAD

**Issue by dravid-cmyk** [TheLastBen/fast-stable-diffusion#882]
![Capture](https://user-images.githubusercontent.com/119574962/205637423-a5273fd6-091c-4097-a94d-d7ad78878898.PNG)
![gg](https://user-images.githubusercontent.com/119574962/205637427-f8ebf4fc-6177-4a59-bc8a-1eb6172908b8.PNG)

**Comment by TheLastBen** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/
this is the repo where you should ask the question.

**Comment by tuangd** [comment]
This is weird I got the same error. And I run the same repo on my machine (updated both to the current repo). But on my machine it doesn't produce this error.
---
`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 152, in img2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 532, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 814, in init
    mask = mask.crop(crop_region)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 1207, in crop
    raise ValueError("Coordinate 'right' is less than 'left'")
ValueError: Coordinate 'right' is less than 'left'`

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by tuangd** [comment]
I saw on Automatic repo that it's still a bug tho. [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5511)

**Comment by TheLastBen** [comment]
if you use the latest colab it should work without issue, i'm testing inpainting right now and it works

**Comment by aolko** [comment]
Still broken
