### ISSUE TITLE
size mismatch errors when trying to load up a trained model

### ISSUE THREAD

**Issue by SAC020** [TheLastBen/fast-stable-diffusion#885]
Resumed training on a SD20 model today and the resulting ckpt throws this error upon trying to load it in SD.

I **do** have the yaml named the same as the ckpt, and the iterations trained yesterday load up fine with the same yaml (renamed accordingly)

```
`Traceback (most recent call last):
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ai\stable-diffusion-webui\modules\ui.py", line 1618, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "C:\ai\stable-diffusion-webui\modules\ui.py", line 1459, in run_settings_single
    if not opts.set(key, value):
  File "C:\ai\stable-diffusion-webui\modules\shared.py", line 473, in set
    self.data_labels[key].onchange()
  File "C:\ai\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "C:\ai\stable-diffusion-webui\webui.py", line 63, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "C:\ai\stable-diffusion-webui\modules\sd_models.py", line 292, in reload_model_weights
    load_model(checkpoint_info)
  File "C:\ai\stable-diffusion-webui\modules\sd_models.py", line 261, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "C:\ai\stable-diffusion-webui\modules\sd_models.py", line 192, in load_model_weights
    model.load_state_dict(sd, strict=False)
  File "C:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for model.diffusion_model.input_blocks.1.1.proj_in.weight: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.1.1.proj_out.weight: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.proj_in.weight: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.2.1.proj_out.weight: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.input_blocks.4.1.proj_in.weight: copying a param with shape torch.Size([640, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 640]).
        size mismatch for model.diffusion_model.input_blocks.4.1.proj_out.weight: copying a param with shape torch.Size([640, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 640]).
        size mismatch for model.diffusion_model.input_blocks.5.1.proj_in.weight: copying a param with shape torch.Size([640, 640, 1, 1]) 

<...>

        size mismatch for model.diffusion_model.output_blocks.10.1.proj_out.weight: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.output_blocks.11.1.proj_in.weight: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320]).
        size mismatch for model.diffusion_model.output_blocks.11.1.proj_out.weight: copying a param with shape torch.Size([320, 320, 1, 1]) from checkpoint, the shape in current model is torch.Size([320, 320]).`
```

**Comment by TheLastBen** [comment]
that error is caused by a wrong yaml, check again

**Comment by bach777** [comment]
I'm having the same problem, I put the yaml v2-768 file in the SD model directory folder, renamed the yaml file to the same name as the ckpt file, tried to load and got this error
![A](https://user-images.githubusercontent.com/115612779/205786860-17b95b7f-8ed1-4854-82bb-f0706a2c7866.png)
I also tried to load the files with the default names (768-v-ema.ckpt and 768-v-ema.yaml) but it did not work.

**Comment by LIQUIDMIND111** [comment]
> yaml for the v2-768 https://github.com/Stability-AI/stablediffusion/blob/main/configs/stable-diffusion/v2-inference-v.yaml
> 
> yaml for the v2-512 https://github.com/Stability-AI/stablediffusion/blob/main/configs/stable-diffusion/v2-inference.yaml

i thought you said WE did not needed to create any yaml files FOR EACH individual model..... hum

**Comment by TheLastBen** [comment]
He is using local A1111, not the colab
