### ISSUE TITLE
Cannot run last step of Fast Stable Diffusion

### ISSUE THREAD

**Issue by Moffittk** [TheLastBen/fast-stable-diffusion#890]
I am getting the following error when trying to load the UI in the last step:  
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 194, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 138, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=111500)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 794, in create_ui
    init_img_with_mask = gr.Image(label="Image for inpainting with mask", show_label=False, elem_id="img2maskimg", source="upload", interactive=True, type="pil", tool=cmd_opts.gradio_inpaint_tool, image_mode="RGBA").style(height=480)
AttributeError: 'Namespace' object has no attribute 'gradio_inpaint_tool'

**Comment by Moffittk** [comment]
Yes.  I updated the repo.  And was using the latest collab.

**Comment by thebigzahi** [comment]
I had the same problem, updating the repo didn't solve the problem, deleting the stable diffusion webui folder from Drive did it for me.

**Comment by Moffittk** [comment]
Renaming the SD Web UI folder did it for me.

**Comment by TheLastBen** [comment]
> Renaming the SD Web UI folder did it for me.

if you don't need the folder, it's better to delete it to free up space

**Comment by Moffittk** [comment]
Yes, renamed to test whether it worked first ;)
