### ISSUE TITLE
IMG2IMG not working v1.5

### ISSUE THREAD

**Issue by redsparrowgit** [TheLastBen/fast-stable-diffusion#896]
![image](https://user-images.githubusercontent.com/119093900/205929203-cec36fe4-eda6-4417-bb56-80c9de8ac694.png)

Connected
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-196' coro=<Queue.process_event() done, defined at /usr/local/lib/python3.8/dist-packages/gradio/queue.py:222> exception=RuntimeError("Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/queue.py", line 275, in process_event
    await event.disconnect()
  File "/usr/local/lib/python3.8/dist-packages/gradio/queue.py", line 305, in disconnect
    await self.websocket.close(code=code)
  File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 180, in close
    await self.send(
  File "/usr/local/lib/python3.8/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 316, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.

**Comment by TheLastBen** [comment]
try checking the box "use_gradio_server"

**Comment by Shiffo0** [comment]
Where do you need to check the box of use_gradio_server? Is that in the settings of the Webui? Or is that in the Colab Notebook?

**Comment by TheLastBen** [comment]
it's in the notebook

**Comment by kengoqw** [comment]
Couldn't find the settings in my notebook.
I need some details.

**Comment by TheLastBen** [comment]
use ngrok
