### ISSUE TITLE
Python error on latest build 

### ISSUE THREAD

**Issue by createperhaps** [TheLastBen/fast-stable-diffusion#907]
(grabbed December 7, 2:58 pm EST) - I don't see any software versions when you push.

When I start the colab I get to "start stable-diffusion" I am getting the following error code.

```
/usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
WARNING:xformers:WARNING: /usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
```

However, SD continues to open. When I start to compile I get the following error code:

```
Error completing request
Arguments: ('photograph of a beautiful nude woman reading a book by Corinne Day, (lips parted), curtain in the background, ((thighs)), perfect feet, pale skin, window light, curtain shadows on woman, high quality, (wet hair), fairy tale, perfect hands, beautiful face', 'anime, cartoon, fake, drawing, illustration, boring, 3d render, long neck, out of frame, extra fingers, mutated hands, extra fingers, missing fingers monochrome, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), blurry, ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, glitchy, bokeh, (((long neck))), (child), (childlike), 3D, 3DCG, cgstation, ((large breasts)), red eyes, extra heads, man asian, text ,watermarks, logo, black and white, painting,((artifacts))', 'None', 'None', 70, 15, True, False, 1, 1, 7, 1908854459.0, -1.0, 0, 0, 0, False, 768, 512, False, 0.7, 0, 0, 0, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
    processed = process_images(p)
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/processing.py", line 430, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/processing.py", line 531, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/processing.py", line 664, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/sd_samplers.py", line 507, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/sd_samplers.py", line 422, in launch_sampling
    return func()
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/sd_samplers.py", line 507, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/sd_samplers.py", line 315, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 776, in forward
    h = module(h, emb, context)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/sd_hijack_checkpoint.py", line 4, in BasicTransformerBlock_forward
    return checkpoint(self._forward, x, context)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/attention.py", line 262, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/gdrive/.shortcut-targets-by-id/1in9dwXQDzAxLTNEepIKC2q3BCFIrQWEu/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 227, in xformers_attention_forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)
  File "/usr/local/lib/python3.8/dist-packages/xformers/ops/memory_efficient_attention.py", line 967, in memory_efficient_attention
    return op.forward_no_grad(
  File "/usr/local/lib/python3.8/dist-packages/xformers/ops/memory_efficient_attention.py", line 343, in forward_no_grad
    return cls.FORWARD_OPERATOR(
  File "/usr/local/lib/python3.8/dist-packages/xformers/ops/common.py", line 11, in no_such_operator
    raise RuntimeError(
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?
```

I thought perhaps I did something, but it wasn't working on my backup, older colab version.

**Comment by CJohnDesign** [comment]
Duplicate issue: https://github.com/TheLastBen/fast-stable-diffusion/issues/904

**Comment by ReEnMikki** [comment]
Same error, waiting for fix

**Comment by createperhaps** [comment]
closing this, we dont need a duplicate
