### ISSUE TITLE
WHAT A PAIN, CANNOT RESUME TRAINING BECAUSE OF THIS

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#908]
Session found, loading the trained model ...
Converting to Diffusers ...
/usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
WARNING:xformers:WARNING: /usr/local/lib/python3.8/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
Need to compile C++ extensions to get sparse attention support. Please run python setup.py build develop
/usr/local/lib/python3.8/dist-packages/diffusers/models/attention.py:429: UserWarning: Could not enable memory efficient attention. Make sure xformers is installed correctly and a GPU is available: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?
  warnings.warn(
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1107, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1076, in convert
    key_count = save_stable_diffusion_checkpoint(v2_model, args.model_to_save, text_encoder, unet,
  File "/content/convertodiff.py", line 1013, in save_stable_diffusion_checkpoint
    torch.save(new_ckpt, output_file)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/models does not exist.

**Comment by LIQUIDMIND111** [comment]
bro screw this free Google free collab, i was hoping to resume daily, but now i cannot resume a work? what a waste of time.... now i have to START ALL OVER with a new Google premium account? Jesus.....

**Comment by LordSuricato** [comment]
> 
Remember that this is an open source project and its use is at your own risk. On the other hand, you can also set a version of the notebook to avoid problems with code changes on github.

**Comment by LIQUIDMIND111** [comment]
> > 
> 
> Remember that this is an open source project and its use is at your own risk. On the other hand, you can also set a version of the notebook to avoid problems with code changes on github.

you like SAVE A COPY?
