### ISSUE TITLE
Freezing during image2image

### ISSUE THREAD

**Issue by alexanderytaylor** [TheLastBen/fast-stable-diffusion#91]
I keep this error when trying Image2Image:

`Connected
Task exception was never retrieved
future: <Task finished coro=<Queue.process_event() done, defined at /usr/local/lib/python3.7/dist-packages/gradio/queue.py:222> exception=RuntimeError("Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 275, in process_event
    await event.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 305, in disconnect
    await self.websocket.close(code=code)
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 181, in close
    {"type": "websocket.close", "code": code, "reason": reason or ""}
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 316, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.`

**Comment by TheLastBen** [comment]
Check the box "use gradio server", then rerun the last cell

**Comment by alexanderytaylor** [comment]
I tried that but only got a very basic UI

**Comment by alexanderytaylor** [comment]
Ah I've got the gradio server working

**Comment by alexanderytaylor** [comment]
Still getting an error for image2image on Automatic1111 with "use gradio server" checked

```
Task exception was never retrieved
future: <Task finished coro=<Queue.process_event() done, defined at /usr/local/lib/python3.7/dist-packages/gradio/queue.py:222> exception=RuntimeError("Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 275, in process_event
    await event.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 305, in disconnect
    await self.websocket.close(code=code)
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 181, in close
    {"type": "websocket.close", "code": code, "reason": reason or ""}
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 316, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.

```

**Comment by TheLastBen** [comment]
try a clean install and run

**Comment by jcplus** [comment]
```
Task exception was never retrieved
future: <Task finished coro=<Queue.process_event() done, defined at /usr/local/lib/python3.7/dist-packages/gradio/queue.py:222> exception=RuntimeError("Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 275, in process_event
    await event.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/gradio/queue.py", line 305, in disconnect
    await self.websocket.close(code=code)
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 181, in close
    {"type": "websocket.close", "code": code, "reason": reason or ""}
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 316, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.close', after sending 'websocket.close'.
```
Having the same issue here when doing *extra image*. Happening on both tunnel and gradio servers. Change mode to *text2image* and it works then change back to *extra* it happens again.

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by Maxadox** [comment]
same here, any news on this issue?

**Comment by Maxadox** [comment]
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gradio/tunneling.py", line 39, in handler
    chan.send(data)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed

**Comment by TheLastBen** [comment]
Try using the gradio server

**Comment by Maxadox** [comment]
this is what I get with gradio server and a fresh restart:

```
Warning: unknown mime-type for "outputs/extras-images" -- using "application/octet-stream"
Error: no "view" mailcap rules found for type "application/octet-stream"
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'outputs/extras-images'
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gradio/tunneling.py", line 39, in handler
    chan.send(data)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
```

**Comment by Maxadox** [comment]
worked! thanks
