### ISSUE TITLE
I AM PAYING GOOGLE PRO AND STILL GET ERRORS RESUMING? WTH?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#918]
Session found, loading the trained model ...
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1107, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1076, in convert
    key_count = save_stable_diffusion_checkpoint(v2_model, args.model_to_save, text_encoder, unet,
  File "/content/convertodiff.py", line 1013, in save_stable_diffusion_checkpoint
    torch.save(new_ckpt, output_file)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/models does not exist.
Conversion error, if the error persists, remove the CKPT file from the current session folder
[ ]

**Comment by LIQUIDMIND111** [comment]
EVEN ON HIGH PREMIUM GPU DOES NOT WORKS, PLEASE..... VERIFY YOUR CODE.

**Comment by LIQUIDMIND111** [comment]
SO STARTING TODAy i wasted 20 computational units!!!!

You are subscribed to Colab Pro. [Learn more
Available: 81.96 compute units
Usage rate: approximately 1.96 per hour
You have 1 active session.

PLEASE BEN this is ridiculous....
