### ISSUE TITLE
Model Download cell error

### ISSUE THREAD

**Issue by ReEnMikki** [TheLastBen/fast-stable-diffusion#950]
```
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1115, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1066, in convert
    text_encoder, vae, unet = load_models_from_stable_diffusion_checkpoint(v2_model, args.model_to_load)
  File "/content/convertodiff.py", line 835, in load_models_from_stable_diffusion_checkpoint
    checkpoint = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "/content/convertodiff.py", line 817, in load_checkpoint_with_text_encoder_conversion
    state_dict = checkpoint["state_dict"]
KeyError: 'state_dict'
rm: cannot remove '/content/stable-diffusion-custom': No such file or directory
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
Conversion error
```
I use a custom model from huggingface that is 2.13GB, based on v1.5, so in settings of this cell I also selected v1.5

**Comment by ReEnMikki** [comment]
There used to be an option to check if there is Conversion error but now I don't see it anymore oof, why did u remove that

**Comment by TheLastBen** [comment]
You are probably loading a model that was converted with a broken script, if not, send me the model, I'll check it out

**Comment by ReEnMikki** [comment]
> You are probably loading a model that was converted with a broken script, if not, send me the model, I'll check it out

Weird, that model is merged using A1111's Webui at the ratio of 0.5:0.5 from 2 other models, both are trained from your Fast DB. Sorry for my lack of knowledge on this topic. I just used another model (trained from your Fast DB) to train and it's working normally for me now.

**Comment by ReEnMikki** [comment]
> You are probably loading a model that was converted with a broken script, if not, send me the model, I'll check it out

I'll send you the model link via Discord dm

**Comment by TheLastBen** [comment]
I tested it with the latest official diffusers script, still not working, the model is converted incorrectly

**Comment by ReEnMikki** [comment]
> I tested it with the latest official diffusers script, still not working, the model was converted incorrectly

Is there any possible way to convert that model again the correctly ?
