### ISSUE TITLE
AUTOMATIC1111.ipynb Error when running Start stable-diffusion

### ISSUE THREAD

**Issue by Wxcct** [TheLastBen/fast-stable-diffusion#953]
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/codeformer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/blip/models/blip.py
Warning: k_diffusion not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 8, in <module>
    import k_diffusion.sampling
ModuleNotFoundError: No module named 'k_diffusion'

**Comment by TheLastBen** [comment]
remove the folder sd and do a clean run

**Comment by Wxcct** [comment]
> remove the folder sd and do a clean run

Thanks,it works.
