### ISSUE TITLE
Generated .ckpt-files of last two days don't get loaded in Automatic1111 (on runpod.io)

### ISSUE THREAD

**Issue by wiwatoms** [TheLastBen/fast-stable-diffusion#959]
Hey Ben,

First big thanks for all your great work and incredible community support! Really appreciated!

My issue: All generated .ckpt in the Google-Colab-Notebook (I always refresh before using) within the last two days can't be loaded anymore. The place where I load the model in automatic's GUI (I use the standard one on runpod.io) shows me "Error" in red at the .ckpt file after choosing it. Same the number where it usually counts the amount of maximum characters I can use. When I generate an image it gives me this error: "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
Time taken: 0.08sTorch active/reserved: 1/2 MiB, Sys VRAM: 1480/16118 MiB (9.18%)".

All the old .ckpt files of your Colab from earlier still work fine in the same automatic GUI. I didn't change any settings and use exactly the same parameters and workflow like before. I am pretty confused and don't know what to do.

Any ideas?

**Comment by TheLastBen** [comment]
Hi, have you tried loading them in the fast-A1111 colab ?

**Comment by wiwatoms** [comment]
I skipped to load them in Colab before, because it's too slow in generation. Gives me following error message:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 26, in <module>
    ldm.modules.attention.BasicTransformerBlock.ATTENTION_MODES["softmax-xformers"] = ldm.modules.attention.CrossAttention
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

I've looked up the issue already, I understand I have to delete the folder "SD". Does it mean, all the trained model are garbage and I have to redo them?

**Comment by TheLastBen** [comment]
Your sd folder is very old, remove/rename it and do a clean run with the latest colab

**Comment by wiwatoms** [comment]
I did. With the "renewed" sd folder the .ckpt gets loaded in the Google Colab version. But in the runpod.io Automatic1111 GUI it still gets the same error. Any ideas?

**Comment by TheLastBen** [comment]
the A1111 runpod is out of date
