### ISSUE TITLE
error when install extension

### ISSUE THREAD

**Issue by misiek75** [TheLastBen/fast-stable-diffusion#972]
The following error appears when installing the Dreambooth extension 

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 10, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.sd_to_diff import extract_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 36, in <module>
    from diffusers import (
ImportError: cannot import name 'HeunDiscreteScheduler' from 'diffusers' (/usr/local/lib/python3.8/dist-packages/diffusers/__init__.py)

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 5, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.diff_to_sd import compile_checkpoint
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/diff_to_sd.py", line 215, in <module>
    def convert_text_enc_state_dict_v20(text_enc_dict: dict[str, torch.Tensor]):
TypeError: 'type' object is not subscriptable

**Comment by TheLastBen** [comment]
in a new cell, run 
`!pip install -U diffusers`

**Comment by TheLastBen** [comment]
did you check the A1111 repo for similar issues ?

**Comment by misiek75** [comment]
I looked through and no one reported any promblems

**Comment by TheLastBen** [comment]
check that you have a correct version of the model

**Comment by misiek75** [comment]
The problem would be with an outdated version of python. In order for this to work, version 3.11 must be installed
