### ISSUE TITLE
CUDA out of memory only for dump_only_textenc function

### ISSUE THREAD

**Issue by barbayrak** [TheLastBen/fast-stable-diffusion#975]
When I try to run the script on a machine, 

I am trying v2.1 512px model as basemodel

It first tries to run dump_only_textenc with 350 steps; however it gives an error

```
::::DEBUG::::dump_only_textenc Script : accelerate launch /opt/ml/input/data/diffusers/examples/dreambooth/train_dreambooth.py --image_captions_filename --train_text_encoder --dump_only_text_encoder --pretrained_model_name_or_path=/opt/ml/input/data/stable_diffusion_bucket/content/stable-diffusion-2-1-base --instance_data_dir=/opt/ml/input/data/stable_diffusion_bucket/user_images/kbbayrak --output_dir=/tmp/weights --instance_prompt= --seed=472031 --resolution=512 --mixed_precision=fp16 --train_batch_size=1 --gradient_accumulation_steps=1 --gradient_checkpointing --use_8bit_adam --learning_rate=2e-6 --lr_scheduler=polynomial --lr_warmup_steps=0 --max_train_steps=350
The following values were not passed to `accelerate launch` and had defaults used instead:
#011`--num_processes` was set to a value of `1`
#011`--num_machines` was set to a value of `1`
#011`--mixed_precision` was set to a value of `'no'`
#011`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/opt/conda/lib/python3.8/site-packages/diffusers/configuration_utils.py:195: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
0%|          | 0/350 [00:00<?, ?it/s]
[2022-12-11 20:57:18.197: W smdistributed/modelparallel/torch/nn/predefined_hooks.py:75] Found unsupported HuggingFace version 4.25.1 for automated tensor parallelism. HuggingFace modules will not be automatically distributed. You can use smp.tp_register_with_module API to register desired modules for tensor parallelism, or directly instantiate an smp.nn.DistributedModule. Supported HuggingFace transformers versions for automated tensor parallelism: ['4.17.0', '4.20.1', '4.21.0']
[2022-12-11 20:57:18.250 algo-1:103 INFO utils.py:27] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2022-12-11 20:57:18.395 algo-1:103 INFO profiler_config_parser.py:111] User has disabled profiler.
[2022-12-11 20:57:18.396 algo-1:103 INFO json_config.py:91] Creating hook from json_config at /opt/ml/input/config/debughookconfig.json.
[2022-12-11 20:57:18.397 algo-1:103 INFO hook.py:201] tensorboard_dir has not been set for the hook. SMDebug will not be exporting tensorboard summaries.
[2022-12-11 20:57:18.397 algo-1:103 INFO hook.py:254] Saving to /opt/ml/output/tensors
[2022-12-11 20:57:18.397 algo-1:103 INFO state_store.py:77] The checkpoint config file /opt/ml/input/config/checkpointconfig.json does not exist.
#033[0;32mkbbayrak  #033[0m
#033[0;32mkbbayrak  #033[0m
0%|          | 1/350 [00:04<25:56,  4.46s/it]
0%|          | 1/350 [00:04<25:56,  4.46s/it, loss=0.0685, lr=1.99e-6]
Progress:|                         |:   0%|          | 1/350 [00:04<25:56,  4.46s/it, loss=0.0685, lr=1.99e-6]
#033[0;32mkbbayrak  #033[0m

Traceback (most recent call last):
  File "/opt/ml/input/data/diffusers/examples/dreambooth/train_dreambooth.py", line 823, in <module>
main()
  File "/opt/ml/input/data/diffusers/examples/dreambooth/train_dreambooth.py", line 671, in main
model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/utils/operations.py", line 490, in __call__
return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 407, in forward
sample = upsample_block(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 1198, in forward
hidden_states = torch.utils.checkpoint.checkpoint(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
return CheckpointFunction.apply(function, preserve, *args)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 96, in forward
outputs = run_function(*args)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 1191, in custom_forward
return module(*inputs, return_dict=return_dict)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/attention.py", line 216, in forward
hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/attention.py", line 484, in forward
hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/attention.py", line 589, in forward
hidden_states = self._attention(query, key, value)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/models/attention.py", line 611, in _attention
attention_probs = attention_scores.softmax(dim=-1)

RuntimeError: CUDA out of memory. Tried to allocate 320.00 MiB (GPU 0; 14.76 GiB total capacity; 13.33 GiB already allocated; 207.88 MiB free; 13.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.
```

After this error it continues to run the the train_only_unet function with 3000 on top of it, and it works as expected.

Any idea why ?

**Comment by barbayrak** [comment]
Apparently , Idk why but replacing mixed_precision=fp16 with mixed_precision=no only in dump_only_textenc function removed my memory problem

**Comment by TheLastBen** [comment]
what gpu are you using ? check with :

`!nvidia-smi`

**Comment by barbayrak** [comment]
> what gpu are you using ? check with :
> 
> 
> 
> `!nvidia-smi`

It is Nvidia T4 in Aws (ml.g4dn.xlarge)

**Comment by TheLastBen** [comment]
you're not using google colab ?

**Comment by barbayrak** [comment]
> you're not using google colab ?

No I am running the script on my cloud instance. I am just curious about why it might happen.
