### ISSUE TITLE
Training cell error: Something went wrong.

### ISSUE THREAD

**Issue by ReEnMikki** [TheLastBen/fast-stable-diffusion#984]
```
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 823, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 575, in main
    train_dataloader = torch.utils.data.DataLoader(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 344, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=4000', '--stop_text_encoder_training=10', '--save_n_steps=4000', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Guwe', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Guwe/instance_images', '--output_dir=/content/models/Guwe', '--instance_prompt=', '--seed=305646', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=16000']' returned non-zero exit status 1.
Something went wrong
```

**Comment by ReEnMikki** [comment]
Nvm, issue has been solved, I forgor to run the prior cell

**Comment by sanjaymalladi** [comment]
what did you do to solve this error

**Comment by TheLastBen** [comment]
> what did you do to solve this error

by uploading instance images
