### ISSUE TITLE
Training error at start

### ISSUE THREAD

**Issue by Raz0rStorm** [TheLastBen/fast-stable-diffusion#997]
Error occurred at the start of training
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 372, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 466, in _dict_from_json_file
    return json.loads(text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 3 (char 158)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 823, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 541, in main
    noise_scheduler = DDPMScheduler.from_config(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 193, in from_config
    config, kwargs = cls.load_config(pretrained_model_name_or_path=config, return_unused_kwargs=True, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 374, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/content/stable-diffusion-custom/scheduler/scheduler_config.json' is not a valid JSON file.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--Style', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/chenbin', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/chenbin/instance_images', '--output_dir=/content/models/chenbin', '--instance_prompt=', '--seed=224291', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=3000']' returned non-zero exit status 1.
Something went wrong

**Comment by MANNNNEN** [comment]
same as this #1017 

In stable-diffusion-custom/scheduler/scheduler_config.json there is an extra comma that is the issue.

```
{
  "_class_name": "PNDMScheduler",
  "_diffusers_version": "0.10.0.dev0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  ,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null
}
```
Removing the comma fixes the issue and the train step continues.
