### ISSUE TITLE
cannot save image as jpeg

### ISSUE THREAD

**Issue by maxixa** [TheLastBen/fast-stable-diffusion#998]
get some errors 

Error completing request
Arguments: ('cars', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, False, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
    processed = process_images(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 464, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 607, in process_images_inner
    images.save_image(image, p.outpath_samples, "", seeds[i], prompts[i], opts.samples_format, info=infotext(n, i), p=p)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 536, in save_image
    _atomically_save_image(image, fullfn_without_extension, extension)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 508, in _atomically_save_image
    image_format = Image.registered_extensions()[extension]
KeyError: '.jpg'

**Comment by madebycambiamentico** [comment]
same problem here today, png save ok, jpg is bugged.

![image](https://user-images.githubusercontent.com/6808468/207637858-34ad41f1-008f-4ebd-b818-8804ecb9af8d.png)

**Comment by TheLastBen** [comment]
check the A1111 repo if there is a similar issue
